### ISSUE TITLE
Street name not used in route instructions (reference used instead?)

### ISSUE THREAD

**Issue by dondos** [Project-OSRM/osrm-backend#1299]
For roads having a reference OSRM uses that instead of the street name.
Shouldn't street name have priority over street reference?
![ruta_cluj](https://cloud.githubusercontent.com/assets/9431355/5245045/036ec1d6-795f-11e4-8835-e3a8b433d60f.png)
The above instructions should state: Turn right onto Strada Traian Vuia (not onto DN1C). 

A similar example: http://router.project-osrm.org/viaroute?&loc=46.766638,23.585123&loc=46.768457,23.584442&instructions=true&alt=false
There should be the name "Calea Motilor" used instead of "DN1".

**Comment by TheMarex** [comment]
This is implemented. https://github.com/Project-OSRM/osrm-backend/pull/1506

**Comment by awikatchikaen** [comment]
Hi, I reopened this discussion because I think "name (ref)" is confusing.
I don't know other countries, but in France, a route with ref D37 can can throught differente village, and each on have a "local" name for this road. And portions between don't have name

So the instruction list are :
Continue on Road1 (D37)
Continue on D37
Continue on Road2 (D37)
Continue on Road3 (D37)
Continue on D37

At first look, it seems we will change directions multiples times ... 
This seems better to me, the name is secondary :
Continue on D37  (Road1)
Continue on D37
Continue on D37 (Road2)
Continue on D37 (Road3)
Continue on D37

And even better, I think than those lines should be merged to an unique instruction : 
Continue on D37
