### ISSUE TITLE
calculate route error

### ISSUE THREAD

**Issue by solidsnake2013** [Project-OSRM/osrm-backend#1331]
Hi all

I want use orsm calculate a route.

http://localhost:5000/viaroute?loc=49.02349,12.092943&loc=49.023449,12.091581&loc=49.024292,12.08847&loc=49.024593,12.087125&loc=49.024899,12.086127&loc=49.02349,12.092943&output=gpx

![errorroute](https://cloud.githubusercontent.com/assets/5283898/5625096/b1102f4e-95ae-11e4-8457-239c3ec0d553.jpg)

you can see on this picture.

Why more than expected a route?

(I use a bicycle traffic way)

**Comment by emiltin** [comment]
if you place markers right at intersection, it might acutally be placed a tiny bit down the sideroad, which mean osrm will turn into the sideroad

**Comment by solidsnake2013** [comment]
@emiltin 
Thanks your answer.

But this is we have some questions.
I have what way to solve it?

**Comment by emiltin** [comment]
try to place markers between sideroads, instead of at intersections, or remove them altogether

**Comment by solidsnake2013** [comment]
the markers is customer provide.
we Hardly do correction.
Or whether there is a way try to test a point on the a sideroads?

**Comment by emiltin** [comment]
there is work ongoing to make osrm smarter in these cases, see https://github.com/Project-OSRM/osrm-backend/issues/930.

you might be able to move via point yourself to avoid sidestreets. you can use the /nearest api call to get the name of the street a specific location is placed on: https://github.com/Project-OSRM/osrm-backend/wiki/Server-api#nearest-point-on-a-street. maybe you could use this to check if a point is located at a sidestreet or not. as a hack, maybe you could move via points around one at a time, and see if the route becomes shorter.

@DennisOSRM would it be possible to set a 'via point range' in the profile, so that the via point will be considered visisted if osrm is within that range from the via point? say you set it to 100m, then if the via point is 50m down a sidestreet, osrm would not have to turn into the sidestreet.

**Comment by emiltin** [comment]
Another workarond you can try is to allow u-turns at via points, see https://github.com/Project-OSRM/osrm-backend/issues/100. I think you just add uturns=1 to the query. The instructions might be more confusing, but the route will be shorter.

**Comment by solidsnake2013** [comment]
we can need the Inflection point limit function. this function is very good.
but Occasionally bring surprise

**Comment by DennisOSRM** [comment]
We are working on _matching_ a set of points into the the most reasonable route. Here's a screen shot from work in progress:

![screenshot 2015-01-06 10 17 49](https://cloud.githubusercontent.com/assets/1067895/5626555/6680696a-958d-11e4-931d-87961a10b970.png)

Three locations are given (red, yellow, blue) and you see candidate locations what this could mean (light red, light yellow, light blue). From that we infer the _most reasonable_ path (red line). Once we have that, it should essentially fix your issue.

**Comment by emiltin** [comment]
looks great. will there be a setting to adjust the match range? different profiles might require different ranges.

**Comment by TheMarex** [comment]
@emiltin as potential candidates for a via the nearest 10 points are considered. There is a parameter you can tune, that would allow for more detours.

**Comment by emiltin** [comment]
what about a parameter to tune to distance that candicates are placed from the marker?

**Comment by TheMarex** [comment]
Candidates are the nearest 10 points. Depending on the density of that area the distance of these points can be quite large. However the method we use is based on [this paper](http://dl.acm.org/citation.cfm?id=1653818). The approach uses some probabilistic modeling that includes:
- Distance to the candidate of the candidates of the previous via (roughly)
- Distance of the candidate to the input via point
If you are interested you should try to read the paper. It is quite approachable after you understood how [HMMs](https://en.wikipedia.org/wiki/Hidden_Markov_model) work.

So distant candidates for a via get filtered out by the modeling anyway because the probability that they "fit" to the given via is very small.

**Comment by emiltin** [comment]
Thanks, interesting paper. Btw it can be read for free at http://research.microsoft.com/en-us/um/people/jckrumm/Publications%202009/map%20matching%20ACM%20GIS%20camera%20ready.pdf.

I still think there are some distances constants that determine what is a reasonable route, like the 200m cutoff mentioned in the paper. In the example Dennis posted above, some of the yellow dots could be reasonable if you're walking and u-turns are allowed anywhere.

**Comment by DennisOSRM** [comment]
> I still think there are some distances constants that determine what is a reasonable route, like the 200m cutoff mentioned in the paper. In the example Dennis posted above, some of the yellow dots could be reasonable if you're walking and u-turns are allowed anywhere.

Right, there are varying degrees of being reasonable ;-)

**Comment by daniel-j-h** [comment]
Map Matching is implemented by now: use it for noisy traces.
