### ISSUE TITLE
osrm file change

### ISSUE THREAD

**Issue by jellevictoor** [Project-OSRM/osrm-backend#1356]
I have a linux image with osrm v3.5.0 where i extract my osm files to osrm. these osrm files are read by java code that allows me to handle the routing info in my project.
I wanted to migrate this to ec2 and I got the last 4.3 build. Everything worked to generate my osrm files, but my java code won't read my osrm file anymore.
Is there an overview of how the output of osrm-extract files changes? A sort of migration guide or such?

**Comment by TheMarex** [comment]
As the ```.osrm``` dataformat is only supposed to be used internally as an intermediate representation, we do not really document that. You can however have a look at the relevant code in https://github.com/Project-OSRM/osrm-backend/tree/master/extractor to see how it is serialized.
In generally a quite a bit has changed since 3.5, so I would expect you need to do a major overhaul.

**Comment by woodbri** [comment]
The .osrm format changes pretty regularly. see #984 and #874 for other users with this problem also. In #874, Dennis mentions doing something with protobuf to make a stable interface, but I'm not sure anything along these lines has happened (or I have missed the discussion on it).

**Comment by DennisOSRM** [comment]
We have been entertaining the idea to use googles protocol buffers to store the intermediate data, but never gotten around to do so. yet.

**Comment by jellevictoor** [comment]
ok, I was not aware that this is an internal structure and not to be used for input in other projects. Is there an output file we can build on or is this also not recommended?

**Comment by DennisOSRM** [comment]
Please go ahead and build on the file in the current format. we'll keep in mind that it is used by third parties and discuss/announce breaking changes in advance.

**Comment by jellevictoor** [comment]
Ok Dennis, thanks allot. But a changelog for version 3.5 'till 4.3 is probably unexisting :)

**Comment by DennisOSRM** [comment]
0.3.5 till 4.5.0. :grinning: 

Unfortunately not. But most things should be quite straight-forward. IIRC, most changes affect flags.

**Comment by jellevictoor** [comment]
Ok thanks, I'll join the conversation on IRC and have a look at the code. Will close this issue since I have my answer.

**Comment by DennisOSRM** [comment]
Sure, it's #osrm on oftc.net

**Comment by woodbri** [comment]
I updated this page back around 0.3.5:
https://github.com/Project-OSRM/osrm-backend/wiki/OSRM-normalized-file-format
@jellevictoor it would be great if you could update this page based on your findings for 4.5.0 so other people can make use of that knowledge.

**Comment by JanChristiaens** [comment]
@woodbri I'm the writer of the code that @jellevictoor is using. I checked the osrm file generated with the 4.3 build. It seems that the format has changed lightly since v3.5:
- the header length is shortened from 188 to 156 bytes
- the edge size is shortened from 28 to 27 bytes, the direction (bidirectional / one way) was stored in 2 bytes (byte [13-14]: 00 00 is bidirectional, 01 00 is one way) thus i think that byte 14 is omitted.

After applying these changes, my code seems to read the osrm file without any problems.
