### ISSUE TITLE
Inconsistency between table and viaroute solutions

### ISSUE THREAD

**Issue by ZupoLlask** [Project-OSRM/osrm-backend#1374]
Dear Community,

I've stumbled upon a routing inconsistency between viaroute and table solutions.

Although all 3 locations are considered routable with:
- http://router.project-osrm.org/table?loc=41.143505,-8.621610&loc=41.146953,-8.622990&loc=41.148046,-8.623843

The same 3 locations produce "{"status_message":"Cannot find route between points","status":207}" with:
- http://router.project-osrm.org/viaroute?loc=41.143505,-8.621610&loc=41.146953,-8.622990&loc=41.148046,-8.623843

Can you please help?

**Comment by emiltin** [comment]
difference with the z parameter?

**Comment by ZupoLlask** [comment]
No difference at all...

**Comment by ZupoLlask** [comment]
@emiltin Maybe this is somewhat related with #930. What do you think?

**Comment by TheMarex** [comment]
Yeah the behavior of viaroute and table is currently not the same. This will probably change in the future to be more consistent.
That said. I'm not sure why viaroute fails in this example. #930 should have fixed most "No route found" errors.

**Comment by DennisOSRM** [comment]
Looks like a minor regression

**Comment by ZupoLlask** [comment]
When there's a fix to test this regression please let me know.

**Comment by MoKob** [comment]
Was able to reproduce (and fix) this locally.

The problem here is that the via-node is mapped to a street that requires a u-turn at the via-node. The default search does not allow via-nodes at u-turns.

Passing http://router.project-osrm.org/viaroute?loc=41.143505,-8.621610&loc=41.146953,-8.622990&u=true&loc=41.148046,-8.623843 (allow a u-turn at the via location), the plugin can find the correct route.

The difference here is that the table plugin does not have to worry about u-turns (point-to-point).
