### ISSUE TITLE
OSRM does not ignore highway service roads

### ISSUE THREAD

**Issue by xyz32** [Project-OSRM/osrm-backend#1386]
The emergency links between highway directions are not ignored by OSRM.
Steps:
1. Plan a rout that navigate near an emergency link on a highway.
2. Observe OSRM using the emergency link.

See the route planed here: http://www.openstreetmap.org/directions?engine=osrm_car&route=45.9099%2C-72.4878%3B45.9161%2C-72.4859

or this: http://www.openstreetmap.org/directions?engine=osrm_car&route=45.93830%2C-72.45397%3B45.93841%2C-72.45432#map=19/45.93878/-72.45372

**Comment by emiltin** [comment]
the link also has access=no

**Comment by DennisOSRM** [comment]
Yup, the access tag was added recently. Should be reflected with the next data update or the one after that

**Comment by emiltin** [comment]
oh, i thought that access tag had been parsed since a long time?

**Comment by DennisOSRM** [comment]
sure, it's just beed added recently to the way in question

**Comment by emiltin** [comment]
ah ok

**Comment by xyz32** [comment]
The access=no has been added yesterday by me to try to figure out what is going on. But the link was set to emergency long time ago and OSRM is still using it.

**Comment by DennisOSRM** [comment]
As mentioned before, it takes some time before a change is reflected in the routing. Updates occur roughly twice a day with a 10--14 hour lag. In short, give it some time.

**Comment by xyz32** [comment]
Looks like this issue has diverted to an tangent issue:
1) OSRM database not updated (10--14 hour lag) for the access=no tag. FIXED (wait for database sync)
Original issue:
2) OSRM uses emergency links for routing. Still OPEN: https://www.openstreetmap.org/directions?engine=osrm_car&route=45.71245%2C-72.77065%3B45.71265%2C-72.77087#map=17/45.71302/-72.77117

OSRM shoul ignore Emergency links, with or without the access flag.

**Comment by blinkenlight** [comment]
The issue I'm having with OSRM may not be identical to the one reported above, but it sure can be described with the same exact words - I think any service roads should only be used as a last resort, if nothing else goes there (if you wish, I can open a new issue for this, let me know). The thing is I noticed a disproportionately strong propensity of OSRM to take "shortcuts" through hilariously obscure service roads in a city map when an almost identically long secondary or tertiary main artery connects the same endpoints (see [osrm.at/b1i](http://osrm.at/b1i) for an example - the obvious route would be [osrm.at/b1l](http://osrm.at/b1l)); Technically the routing is not incorrect - those alleyways behind the buildings do exist and can be traversed with a car - but no-one in their right mind would choose to go that way (or indeed would be able to without having a nervous breakdown trying to squeeze through - in practice, you only enter those if you live there and want to park your car...). It's obviously not even an actually shorter route (not in any meaningful way at least), and this sort of thing keeps happening with every single route in my experience. Note that the strategy on the page is labelled "car(fastest)", not "walk(shortest, down to mm, ok with getting mugged)" - I think it would be a shame to leave this quirk like that, in an otherwise awesome service... :)

**Comment by DennisOSRM** [comment]
Lets try not to conflate issues here. The original point of the issue was that a road that is closed to general traffic is (or was) being used.

What @blinkenlight is asking for is to have a (turn) penalty on leaving an important road and also implicitly to minimize turns.

**Comment by DennisOSRM** [comment]
See #1387 for an issue on road preference.

**Comment by xyz32** [comment]
OK database seems to have updated so:
OSRM using emergency links still open: http://www.openstreetmap.org/directions?engine=osrm_car&route=45.93830%2C-72.45397%3B45.93841%2C-72.45432#map=19/45.93878/-72.45372

OSRM ingnoring links with access=no tag: FIXED (as expected).

**Comment by DennisOSRM** [comment]
> OSRM ingnoring links with access=no tag: FIXED (as expected).

For future reference, as folks pick up unconnected pieces of info from issues, I'd like to stress that this has not been a a case of handling the access tag incorrectly.

**Comment by emiltin** [comment]
i think the original problem was that osrm follows roads with:

highway=service
service=emergency_access

**Comment by xyz32** [comment]
@emiltin Yes that is the issue, I have also been able to find the wiki page that describe an emergency link: http://wiki.openstreetmap.org/wiki/Proposed_features/emergency_vehicle_access

**Comment by DennisOSRM** [comment]
> i think the original problem was that osrm follows roads with:
>
> highway=service
> service=emergency_access

Right, and then the issue was that having access information in the `service` but not the `access` tag is quite inconsistent. Looking at the link from @emiltin the much cleaner tagging would be to disallow access by `access=emergency`. If we agree on this, it could be added rather quickly.

**Comment by xyz32** [comment]
The annoying thing now is that the decision about the "access=emergency" tag in the wiki was left sort of open. See the comments at the end of the wiki article.

As for the fix for this issue I would vote OSRM to ignore "access=emergency" roads.

**Comment by DennisOSRM** [comment]
Well, decision on the wiki are a cargo cult. :grinning: 

Will add support (or rather unsupport) for `access=emergency` in a bit.

**Comment by DennisOSRM** [comment]
Turns out, this is already implemented for [more than a year](https://github.com/Project-OSRM/osrm-backend/blame/master/profiles/car.lua#L6).

**Comment by xyz32** [comment]
So, why is the routing using emergency roads?

**Comment by DennisOSRM** [comment]
Not using `access=emergency` tags.

**Comment by xyz32** [comment]
yes sorry I just seen the discussion on #733. I will update the map to respect that then. Thank you.

**Comment by joostschouppe** [comment]
I couldn't find a more general discussion on highway=service without extra tags. Shouldn't they be considered as at least as restrictive as access=destination? Or is it really a choice to allow them for standard routing?

**Comment by danpat** [comment]
Handling here is slowly improving:

  https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L136-L143

we now *penalize* access to some service road types (but not all).

The medium-term goal is to implement a solution for https://github.com/Project-OSRM/osrm-backend/issues/592 - this would allow the turn function to penalize access to service roads without needing to remove them from the routing network.

We want to keep them in the network so that routes can start and end on them (e.g. if you're requesting a route based on your current position from your phone).

**Comment by joostschouppe** [comment]
Hmm, I'm not sure that's the best approach. There are [huge amounts](http://overpass-turbo.eu/s/o9O) of service roads without an extra tag. I don't think that's even wrong. BTW, service=parking is rare and not documented. Parking_aisle is also considered wrong for parking entrances.
I would agree that they should be avoided, and should not be removed. As a rule of thumb, I would say they shouldn't be used unless they are the only way to get to your destination (or waypoint). Which I would suppose you already implemented for highways tagged access=destination.

**Comment by daniel-j-h** [comment]
@joostschouppe we penalize turns onto `access=destination` ways; the same could happen for service roads. Please see this diary post and the following issue from today:

- https://www.openstreetmap.org/user/happygo/diary/40564
- https://github.com/Project-OSRM/osrm-backend/issues/3913#issuecomment-292474748

What you'd have to do is in the car profile (`profile/car.lua`) penalize turns onto service roads. Then the routing engine will only route you there if there is no other way.

**Comment by joostschouppe** [comment]
OK, now I get it. Thanks for taking the time to explain.
