### ISSUE TITLE
Multiple routing pairs

### ISSUE THREAD

**Issue by mantesat** [Project-OSRM/osrm-backend#1419]
Just a suggestion for a new request type: I thnik that it would be great if a special request could return multiple from-to pair routing results. I know that one can use multiple from-to calls to the server, and there is always the matrix/table request type, but I think that it would be fairly easy to add a request type that can return a response containing routings for multiple from-to point pairs. This would allow getting multiple routing results between point pairs at once, eliminating networking lags.

Anyway, this is just a suggestion.

**Comment by TheMarex** [comment]
Thanks for the suggestion.
In applications where that latency is a problem, I would suggest running OSRM as a backend service using ```node-osrm````and build your on application specific API on top of that. In general the HTTP interface of OSRM is very simple by design. For serious applications we suggest using the node bindings anyway.
So its unlikely that we will add something like that.
