### ISSUE TITLE
Lua error trying to extract map

### ISSUE THREAD

**Issue by JChamon** [Project-OSRM/osrm-backend#1426]
I'm following this tutorial (https://www.digitalocean.com/community/tutorials/how-to-set-up-an-osrm-server-on-ubuntu-14-04) as good as I can, but I found some problems while trying to extract the map.

First, despite having created the symbolic links for profile and bin, it said `Profile profile.lua not found!` so I had to copy *car.lua* into osrm folder and rename it to *profile.lua* and the same for *lib* folder.

Then, the following error appeared:

> [info] Input file: map.osm
> [info] Profile: profile.lua
> [info] Threads: 1
> [info] Using script profile.lua
> [STXXL-MSG] STXXL v1.3.1 (release)
> [STXXL-MSG] 1 disks are allocated, total space: 4 MiB
> [info] Parsing in progress..
> [info] input file generated by Osmosis 0.43.1
> [info] timestamp: n/a
> PANIC: unprotected error in call to Lua API (attempt to index a nil value)

Any guess?

**Comment by emiltin** [comment]
instead of symlinking, just pass the path to the lua file. run the bins with --help to view the options.

**Comment by TheMarex** [comment]
Any updates @JChamon?

**Comment by daniel-j-h** [comment]
I had the same issue a couple of weeks ago after setting up a dev env again.

The problem is that you built luabind against lua version X but osrm-backend's cmake scripts find lua version Y. (In my case I built luabind against Lua 5.1, but then CMake pulled in Lua 5.2). This does not work.

Solution is to either built a local luabind against the Lua version that CMake finds or specify the Lua version to CMake. In any case, those two have to match. Verify that by `ldd` on libluabind and read the CMake output.
