### ISSUE TITLE
Remove dependence of lua_state from EdgeBasedGraphFactory

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1448]
Currently the EdgeBasedGraphFactory uses lua to call the turn penalty function for every turn. Since this function should be pure, it would completely suffice to pre-compute the penalty for every integer angle in [0, 360] and save that as lookup table. Should also be a lot faster.

**Comment by emiltin** [comment]
The turn function would be much more useful if it could get input about the from/to ways. See #477. Caching would not be possible in that case.

**Comment by TheMarex** [comment]
The problem is that we have already lost all information about the original way at that point of the code (that is gone after the extract step). Would average speed of both the from and to way help? Turns where the average speed on the to way is much lower than on the from way should get a penalty (think taking a motorway exit).

**Comment by emiltin** [comment]
for bikes, average speed doesn't really help, since you would typically go as fast on a smaller road than on a big road. the issue is that turning left from a big road into a small road not a good suggestion unless there's a traffic signal. (tags on the node itself would be rquired also for this use case).

what about idea for a simple key-value store for sending tags along with the routing results - could that be usd for this purpose as well? #1342

**Comment by TheMarex** [comment]
#1342 Could be used, but there is a number of considerations when it comes to performance. You would need to transform the data that was stored in they key/value storage to a format that is readable by lua, which would mean quite a bit of overhead.

But I get your point, we probably don't want to remove this after all.
