### ISSUE TITLE
Problem with "segmentation error (core dumped)"

### ISSUE THREAD

**Issue by pedrogeo** [Project-OSRM/osrm-backend#1468]
Hello,

I'm using OSRM for the first time with a virtual machine (Ubuntu 14.04.2 LTS). I have found a topic which interested me and I decided to follow the same steps. The topic is here :

http://motive.cemagref.fr/people/nicolas.dumoulin/distances-osrm

The scripts are here :

http://trac.clermont.cemagref.fr/svn/PRIMA/distances-OSM/

All the steps worked well (I work with another region than the author) but I have some problems with the execution of the last python script (called by the author "distanceOSRM.py"). This script works well till the moment when it crashs with the message "segmentation error (core dumped)". 

I don't understand because a part of the datas are created by the script (352 lines).

Is someone can help me to resolve this problem ?

Sorry for my bad english but I'm french and I don't speak english often.

Pierre

**Comment by TheMarex** [comment]
Looking at the script, you should contact the author of them. If the python script crashes, that has nothing to do with OSRM, since it queries the server by HTTP. If it is the OSRM process is crashing, that is something different.
In that case go to the build folder of `osrm-backend` and execute the following steps:

```
cmake .. -DCMAKE_BUILD_TYPE=Debug
make osrm-routed
```

And then start `osrm-routed` like this: `gdb --args ./osrm-routed <OTHER_PARAMETERS>`

**Comment by pedrogeo** [comment]
I gave my datas to another person and It works well for him. I think, it could be my Linux instllation that have a problem. But I'm not so qualified to find what is the problem. Maybe a problem of RAM settings.

Thanks.
