### ISSUE TITLE
Replace BOOST_ASSERT with own assertion

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1504]
Goal: We want to run assertions on large datasets to be sure we didn't miss any edge cases.
Problem:
 - To get `BOOST_ASSERT` in Release builds you need to undefine `NDEBUG`
 - We want syntax checks for assertion expressions in every build modus

How to:
- Enable by default in Debug build
- Disable by default in Release build
- Enable when `USE_ASSERTIONS=1` is passed as option
- `util/assertion.hpp` implemented as inline functions `osrm::assert(EXP)` and `osrm::assert_msg(EXP, MSG)`

**Comment by daniel-j-h** [comment]
What about

    #define BOOST_ENABLE_ASSERT_HANDLER

because we do not want to change all the files in which we're using Boost.Assert, we could define it via CMake, that is passing `-DBOOST_ENABLE_ASSERT_HANDLER` to the compiler wrapped behind an `option(USE_ASSERTIONS OFF)`.

Then, in an implementation file, we define the handlers (they are already declared in Boost):

```c++
namespace detail {
  void assertion_failed_msg(char const* expr, char const* msg, char const* function, char const* file, long line) {
    std::ostringstream fmt;
    fmt << file << ":" << line << "\nin: " << function << ": " << expr << "\n" << msg;
    throw AssertionException{fmt.str().c_str()};
  }
}

// Boost.Assert only declares the following two functions and let's us define them.
// We throw to guarantee for stack-unwinding and therefore our destructors being called.
namespace boost {
void assertion_failed(char const* expr, char const* function, char const* file, long line) {
  ::detail::assertion_failed_msg(expr, "", function, file, line);
}

void assertion_failed_msg(char const* expr, char const* msg, char const* function, char const* file, long line) {
  ::detail::assertion_failed_msg(expr, msg, function, file, line);
}
}
```

This may seem a bit hacky (and probably also is), but allows us to 1/ change the behavior globally with almost no modifications 2/ properly do stack unwinding by throwing an exception.

References:

- http://www.boost.org/doc/libs/1_59_0/libs/assert/assert.html

**Comment by TheMarex** [comment]
@daniel-j-h yes that is excatly what we need. Would like to ship this to the demo server, so we can get assertions in `osrm-extract` and `osrm-prepare` as well.
