### ISSUE TITLE
AppVeyor builds fail

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1516]
Currently the AppVeyor builds fail with [this error message](https://gist.github.com/TheMarex/eccf410f6c1496eacf21).

/cc @springmeyer

**Comment by springmeyer** [comment]
My first though was to try upgrading to VS 2015 - which we'll want to target anyway (instead of the Nov CTP of 2013). Now https://ci.appveyor.com/project/DennisOSRM/osrm-backend/build/job/ojr702vrjt53qn04 is hitting `CMake Error: Could not create named generator Visual Studio 14 Win64`. Perhaps that indicates we need to upgrade cmake to understand VS 2015. I'm not sure. I'll scheme with @BergWerkGIS tomorrow on next steps here.

**Comment by BergWerkGIS** [comment]
Yes,
* upgrading to VS2015 is a good idea, I couldn't get osrm-backend and its deps compile with any older version
* AppVeyor has an older version of cmake (we are already using a newer cmake for other tools, eg. libosmium)

Should I take a look next week?

**Comment by TheMarex** [comment]
@BergWerkGIS would be awesome if you could take a look at this when you have some time in your schedule. Currently I have a bunch of PRs I can't merge because I don't know if the windows builds will pass.

**Comment by BergWerkGIS** [comment]
@TheMarex ok, will look into it this week.

**Comment by BergWerkGIS** [comment]
AppVeyor is green again:
https://ci.appveyor.com/project/DennisOSRM/osrm-backend/history

Artifacts are not packaged yet (will do soon).
Leaving open and assigning to myself, that I don't forget.

**Comment by springmeyer** [comment]
Awesome work @BergWerkGIS!!! When you create the pull fixing can you give us a rundown of what it took to fix?

**Comment by TheMarex** [comment]
@BergWerkGIS awesome. Can you squash + PR that to `develop`?

**Comment by BergWerkGIS** [comment]
Merged
https://github.com/Project-OSRM/osrm-backend/commit/ce152b205fa1e6e3c845e1e30887fb5acad382fc
