### ISSUE TITLE
large GPX points -> /match service -> /viaroute service flow

### ISSUE THREAD

**Issue by BharathMG** [Project-OSRM/osrm-backend#1525]
Hey Guys,

I've been trying to do GPX conversion to a Route using OSRM. I've an OSRM server running in my instance and query it with all the GPX points I have to a match service. Then, with matched points, I query /viaroute service to get turn instructions. 

The problem comes when there are partial map matchings and dealing with them. I cannot just join all the map matchings and query it with viaroute as it cannot make a valid route with partial map matched points. 

So how should I get a valid route with partial map matchings? Like, introducing a via_point between partial map matches and try to make  a route connecting every map matching? Can anyone shed some light on this? 

Thanks a lot!

**Comment by emiltin** [comment]
points are split into partial map matching exactly because no valid route can be found connecting all points. so it probably doesn't make sense to try to join them.
the splits might be caused be invalid map like, like roads that are not conncted. in that case the solution would be to fix the map data.

**Comment by BharathMG** [comment]
Thanks @emiltin ! Closing this.
