### ISSUE TITLE
Not reachable address

### ISSUE THREAD

**Issue by frankvandenbergh** [Project-OSRM/osrm-backend#1542]
I ran the distance matrix and saw a very high value. Digging into this I noticed a not reachable address (52.31856,6.657438). When I look at the map (via http://map.project-osrm.org/) it does look reachable. 

Using the OpenStreetMap editor the roads to this industrial area look ok. When I run http://www.yournavigation.org, that is also based on osm, it is able to navigate to this address.

**Comment by TheMarex** [comment]
Reachable from where? You need both start and destination to determine if its reachable.

**Comment by frankvandenbergh** [comment]
From whatever point you like. In OSRM it is a kind of black zone, but not for other openstreetmap routers.

Easy to test. Copy the address in the from textedit and select a where location by dropping/typing. No route will be calculated. When you next drag the from pointer just outside the area a route will be calculated.

**Comment by lbud** [comment]
Hey @frankvandenbergh, this appears to be a data issue — you can route to, but not from, that point, because the way at http://www.openstreetmap.org/way/175452135 was marked as oneway in the same direction as its opposite side (i.e. the wrong way). I've just reversed it on OpenStreetMap so this should be fixed on http://map.project-osrm.org/ after the next data cycle — please reopen if this persists after tomorrow.
