### ISSUE TITLE
Wrong distance tables on foot profile

### ISSUE THREAD

**Issue by chaupow** [Project-OSRM/osrm-backend#1547]
Being on the foot profile, I seem to always get symmetric distance tables such as
```
     0  54616  84425  88404  49394  52044
 54616      0  68188  92349  43248  85832
 84425  68188      0  43276  40586  76379
 88404  92349  43276      0  49247  54915
 49394  43248  40586  49247      0  51195
 52044  85832  76379  54915  51195      0
```

But when I compute the route of the locations going clockwise and counter-clockwise in the reverse direction, I don't get the same route, but instead

![screenshot 2015-06-25 09 45 37](https://cloud.githubusercontent.com/assets/804027/8349673/fd1a2c50-1b1e-11e5-80c2-3d63a7a98d43.png)

This shows that the distance table should actually not be symmetric. This problem only seems to arise on the foot profile. The car and bike profile return non-symmetric tables.

I'll look into this.

**Comment by MoKob** [comment]
@chaupow Do the durations actually differ? A foot-matrix should always be symmetric (since you can use all ways in both directions).

You can get multiple different ways that offer the same duration though:

Consider:

```
a -- b
|    |
c -- d
```

From `a` to `d` we can use both `a-c-d` and `a-b-d` for the same duration. Which one of these is found depends on the order in which we look at the vertices.

Given that the routes look similar in distance, I'd assume that they are simply different routes for the same distance (which is expected on foot profiles to be much more common).

Since in general distance table durations and shortest path durations seem to match up, except for u-turn penalties, going straight...), I am closing this here.
Feel free to re-open if this should not just be `continue_straight` issues.
