### ISSUE TITLE
Total route duration !== sum of all maneuver durations

### ISSUE THREAD

**Issue by peterqliu** [Project-OSRM/osrm-backend#1575]
http://osrm.at/dLQ

This trip has a total duration of 95s, but its first maneuver takes 169s.

cc/ @lbud

**Comment by TheMarex** [comment]
Best guess would a bug in the edge compression. Note that there should be a turn announced.

**Comment by TheMarex** [comment]
Okay found the root cause of this:

Path unpacking is broken for the first and last segment if these segments are compressed edges. In that case `PathData` will contain the full length of the compressed edge - not only the length of the part that is covered by the `PhantomNode`.

This has some bigger implications on the query code and description generation code. Currently working on fixing this and simplifying the code along the way.

**Comment by danpat** [comment]
This has been fixed.

Current API request:

https://router.project-osrm.org/route/v1/driving/-122.98851,37.995975;-122.998009,37.99736?overview=false&alternatives=true&steps=true

sum of steps durations == summary duration.
