### ISSUE TITLE
Strange routing : any ideas ?

### ISSUE THREAD

**Issue by the-knife** [Project-OSRM/osrm-backend#1606]
Hello,

Any ideas why this way seems to be avoided in [this itinerary](http://osrm.at/f34) ?
Coudn't find anything strange in the openstreetmap data.

Thanks in advance!
the_knife

**Comment by danpat** [comment]
There is a turn restriction in OSM:

<img width="725" alt="screen shot 2015-08-18 at 12 14 26 pm" src="https://cloud.githubusercontent.com/assets/1892250/9340099/bfb5c80c-45a2-11e5-87b7-d557af7b1200.png">

Looking on Google Streetview, it appears that there is a turn lane and I can't see a sign restricting turns here.  It looks like an error in OSM data, you should correct that if it's wrong.

**Comment by the-knife** [comment]
Thanks for searching.

The relation https://www.openstreetmap.org/relation/3724506
indicates that bicycles are able to turn to right even if the traffic signal is red.

As the "no_right_turn" tag is not present, osrm should not prevent to turn, should it?

**Comment by danpat** [comment]
Ah, thanks for double-checking.

Yes, looks like a bug in the restrictions-parsing code.  If we find any relation with a key that begins with "restriction", will will add a restriction for it, and we only look at the "from" "via" and "to" attributes, the actual value of the `<tag k='restriction' v='...'/>` tag is only looked at to see if it begins with `only`.

In short, restriction parsing is broken here, this is a bug.

To fix this however, we would need to move restriction processing and parsing into Lua so that it could be fully customized for bike/car/walk profiles.

Updating title and marking this as a bug.

@the-knife The fix needs to go into `extractor/restrictions_parser.cpp` if you want to have a go at it :-)

**Comment by MoKob** [comment]
fixed
