### ISSUE TITLE
Rising bollards

### ISSUE THREAD

**Issue by planemad** [Project-OSRM/osrm-backend#1616]
Rising bollards `barrier=bollard`+`bollard=rising` like [this one](https://www.openstreetmap.org/node/2121015545) are currently unroutable unless an explicit access tag is set.

![](http://www.businessmagnet.co.uk/manage-account/uploadedImages/74225/rising-bollards.jpg)

Considering this is a movable barrier, this should imply that with the correct permission you should be able to cross it. A possible candidate for the [barrier whitelist](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L6)?

cc @TheMarex

**Comment by TheMarex** [comment]
Hm yes we should handle this similar to gates I guess.

**Comment by daniel-j-h** [comment]
In looking into this I found the following: in [profiles/car.lua](https://github.com/Project-OSRM/osrm-backend/blob/0a53dccd4cdf080d9ce86cfd5e4bab87d11ea468/profiles/car.lua#L135) the `obey_bollards` variable is never read (it's also in `profiles/examples/postgis.lua` and `profile/bicycle.lua` with different values).

Is this because of historic reasons, @TheMarex ?

Bollards are respected through the `barrier_whitelist`, though.

**Comment by TheMarex** [comment]
Good catch. Yes this is probably for history reason. You can remove it.

**Comment by daniel-j-h** [comment]
I implemented this in https://github.com/Project-OSRM/osrm-backend/pull/1627 which got merged into develop, closing here!
