### ISSUE TITLE
Pedestrian roads with motorcar=destination are unroutable

### ISSUE THREAD

**Issue by planemad** [Project-OSRM/osrm-backend#1617]
Roads tagged `highway=pedestrian`+`motorcar=destination` are currently not routable using the car profile. Ideally this should be routable.

http://osrm.at/f5s

The wiki definition of `access=destination` is:
> Only when travelling to this element; e.g., local traffic only.

If any of the routing points are at an element with access=destination, it should definitely route as the user intends to visit that point and not drive by. 

cc @TheMarex

**Comment by daniel-j-h** [comment]
For this we would have to know if it's a route's source or destination. Otherwise we still don't want to route through it.

I had a talk with @danpat about it: it seems to be not possible right now: the profile's callbacks are only triggered on a node, way (and segment for the raster branch) basis.

@TheMarex feel free to churn in here, as you tagged it for the `4.8.0` release. Maybe we're missing something.

**Comment by danpat** [comment]
We discussed something similar here for private areas (i.e. gated communities).  We should allow routing when the destination/source is on one of these restricted areas, but not route through them for others.

This could be achieved with https://github.com/Project-OSRM/osrm-backend/pull/1614  by adding a bit invisible penalty to private->non-private or access/limited-access transitions.

**Comment by TheMarex** [comment]
This ticket is just about making it routable in general - even in the middle of the route. This seldom causes problems as `destination` roads are dead-ends in most cases anyway. It will also get a very low  speed, so it is unlikely to be used as shortcut.

It is possible to do this correctly with CH (for specific travel mode changes), I can dig up the paper for that. The idea is basically to not contract nodes that allow to change the travel mode.

**Comment by daniel-j-h** [comment]
Taking a look at this, I found that in the `car.lua`profile both [`restriction_exception_tags`](https://github.com/Project-OSRM/osrm-backend/blob/f6a90e9b429b4e2fdfa231580ae404d7c0696b14/profiles/car.lua#L13) and [`get_exceptions`](https://github.com/Project-OSRM/osrm-backend/blob/f6a90e9b429b4e2fdfa231580ae404d7c0696b14/profiles/car.lua#L149-L153) are unused (i.e. dead code). @TheMarex any idea to what this was meant for? I will add a destination exception by hand now.

**Comment by daniel-j-h** [comment]
Solved, closing here.

**Comment by kdano** [comment]
"as destination roads are dead-ends in most cases anyway"
That's not true at all. Not where I live.
The point of having a "destination only" sign is exactly to keep out cars that would otherwise choose to pass through the road. There is no need for this with dead-end streets.

Did you really allow routing through destination roads in the middle of the route? I think that's worse than not allowing routing at all. The solution should be something like what danpat said.
