### ISSUE TITLE
Detecting impossible routes

### ISSUE THREAD

**Issue by jinalfoflia** [Project-OSRM/osrm-backend#1652]
There are instances where we know if the routes between the two points are impossible (for e.g. There can be no route between Australia and New Zealand). In instances like these, where OSRM shows nothing, we can have an error message displayed stating that it's an `impossible route`

![screen shot 2015-09-07 at 3 51 14 pm](https://cloud.githubusercontent.com/assets/4470913/9714894/1ac1b2f2-5579-11e5-8f5b-dbbaa500e5dd.png)

Currently, after receiving the route failures, the [script](https://github.com/mapbox/directions-feedback/blob/master/scripts/sumologic.py#L61-L108) filters out the impossible routes with the help of the polygons. So for every failure we check the location of the waypoints, if any of them lie in a different polygon a route cannot exist.

![screen shot 2015-09-07 at 3 54 18 pm](https://cloud.githubusercontent.com/assets/4470913/9714858/c15b469c-5578-11e5-9f6f-2087af2c4f40.png)

/cc @TheMarex @geohacker @planemad

**Comment by emiltin** [comment]
what about ferry routes?

**Comment by planemad** [comment]
@emiltin the [routing continents](https://github.com/mapbox/directions-feedback/blob/master/scripts/continents.json) take into account ferry routes as well. Here's roughly how the impossible routing detection works:
- Divide the world into routable zones within which there is a possiblity of a route, and between which there is no possibility of a route. You can see Madagascar falls outside the Eurasian zone and there is no car ferry between the two. The rest of the world is also a zone.
- For each waypoint, find out the routing zone it falls in
- If all waypoints are in the same zone, a route is possible, else mark as impossible route.

As we do directions QA we constantly research on possible ferry routes between islands where routing fails and when we find there is none, we update the routing continents to include this.

**Comment by TheMarex** [comment]
This should get covered by component ids. Unfortunately we set the component id of big components (like continents to `0`).

Since the component id is a 32bit integer we could use some hacky solution like setting the MSB to `1` and check if the component id is smaller than `0` to determine if its a big component.
- [ ] Check if there are less than `2^31` components in the planet file
- [ ] Make `unsigned` into `int` [here](https://github.com/Project-OSRM/osrm-backend/blob/fca4aeb50b92a26d4c44a02491a24a203526c0d4/data_structures/edge_based_node.hpp#L65) and [here](https://github.com/Project-OSRM/osrm-backend/blob/fca4aeb50b92a26d4c44a02491a24a203526c0d4/data_structures/phantom_node.hpp#L88)
- [ ] Adapt all the `== 0` checks to `< 0` checks.
- [ ] Make `0` an invalid component id

**Comment by TheMarex** [comment]
Implemented in https://github.com/Project-OSRM/osrm-backend/pull/1783 major downside is that we would need a different component search on an undirected graph to safely exit early.

**Comment by planemad** [comment]
@TheMarex :boom: would love to know more about how something like this works.
