### ISSUE TITLE
startup time

### ISSUE THREAD

**Issue by bjtaylor1** [Project-OSRM/osrm-backend#1671]
Hello,
I have noticed that the first time I start up osrm-routed, it takes  quite a long time to start up, maybe 30s or so before it's 'running and waiting for requests'.
However, if I stop the process, and restart it, on the second and subsequent times, it is nice and quick (maybe 3 or 4s).
If I restart the machine however, and then restart the process, it's slightly quicker than the very first time, but still quite slow (10s).
Can anyone explain this difference? Is it  caching stuff somewhere?

Is there a way to improve start up times in the situation when the machine has just been restarted?

**Comment by daniel-j-h** [comment]
Could you run `htop` and `iotop` when starting `osrm-routed` for the first time, to see if you can detect any spikes in CPU or I/O usage? In addition, we need more information: is this behavior the same for all datasets, are you on the latest stable release, do you have any logs where it is hanging, and so on.

**Comment by TheMarex** [comment]
@bjtaylor1 that is the time it takes to load the data into memory. What you see is file system caching.

If you want to swap data out I would recommend using `osrm-datastore` and run `osrm-routed` with the `-s` option. It will load new data to memory while the server is still running. However you will of course need twice the RAM since you will have to fit two datasets into memory at once.
