### ISSUE TITLE
Provide better out-of-memory messages

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#1729]
When osrm bins run out of memory, they will often exit with messages that users intepret as a crash.

- Perform simple upfront checks to avoid starting task that can obvious not be completed due to lack of memory.
- Provide clearer messages in case memory runs out.

**Comment by daniel-j-h** [comment]
There are a few sides to this problem, e.g. we may get killed by the Kernel OOM killer, e.g. due to fragmentation as seen in https://github.com/Project-OSRM/osrm-backend/issues/1698. In case we throw a `std::bad_alloc` there should be no reason why not to catch it at top level and translate it to a better human readable message.

**Comment by danpat** [comment]
Ref #1736

**Comment by daniel-j-h** [comment]
`std::bad_alloc` handled in https://github.com/Project-OSRM/osrm-backend/issues/1741 --- feel free to change the messages or add more information.

**Comment by daniel-j-h** [comment]
Nothing actionable here, closing. We did not implement heuristics for file sizes, memory usage or related. If we detect that we are out of memory, we simply print human readable messages. Tracking I/O system failures such as out-of-disk-capacity in https://github.com/Project-OSRM/osrm-backend/issues/1682.
