### ISSUE TITLE
Wrong route result when sum of ways to nearest nodes is lesser than way from start to end

### ISSUE THREAD

**Issue by edpop** [Project-OSRM/osrm-backend#1733]
Hello.
Do you plan to do something with this? Or how to configure it?
![pretty_route](https://cloud.githubusercontent.com/assets/13479292/10423182/205a5dc8-7107-11e5-86c4-93c6f4d601cc.png)

Thank you!

**Comment by TheMarex** [comment]
@edpop can you elaborate a little more as to what the problem in your case is?

**Comment by edpop** [comment]
From a user perspective, this solution is obviously wrong. Because algorithm offers to go on foot anyway, it should consider a straight way from start to end in all type of transport.

**Comment by danpat** [comment]
The routing engine can only travel on paths that it knows about.  What if there was a cliff that was not marked on the map, or the area was closed because of land-mines (an extreme example), or this was a lake?

If there is really a path in this location, then it needs to be added to the map for routing.  We cannot fix this.

**Comment by MoKob** [comment]
From a user perspective, the request is unreasonable to begin with. Just as for [this](http://map.project-osrm.org/?z=14&center=38.869552%2C-77.036691&loc=38.863504%2C-77.029867&loc=38.863437%2C-77.034330&hl=en&ly=&alt=&df=&srv=) route, we could offer to swim. 

The query looks for the closest point that is routable from your desired start and end points.
If unreasonable points are specified for the mode of transportation, the result can be not any more reasonable than the input.
