### ISSUE TITLE
Fix osrm shipped with Debian GIS

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#1744]
Breaking out from https://github.com/Project-OSRM/osrm-backend/issues/1738#issuecomment-149019046

> https://wiki.debian.org/DebianGis includes  OSRM 4.7 version and seem to have all the [outdated cpack information](https://github.com/Project-OSRM/osrm-backend/blob/develop/cmake/CPackDebianConfig.cmake) in it

@daniel-j-h can you open a ticket with them with some instructions to fixing? let's not spend much time on this though, let the Debian GIS people fix it ...

**Comment by TheMarex** [comment]
In the past we have tried to avoid distributions (especially Debian because its life cycle is so long) packaging OSRM because we don't do any kind of backwards support. We will never release `4.7.3` after already pushing out `4.8.0`. Can we get them to remove the package again?

**Comment by joto** [comment]
You don't have to support older versions of your software for Debian. Of course it is nice if you do, but it is Debian's responsibility and they will hopefully do backports if there are larger problems. If you have a clear release policy, they can't complain if you don't fix old versions.

I think having Debian packages is great. It gives many more people access to the software and helps with testing on strange architectures. And it is a good idea to work with them a bit by looking at the package, talk about which parts to include and which parts might not be ready for packaging, dependencies etc. Going through the packaging often surfaces issues around documentation, copyright and deployment. Fixing those issues also helps non-Debian users. On the other hand, if you ignore the Debian people, bad packages might create problems later. And of course, you could tell them you don't want your software packaged, but it is their decision. There were, obviously, some people interested in the package, otherwise it wouldn't exist.

After my old Osmium library was packaged for Debian without any input from me, I have now established a working relationship with the Debian guys for my new Osmium library and related software, recommended which parts made sense to package and which software isn't stable enough (yet) etc. This has resulted in useful packages which I use myself. So I can only recommend spending a bit of time on these packaging issues, most of the work will be done by the Debian people for you.

**Comment by sebastic** [comment]
FWIW, I'm working on updating the OSRM Debian package to 4.8.1.

What's the actual issue regarding the cpack information?

**Comment by sebastic** [comment]
The [osrm Debian package](https://tracker.debian.org/pkg/osrm) uses the regular Debian packaging tools instead of CPack, `cmake/CPackDebianConfig.cmake` is irrelevant for the Debian package included in Debian & Ubuntu.

As part of the package changes for the 4.8.1 release, the now obsolete protobuf & osmpbf dependencies are no longer included in the build dependencies. The build dependencies include the same packages as documented in the [Building OSRM - Debian jessie](https://github.com/Project-OSRM/osrm-backend/wiki/Building-OSRM#debian-jessie) instructions.

Regarding this issue, I don't see anything that needs to be fixed in the osrm package included in Debian.

Please note that the osrm package in Debian uses [libosmium](https://tracker.debian.org/pkg/libosmium), [protozero](https://tracker.debian.org/pkg/protozero) & [utfcpp](https://tracker.debian.org/pkg/utfcpp) packages instead of the embedded copies included in `third_party/libosmium/` (related reading: [UpstreamGuide](https://wiki.debian.org/UpstreamGuide#No_inclusion_of_third_party_code)).

CC: @cbaines who is the reason we have osrm in Debian and should be made aware of this discussion.

**Comment by daniel-j-h** [comment]
I talked to @TheMarex and @danpat and came to the conclusion that we don't think it would make much sense to have OSRM packaged and eventually shipped in a stable Debian release.

This has several reasons, which I try to explain in the following.

Although we do releases, OSRM is always in flux and will probably change drastically in the coming months. Therefore it is not possible for us to do any support for older versions. Especially not with the current capacity of active developers. That is, we not only don't have the capacity to backport important fixes and security updates, we also can't validate and act upon user reports against older versions as there is just too much infrastructure changing.

Then there are problems inherent in OSRM, for example we basically only support amd64 as an architecture. We also do serialization in a way that depends on the compiler, stdlib and platform the user runs OSRM on. This binary dump is in no way stable and its format can change at any point in time. Having a packaged OSRM would imply greater stability that we can guarantee for.

With these issues in mind, we don't think OSRM makes a great package in any kind of stable release. I can tell you that we actually develop and test on Debian and Ubuntu systems, making sure users have all the information they need to build OSRM from source in the easiest way possible. At this point in time, we can not guarantee for more stability.

**Comment by sebastic** [comment]
[osrm (4.8.1+ds-1~exp1)](https://tracker.debian.org/news/720747) is available in the Debian experimental repository, and I've requested removal of the package from testing/unstable (in [Debian Bug #802772](https://bugs.debian.org/802772)) to not have it included in the next stable release. Because Ubuntu generally syncs its packages from Debian unstable (and from testing for LTS if I'm not mistaken), Ubuntu wily should be the only release to ship the osrm package, it should be automatically removed from xenial following its removal from Debian unstable.

If you object to the packaging in experimental we can have the package removed entirely, but the people who worked on the initial osrm package objected to its complete removal. Leaving the package in experimental only was deemed a reasonable compromise, as discussed in the [Removing OSRM from Debian](https://lists.debian.org/debian-gis/2015/10/msg00026.html) thread on the debian-gis list.

**Comment by TheMarex** [comment]
Not actionable anymore. We seem to be in `experimental` now. Closing.
