### ISSUE TITLE
Via points in route_instructions

### ISSUE THREAD

**Issue by drew-py** [Project-OSRM/osrm-backend#1748]
OSRM is fantastic for providing driving directions for routes with multiple stops using 'viaroute'.

Is there a way to use the API to insert steps in the route_instructions for the locations that the viaroute call is plotting the route between?

E.g.
Start from location 1
Left on X for 500m
Right on Y for 100m
Arrived at Location 2
Right on Z for 150m
etc.

**Comment by TheMarex** [comment]
Can you elaborate more on what you mean by

> insert steps in the route_instructions for the locations that the viaroute call is plotting

?

**Comment by roodrallec** [comment]
so that there is a way in the route_instructions to know when you've reached a point that you supplied as a via_route location. This could be useful, for example, to break down the leg times of a journey between the points you've supplied. I was hoping that the via_indices response would provide indices which would map onto the fourth element (the position tag) in one of the arrays returned by route_instructions, but have not found that this was the case.

**Comment by TheMarex** [comment]
You can just check if the turn instruction id is set to `8` as provided here: https://github.com/Project-OSRM/osrm-backend/blob/bb49e03435c4f71afbfc2bbbc645af8a8c168bed/data_structures/turn_instructions.hpp#L42

**Comment by drew-py** [comment]
@roodrallec's comment was what I was looking for and it seems that this reply is the solution.

If you can fish out the instruction id 8 items and match them in order to the returned via_route locations that is exactly what I was looking for. Thank you.
