### ISSUE TITLE
Highway not routable

### ISSUE THREAD

**Issue by freayd** [Project-OSRM/osrm-backend#1791]
Hello,

Strangely, this section of highway is not routable : http://map.project-osrm.org/?z=10&center=32.622852%2C106.004538&loc=32.411560%2C105.751305&loc=32.658996%2C105.934639&hl=en&ly=&alt=&df=&srv= I tried to identify any issue in the data but can't find anything wrong.

I'm not sure to understand the meaning but the small components layer highlights the south lane of the highway. Is it related to the routing issue? The resulting route seems to avoid this south lane by making a huge detour and going back to the closest point on the opposite (north) lane.

Any help appreciated!

**Comment by TheMarex** [comment]
@freayd yes the highway seems to be disconnected. I tried to trace it back but didn't find the original source of the problem.

**Comment by emiltin** [comment]
i don't understand why osrm refuses to route on places like this:

http://map.project-osrm.org/?z=18&center=32.417857%2C105.755092&loc=32.417560%2C105.755167&loc=32.418887%2C105.754824&hl=en&ly=&alt=&df=&srv=

the destination way is marked as a small component, which i guess is because it will not route on it.

**Comment by freayd** [comment]
Somehow it works now, although I haven't touched the data, maybe it was related to another bug which have been resolved in the meantime. @emiltin your example seems also to be routed correctly.

Thanks for help!
