### ISSUE TITLE
undefined reference to `RouteParameters::RouteParameters()'

### ISSUE THREAD

**Issue by JendaPlhak** [Project-OSRM/osrm-backend#1807]
I belive I have quite correctly installed OSRM, can see `libOSRM.a` file in `/usr/local/lib`. 
However when I compile following simple program with command `clang++ -std=c++11 -I/usr/local/include -L/usr/local/lib -lOSRM foo.cpp` 

    #include <osrm/route_parameters.hpp>
    #include <iostream>

    int main(int argc, char const *argv[])
    {
        RouteParameters params;
        params.output_format = "json";
        std::cout << params.output_format << std::endl;
        return 0;
    }

I get linker error 

    /tmp/foo-984c5f.o: In function `main':
    foo.cpp:(.text+0x21): undefined reference to `RouteParameters::RouteParameters()'
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Even though verbose output of linker shows 

    attempt to open /usr/local/lib/libOSRM.so failed
    attempt to open /usr/local/lib/libOSRM.a succeeded

That is just weird in my opinion... :-/

Clang++ version is `Ubuntu clang version 3.6.0-2ubuntu1~trusty1` but it is the same story with g++. System is ubuntu 14.04.

**Comment by woodbri** [comment]
Have you added /usr/local/lib to your ``ld.so.conf`` and run ``sudo ldconfig``

**Comment by JendaPlhak** [comment]
Well my `ld.so.conf` contains `include /etc/ld.so.conf.d/*.conf` and file `/etc/ld.so.conf.d/libc.conf` contains line `/usr/local/lib`. So I would say that's covered.

**Comment by woodbri** [comment]
I don't have a recent version of OSRM, but on my system ``locate libOSRM`` does not fine a .so only .a files.

**Comment by danpat** [comment]
@JendaPlhak Did you compile OSRM yourself?  Do you have any `libOSRM.a/.so` files anywhere else on your system?

**Comment by JendaPlhak** [comment]
Is it relevant? I indeed have only the .a file. But as I wrote, from the output of verbose linker I can be assumed that he is aware of libOSRM.a file.

**Comment by danpat** [comment]
@JendaPlhak It's possibly related, which is why I asked.  If your `libOSRM.a` file was generated with a different compiler/libstdc++ combination than the version of `clang` you're using now, it's quite possible that the symbols in the `.a` file don't match what your compiler is now generating based on the `.h` file you've included, and this leads to the Symbol Not Found Error.  This is known as "ABI compatibility", and it's a real pain in the C++ world.

It can be made to work, but nobody has put a lot of thought into it for OSRM.  If you've installed OSRM from binaries you've obtained elsewhere, you should either:

  a) Try to track down the compiler and libstd++ version that OSRM was built with, and use that, OR
  b) Build OSRM from source with the same compiler as you're using from your project

This way, you'll get consistent symbol mangling between codebases, and your symbol names will match.

**Comment by woodbri** [comment]
On 12/8/2015 1:26 PM, Jan Plhak wrote:
> Is it relevant? I indeed have only the .a file. But as I wrote, from the
> output of verbose linker I can be assumed that he is aware of libOSRM.a
> file.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Project-OSRM/osrm-backend/issues/1807#issuecomment-162969378>.
>

Make sure the the libOSRM.a that you have in /usr/local/lib is the one 
you compiled. Did you dos a ``sudo make install`` or copy the recently 
compiled libOSRM.a into /usr/local/lib otherwise you might have an old 
version there.

**Comment by JendaPlhak** [comment]
I have verified the time stamp after make install and it seems to be right. I will try to inspect the ABI issue.

**Comment by JendaPlhak** [comment]
Just a question - how can I change the compiler used by cmake and make?

**Comment by danpat** [comment]
You can instruct `cmake` which compiler to build into the generated makefiles with:

    CXX=g++-3.3 cmake

This will use `g++-3.3` as the compile command when you later run `make`.  You can replace `g++-3.3` with `clang++`, `g++-4.8` or whatever you like.

**Comment by daniel-j-h** [comment]
You have to explicitly tell CMake to build the shared library; this is how you would use GCC 5 and generate the shared library:

    env CPP=cpp-5 CC=gcc-5 CXX=g++-5 cmake .. -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON
    make -j $(nproc)

**Comment by TheMarex** [comment]
Closing as user error.
