### ISSUE TITLE
Service not Found on locate endpoint

### ISSUE THREAD

**Issue by aabanaag** [Project-OSRM/osrm-backend#1835]
encountered an error: 
<code>
status: 400
status_message: "Service not found"
</code>
running this request
<code>
locate?loc=14.568931,121.023415
</code>

Looked at the changes but haven't found any references on why the locate endpoint was removed.

**Comment by daniel-j-h** [comment]
We had this question coming up a few days ago in the IRC channel. Turned out the locate service was removed long ago because it required custom code in the rtree logic. No one noticed this for roughly a year, as it was not a popular service.

I updated the Wiki, removed the locate service, four days ago:

https://github.com/Project-OSRM/osrm-backend/wiki/Server-api/_history

Sorry for the confusion.
