### ISSUE TITLE
Offsets from StaticRTree are incorrect after traffic data updates

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#1857]
# Background

The `StaticRTree` stores an `EdgeBasedNode` struct, which contains `forward_offset`, `reverse_offset`, `forward_weight` and `reverse_weight`.  These values are calculated during `osrm-extract`.

If the traffic update features of `osrm-prepare` are used to update weights, the values stored in the `StaticRTree` are not currently updated.  This means that the `PhantomNode` offset values will be incorrect, leading to incorrect route lengths.

Practically, for a 2 coordinate route, the effect is probably quite small.  Traffic speeds that are close to the original esimates will mean that the offsets will only be wrong by a small amount, and in most cases, won't lead to different routing.

However, routes with lots of vias will be more significantly affected.  If traffic data is used, the `PhantomNode`s returned by the `StaticRTree` will not be in quite the right place, and the offset errors will compound along the route.

# The naive fix
The naive fix is to update the `StaticRTree` when new weights are loaded during `osrm-prepare`.  However, this will be a terribly expensive operation, as we would need to re-scan each compressed edge for each update to an offset made on a segment on that edge.  This will massively blow out the runtime for `osrm-prepare`, which is very undesirable for traffic updates.

# Proposed solution
The alternative is to calculate the offsets on the fly.  This will require retrieving segment durations (which will be up-to-date after traffic data imports), and calculating the offset values after the `PhantomNodes` are found.

https://github.com/Project-OSRM/osrm-backend/blob/1da1fa5a3174c8cc95b1b25e71323c9fc41fcad4/include/engine/datafacade/internal_datafacade.hpp#L427-L436

Similar to ^^, we could also fetch segment weights, then calculate the offsets.  This call would happen for each `via` in the request.

**Comment by MoKob** [comment]
would also love to stay in the loop here.

**Comment by TheMarex** [comment]
### Serialize out the information we actually need.

Luckily `CompressedEdgeContainer` already has the information we need: the duration for each segment. However we discard it on serialization [here](https://github.com/Project-OSRM/osrm-backend/blob/1da1fa5a3174c8cc95b1b25e71323c9fc41fcad4/src/extractor/compressed_edge_container.cpp#L78) (note that we only use `current_node.first`).

So we need to serialize out `second` as well.

### Remove `{forward,reverse}_{offset,weight}`

- [EdgeBasedNode](https://github.com/Project-OSRM/osrm-backend/blob/1da1fa5a3174c8cc95b1b25e71323c9fc41fcad4/include/extractor/edge_based_node.hpp#L73-L76)
- (fold offset and weight into one value) [PhantomNode](https://github.com/Project-OSRM/osrm-backend/blob/1da1fa5a3174c8cc95b1b25e71323c9fc41fcad4/include/engine/phantom_node.hpp#L59-L62)
- `EdgeBasedGraphFactory` [computation](https://github.com/Project-OSRM/osrm-backend/blob/1da1fa5a3174c8cc95b1b25e71323c9fc41fcad4/src/extractor/edge_based_graph_factory.cpp#L109-L125) and [construction](https://github.com/Project-OSRM/osrm-backend/blob/1da1fa5a3174c8cc95b1b25e71323c9fc41fcad4/src/extractor/edge_based_graph_factory.cpp#L138-L143)
- Maybe tune [LEAF_NODE_SIZE](https://github.com/Project-OSRM/osrm-backend/blob/1da1fa5a3174c8cc95b1b25e71323c9fc41fcad4/include/util/static_rtree.hpp#L40) as we now have smaller leaves -> speed up

### Adapt query

- Instead of getting the offset/weight values from the `EdgeBasedNode` we need to compute them
- That means we need acces to the compressed geomtry (Datafacade?)
- Use the `0 .. forward_segment_position` for computing the prefix sum of `forward_offset` and `num_edge_segments - forward_segment_position + 1.. num_edge_segments` for the `revese_offset` (don't trust my math here heh)
- Put the `offset + ratio * weight` in `PhantomNode`

### Adapt Datafacade

- Straight forward: Adapt the loading of the compressed geometry [here](https://github.com/Project-OSRM/osrm-backend/blob/1da1fa5a3174c8cc95b1b25e71323c9fc41fcad4/include/engine/datafacade/internal_datafacade.hpp#L174-L200)
- Don't forget to update `datastore` as well

### Adapt the update process

- We need to figure out a mapping OSM id based segments (u, v) to geometry index
- Easiest way I see is to go over _all_ compressed edges, uncompress them, walk over each segment (x, y) look up the original OSM id (should be saved in the .nodes file) and then figure out if we need to update this pair. (should be somewhat efficient if the osm segments are sorted lexicographical)
- I don't see a way how we could go directly from OSM based segments (u, v) to the id of the compressed edge (except maybe yet another lookup table)

**Comment by danpat** [comment]
Work progressing here: https://github.com/Project-OSRM/osrm-backend/tree/dynamic_offset_calc

**Comment by danpat** [comment]
Current state of the `dynamic_offset_calc` branch:

   - segment weights are now saved alongside compressed geometry
   - the GeospatialQuery has been updated to pull these weights when calculating offsets
 
Still TODO:

   - [ ] In the GeospatialQuery, Handle node-based-nodes that don't end up with compressed geometry - i.e. single-segment roads.
   - [ ] Remove offsets/weights from the EdgeBasedNode
   - [ ] Consider adjusting the branching factor and leaf node size now that the EdgeBasedNodes are smaller
   - [ ] Implement updating of these weight values during traffic data imports

**Comment by danpat** [comment]
In e1b69b17fe80f41f65e90e59784ad2998eb4a14b, I implemented the updating behaviour for all values.  All that remains is bugfixing and writing some test cases.

**Comment by TheMarex** [comment]
This has landed and seems to work.
