### ISSUE TITLE
No access to OSRM API 

### ISSUE THREAD

**Issue by lorenzobonora** [Project-OSRM/osrm-backend#1881]
Hi there,

I need your help.

We have a webapp running on OSRM API.
We have realized the update of the new massive release 4.9.0 on the 24 of December and it worked fine but since one week it stopped working.

Error given is:
XMLHttpRequest cannot load http://router.project-osrm.org/viaroute?instructions=true&alt=true&loc=40.4167754,-3.7037902&loc=40.9429032,-4.108806899999999. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://helloriders.es' is therefore not allowed access.

It seems we have been blocked or something similar.
Could you help me please?

Thanks in advance and king regards,

**Comment by daniel-j-h** [comment]
Please do not cross-post on the mailinglist and here, too. As I already replied on the mailinglist: 

The demo server has some hiccups from time to time, due to its nature of being a demo server.

Please also see the API usage policy for the demo server:
https://github.com/Project-OSRM/osrm-backend/wiki/Api-usage-policy
