### ISSUE TITLE
Inconsistency between trip and viaroute 

### ISSUE THREAD

**Issue by ZupoLlask** [Project-OSRM/osrm-backend#1943]
Hi guys!

I've stumbled upon some situations where `trip` considers points unroutable while `viaroute` considers otherwise... Which doesn't make any sense.

http://router.project-osrm.org/viaroute?loc=41.142845%2C-8.614152&loc=41.14159%2C-8.614842&loc=41.140832%2C-8.615275

http://router.project-osrm.org/trip?loc=41.142845%2C-8.614152&loc=41.14159%2C-8.614842&loc=41.140832%2C-8.615275

As you'll notice, while `viaroute` returns "Found route between points", `trip` returns 2 permutation groups, which is obviously unexpected.

**Comment by ZupoLlask** [comment]
From my research, it seems `viaroute` is finding a "nearest viable routing point" while `trip` isn't.

Can we make this consistent?

**Comment by TheMarex** [comment]
@ZupoLlask The snapping behavior is inherently different between `viaroute` and `trip`. Trip decomposes the trip into groups of points that are in the same component, while `viaroute` will just fail. This is due to algorithmic limitations since for the optimizations that trip does it is important that for all points A and B there exists a path A->B and B->A.

If you want to force the same snapping behavior as `viaroute` do the following: Make a `viaroute` request with the coordinates in any order. Save the `hint_data` from the response as outlined [here](https://github.com/Project-OSRM/osrm-backend/wiki/Server-api) and supply them over the `hint` parameter for each coordinate.

**Comment by ZupoLlask** [comment]
Will that proposed procedure produce less optimized trip results?

--
Helder Alves
+351912384076
Em 01/02/2016 15:13, "Patrick Niklaus" <notifications@github.com> escreveu:

**Comment by TheMarex** [comment]
@ZupoLlask no it just works around the different snapping behavior.
