### ISSUE TITLE
Switch profiles from Lua to library interface

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#1974]
Instead of relying on Lua for our profile needs I would like to change the interface of `libosrm_extract` to:

```
Extractor::Run(const Profile& profile)
```

```
class Profile
{
    virtual ~Profile() = default;

    virtual ExtractionWay processWay(const osmium::Way&) = 0;
    virtual ExtractionNode processNode(const osmium::Node&) = 0;
    virtual double processSegment(const Segment&) = 0;
}
```

This abstract over calling lua directly. `osrm-extract` can implement a `Profile` that uses all the current scripting code contained in `libosrm_extract` to be backward compatible in the meantime.

Long term goal is to _drop_ Lua as a dependency. Profiles will be moved to the `node-osrm` side and will be implemented in JS.

**Comment by daniel-j-h** [comment]
Would finally resolve https://github.com/Project-OSRM/osrm-backend/issues/1646.

**Comment by emiltin** [comment]
I think JS for the profiles is a good idea. In fact I was in favour of it back in issue nr 1(!) https://github.com/Project-OSRM/osrm-backend/issues/1

Only drawback is that people will have to rewrite their profiles.

**Comment by emiltin** [comment]
What timeline do you envision for moving profiles to JS? I started some refactoring of the LUA profiles, but wonder if it's still relevant.

**Comment by pnorman** [comment]
What would moving to JS over Lua gain?

**Comment by daniel-j-h** [comment]
Lua / Luabind is a major pain point. All known distributions bundle a Luabind version from 2010 that has major issues, e.g. not being able to build with recent Boost versions. Most distributions heavily patch Luabind, even brew uses the mapbox/luabind fork.

Although _some_ development has happened in Luabind, there has never been another official release. I reached out to popular Luabind fork maintainer and even the original Luabind devs, but only got a response from two of them. One developer wanted to keep his fork in C++03 compatibility mode. More discussion on the situation happened over at: https://github.com/Project-OSRM/osrm-backend/issues/1646

Here are some more Lua / Luabind user problems I could find that came up during the last months:

- https://github.com/Project-OSRM/osrm-backend/issues/1958
- https://github.com/Project-OSRM/osrm-backend/issues/1942
- https://github.com/Project-OSRM/osrm-backend/issues/1925
- https://github.com/Project-OSRM/osrm-backend/issues/1580
- https://github.com/Project-OSRM/osrm-backend/issues/1562
- https://github.com/Project-OSRM/osrm-backend/pull/1647#issuecomment-139059744

The benefits are:

- consolidating dependencies: @lbud is currently re-writing the cucumber test suite in cucumber.js so that we can get rid of ruby. A few weeks ago I already ripped out the osmosis dependency, so we also no longer depend on Java. With this change, we also no longer depend on Lua. node-osrm already depends on node, and these are the only supported bindings (from us).
- re-factoring the profiles: the profiles need a _huge_ refactor anyway: from global state to undocumented behavior and hacks; and when we're breaking things then we break it heavily and only once. @MoKob has some ideas re. profiles.
- for the future (no guarantees, but we're keeping a foot in the door here): user-provided sandboxed profiles not only during heavy pre-processing but in a more real-time'ish fashion.

**Comment by emiltin** [comment]
I'm almost done with a major rewrite of all the LUA profiles, amonst other things reorganizing the code into a class hierachy and splitting the code into methods. I understand we're moving to JS, which is think is a good idea, even so I think the rewrite can be useful. I can create a PR for review/discussion soon.
