### ISSUE TITLE
Consider Road Precedence for Turn Penalties

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#1997]
Driveways currently break OSRM profiles.
A turn past a driveway introduces turn penalties in OSRM that lead to funny routing results just like [this](http://map.project-osrm.org/?z=18&center=52.545513%2C13.493112&loc=52.545637%2C13.494489&loc=52.546292%2C13.491881&hl=en&ly=&alt=&df=&srv=).

Due to the additional intersections along the road, the direct connection becomes costly and is ignored, leading to an increase of distance by a factor of 4 over the shortest path.

**Comment by emiltin** [comment]
It's not caused by intersections or turn costs but by lanes=1.The southern street has maxspeed=30. The northern street also maxspeed=30 and in addition has lanes=1. Bidirectional roads with a single lane has their speed lowered to half.

Turns with a small angle (ie going almost straight ahead) incurs no or very small costs.

**Comment by MoKob** [comment]
Ah. Ok. Wasn't aware of that dirty hack. Well that explains a lot, but seems like a drastic measure.

**Comment by emiltin** [comment]
Well I wouldn't call it a hack. It's simply a choice in the profile. I agree 0.5 seems a bit drastic.

**Comment by TheMarex** [comment]
@MoKob accidental close?

**Comment by MoKob** [comment]
@TheMarex no, since the original issue is not relevant. What remains is just the known required cleanup of the profile.
