### ISSUE TITLE
Debug tiles don't properly clip geometry

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2003]
The tiles generated in the `debug_tileserver` don't properly clip lines.  This leads to badly formed vector tiles that render like this:

<img width="517" alt="screen shot 2016-02-20 at 10 08 04 pm" src="https://cloud.githubusercontent.com/assets/1892250/13201070/77a856b0-d81e-11e5-8234-2b3d5b1c0ad6.png">

They're most obvious when you zoom a long way in and line coordinates land outside the VT buffer zone.

Before calculating VT coordinates, individual geometries should be clipped to the bounding box of the vector tile being generated.

@springmeyer what's the lightest-weight way to get this done?  We only need to clip two-coordinate lines and points (trivial), is there a lightweight clipper library that doesn't add a lot of overhead?

**Comment by springmeyer** [comment]
I recommend `boost::geometry::intersection` - usage example at https://github.com/mapbox/mapnik-vector-tile/blob/75c4868d0900963c19e0adcd00ec8d5c87572a57/src/vector_tile_geometry_clipper.hpp#L156-L178

Note: clipping by bbox works for double coords but not integer coords (due to https://github.com/boostorg/geometry/pull/329) hence that code clips a line by a closed linestring.

**Comment by danpat** [comment]
Fixed with https://github.com/Project-OSRM/osrm-backend/commit/96f1c0a1a1dccfeb96bf0e5098f7b911e63134cf
