### ISSUE TITLE
Respect bearing and uturn for first coordinate

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#2013]
Given

- the first coordinate only allows bearings towards north into a deadend street
- the route will go south
- the first coordinate allows uturns

Then

- the first instruction should be a uturn

Currently

- the route will follow the deadend street to the end and do a uturn there

**Comment by danpat** [comment]
The problem here is that `bearing` filters out all edge candidates that don't match the direction.  The `uturn` has no options when this has happened.

What we should do here is that if `bearing` is true, then we allow not just matched forward edges, but their corresponding reverse edges as well.  Currently, the reverse edges are removed.

When `uturn` is false, we should maintain the current behaviour and filter out reverse edges.

**Comment by danpat** [comment]
To clarify the desired behaviour here:

If u-turns are enabled and a bearing is supplied, the RTree search should return PhantomNodes with both directions enabled.  Then, when we're constructing the instructions, if the chosen edge does not match the bearing, we should insert an initial u-turn instruction.

This needs to be applied to all vias and the endpoint as well.

**Comment by TheMarex** [comment]
This was fixed in a405d0d2a19bc1b0845c31d1dba3f354a82b57bf.
