### ISSUE TITLE
Organize headers in ./include to allow building external apps against in-place headers

### ISSUE THREAD

**Issue by springmeyer** [Project-OSRM/osrm-backend#2025]
Ideally an application that depends on libosrm could build cleanly by either using include flags like: `-I/path/to/osrm-backend/include` or `-I/usr/local/include` (when osrm-backend is installed into the `/usr/local` prefix.

Currently however this is not possible because the organization of headers between the local `include` folder and the installed folder differ:

One example is:

 - locally:  `include/engine/api/route_parameters.hpp`
 - installed: `include/osrm/engine/api/route_parameters.hpp`

(In this case this is with the `rewrite/new-api` branch).

Proposal: move all public headers into `./include/osrm/`. At the same time I think it would make sense to refer to all those headers using the `<osrm/header.hpp>` style within the OSRM backend code too. This is the convention I see with most C++ applications that are written as libraries.

/cc @TheMarex @daniel-j-h @lbud

**Comment by daniel-j-h** [comment]
This will not work, since the public headers still include e.g. `"engine/api/route_parameters.hpp"` (that is, not osrm prefixed).

I ran into this a week ago and worked around it as follows: we install files into $prefix/osrm, $prefix/osrm/engine and so on, so that the header includes still work. We then add $prefix/osrm to the include paths in addition to $prefix so that includes searching for "engine/.." still work.

- https://github.com/Project-OSRM/osrm-backend/commit/0fc87c4d276ea140c1db4acb6641605a412e0272
- https://github.com/Project-OSRM/osrm-backend/commit/97e47d64dfe81ee2e27bbe9c7dc05fcee761dcd6

**Comment by daniel-j-h** [comment]
After having a great talk with @joto about library design I'm tracking this in https://github.com/Project-OSRM/osrm-backend/issues/2031.

FYI: needs a somewhat drastic redesign.
