### ISSUE TITLE
Tagging bicycle lanes present at the center of the road during turn lane mapping

### ISSUE THREAD

**Issue by jothirnadh** [Project-OSRM/osrm-backend#2048]
The data team at Mapbox has been tagging `turn:lanes` to improve the guidance information in OSM. Details and discussion  [here](https://github.com/mapbox/mapping/issues/153) and [here](https://github.com/mapbox/mapping/issues/144)

We could use some help on the best way to to tag such a scenario, where a bicycle lane is in between car turn lanes:

![image](https://cloud.githubusercontent.com/assets/5991158/12560401/8861d14a-c368-11e5-9c6c-8133babbfa67.png)

Currently we tag turn lanes as we would by ignoring the bicycle lane all together.
![java openstreetmap editor 2016-01-25 20-35-24](https://cloud.githubusercontent.com/assets/369696/12560613/68d49646-c3a4-11e5-807e-c7b118dd34bd.png)
*we are tagging it as `turn:lanes= ||right`*

In most cases the bicycle lanes are at the extreme ends of the road and is not an issue, but what would be the best way to tag this so that it could be used by OSRM for navigation and guidance?

cc @Andygol @freenerd @MoKob @planemad @abhisheksaikia

**Comment by planemad** [comment]
@jothirnadh There is some detailed bicycle lane tagging scenarios in the [OSM Wiki](http://wiki.openstreetmap.org/wiki/Bicycle), but there is nothing that describes this scenario.

According to the [OSM:Key:lanes](http://wiki.openstreetmap.org/wiki/Key:lanes)
> The lanes=* key should be used to specify the total number of traffic lanes a road has which are available to motorised traffic wider than a motor cycle.
Thus the cycle lane should be ignored from the `lane` and `turn:lane` tags and the tagging decision is correct

Lane guidance based on this data would assume the road has a total of three lanes. If the driver had to turn right, the instruction would be `Take the rightmost lane to turn right` and this would be correct.

However the device would not able to reliably visualize the junction accurately for the driver. Could this result in a safety issue due to misrepresentation?

**Comment by TheMarex** [comment]
Lane guidance is primarily aimed at cars, as they usually are the only type of vehicle that can chose between multiple way. Thus I would expect turn lanes to capture lanes for cars only.

For bicycle routing it is more important to have tags like that specify if there is a bike lane and if its shared. (to prefer these ways in routing)

> However the device would not able to reliably visualize the junction accurately for the driver. 

I think simplifications are okay in a lot of cases. After all the driver still has road markings and the actual road to guide him.

> Could this result in a safety issue due to misrepresentation?

While it would be great to have a warning like "Use the right most lane, mind the shared bicycle lane", I think we will have a hard time capturing this in the data. That said an easy way to get the same feature is to just emit this warning every time a car turns from a road with a shared bicycle lane (without knowing if it would really block the drive path), just to be on the safe side.

**Comment by abhisheksaikia** [comment]
In a bid to get more eyes and reviews on the [Navigation Mapping guide](https://github.com/mapbox/mapping/wiki/Mapping-to-improve-navigation-data-in-OpenStreetMap),the team at Mapbox posted a communication on the [Talk](https://lists.openstreetmap.org/pipermail/talk/2016-March/075689.html) and [OSRM](https://lists.openstreetmap.org/pipermail/osrm-talk/2016-March/001148.html) OSM mailing list about our navigation mapping guide. The response from the community has been encouraging so far, with suggestions and feedback on how to further improve the guide.

I have gisted up the discussion on the [Talk-OSM](https://lists.openstreetmap.org/pipermail/talk/2016-March/075689.html) mailing list for anybody who wants extra background on this issue. 
1. https://gist.github.com/abhisheksaikia/a086e75e3c6ce91cf1b9
2. https://gist.github.com/abhisheksaikia/0a65c3ccfc1f8875d763

**The main point of discussion and feedback by the community was the inclusion of cycle lanes during counting `lanes=*` and also during `turn:lanes=*` mapping effort. The community is of the opinion that mapping cycle lanes during turn lanes is also crucial from the guidance point of view and present OSM tags do not adequately define the position of cycle lanes.**


### Present mapping scheme:
At present the team at Mapbox is using the following tagging scheme while mapping turn lanes and lanes:

> lanes=*
lanes:forward=*
lanes:backward=*
turn:lanes=*
turn:lanes:backward=*
turn:lanes:forward=*

* The bicycle lane has not been counted when tagging `lanes` and `turn:lanes`. The reason behind it is that the team is following the definition of lanes as mentioned in the [Key:lanes OSM wiki](http://wiki.openstreetmap.org/wiki/Key:lanes)

> The lanes=* key should be used to specify the total number of traffic lanes a road has which are available to *motorized* traffic wider than a motor cycle.

But the community is of the view that cycle lanes should also be counted as lanes and the definition in the [Lanes OSM wiki](http://wiki.openstreetmap.org/wiki/Lanes) should be followed:
> The subkey :lanes can be used to tag individual lanes of a road.
Please be aware that this extension covers all kinds of lanes for all kind of vehicles and is not restricted to motorized traffic.

### Proposed changes to the tagging scheme based on the suggestions by the community:

@planemad @maning and me discussed the changes that can be made in the process of mapping turn lanes and came across three specific scenarios while including bicycle lanes in mapping turn:lanes.

![screen shot 2016-03-15 at 5 23 13 pm](https://cloud.githubusercontent.com/assets/13744156/13776893/a1050c9e-ead2-11e5-8e53-a6ead946165b.png)

*A tagging scheme described in the [Lanes OSM wiki](http://wiki.openstreetmap.org/wiki/Lanes) which is relevant to this discussion*

### Scenarios

#### 1. The bicycle lane changes character from being a `designated` cycle lane near a junction and allows *motorized* traffic:

![screen shot 2016-03-15 at 5 36 58 pm](https://cloud.githubusercontent.com/assets/13744156/13777341/91471c5e-ead5-11e5-8e4b-d6b6b5178c76.png)

*The screenshot of a designated bicycle lane changing to a shared lane*


The tagging scheme proposed similar to the one in the [Lanes OSM wiki](http://wiki.openstreetmap.org/wiki/Lanes):

>  lanes=4
turn:lanes=left|||
vehicle:lanes=yes|yes|yes|yes 
bicycle:lanes=|||yes

Changes from our present tagging scheme:
* `lanes=4` instead of `lanes=3` counting the cycle lane as a lane.
* `turn:lanes=left|||` also including the cycle lane in the tagging
* `bicycle:lanes=*` and `vehicle:lanes=*` tag included to assign the motorized vehicle lanes and bicycle lanes.

#### 2. When a designated bicycle lane is not on the sides of the road but in the middle of lanes:

![screen shot 2016-03-15 at 5 58 19 pm](https://cloud.githubusercontent.com/assets/13744156/13777712/baf4cacc-ead7-11e5-9626-d004d00f3925.png)

* A bicycle lane in the middle of lanes and also in a bidirectional way*

The way is a bidirectional way and the following tagging system is proposed:

>  lanes=7
lanes:backward=4
lanes:forward=3
turn:lanes:backward=||through|right (the **through** indicated the bicycle turn lane)
bicycle:lanes:backward=||designated|
bicycle:lanes:forward=|designated|
vehicle:lanes:backward=yes|yes|no|yes
vehicle:lanes:forward=yes|no|yes

#### 3. When a bicycle lane is at both corners of a bi directional way:

![screen shot 2016-03-15 at 6 09 39 pm](https://cloud.githubusercontent.com/assets/13744156/13778029/5b992c9c-ead9-11e5-864c-52a6c07c1453.png)

* Designated bicycle lanes at both the corners of a bi directional way*

Proposed tagging scheme:

> lanes=7
lanes:backward=3
lanes:forward=4
turn:lanes:forward= left|||through
vehicle:lanes:forward=yes|yes|yes|no
vehicle:lanes:backward=yes|yes|no
bicycle:lanes:forward= |||designated
bicycle:lanes:backward= ||designated


@freenerd @MoKob and @TheMarex Can you have a look at this and your thoughts on whether these changes suggested by the community is really required from the OSRM point of view and if yes, is the proposed tagging scheme correct? Also, does the definition of `lanes` in the wiki needs to be changed to include all traffic rather than only `motorized` traffic as it is defined at present?


cc @jothirnadh

**Comment by TheMarex** [comment]
I think this will work to filter out bike lanes for car navigation. Only concerns:

1. People tagging `lanes:{forward|backward}=` without an indication what is bicylce and what is vehicle, needs manual verification of everything tagged in the old scheme
2. What is the default mode assumed if there are no bicycle lanes present? Car? Or is it always tagged explicitly over the `vehicle:lanes` key?

**Comment by MoKob** [comment]
Closing here, since nothing actionable in OSRM-backend and discussion seems stale. Feel free to re-open if further _guidance_ is needed.
