### ISSUE TITLE
A lot of warnings when extracting datasets

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2059]
Currently when running `osrm-extract` (on the latest `rewrite/new-api` branch) and the car profile on the Berlin dataset I get the following warnings:

> [warn] Graph Broken. Dead end without exit found or missing reverse edge.

Routing seems to work fine and I suspect the assumption behind the warning might be wrong.

/cc @MoKob

**Comment by MoKob** [comment]
@TheMarex no, the warning is correct but might be it should be disabled. It reports dead end streets that cannot be left. These often happen if the graph is cut out from a different point. Can also be related to small components. In general, a dead end street should not exist in a routing graph, since it would pile cars in the end.

**Comment by daniel-j-h** [comment]
What about moving them to the debug level (`logDEBUG`)?

**Comment by MoKob** [comment]
Its definitely a list of points (if we add coordinates) that we could give to the data team to make sure they get fixed. I don't care to much about which level they are on.

**Comment by daniel-j-h** [comment]
I can no longer see this warning on master, and I can't find references to it in the source code.

These are the only warnings I get on Berlin:

    [warn] Restriction references invalid node: X
    [warn] Restriction references invalid way: Y

@MoKob I suppose you removed it? Can we close this ticket?

**Comment by MoKob** [comment]
The respective warning is removed.
