### ISSUE TITLE
Length Zero Segments

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#2096]
https://github.com/Project-OSRM/osrm-backend/blob/rewrite/new-api/include/engine/guidance/assemble_steps.hpp#L62-L143 does a step-back from OSRM-4.9.

Given a coordinate that snaps to an intersection of two roads, we have to select a phantom node pre-route. This can result in an additional turn-instruction both at the front and at the end of the route.

E.g
(1)
a ----- b
 |
 | 
 c
(2)

This could result in `Head West on (ab) for 0 m`, `Turn Left onto (ac)`, `Arrive at (2)`, when routing from `(1)` to `(2)`.

In my view, the removal of this additional segment in the front/back is something that we should keep.
The Route (1)-(2) should result in `Head South on (ac)`, `Arrive at (2)`.

/cc @TheMarex

**Comment by TheMarex** [comment]
This should be solved in post-processing not during initial assembly to reduce code complexity. This is just a special case of segment merging - we should detect similar cases of absurdly short segments (say below 2 meters) and merge them to the previous/next segment.

How do you see this integrated into `include/guidance/post_processing.cpp`? I see that you operate on `PathData` instead of `RouteStep` objects. It would be beneficial if you could port this to use `RouteStep`, which would enable easier layering (also the `PathData` is already filtered and assembled into segments, which is what you are actually interested at that point, no?).

**Comment by danpat** [comment]
@TheMarex we should consider http://wiki.openstreetmap.org/wiki/Tag:highway%3Dstop#Tagging_minor_road_stops
before doing any merging.

**Comment by TheMarex** [comment]
@danpat this would happen post-routing when the after instructions are generated. We don't even have knowledge about stop signs at this level.

**Comment by MoKob** [comment]
Wherever you solve it, it requires to adjust stuff thats stored in the phantom node in ways that are hard to do, when you use preprocessed data in that phantom-node.

**Comment by TheMarex** [comment]
@MoKob this was addressed by moving `post-processing` to `RouteStep`, right?

**Comment by MoKob** [comment]
No. It just no becomes possible to solve it. So far the segments are processed as they come from `assemble_steps` and `assemble_geometry`. The post-processing still needs to handle unnecessary segments in the front-back.

**Comment by MoKob** [comment]
fixed with https://github.com/Project-OSRM/osrm-backend/issues/2159
