### ISSUE TITLE
Remove two branch system

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2112]
Currently we are using a workflow were `develop` is the unstable development branch and `master` is the stable main branch. Releases are done by merging develop into master.

For the `5.0` release we are going to merge `develop` into `master` one last time **and then only work on `master`**. Then we switch the default branch to `master` and **deleting the `develop` branch**.

We will do the same for `node-osrm`.

Rational behind this change is that its hard to figure out which git tag points to which commit in `develop` since tags are only created on the merge commits in `master`.

**Comment by daniel-j-h** [comment]
Sounds reasonable, but we should make sure the documentation consistently shows checking out master _and then a specific tag_, otherwise users will always run what is now develop by default.

In addition, making proper releases on Github: https://github.com/Project-OSRM/osrm-backend/releases (up till now these are only auto-releases based on tags)

**Comment by daniel-j-h** [comment]
Master is the default now for both osrm-backend as ell as node-osrm.
