### ISSUE TITLE
Some points are missing as a result of the request

### ISSUE THREAD

**Issue by Ganipolsky** [Project-OSRM/osrm-backend#2143]
For 12 point 
http://router.project-osrm.org/trip?instructions=false&geometry=false&loc=55.574920,37.655074&loc=55.744380,37.499190&loc=55.800220,37.543990&loc=55.784000,37.560021&loc=55.833198,37.497207&loc=55.840699,37.487208&loc=55.855594,37.478292&loc=55.865270,37.437910&loc=55.858200,37.426900&loc=55.809860,37.461470&loc=55.806611,37.466557&loc=55.789470,37.478830
Result
permutation":[1,3,2,11,10,9,4,7,8,0]
Absent point 5 and 6

**Comment by vvk95** [comment]
Points 5 and 6 located on an "islands", without links with the main road network. Therefore, they were placed in separate trips in result response.

Point 5 - because the roads are tagged "access=no". You can edit your lua profile, if you have your own osrm local server.
Point 6 - because there is a road connection error.

**Comment by Ganipolsky** [comment]
Thank you so much
