### ISSUE TITLE
OSRM on IPFS ?

### ISSUE THREAD

**Issue by temsa** [Project-OSRM/osrm-backend#2144]
How hard would it be to run OSRM with data over [IPFS](http://ipfs.io/) ?

This could be super useful as people could share their build of a part of the planet, or the whole planet easily:

- for servers, as you can run a server without having the whole data or no data at all locally at start at least, and each server would share some parts of it as the local ipfs daemon would share it

- for the project as a demo, so people could try running in a few minutes the project over the whole planet, without it requiring costly infrastructures for the project, and no big memory / big harddrive / big cpu

**Comment by daniel-j-h** [comment]
The problem with sharing data files: https://github.com/Project-OSRM/osrm-backend/issues/825#issuecomment-169690824.

Even if the files were portable, there is a reason we load everything from disk and even lock the virtual address space to RAM in the server: to not hit the disk. I can't think of what an additional network layer does to the latency.

**Comment by temsa** [comment]
Files are immutable in IPFS, meaning they can be stored forever.

The IPFS daemon maps the whole ipfs network into a local mountpoint `/ipfs` ( yet mutation can be done through the "name resolution" of `/ipns`, more or less the equivalent of an ip in a network for ipfs, and an domain name for ipns ).

Files stored in ipfs are named by their hash, so they are unique for the same content in the network, and you can access them like a localfile through `/ipfs/<hash>` (with `<hash>` beoing actually the hash of the file).

In fact, if you read a file, chances are the daemon will store them locally, or at least parts of it. I do not know yet if ipfs knows how to only map the reading of the part of a file, so it would lazily download what you need from the network.

My guess is, the blocking parts for OSRM running above IPFS would be : 

- the name convention ( relying on a directory with different extensions on different files, if I'm not wrong about that ). It can be circumvented through symbolic links, yet would be impractical

- the portability of the files.

BTW, if generated files would be readable by block (ideally the size of an ipfs block) it would certainly feat pretty well with the usage.

**Comment by daniel-j-h** [comment]
> My guess is, the blocking parts for OSRM running above IPFS would be :
> 
>   -  the name convention ( relying on a directory with different extensions on different files, if I'm not wrong about that ). It can be circumvented through symbolic links, yet would be impractical
> 
>   -  the portability of the files.

The OSRM toolchain takes e.g. a `france.osm.pbf` pre-processes it and saves a handful of `france.osrm.*` files. It then reads the files based on the `france.osrm` base path using file based I/O.

It does not matter which VFS implementation is getting used, e.g. you can put the files on a `tmpfs` and it will work just fine. Not sure how IPFS handles this, but in a similar way `tmpfs` works, you could write your own VFS implementation (e.g. via [FUSE](https://en.wikipedia.org/wiki/Filesystem_in_Userspace)) and then dispatch the I/O calls to whatever backing store you want to.

As mentioned in the ticket I linked above, files depend on architecture, endianess, compiler, stdlib, .. just to name a few. In theory it should work in cases when you run e.g. the same software stack (say Ubuntu and its packages) on the same machines.

**Comment by danpat** [comment]
@temsa Are you imagining a situation where OSRM would not keep data in memory, but would read data from disk as requests arrive?

If that's the case, then the idea is probably a non-starter.  OSRM is designed as a high-performance routing service - it can serve hundreds (perhaps thousands?) of routing requests per second, and a big part of that is avoiding I/O.  If data resided primarily on disk, and we didn't keep everything in RAM, the I/O overhead would have a massive impact on performance numbers - this isn't something we will want to do.

Also, with regard to distributed processing - the OSRM datafiles are highly intertwined.  The Contraction Hierarchy approach that OSRM uses means that it's quite difficult to divide up the data files into more manageable pieces - the CH algorithm prefers to operate on the whole graph at once.  Any change here would be a major undertaking, and it's likely that because of the data sizes, overall performance would drop.  We'd gain distributed processing, but we'd lose because so much data would need to be moved around.

There are other graph acceleration algorithms that are much more amenable to processing parallelization, but at this stage, OSRM doesn't implement any of them :-(

**Comment by temsa** [comment]
@danpat : I know what can do OSRM ! :+1:  I'm using it for more than a year for the whole France and it works great (albeit being a bit too much optimistic for travel time in big cities, even with no traffic), using about 5GB of disk and 1.5GB of ram wrapped in a node-osrm app, it can serve at least hundreds of request per seconds : with tens of them I barely use more than 0-3% of the CPU to do both my business logic and the queries.

My vision was not something only used through network, but I was seeing the possibility of something providing lazy loading, meaning it reads only what it needs from the disk/network, so if all your queries are on a particular city, you would not need to load the full world in memory (and the first query being long would have been ok).

I guess CH has it's limit ( including realtime traffic if I remember well, you can only implement statistic traffic ), and making it run above some block based data would be pretty hard if not impossible.

Too bad, the only problem I see running OSRM for a lot of project is it's long build time, it's big RAM usage (which is even quite massive if you want to go fast for the build, ~160GB of RAM for building the world, and for running, not building, something big like the France it's already more than 1GB), and quite some disk usage too.
Running it above IPFS would have abled to share world builds and run directly above it, yes first queries would have been slow, yet certainly not as slow as building the world yourself.

Thanks for your answer anyway :)

**Comment by temsa** [comment]
BTW @daniel-j-h I was thinking, with a proper 'namespacing' for the software stack (architecture, endianess, compiler, stdlib,... ), we could still share files in a smart way ( most people interested in OSRM are likely to run either MacOSX latest version or Ubuntu latest version, on X86, for a start).

So the only remaining issue for at least sharing properly builds would be the naming issue, as you cannot create a `france.osrm` on IPFS, as file names are only hashes, they cannot have a nice name, not can you rely on a glob pattern to match them like `france.osrm.*`

Just for reference, and because parts of the problem is the same, you can have a look at the [EverythingStays](https://github.com/EverythingStays/EverythingStays) project, which aims at providing `npm` packages over `IPFS to avoid recent issues there was with NPM

**Comment by danpat** [comment]
@temsa We looked into alternative ways of loading OSRM data (https://github.com/Project-OSRM/osrm-backend/issues/1947) that might make this approach easier - unfortunately, there seem to be some performance side-effects that we don't want.

If we can get `mmap` performing similarly to direct memory access, that would probably enable using IPFS like you're describing.

The remaining work would be around disk locality - making sure that geographically nearby data is nearby on disk, so that filesystem caching is effective.  The RTree (used for nearest-neighbor searches) already does this using Hilbert curves.

I suspect CH will get in the way here - contracted graphs have shortcuts that span massive geographical distances - I don't know if there is a way to optimize disk locality there, so performance might always be terrible :-(

**Comment by daniel-j-h** [comment]
Closing this since it's not actionable for us.
There's a ticket towards a better and more portable file format: https://github.com/Project-OSRM/osrm-backend/issues/2242.

Related: I got a IPFS sticker :P
