### ISSUE TITLE
Coordinate parsing should allow integers

### ISSUE THREAD

**Issue by miccolis** [Project-OSRM/osrm-backend#2173]
Currently a path like `/route/v1/bicycle/80,80;80,0.json?steps=true&alternatives=false` will get `{ code: 'InvalidQuery', message: 'Query string malformed close to position 11’ }`

I noticed this when running `./node_modules/.bin/cucumber.js features/testbot/planetary.feature `

**Comment by daniel-j-h** [comment]
Here's a small self-contained reproducible test-case:

```c++
#include <vector>
#include <string>
#include <iterator>
#include <iostream>

#include <boost/spirit/include/qi.hpp>

using namespace boost::spirit;
using namespace boost::spirit::qi;

int main() {
  const std::string input{"4.0.json"};

  auto first = begin(input);
  const auto last = end(input);

  std::vector<double> into;

  const auto ok = parse(first, last,                  //
                        (int_ | double_) >> ".json",  //
                        into);

  if (ok && first == last) {
    std::cout << "Ok, got: ";
    for (auto&& each : into) std::cout << each << " ";
    std::cout << "\n";
  } else {
    const auto pos = std::distance(first, last);
    std::cerr << "Error at position: " << pos << "\n\n";
    std::cerr << input << "\n" << std::string(pos, ' ') << "^\n";
  }
}
```

Output:

```
Error at position: 8

4.0.json
        ^
```

**Comment by daniel-j-h** [comment]
For the record, this is what I got so far going down the Spirit :rabbit: hole:

For parsing `1,2;3,4.json` ideally we could use `((double_ % ",") % ";") >> ".json"`.

Spirit's `parser % seperator` DSL expands to `parser >> *(seperator >> parser)`. We can simplify the test case to a trivial `double_ >> ".json"`; once this works the other pieces just fall into place.

`double_ >> ".json"` parses `4.1.json` fine but fails on `4.json` since the primitive `double_` parser is too greedy.

Spirit's DSL maps to PEG (Parsing Expression Grammar); it may look like EBNF but the choice operator `|` is evaluated from left to right in PEG. So the next logical step is to make use of this:

Unfortunately `(int_ | double_) >> ".json"` also fails to parse `4.json`.

**Comment by danpat** [comment]
@daniel-j-h Tried `(double_ | int_) >> ".json"` ?

Assuming those are tried in-order, maybe that will work....

**Comment by daniel-j-h** [comment]
Nope does not help either. Currently looking into Spirit v2 details and reaching out to some guys.

Forcing the user to always add a `.0` for full digits _could_ be an option, but it's just oh so ugly.

**Comment by daniel-j-h** [comment]
((double_ >> ".") | (int_ >> ".")) >> "json"

Parses both `4.json` and `4.1.json` into a `double` just fine, but parsing `4.json` into a `vector<double>` results in a vector with _two_ elements: `{4, 4}` --- wat.

**Comment by daniel-j-h** [comment]
We need to use the `hold` directive to at least solve the issue with two 4s in the vector. This is due to alternative parsers pushing unconditionally into the vector, so if the first alternative fails its pushed elements are still in the vector and the second alternative runs pushing itself into the vector.

    (hold(double_ >> ".") | (int_ >> ".")) >> "json"

http://lists.boost.org/boost-users/2016/03/85960.php

http://www.boost.org/doc/libs/1_55_0/libs/spirit/doc/html/spirit/qi/reference/directive/hold.html

This solves correctly parsing the last number followed by ".json" (be it e.g. "4.0.json" or "4.json"). Still needs integration into the final parser for ";"-separated ","-pairs.

**Comment by daniel-j-h** [comment]
Following up on the conversion from yesterday, Rainer Deyke came up with

    ((double_ % ",") % ";") >> -lit('.') >> "json"

which works for our use case but also accepts "1,2;3,4json".

**Comment by daniel-j-h** [comment]
^ this is the hacky way that does not require backtracking; @TheMarex you're okay with this? Or should we use a strict real parser policy always requiring the "." in numbers?

Keep in mind we already successfully parse +number, -number, -inf, +inf, -nan, etc.

**Comment by TheMarex** [comment]
@daniel-j-h for now accepting `4json` long with `4.json` and `4.0.json` is okay with me.

**Comment by daniel-j-h** [comment]
With https://github.com/Project-OSRM/osrm-backend/pull/2188/commits/ebb6fa987be0816d3a6ba77f849fd41ef415c2d9:

    $ http 'http://localhost:5000/route/v1/driving/7.416351,43.731205;7.420363,43.736189;7.420363,43.736189.json \
      | jq '.code'

    "Ok"

but also

    $ http 'http://localhost:5000/route/v1/driving/7.416351,43.731205;7.420363,43.736189;7.420363,43.736189json' \
      | jq '.code'

    "Ok"
