### ISSUE TITLE
Query syntax error position indicators

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2193]
When there's a syntax error in the query part of a URL, but the service/version/profile part parses OK, the error position in the message refers to the error offset within the query part only, not the whole URL.

This is a change from previous behaviour, the syntax error position was previously relative to the first char in the PATH_INFO part of the URL.

Example:

`route/v1/driving`
gives
`URL string malformed close to position 0: "/ro"`

but

`route/v1/driving/1,1,1`
gives
`Query string malformed close to position 3`

It's not technically wrong, but it's not obvious what `position 3` is relative to.

**Comment by daniel-j-h** [comment]
The reason for this is URL parsing happening in `request_handler.cpp` (see the `parseURL` call chain), after that only the query part is passed on and parsed separately in each `*_service.cpp`.

**Comment by TheMarex** [comment]
@daniel-j-h this should be fixed by https://github.com/Project-OSRM/osrm-backend/pull/2312 and your expectation point work, no?

**Comment by oxidase** [comment]
@TheMarex no, it will not fix, because `query` argument in parameter parsers does not contain "/route/v1/profile/" prefix. With the change
```
-    virtual engine::Status RunQuery(std::string &query, ResultT &result) = 0;
+    virtual engine::Status RunQuery(std::size_t prefix_length, std::string &query, ResultT &result) = 0;
``` 
it could be possible to compute the prefix length at parse time, pass it into query handler and compute correct positions. If the change in BaseService is ok, I can create a PR to fix the issue in the evening.
