### ISSUE TITLE
Release 5.0.0 RC1

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2197]
```
E-Mail

We pushed out the first RC for 5.0.0. As the version indicates this release breaks the backwards compatibility of the public API. The HTTP API was completely rewritten and is now a little bit less verbose. We refactored the C++ library interface as well, making it a lot easier to consume. Explore `example/example.cpp` on how to use it. Please let us know if you find any bugs that go beyond the known issues below.

- Renamed osrm-prepare into osrm-contract
- osrm-contract does not need a profile parameter anymore
- New public HTTP API, find documentation [here](https://github.com/Project-OSRM/osrm-backend/wiki/New-Server-api)
- POST support is discontinued, please use library bindings for more complex requests
- Removed timestamp plugin
- Coordinate order is now Longitude,Latitude
- Cucumber tests now based on Javascript (run with `npm test`)
- Profile API changed:
   - `forward_mode` and `backward_mode` now need to be selected from a pre-defined list
   - Global profile properties are now stored in a global `properties` element. This includes:
     - `properties.traffic_signal_penalty`
     - `properties.use_turn_restrictions`
     - `properties.u_turn_penalty`
     - `properties.allow_u_turn_at_via`

Known issues:
- Units uncovered that zero-length trips might have a duration bigger than zero #2134
- pkg-config does not work as expected, include paths might be insufficient #2195
- Position hint on requests with syntax error might be off #2193
- Queries with integer coordinates might fail to parse if `.json` is added #2173

As always this release is in sync with a `node-osrm` release. `npm install https://github.com/Project-OSRM/node-osrm/archive/v5.0.0-rc.1.tar.gz` (we don't publish pre-releases because of he semantic versioning bug in npm were 4.9.1 < 5.0.0-rc.1, that means new users would suddenly download the RC)

This release was made possible by: @daniel-j-h, @danpat, @karenzshea, @lbud, @miccolis, @mokob, @springmeyer, @themarex, @willwhite

We expect to push out at least another RC before we tag `5.0.0`.

Cheers,
Patrick
```

- [x] Tag `osrm-backend` `v5.0.0-rc.1`
- [x] Tag `node-osrm` `v5.0.0-rc.1`

**Comment by TheMarex** [comment]
Getting a link error while building node-osrm, delaying until monday, if someone doesn't figure it out.

**Comment by springmeyer** [comment]
I see two new link errors.

1) boost_test_main

This one is happening because `-DBOOST_TEST_DYN_LINK` is hardcoded in the `osrm-backend/CMakeLists.txt` but a static `libboost_unit_test_framework.a` is used. They way boost works a shared library is needed if `-DBOOST_TEST_DYN_LINK` is set and a static library is needed if it is not set.

The easiest solutions to this I can think of are:

a) make it possible to disable osrm-backend putting `-DBOOST_TEST_DYN_LINK` in the build flags.
b) make it possible to disable building the unit tests altogether so node-osrm can just dodge this problem

More background on this...The use of a static library is critical currently for node-osrm because otherwise the osrm-extract and other command line binaries would not be portable until https://github.com/Project-OSRM/osrm-backend/issues/2065 is fixed. What is currently happening to allow them to be portable is that the linker notices `libboost_unit_test_framework.a` is unnused and then discards it as a dependency. This does not happen when a dynamic library is used.

Once https://github.com/Project-OSRM/osrm-backend/issues/2065 is fixed then we can move to the mason package that uses a shared library https://github.com/mapbox/mason/blob/master/scripts/boost_libtest_shared and still avoid having to bundle that unnecessary shared library to keep the command line tools working.

2) boost iostreams zlib missing

```
Undefined symbols for architecture x86_64:
  "_deflateInit2_", referenced from:
      boost::iostreams::detail::zlib_base::do_init(boost::iostreams::zlib_params const&, bool, void* (*)(void*, unsigned int, unsigned int), void (*)(void*, void*), void*) in libboost_iostreams.a(zlib.o)
  "_deflateReset", referenced from:
      boost::iostreams::detail::zlib_base::reset(bool, bool) in libboost_iostreams.a(zlib.o)
  "_inflateInit2_", referenced from:
      boost::iostreams::detail::zlib_base::do_init(boost::iostreams::zlib_params const&, bool, void* (*)(void*, unsigned int, unsigned int), void (*)(void*, void*), void*) in libboost_iostreams.a(zlib.o)
  "_deflateEnd", referenced from:
      boost::iostreams::detail::zlib_base::reset(bool, bool) in libboost_iostreams.a(zlib.o)
  "_inflateReset", referenced from:
      boost::iostreams::detail::zlib_base::reset(bool, bool) in libboost_iostreams.a(zlib.o)
  "_inflate", referenced from:
      boost::iostreams::detail::zlib_base::xinflate(int) in libboost_iostreams.a(zlib.o)
  "_deflate", referenced from:
      boost::iostreams::detail::zlib_base::xdeflate(int) in libboost_iostreams.a(zlib.o)
  "_inflateEnd", referenced from:
      boost::iostreams::detail::zlib_base::reset(bool, bool) in libboost_iostreams.a(zlib.o)
  "_crc32", referenced from:
      boost::iostreams::detail::zlib_base::after(char const*&, char*&, bool) in libboost_iostreams.a(zlib.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [server-tests] Error 1
make[1]: *** [CMakeFiles/server-tests.dir/all] Error 2
```

This is happening because the boost_iostreams mason package was built without zlib support (intentionally since it was previously not required). It looks like this is also an error coming from the tests. Can we just disable the building of the tests somehow but adding a cmake option? Ideally we don't want any extra dependencies to the portable binaries that are not required - I presume the zlib requirement is only for the unit tests?

**Comment by springmeyer** [comment]
> This is happening because the boost_iostreams mason package was built without zlib support (intentionally since it was previously not required).

Wait, I was wrong. It looks like just adding `-lz` to the linker line (I tried this manually) fixes the problem. So it seems like osrm-backend is missing adding `-lz` somewhere in the build?

**Comment by TheMarex** [comment]
I worked around the linking errors by pulling the tests from the default target again. Hopefully this should run through now.

**Comment by TheMarex** [comment]
RC 1 is released.

**Comment by springmeyer** [comment]
new pulls to attempt to fix the issues above at https://github.com/Project-OSRM/osrm-backend/pull/2234 and https://github.com/Project-OSRM/osrm-backend/pull/2233
