### ISSUE TITLE
Remove summary

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2214]
Generating a summary is cost intensive and has little gain.

1. we don't want to put it behind a flag, because more options
2. it only makes sense with `alternatives=true` + `steps=true`
3. it costs a lot of time to compute
4. it can be computed on the client as well (maybe even better?)

Proposal: Drop summary generation completely.

/cc @freenerd

**Comment by freenerd** [comment]
Yes :+1: 

The only use case I see for it is comparing alternative routes and showing the difference between them in a text-only interface. I think ETA/Distance are better indicators though, the ultimate choice determinator likely will be displaying the overview geometry on a map though, so that's preferred.

**Comment by daniel-j-h** [comment]
Done in https://github.com/Project-OSRM/osrm-backend/issues/2220.
