### ISSUE TITLE
32-bit node IDs as an option?

### ISSUE THREAD

**Issue by jcoupey** [Project-OSRM/osrm-backend#2264]
This sums up a discussion happening on the OSRM irc channel.

The move to 64-bit node IDs (#322) has increased some requirements during `osrm-extract`. This was pushed by the node IDs getting above 2^32 but the limitation is not the number of nodes itself. So it might be useful in some cases to be able to got back to a 32-bit mode after renumbering the nodes with [osmium-renumber](http://docs.osmcode.org/osmium/latest/osmium-renumber.html).

Questions raised:
- is there more to it than just changing: https://github.com/Project-OSRM/osrm-backend/blob/develop/include/util/typedefs.hpp#L39?
- how would this benefit the overall data-preparation performance?
- would this allow to increase the size of the extracts that OSRM can handle on a given hardware configuration?
- what kind of extract size can `osmium-renumber` handle? 

On the last point, the man page states that `osmium-renumber` is intended for small extracts, but @systemed reported it has recently been made much faster and memory efficient (https://github.com/osmcode/osmium-tool/commit/75d30caa2cc401280e762fd9d09b6d31f4b1855d).

**Comment by TheMarex** [comment]
We plan to expose OSM node ids soon for linear referencing the route #2054. Hence we rely on the fact that the ids in the data dump are actually the real OSM ids. I don't think its worth the trouble of maintaining a switch to make this an option. It would also mean that we have an option that would break anything that we do in #2242.

This switch didn't actually increase the memory usage on the server side. Pre-processing got slower. But then again we have not done any investigation into `osrm-extract` performance in the last few releases. There might be a lot of low-hanging fruit, w.r.t to data that is written on disk an never used again. A slower `osrm-extract` only means slower turn-around times for full data updates. This has a low priority for us.

If we tackle #2242 we can expect a lot of the waste in `osrm-extract` to go away since we need to rewrite the storage layer for this.

**Comment by jcoupey** [comment]
I see there are lots of good reasons not to go this way on a "mainstream" version. 

My main concern was not the data turn-around time (even if it's nice to have a faster extraction). I was tempted to try this in order to raise the maximum extract size a given machine can handle. Maybe I'm mistaken here and a bottleneck would remain in `osrm-contract` (rather than `osrm-extract`)?

**Comment by TheMarex** [comment]
@jcoupey usually osrm-extract is very tame on memory usage compared to osrm-contract.

**Comment by jcoupey** [comment]
Ok, so it all comes down to speeding up the extraction, which might happen too anyway if you refactor that part of the code. Not sure this is worth the trouble...

**Comment by danpat** [comment]
I'd be dubious that there would be any significant advantage to pre-running `osmium-renumber`.

Fundamentally, renumbering requires keeping a map of all the nodeIDs in memory.  OSRM is already doing this, we renumber the 64bit values into 32bit "internal node ids", because we know that we're only using a fraction of all the nodes in most OSM files (of the 3,313,970,004 nodes in the latest planet, the `car` profile only keeps 585,662,259, that's lots of breathing room in 32bit space).
