### ISSUE TITLE
Too many "new name" instructions

### ISSUE THREAD

**Issue by MKergall** [Project-OSRM/osrm-backend#2273]
We get repeated "new name" steps, even when the road name doesn't change. This typically happens on highways. 

Example: request the route from Poznan to Warszawa: you will get numerous "new name" steps, all having name = "Autostrada Wolnosci (A2)". 
Test url: http://router.project-osrm.org/route/v1/driving/16.920218,52.400392;21.006726,52.231922999999995?alternatives=true&overview=full&steps=true

(This is a relatively minor issue. The service is working fast and fine, and this new API is a huge progress. Congratulations to the team!)

**Comment by MKergall** [comment]
(could be redundant with: issue #2263)

**Comment by MoKob** [comment]
I've had a look at the OSM data. It seems that (at least all the locations I checked) are data issues.
They contain segments for which the name of the motorway is missing (e.g. segments in tunnels or under bridges that are unnamed).

We have a patch ready for 5.1 (https://github.com/Project-OSRM/osrm-backend/pull/2262)  that detects many of these short name-changes and suppresses them.

Still, this is mostly a data issue that, even though we can detect it, should be fixed in the data.
