### ISSUE TITLE
Textual instructions in the response

### ISSUE THREAD

**Issue by MKergall** [Project-OSRM/osrm-backend#2308]
The new OSRM API improved the level of detail of instructions - which is good. 
And we see various plans (from @MoKob) to improve this even further. 

But this is increasing the complexity on client side, to transform those informations in readable instructions. 

Could OSRM propose an option where textual instructions are built on server side (with support for language choice) and provided in the response - as done by most of other routing engines?

**Comment by TheMarex** [comment]
We have no immediate plans to do this, at least as long we are have a C++ HTTP server. This might change if we move that to `node-osrm` since that would mean we could reuse the code easily.

Some problems associated with this:

- We want to be able to update instructions without going through native builds
- Handling localization is complex
- We actually found that most client applications want to do their own textual instructions, mostly to have complete control which information is exposed to the user and being able to use platform specific localization for the whole app.

**Comment by daniel-j-h** [comment]
There is now https://github.com/Project-OSRM/osrm-text-instructions - work in progress.

Feel free to contribute to it or open tickets if you encounter issues.
