### ISSUE TITLE
Windows compilation error LNK2019: unresolved external symbol XML_ParserCreate [...]

### ISSUE THREAD

**Issue by jperaltamalvar** [Project-OSRM/osrm-backend#2364]
I am using Visual Studio Community 2015 (14.0.23107.0 D14REL)

I followed instructions from the [wiki](https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation).
  
See all build errors in attached file: [build_errors.txt](https://github.com/Project-OSRM/osrm-backend/files/247130/build_errors.txt)

**Comment by BergWerkGIS** [comment]
@jperaltamalvar your are using an outdated RC, please update your Visual Studio install to the latest version (currently `14.0.25123.00 Update 2`):
https://www.visualstudio.com/en-us/downloads/download-visual-studio-vs.aspx
https://www.visualstudio.com/en-us/news/vs2015-update2-vs.aspx

and let me know, if this helps?

OSRM makes heavy use of modern C++ features and a lot has happened with Visual Studio's C++ support since the RCs (RTM, Update 1, Update 2).

**Comment by jperaltamalvar** [comment]
Thanks for you feedback!

I've updated VisualStudio, now `14.0.25123.00 Update 2`, deleted the "build" folder to avoid caches but I'm still getting the same error (exactly the same build_errors.txt).

Searching other errors that might be causing this one I've seen this in CMakeError.log: 
`fatal error C1083: Cannot open include file: 'pthread.h': No such file or directory [C:\Dev\OSRM\osrm-backend\build\CMakeFiles\CMakeTmp\cmTC_94b14.vcxproj]`

**Comment by BergWerkGIS** [comment]
I'm not able to reproduce, latest `mater` compiles fine for me. 
Tried on 3 different machines.

> deleted the "build" folder

not necessary, `build-local.bat` does this automatically

@jperaltamalvar could you try the following and post `osrm-build-log.txt` to a gist?

```
cd <where you cloned osrm-backend>
git pull
build-local.bat > osrm-build-log.txt 2>&1
```

> Searching other errors that might be causing this one I've seen this in CMakeError.log: 

You can ignore this one, I got it too, because `pthread.h` is not available on Windows.
Maybe CMake making sure that it really runs on Windows :smirk:

**Comment by jperaltamalvar** [comment]
I will find another PC and try to start from scratch, I'm sure I'm missing some basic stuff.

Meanwhile, here you have the log: [osrm-build-log.zip](https://github.com/Project-OSRM/osrm-backend/files/250081/osrm-build-log.zip)

**Comment by jperaltamalvar** [comment]
I have been able to compile the Windows version with another PC, no Linking error... so it is definetely something specific of my laptop.

@BergWerkGIS thanks for your support!
