### ISSUE TITLE
Duplicate maneuvers 

### ISSUE THREAD

**Issue by bsudekum** [Project-OSRM/osrm-backend#2415]
In OSRM v5.1.0 I'm seeing an issue where the user is being alerted about a new maneuver for the street they are currently on: 

```
{
    geometry: "_wzrFxitiM?W@]@Sj@qF",
    maneuver: {
        exit: 1,
        bearing_after: 90,
        bearing_before: 72,
        location: [
        -75.147971,
        39.955201
        ],
        modifier: "slight left",
        type: "merge",
        instruction: "Merge slightly left onto I 676;US 30" // <--- Ok, they get onto I 676;US 30
    },
    mode: "driving",
    duration: 6.6,
    name: "I 676;US 30",
    distance: 137.7
},
{
    geometry: "ouzrF|_tiMjF{i@zDa_@~JacALiARcAReATcAZeAb@cA\{@p@sAdBwCn@o@d@U",
    maneuver: {
        bearing_after: 103,
        bearing_before: 103,
        location: [
            -75.146391,
            39.954957
        ],
        modifier: "straight",
        type: "new name",
        instruction: "Go straight onto Benjamin Franklin Bridge (I 676;US 30), I 676;US 30 becomes Benjamin Franklin Bridge (I 676;US 30)" // <-- They're already on I 676;US 30
    },
    mode: "driving",
    duration: 133.1,
    name: "Benjamin Franklin Bridge (I 676;US 30)",
    distance: 2417
}
```

Ideally, the second maneuver would be omitted.

/cc @MoKob @TheMarex

**Comment by MoKob** [comment]
This is a kind of difficult question how to avoid these name changes. The problem is that in Germany, we often have streets that keep the reference but have a far more prominent name that changes often.

Consider a case like: http://map.project-osrm.org/?z=12&center=48.540705%2C8.460331&loc=48.810933%2C8.584099&loc=48.473149%2C8.426857&hl=en&alt=0

The reference stays the same, but the name changes quite often. It is kind of a philosophical question, but I feel that the decision whether to announce or suppress this name change is not a backend-question but a frontend-question.
I feel that the API should at least know about these changes to possibly show them on screen, without an announcement.

The problem here is that the Bridge in question offers an off-ramp. Due to the off-ramp we don't see a sequence of `US 30 -- Bridge -- US 30`. Such a sequence would be suppressed.
In the case that the off-ramp is taken, which seems to be the case in the route you have seen, we cannot distinguish between a short change like the bridge and a longer change like in the route I linked above.

If the frontend should only display the information, it would be less of a disturbance. But in the current situation I would feel that a complete suppression of this kind of instruction would result in a larger loss of information than the benefit of not having these instructions present.

**Comment by bsudekum** [comment]
Ok, per voice, we're going to leave this. The example above is an extenuating circumstance. Suppressing all situations like this or situations below a certain distance threshold would be dangerous.
