### ISSUE TITLE
Turn penalties for very sharp angles

### ISSUE THREAD

**Issue by planemad** [Project-OSRM/osrm-backend#2501]
While reviewing Mapillary images to add turn restrictions, i've come across cases where mappers have added turn restrictions at sharp angle junctions like these:

<img width="588" alt="screenshot 2016-06-02 15 52 15" src="https://cloud.githubusercontent.com/assets/126868/15742016/1ec398b8-28da-11e6-9769-974b682d91ee.png">
_OSM: https://www.openstreetmap.org/relation/1580276_

It seems like mappers do this to avoid physically impossible turns in the routing engine. This goes against the principle of mapping what is verifiable, since there is no corresponding restriction signage on the ground, and should probably not be encouraged since there is no way to verify them.

Will removing such restriction affect routing or does OSRM already penalize such turns?

cc @MoKob @daniel-j-h

**Comment by MoKob** [comment]
Removing such an restriction will allow OSRM to route over it. Looking at the GPS, a turn like this would essentially be a `u-turn` on N St NE which does not require a sign to be forbidden.

While given the location, it is unlikely that we would see such a route, it is not impossible. Starting just before the sharp turn, routing to New York Avenue would take this impossible turn.

The signage on the ground here is indeed not present, but it is not required from the context, as far as I can judge this intersection.

The problem here is that not all turns need to be explicitly forbidden. Some are implicitly impossible by being equivalent to a u-turn, which is not allowed on a road by default.

**Comment by planemad** [comment]
Here is a Mapillary photo from the location looking West from North St. The no left sign is into New York Ave and in this case redundant because it is already a oneway. It does not look like there is any signage present for the restriction that has been added.

![](https://d1cuyjsrcm0gby.cloudfront.net/mqoAp2JbcSmP3_GspgAM0g/thumb-640.jpg)

@MoKob the original question remains, should such adding of restrictions when there is no physical signage present be encouraged? This to me feels like mappers are `tagging for the router` rather than mapping what is visible.

> Some are implicitly impossible by being equivalent to a u-turn, which is not allowed on a road by default.

This is interesting. I'm assuming this means on a two way highway, a u-turn is not allowed even at a traffic light? How does one tag it, if indeed you can make a u-turn there?

**Comment by MoKob** [comment]
@planemad the restriction in question is heading `east`, isn't it?

I don't know how to encourage/discourage the mapping behaviour in this case in general. I feel that not all restrictions need to be visible, since not all restrictions are usually given as signs. That doesn't make them less correct.

Consider http://www.openstreetmap.org/node/267332420. Even though the turn is not explicitly forbidden, no one would ever deem the turn reasonable. It is a special road that is not allowed to turn on (due to the solid line just after), but not explicitly marked.

So if the context is correct and is forbidding a turn at that location, I feel the mapping should be allowed and kept this way.

On most highways, u-turns can be allowed at traffic lights. They are not allowed in the middle of the road, though. On traffic-lights/intersections, they have to be disable via a relation, if forbidden. OSRM does not use these kind of u-turns most of the time, though.

**Comment by planemad** [comment]
@MoKob Here is an annotated version of the restriction.
<img width="617" alt="turn_penalties_for_very_sharp_angles_ _issue__2501_ _project-osrm_osrm-backend" src="https://cloud.githubusercontent.com/assets/126868/15777162/e852c9da-29aa-11e6-9fb4-3c3c934ae930.png">

> I feel that not all restrictions need to be visible, since not all restrictions are usually given as signs. That doesn't make them less correct.

The primary concern is how to validate existing restrictions when we cannot verify its existence from street photographs. If we have a consistent approach, we could term them invalid and remove them, since the restriction cannot be legally enforced like in this case, it is just practically difficult.

But the mapping approach currently on OSM is inconsistent and now there is no distinction between a restriction enforced by law and a restriction created for a map routing engine. The end result is a large number of restriction which can only be validated by the mapper who added them.

**Comment by MoKob** [comment]
Well. I get that it would be nice to have a more consistent view. But I fear that the damage to route results would just be too great if we simply started to remove all restrictions that cannot be verified from images.  And again, this image is from the wrong side. If you look at the other side, you can see: 

<img width="708" alt="screen shot 2016-06-03 at 13 38 47" src="https://cloud.githubusercontent.com/assets/12932279/15777563/a67ff7ae-2990-11e6-9dc0-057a170eb263.png">

It is not always possible so see everything, so removing all restrictions that cannot be verified is a dangerous path I don't want to head down.

**Comment by planemad** [comment]
Oh wow, nice find 👍 . Lets revisit once I get a feel of how big an issue this is on the data side.
