### ISSUE TITLE
provide 'total' turn direction for all roundabouts

### ISSUE THREAD

**Issue by emiltin** [Project-OSRM/osrm-backend#2529]
for roundabout turns, the modifier provides the turn direction just like normal turns.

i think it would be useful (and more streamlined) to provide this for all roundabout types. even for mid-sized roundabouts, i believe it's easier to follow instruction to "continue straight ahead at the roundabout, 2nd exit", than "take the 2nd exit at the roundabout".

especially when cycling, something like 2nd exit is often not very clear. e.g. are pedestrian paths counted?

total turn direction can be computed in the front-end by comparing bearings before and after but this it's a bit impractical.

**Comment by emiltin** [comment]
of course works best if there are few exist. would it be possible to get the total number of exits?

**Comment by emiltin** [comment]
hm, it actually seems bearing_after is the bearing when turning into the roundabout, not leaving it?

**Comment by emiltin** [comment]
it would also be nice to have the location (lon,lat) of the final turn out of the roundabout. currently you only get the location of where you enter the roundabout, or am i missing something?

**Comment by MoKob** [comment]
@emiltin both the bearings and the location of the final turn can be found from the intersections array. The turn in general with full bearing is something that would be too confusing for large roundabouts, at least for cars where counting exits is the convention people are used to.

The turn direction is something we need for distinguishing between left hand and right hand driving, even though this is not yet implemented.

**Comment by emiltin** [comment]
thank you, i will look more at the intersections data.
you're right that the full heading makes sense mainly for smaller roundabouts, but i notices a lof of smaller roundabouts (not roundabout turns) that are small and simple enough that this would be easier than counting exits.

it might also be useful to indicate to the user if you continue on the same way (same name) after the roundabout

**Comment by MoKob** [comment]
@emiltin currently the size is a simple guess for when we switch between roundabout-turns and roundabouts. If you feel that the switch is made to early, I'd welcome a few links to roundabouts and we might choose to change the threshold (or if we finally manage to move the decision into the profile, you can specify a personal limit)

**Comment by emiltin** [comment]
the demo server seems to have a problem t the moment (no route is computed), but i was looking at these three roundabouts. there's clear main way that continues straight ahead in all of them.

http://map.project-osrm.org/?z=15&center=55.655110%2C12.587092&loc=55.659650%2C12.583508&loc=55.653016%2C12.588658&hl=en&alt=0

specifying the treshold in the profile sounds useful.

**Comment by MoKob** [comment]
From the first look, they look like rasonable candidates. One thing to consider is that bike-profiles might prevent a conversion to roundabout-turns, since they are only considered if there is a clear distinction between possible exits.
Right now, and as long as we don't have a reasonable model of counting exits in roundabouts for bikes, often the number of possible exits could prevent an interpretation as roundabout turn.

**Comment by emiltin** [comment]
I tried processing the data with the default car profile, and same roundabout instructions are returned, ie no roundabout-turns.

**Comment by MoKob** [comment]
I've had a look at it. Right now the threshold to decide between roundabout turns and roundabouts is set to 15 meters of radius. At least the roundabout that I checked has the radius of 17 meters.

For your own configuration, you can increase this angle ([here](https://github.com/Project-OSRM/osrm-backend/blob/0e4061f85816b5499896022eb151a1402ae3aad0/include/extractor/guidance/constants.hpp#L25)), or wait for the second round of guidance configuration to be moved into the profiles (https://github.com/Project-OSRM/osrm-backend/issues/2113).

Since the method to compute the direction internally is just the same that you describe

>total turn direction can be computed in the front-end by comparing bearings before and after but this it's a bit impractical.

I will close here in favour ofhttps://github.com/Project-OSRM/osrm-backend/issues/2113 . Moving the decision into the profile for when to announce turns will move it to a pure configuration issue where you can easily adjust it to your own likings (right now you need to recompile).

Internally, we want to have the modifier to indicate the direction you actually enter the roundabout in (left-sided driving, the famous magic roundabout...)
