### ISSUE TITLE
No turn announced, but there probably should be

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2550]
On IRC in #osm, this route was pointed out:

http://map.project-osrm.org/?z=18&center=51.406740%2C-3.280218&loc=51.406314%2C-3.279966&loc=51.407274%2C-3.281205&hl=en&alt=0

No instruction is announced, but one was expected.

/cc @muzer

**Comment by daniel-j-h** [comment]
For the record, testing this locally against master emits a "new name, slight right".

Looking a bit more into it, it looks like this area was changed a couple of hours ago in
http://www.openstreetmap.org/changeset/40029188

Here are the changes visualized
http://osmhv.openstreetmap.de/changeset.jsp?id=40029188

![before-after](https://cloud.githubusercontent.com/assets/527241/16074912/f5642786-32ec-11e6-8083-ccea8c6b2f7c.png)

(red before, green after)

The demo server still routes on old geometry as of this writing since we "only" update once a day. @MoKob is looking into the specific instruction generated.

**Comment by MoKob** [comment]
While this is obviously an issue of the out-of-date data (give it a day until you can start to expect new data to be reflected in OSRM, the difference in the geometry gives the idea), it surfaced an error that I fixed in #2551. The turn onto Jenner Road itself, as modelled in the old data, is a nearly straight move onto a road, which is announced as a new-name instruction. 

With the new modelling, it should emit the correct turn left/turn right instructions. Closing here, as nothing actionable. Feel free to re-open if the problem should persist.
