### ISSUE TITLE
handling failed matches

### ISSUE THREAD

**Issue by bvbever** [Project-OSRM/osrm-backend#2554]
When running a route without a successful result in Mozilla firefox (I copy pased the routingurl into), I get a message "Could not find a matching segment for any coordinate" and a code "NoSegment".
Nevertheless firebug give the status "400 Bad Request". 
So, when I use the routing in PHP in a file_put_contents($url) I get the message 'failed to open stream: HTTP request failed! HTTP/1.0 400 Bad Request'.

It is possible to alter the status to 'Ok' or something ? So I can get the real message into my php result ?

**Comment by danpat** [comment]
@bvbever Can you paste a short code snippet demonstrating the problem?

AFAIK, you probably want either `file_get_contents`, or you should consider using the cURL extension.

**Comment by bvbever** [comment]
Indeed I ment `file_get_contents`...
@danpat https://router.project-osrm.org/route/v1/driving/1.93,17.64;-76.64,36.17

**Comment by TheMarex** [comment]
Error code 400 is the right code here since this is an abnormal condition (similar to resource not found). Not sure what the appropriate method for PHP would be here but this works as expected in JS.

**Comment by danpat** [comment]
Indeed, I meant to post a followup here.  @bvbever you'll need to use the `curl` library functions instead of `file_get_contents`.  `file_get_contents` is a very simple URL fetcher, and doesn't give you any flexibility when handling HTTP responses.

Get started with the example here:

http://php.net/manual/en/curl.examples-basic.php
