### ISSUE TITLE
De-duplicate forward/reverse geometries

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#2592]
Currently, the `.geometry` file contains lists of node IDs for compressed edges in the node-based graph.  These map directly to coordinates, and are used to return the final coordinates in a route.

However, we're storing the same geometry twice - once for the forward direction, once for the reverse.  This leads to quite a bit of waste.

Currently, each compressed geometry contains the 2nd to N nodes for the edge.  The first node is never needed, because it can be retrieved from the last node of the previous edge if a route traverses multiple edges, and is not required for the first edge, as the first PhantomNode will represent the first coordinate on a section of geometry, never the first node.

However, we're storing the almost the same geometry for the reverse version of the edge - nodes 1 to N-1, in reverse order.  This essentially doubles the size of the `.geometry` table.

We should consolidate these to include all nodes along an edge, and update logic to traverse the list either forwards or reverse.  There will be some duplication of nodes at intersection points, but this should be far less than the doubled geometries we have right now.

**Comment by TheMarex** [comment]
Problem is that we need a way to figure out who to derive both forward and reverse weights from each ID. I would imagine we need to split the EdgeWeight vector into forward and reverse weights, which in turn might again need a little bit extra space.

**Comment by lbud** [comment]
Braindumping my progress on understanding this @TheMarex:

Currently graph compression works such that in this basic case

```
   f1     f2
        ͢
  ____   ____  
u      v      w
  ----   ---- 
       ⃪
   r2     r1 
```
we'd basically add `uv` and then attach `vw` onto it, attach maybe `wx` onto that, etc…
and then in reverse we'd add `wv`, and then attach `vu` onto it, and then maybe `ut`, etc.

BUT in a world where we store only one `EdgeBucket` per edge with both forward and reverse weights, we'll want this scenario to translate to EdgeBuckets as
```
{
    node = v
    fwd_weight = f1
    rev_weight = r1
}
{
    node = w
    fwd_weight = f2
    rev_weight = INVALID_WEIGHT
}
{
    node = u
    rev_weight = r2
    fwd_weight = INVALID_WEIGHT
}
```

That’s all well and good, but then for the next edge in the same compressed segment, say to the right of `vw`:
```
   f1     f2     f3
        ͢
  ____   ____   ____
u      v      w      x
  ----   ----   ----
       ⃪
   r2     r1     r3
```
we’ll want to be able to pull out the `w` edgebucket so that we can attach the `xw` reverse weight to it, so
```
{
    node = w
    fwd_weight = f2
    rev_weight = r3
}
```

It _seems_ like we'll have to modify what we're working with in `GraphCompressor::Compress` to additionally find the edges on either side of this edge, so that we can check to see if the end node of a forward edge has already been added as the end of the next reverse edge or vice versa, in which case we'll be modifying an existing EdgeBucket with an INVALID_WEIGHT placeholder rather than adding an EdgeBucket.

Does this seem right or am I way off base?
