### ISSUE TITLE
 Fingeprint does not match in *.osrm.icd

### ISSUE THREAD

**Issue by javawolfpack** [Project-OSRM/osrm-backend#2604]
I've moved the extracted and contracted osrm files from a Google compute system to a local server and keep getting the following when I try to use osrm-routed on them:

>[warn] [exception] Fingeprint does not match in north-america-latest.osrm.icd

I'm using the northamerica pbf from http://download.geofabrik.de/
Additionally, these files work without any issue on two small VMs I have the osrm-backend built on, but they are super slow, so not sure why I'm having issues on a physical server. They all are running Ubuntu 16.04 server. Not sure if this is an issue exactly or if there is a fix. Seemed like the best place to inquire about this as the irc chatroom seems to be dead.

**Comment by danpat** [comment]
@javawolfpack The fingerprint check tries to verify that you're using datafiles generated using the same version of OSRM as you're trying to run with.  The files are generally not backwards compatible.

**Comment by javawolfpack** [comment]
Okay that makes sense, thanks. Not sure if there is an easy way get on the same version on both. As should be the same version on both.

**Comment by danpat** [comment]
@javawolfpack Basically, there's no cross-platform, cross-machine or cross-version compatibility guarantees.  If you compile OSRM on two different setups, compiler differences may break the file formats compatibility.

Several of the files are basically just memory dumps, so architecture differences (big/little endian, word sizes, default word alignment) can mean broken files.  We also frequently change the data that's stored in the files, so they're not really usable between OSRM versions (i.e. you can't `osrm-extract/contract` with 5.1.0 and expect the files to work with `osrm-routed` from 5.2.0).

Please re-open this ticket if you think you've got two identical setups and you're still getting this error.

**Comment by TechnologySolutionsGroup** [comment]
I too am getting this same issue, and not sure why there should be checks like this. I initially used a powerful Amazon instance: r3.4xlarge, to process the the North America maps. Then wanted to use a different Amazon instance, as "r3.4xlarge" is very expensive.

I did all the compiles within the same day, same Ubuntu distros, etc..., so everything should be exactly the same, but am getting the same "Fingeprint does not match in /mnt/north-america-latest.osrm.icd" error.

It would seem that this scenario should be supported. As using a powerful Amazon instance, just for a few hours, to process the North America map, then switch to a standard Amazon instance to run the backend would be what many people work do?

**Comment by javawolfpack** [comment]
I thought that was the case on my end too; however, the versions of OSRM I was using on the two was different... and this resulted in the error. I agree with you as that's what I did on the Google Cloud and then could run it on a local VM instance; however, the server I had laying around that would have run OSRM faster didn't have the same version of OSRM.

**Comment by TechnologySolutionsGroup** [comment]
Well in my case I started and created both Amazon instances within the same day, compiled, built, etc..., so they were brand new instances, all updated with the latest updates, and all within an 8 hour period. To me, this should work and not give a "Fingerprint does not match..." error. :(

**Comment by javawolfpack** [comment]
There could be nuances in the compilers used on the different AWS instances, without poking into the details personally I couldn't say for sure; however, if this is the case the resultant compiled code on both machines will generate different fingerprints for their executable. This would be the case even if the source is the same version... I do agree it would be nice if the system worked on a version vs fingerprint basis for this kind of problem. Technically open source, so maybe if I get time/motivation :)

**Comment by TechnologySolutionsGroup** [comment]
Well I "have" get it working across two instances, so I'll dig into the code myself and see why it won't work. :)

**Comment by javawolfpack** [comment]
I'd make sure you have the same code for both systems, so you can rule that out of the issues.

**Comment by TechnologySolutionsGroup** [comment]
Well like I said, I did everything within an 8 hour period today, so I don't know if there was a new code push within this 8 hour window, all the code should have been exactly the same.

**Comment by danpat** [comment]
@TechnologySolutionsGroup If you're using the latest `master` code directly via `git`, then yes, you could easily get different versions - we often push new code there multiple times a day.

The fingerprint value is generated based on md5sums of source code files - if you're getting a fingerprint error, then you've almost certainly got different code versions on your two machines.

It sounds like you should be using a tagged release - the latest version is 5.4.1, and you can download a zip file/tarball from GitHub at: https://github.com/Project-OSRM/osrm-backend/releases.  This would guarantee you've got the same source code at least.

While we make no guarantees about inter-machine compatibility, practically, if you're using pretty similar looking machines (x86_64, Ubuntu), then you should end up with files that are compatible.

The file format situation isn't ideal, we know.  The core team here at Mapbox have been mulling which approach is going to work best to fix this problem - it's a fair amount of work to fix a problem that we (at Mapbox) don't often encounter (i.e. never, because our environments are quite homogenous).  Patches from the community are very welcome though, I understand the frustration.

**Comment by TechnologySolutionsGroup** [comment]
OK, I'll try tomorrow with tagged releases, or first, I'll just try copying binaries from one machine to another, see if that works, since that would be faster than re-processing all of North America again. :)

The reason I went to a larger Amazon instance, is that I could never get North America to process within 24 hours, where as on a "r3.4xlarge" instance I could get it to process within 4 hours.

I don't care if routing / trips take a while to process on a slower instance, but want to process North America at least once a month.
