### ISSUE TITLE
Handle lanes within a roundabout

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#2626]
https://github.com/Project-OSRM/osrm-backend/pull/2612 implements Lane Anticipation in roundabouts based on a roundabout's `enter` and `leave` instruction. For all other (silent) instructions inside a roundabout we currently do not get any lane information for post processing to work on.

We still want to
- issue `UseLane` instruction inside roundabouts
- do lane anticipation for lane changes within a roundabout

This depends on @MoKob's turn handler work https://github.com/Project-OSRM/osrm-backend/pull/2614.

**Comment by MoKob** [comment]
@daniel-j-h there seems to be some confusion. We don't need `UseLane` and any modifications in `turn_handler` changes on roundabouts.

What needs to be adjusted is the `turn_lane_handler` and lane anticipation might have to introduce `UseLane` instructions. The roundabout itself has fitting instructions already (namely `StayOnRoundabout`) that are not exposed to the outside but which can be used to assign intermediate lanes.
Lane anticipation has to work closely with the counting mechanisms of roundabout handling in post-processing, since the post-processing destroys lane information, if any exists, for all intermediate instructions and we cannot simply replace `StayOnRoundabout` with `UseLane` since the information is required for counting.
