### ISSUE TITLE
public demo server down

### ISSUE THREAD

**Issue by chisseucraoul** [Project-OSRM/osrm-backend#2698]
The OSRM routing mode on http://router.project-osrm.org/ currently doesn't produce routes. The javascript console shows a No 'Access-Control-Allow-Origin' header is present error

**Comment by TheMarex** [comment]
Thanks for reporting this. :+1: This is a known issue. We are currently working on fixing this. Hopefully the demo server should be up tomorrow.

**Comment by chisseucraoul** [comment]
hello, i have tested OSRM routing again. i don't have any error but it still doesn't produce routes. Have you made some changes?  thank you for your support

**Comment by daniel-j-h** [comment]
Please follow https://github.com/Project-OSRM/osrm-backend/issues/2706#issuecomment-235921016.

**Comment by SzymiB** [comment]
Hi, I use osrm R-package, and it has't been returning any results since yesterday, and it seems that the demo server is down. Is there any possible timescale when it's likely to be up again?
I have tried to build osrm on my machine, but that was unsuccessful, and I don't really have time to keep trying (I have to submit my dissertation tomorrow and I am using osrm to find optimal routes, and now I need to produce some pretty maps),

Thanks!

**Comment by daniel-j-h** [comment]
You don't have to compile osrm on your own, we provide Node.js bindings and Docker images:

https://github.com/Project-OSRM/osrm-backend#quick-start

No ETA on when the demo server will be up again - we provide no uptime guarantees for it:

https://github.com/Project-OSRM/osrm-backend/wiki/Api-usage-policy

**Comment by SzymiB** [comment]
Thanks for the reply! 
It seems that I don't have enough background knowledge of how to run those things (and I'm on Windows, which seems to not help at all...)

**Comment by miccolis** [comment]
@SzymiB Mapbox sponsors a lot of OSRM development and uses it to for our hosted service, which does have a uptime guarantee. I'm not familiar with the osrm R-package, but perhaps you can signup for a free account and point your R project at our services; https://www.mapbox.com/api-documentation/#directions
