### ISSUE TITLE
Upgrade ARM builds to GCC 5.0

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#2699]
Currently we are building form ARM using GCC 4.8 but we are dropping support for that compiler since it doesn't support C++14.
- [ ] Fix the repository setup scripts https://github.com/Project-OSRM/osrm-backend/blob/master/scripts/travis/before_install.armhf.sh to use the new toolchain https://launchpad.net/~team-gcc-arm-embedded/+archive/ubuntu/ppa
- [ ] Re-enable in the build matrix on travis

**Comment by oxidase** [comment]
Hi, i can update on the weekend the script with new ppa

**Comment by oxidase** [comment]
just looked at ppa. It provides "bare metal" cross-compiler
```
arm-none-eabi-g++ (GNU Tools for ARM Embedded Processors) 5.4.1 20160609 (release) [ARM/embedded-5-branch revision 237715]
```
i don't think that running OSRM without OS is what really needed. 

The problem is that travis supports now only trusty https://github.com/travis-ci/travis-ci/issues/5821 that  has no gcc-5 for ARM . But even installing an ARM toolchain arm-linux-gnueabihf-g++-5  is not enough, because all libraries must be built from sources, like stxxl in the script. It will bring too high overhead for a simple compilation check. 
One possibility would be to create own ppa with a toolchain and prebuilt libraries, but it also brings almost nothing without running all tests.

I would suggest to close PR and add a UB sanitizer job.

**Comment by komms** [comment]
Is it possible to use this osrm routing docker image on arm 64 architecture? Should I cross compile it?

**Comment by komms** [comment]
Successfully built the arm64 container of OSRM.

**Comment by adioanca-rpma** [comment]
Hi @komms 

Could you give some build changes/details/instructions?

Thank you

**Comment by komms** [comment]
I changed the base image in the docker file of OSRM to the same architecture of my embedded system.

**Comment by SiarheiFedartsou** [comment]
Seems to be non actual anymore.
