### ISSUE TITLE
504 Gateway timeout

### ISSUE THREAD

**Issue by simplogithub** [Project-OSRM/osrm-backend#2703]
Please help. the OSRM doesn't response since last Friday. 
any change on the API ? 

http://router.project-osrm.org/route/v1/driving/10.781707,52.419964;11.949,57.6792?alternatives=true&steps=true

**Comment by daniel-j-h** [comment]
We hit an I/O error before the weekend and then a wrong assertions (since the demo server has assertions enabled). We fixed all of this already but it will take a while to re-process the planet.

Sorry for the bumpy ride --- we're moving fast at the moment, and the demo server is exactly the place where we want to see these issues to occur.
