### ISSUE TITLE
Map matching adding "extra coordinates" as per the original coordinates

### ISSUE THREAD

**Issue by kihats** [Project-OSRM/osrm-backend#2768]
I am new to the osrm project. 
I am trying to map-match using this request: `(http://router.project-osrm.org/match/v1/driving/36.7366591,-1.396805;36.7378522,-1.3986011;36.7378522,-1.3986011;36.7378916,-1.3987294;36.7378916,-1.3987294;36.7379231,-1.3989927;36.7379231,-1.3989927;36.7379231,-1.3989927;36.7382217,-1.3986896;36.737892,-1.3987513;36.737892,-1.3987513;36.737892,-1.3987513;36.7376807,-1.3987815;36.7376807,-1.3987815;36.7376807,-1.3987815;36.7376456,-1.3984273;36.7376456,-1.3984273;36.7376456,-1.3984273;36.7378918,-1.3982991;36.7378918,-1.3982991;36.7378918,-1.3982991;36.7378008,-1.3979676;36.7378008,-1.3979676;36.7378008,-1.3979676;36.7378008,-1.3979676;36.7378475,-1.3978716;36.7378475,-1.3978716;36.7378475,-1.3978716;36.7379658,-1.3977528;36.7379658,-1.3977528;36.7379658,-1.3977528;36.7380082,-1.3972748;36.7380082,-1.3972748;36.7380082,-1.3972748;36.738056,-1.3967555;36.738056,-1.3967555;36.738056,-1.3967555;36.7379906,-1.396571;36.7379906,-1.396571;36.7379906,-1.396571;36.7380826,-1.3961273;36.7380826,-1.3961273;36.7380826,-1.3961273;36.7380943,-1.3959417;36.7380943,-1.3959417;36.7380943,-1.3959417;36.7383577,-1.3958751;36.7383577,-1.3958751;36.7383577,-1.3958751;36.7390567,-1.395941;36.7390567,-1.395941;36.7390567,-1.395941;36.7402115,-1.3960733;36.7402115,-1.3960733;36.7402115,-1.3960733;36.7410597,-1.3960701;36.7410597,-1.3960701;36.7410597,-1.3960701;36.7411131,-1.3960772;36.7411131,-1.3960772;36.7411131,-1.3960772;36.7411159,-1.3960872;36.7411159,-1.3960872;36.7411681,-1.3961293;36.7411681,-1.3961293;36.7411681,-1.3961293;36.7411079,-1.3960857;36.7411079,-1.3960857;36.7411079,-1.3960857;36.7411079,-1.3960857?steps=true&overview=full&geometries=geojson&annotations=true)`. 
The result produces extra coordinates even past the last point of the raw coordinates (as the image shows). Kindly advice if this is a problem or there is some information that I am missing.

**The raw coordinates sent for map matching**
![raw coordinates](https://cloud.githubusercontent.com/assets/21008648/17648798/380171e4-622b-11e6-9ea3-bb527ce82da9.png)

**The coordinates received from osrm**
Retrieved from `geometry`
![result coordinates](https://cloud.githubusercontent.com/assets/21008648/17648808/8ae2c2c8-622b-11e6-8ac9-aa7a383434a4.png)

**Comment by MoKob** [comment]
The problem here is border-cases for identical points. Close to all your points are in your request three times or at least twice. If you reduce your request to unique points, the matching will find the correct result.

Try `http://router.project-osrm.org/match/v1/driving/
36.7366591,-1.396805;36.7378522,-1.3986011;36.7378916,-1.3987294;36.7379231,-1.3989927;36.7382217,-1.3986896;36.737892,-1.3987513;36.7376807,-1.3987815;36.7376456,-1.3984273;36.7378918,-1.3982991;36.7378008,-1.3979676;36.7378475,-1.3978716;36.7379658,-1.3977528;36.7380082,-1.3972748;36.738056,-1.3967555;36.7379906,-1.396571;36.7380826,-1.3961273;36.7380943,-1.3959417;36.7383577,-1.3958751;36.7390567,-1.395941;36.7402115,-1.3960733;36.7410597,-1.3960701;36.7411131,-1.3960772;36.7411159,-1.3960872;36.7411681,-1.3961293;36.7411079,-1.3960857?steps=true&overview=full&geometries=geojson&annotations=true`

The request is the same without the duplicated coordinates.

@TheMarex do you think that we should apply some filtering here on our side? Seems like map-matching is behaving badly here. After all, identical measures can occur if we assume a car standing still at a traffic light.

**Comment by daniel-j-h** [comment]
Per coffee-chat with Patrick: yes, we should filter out blobs and do some tidying in the backend, since this should be an implementation detail and not a requirement for the user.

Until then, you can use e.g. https://github.com/mapbox/geojson-tidy to tidy up your traces.

**Comment by daniel-j-h** [comment]
Closing here, please clean up your traces for now as explained above.
Doing this transparently on our side is tracked in https://github.com/Project-OSRM/osrm-backend/issues/2840.
