### ISSUE TITLE
Handle Lanes in Collapse

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#2775]
Capturing from notes from @MoKob:

> Collapsing of instructions is currently not considering lanes at all

**Comment by MoKob** [comment]
To elaborate on this:

When we collapse instructions, we use two mechanisms:

- forwardInto to move data from step `n+1` into step `n`
- invalidateStep to erase the now unnecessary step

To handle lanes correctly in these situations, we need to:

- [ ] adapt [forwardInto](https://github.com/Project-OSRM/osrm-backend/blob/087080a6c3204669275280a68005e538e08ee4d9/src/engine/guidance/post_processing.cpp#L133-L156) to do laneAnticipation (cc @daniel-j-h)
- [ ] possibly adjust collapsing to instead of invalidating to emit a use-lane

Cases to have a look at can be found in the [collapse.feature](https://github.com/Project-OSRM/osrm-backend/blob/master/features/guidance/collapse.feature).

To work on this issue, I suggest to copy these cases into a `collapse_lanes.feature` and add turn lanes to the respective routes.

**Comment by MoKob** [comment]
https://github.com/Project-OSRM/osrm-backend/issues/2702 should be done before to make sure we have lane information in between visible.

**Comment by MoKob** [comment]
By now we have https://github.com/Project-OSRM/osrm-backend/blob/0affec8f1732e9d3cb56bff4f4d08da42f250943/include/engine/guidance/collapse_turns.hpp#L107. Scenarios can be reviewed and updated when they come up. The issue in itself can be closed.
