### ISSUE TITLE
Critical error in the formation of the route

### ISSUE THREAD

**Issue by dpodchernyaev** [Project-OSRM/osrm-backend#2803]
Hello!
In constructing the route Moscow - Yalta was built following rout:
![1](https://cloud.githubusercontent.com/assets/6954406/17887798/c214e026-6930-11e6-9b9f-12d96ddab53e.jpg)

I think that is the wrong route.

This behavior is repeated periodically in the construction of the route across Russia.

Osrm Version: 4.8.1
Map Version: http://be.gis-lab.info/data/osm_dump/dump/latest/RU.osm.pbf

What's strange ..
If you generate a graph for a very old maps <2014-2015 year, the routes across Russia built correctly.

What could be the reason?

**Comment by danpat** [comment]
@dpodchernyaev It looks like you're suffering from a OSM node ID overflow issue.  Your version of OSRM (4.8.1) only supports OSM node ID values up to 2^32 (4,294,967,295), but OSM now has nodes bigger than that.

With older versions of OSRM, the id values will overflow and create "random" looking links across the road network.

On our demo server the route works fine: http://map.project-osrm.org/?z=5&center=50.666872%2C52.185059&loc=55.776573%2C37.573242&loc=45.182037%2C35.068359&hl=en&alt=0

We run OSRM 5.x which has support for 64bit IDs.

You have two options:

  1) Upgrade to a newer OSRM version
  2) Use http://docs.osmcode.org/osmium/latest/osmium-renumber.html to re-number the ID values in your files so they don't conflict.

This was fixed in OSRM here: https://github.com/Project-OSRM/osrm-backend/issues/322#issuecomment-160761875
