### ISSUE TITLE
Got a server error

### ISSUE THREAD

**Issue by booper** [Project-OSRM/osrm-backend#2812]
Is everything ok with servers?
![2016-08-25_1933](https://cloud.githubusercontent.com/assets/583898/17977579/eb528008-6afa-11e6-9458-6c0466a25d1e.png)

**Comment by danpat** [comment]
@booper you're hitting the V4 api (`/viaroute`) which we will be deprecating soon.  We're not monitoring it for uptime at all any more.  Please take this opportunity to move to the new API.

There have been several announcements to various mailing lists and IRC channels regarding the shutdown.

Docs for the new API are here:

https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#http-api

**Comment by danpat** [comment]
For what it's worth, the server was down because of AWS spot pricing outages:

https://aws.amazon.com/ec2/spot/pricing/

we have a bid price in for the server, and when the market price rises, the server gets terminated until the price drops again.  It doesn't happen too often.

Please remember that this is a *demo* server with no uptime guarantees.
