### ISSUE TITLE
nearest service not working on demo server

### ISSUE THREAD

**Issue by lbedogni** [Project-OSRM/osrm-backend#2884]
I notice that the nearest server reports a 500 error on the demo server, with any lon/lat I have tried, including the ones included in the example in the wiki, which is this one:

http://router.project-osrm.org/nearest/v1/driving/13.388860,52.517037?number=3&bearings=0,20

**Comment by MoKob** [comment]
This is due to a temporary workaround we had to do since a performance bug was killing our demo-server. It was possible to start requests that would take minutes to complete.

As a result, we had to disable the nearest plugin for a short while. It will be available again soon.
I am sorry for any inconvenience this may have caused.

**Comment by freenerd** [comment]
Bugfix is deployed and `nearest` enabled again
