### ISSUE TITLE
libosrm compilation based on 64b8456 typedefs change

### ISSUE THREAD

**Issue by JMDelhGit** [Project-OSRM/osrm-backend#2944]
Hi,

After the fix of typedefs from #2938 based on 64b8456 , I had a go to rebuild the whole osrm-backend library

Unfortunately, it looks like the change in typedefs.hpp had some side effects which induce errors in the compilation.

Below a few errors listed:

~osrm/src/contractor/contractor.cpp:49:35: error: unknown type name 'OSMNodeID'; did you mean 'osrm::OSMNodeID'?
template <> struct hash<std::pair<OSMNodeID, OSMNodeID>>
                                  ^~~~~~~~~
                                  osrm::OSMNodeID
~osrm/include/util/typedefs.hpp:38:40: note: 'osrm::OSMNodeID' declared here
    OSRM_STRONG_TYPEDEF(std::uint64_t, OSMNodeID)
                                       ^
 ... several errors with osrm::OSMNodeID

10 errors generated.
make[2]: *** [CMakeFiles/CONTRACTOR.dir/src/contractor/contractor.cpp.o] Error 1
make[1]: *** [CMakeFiles/CONTRACTOR.dir/all] Error 2
make: *** [all] Error 2

**Comment by daniel-j-h** [comment]
In https://github.com/Project-OSRM/osrm-backend/issues/2938#issuecomment-248871398 you said

> I just modify typedef.hpp based on 64b8456

but modifying `typedefs.hpp` alone is not enough: have a look at the full changeset. The error you're seeing is fixed in there already:

https://github.com/Project-OSRM/osrm-backend/commit/64b8456f1ac8a126e51f1f60a93fd116b186e18a

In short: either cherry-pick this commit fully or run from this branch, but editing `typedefs.hpp` alone is not enough.

**Comment by JMDelhGit** [comment]
Oups, I did misunderstand when you mentioned cherry-pick before :-)
All 3 changes made
All recompiled 
ok

Thank you

I close the comment

**Comment by daniel-j-h** [comment]
Thank you for clarifying, and glad I could help!
