### ISSUE TITLE
Profile attribute is unused in HTTP API

### ISSUE THREAD

**Issue by ajnisbet** [Project-OSRM/osrm-backend#2952]
It doesn't look like the `/{profile}/` part of the API URL is used in `/src/server`.  Is that correct?

My understanding is that osrm doesn't work with multiple profiles, and the profiles aren't named anyway.

If it's not used, perhaps the [documentation](https://github.com/Project-OSRM/osrm-backend/blob/05c1fe7f46f1903bfac8feb37f0d434efe5c2b57/docs/http.md#request) could make that more clear and removal from the API could be considered.

**Comment by daniel-j-h** [comment]
Hello, here's what's currently in [the v5 docs](https://github.com/Project-OSRM/osrm-backend/blob/05c1fe7f46f1903bfac8feb37f0d434efe5c2b57/docs/http.md#request):

> profile: Mode of transportation, is determined by the profile that is used to prepare the data

We don't want to remove it since in the future we may want to let osrm handle multiple profiles at once (no guarantee if and when this will ever land :P), so we reserve this prefix already.

Clarifying the docs a bit in https://github.com/Project-OSRM/osrm-backend/pull/2957 feel free to chime in if you think the wording can be made better.

Already closing this here, tracking changes in the pull request linked.
