### ISSUE TITLE
Handle `highway=mini_roundabout` and `traffic_calming=island`

### ISSUE THREAD

**Issue by bhousel** [Project-OSRM/osrm-backend#2961]
[highway=mini_roundabout](http://wiki.openstreetmap.org/wiki/Tag:highway%3Dmini_roundabout) - a cement bump or painted circle.  You can go around it or drive over it (e.g. if you are in a truck).

[traffic_calming=island](http://wiki.openstreetmap.org/wiki/Tag:traffic_calming%3Disland) - is a smallish obstruction that must be driven around (but isn't a real roundabout).

For context, we are looking at this thing (currently tagged as a mini roundabout, but should probably be tagged as an island):  http://www.openstreetmap.org/edit#map=21/43.06438/-89.43877

Happy for any guidance from the OSRM team on how you want these things tagged..

**Comment by MoKob** [comment]
@bhousel can you be a bit more specific on how you define `handling` here? Should this be incorporated into instructions?

Do you expect traffic to slow down?

We need some kind of result for that handling, for us to be able to handle the tagging.

**Comment by bhousel** [comment]
@MoKob Yes traffic would need to slow down and go around them.  I'm not sure whether the user should get notice of a maneuver like "Go around traffic island and continue on 10th Avenue".  I really don't have a strong opinion or know what's best.

But anyway, the thing might be tagged as a node at an intersection, or might be drawn as a small circle of highway.

Here's an [example on Mapillary](https://www.mapillary.com/app/?lat=40.177906388888886&lng=-74.01782472222222&z=17&pKey=R2MBI3fgp56B7ucljWq9Qg&focus=photo) 
That same thing [in OSM](http://www.openstreetmap.org/node/104639892)

**Comment by MoKob** [comment]
@bhousel from the example, the only thing we could to is to use them in the turn-function itself to increase turn penalties. From the navigational standpoint, as long as you don't expect a special instruction, they are natively handled when tagged as node.

If they are tagged as roundabout on a circled way, the intersection would be slower than a normal intersection (two turns instead of one) and announced as a `at the roundabout turn right`.

Unless you can specify any specific shortcoming, I would consider adding the request to our additional turn-penalty parameters.
