### ISSUE TITLE
libosrm API change in v5.2

### ISSUE THREAD

**Issue by jcoupey** [Project-OSRM/osrm-backend#2978]
I've been using `libosrm` with v5.1 and noticed my code didn't compile anymore with more recent versions.

This is caused by https://github.com/Project-OSRM/osrm-backend/commit/fa525ad610af14c03edcd366571c51c100f61d08 introducing a new `annotation_` parameter for the `osrm::RouteParameters`constructor.

I adjusted my code for this new parameter so it is now all right with `libosrm` versions starting at v5.2. Other users might need to be aware of this.

**Comment by daniel-j-h** [comment]
Thanks for bringing this up: a breaking `libosrm` change should have never happened in a minor release. Seems like this one slipped through. We can't do anything about it at this point in time. Sorry.

Here's the breaking change:
https://github.com/Project-OSRM/osrm-backend/commit/fa525ad610af14c03edcd366571c51c100f61d08#diff-20ff672c2bee77817916303c66b1b98eR73

Clients have to adapt calls to the `RouteParameter`'s constructor: an additional `annotations` parameter was added as third argument for requesting metadata (OSM ids) for a route. Set `false` if you only want to make your code compile again.

**Comment by TheMarex** [comment]
Urg sorry, this one slipped through. How are we going to handle additive changes to the parameters in the future? The only backward compatible change I see would either be default values for the new parameters or we disallow adding new parameters.
The latter option has the the downside that it would also translate into us not being able to add flags that would actually be backward compatible on node/HTTP level.

**Comment by daniel-j-h** [comment]
In theory overloading the constructor should work, as in

v1:

```cpp
RouteParameters(bool opt0, bool opt1);
```

v2:

```cpp
RouteParameters(bool opt0, bool opt1, int breakingOpt);
RouteParameters(bool opt0, bool opt1) : RouteParameters(opt0, opt1, false) {}
```
in practice I'm not sure if the variadic template `args...` could be an issue.

**Comment by daniel-j-h** [comment]
A more general idea would be to bring in something like my `libosrm` C-wrapper for which you can easily guarantee both API as well as ABI stability.

https://github.com/daniel-j-h/libosrmc/blob/master/libosrmc/osrmc.h 

Of course this comes with the need to keep the API up to date, but it's only a couple of lines per `libosrm` function, translating between typed objects and opaque pointers for the C API. This would also allow for quite easy FFI bindings.

**Comment by TheMarex** [comment]
@daniel-j-h so you are proposing doing a hour-glass style library? I think it would be great if we would understand the pros and cons of that design decision better.

To your proposal: It is never too late for a bug fix. :-) If that actually works, why not add it in now.

**Comment by daniel-j-h** [comment]
Yes, hour-glass pattern for both API / ABI stability and ability to easily create FFI bindings.

Check out
- https://www.youtube.com/watch?v=PVYdHDm0q6Y
- http://www.slideshare.net/StefanusDuToit/cpp-con-2014-hourglass-interfaces-for-c-apis

I played around with this design pattern in https://github.com/daniel-j-h/libosrmc it's not complete wrt. the `libosrm` API but already gave me a good understanding of how to build something like that and what to look out for. There are also some bindings in that repo for Ansi C, Python, Haskell using FFI.

Cons I see are
- a bit more allocation since the opaque pointer technique only passes around heap addresses, but that's the only way to do it. For example parameters objects have to be alloc-ed and then passed around as a ptr. We could make the library allocator-aware and then a C++ header on top of it could easily use a stack allocator
- has to be kept in sync with the C++ interface: this is not too bad as v5 is in a somewhat stable state. The addition to `RouteParameters` above would have resulted in us adding one new function
- C++ <-> C translation has to be written manually: check the repo's `osrmc.cc`, we can at least use C++14 internally for the impl. which makes most functions a couple of lines only
- Care has to be taken wrt. exceptions and translating them to error conditions instead; a C++ interface on top of this C library then simply can throw again on those error conditions
- Working with the response is a bit clumsy in the C interface since the mapbox/variant structure is quite deep: I started exploring this by providing the user with two interfaces: a simple one providing often used features e.g. to directly get distance / duration, and a more advanced one where e.g. a Waypoint handler function can be set, check out [the docs here](https://github.com/daniel-j-h/libosrmc/blob/adad1e5e8e06ced68fd80c69085b2eda0e45bd4e/libosrmc/osrmc.h#L82-L109)
