### ISSUE TITLE
Notifications for Tunnels, Toll stations, etc.

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3028]
At the moment we're using `Notification` for travel mode changes (e.g. driving, ferry). It makes sense to convey more semantic meaning to clients for example for (longer) tunnels or other road network features.

Example:

![tunnel](https://cloud.githubusercontent.com/assets/527241/19239685/85fe1812-8f07-11e6-9dba-039ef8715cc5.png)

http://map.project-osrm.org/?z=16&center=51.046298%2C13.697033&loc=51.051080%2C13.705080&loc=51.047478%2C13.687710&hl=en&alt=0

At the moment the workaround here is to parse the name field and hope that longer tunnels have a dedicated name. But what about e.g. toll stations, parking lots, etc.?

What's our roadmap with regard to that?

**Comment by MoKob** [comment]
Right now, I would say that `mode change` is the wrong paradigm to use in tunnels/bridges/toll roads. After all, you are still travelling by driving the car.

Mode-Changes are used to describe actual changes in mode like pushing your bike, instead of riding it or taking the ferry instead of driving.

We can use notification to emit informations like tunnels, but we would need some form of annotation feature. The *hope* part you mention is more like a shortcoming which we cannot handle so far. The continue instructions for a tunnel are only due to the new names occurring. Ideally we wouldn't want to mention an intermediate tunnel by name as an instruction.

**Comment by daniel-j-h** [comment]
Update: with 5.9 we have the road classes feature in place and can easily add a `tunnel` road class if needs be. We'd need to parse the [`tunnel=`](http://wiki.openstreetmap.org/wiki/Key:tunnel) tag and set the road class in the [way handler](https://github.com/Project-OSRM/osrm-backend/blob/440dccb81bc6e02ffda076f0977989a4bb0958cf/profiles/lib/way_handlers.lua#L281-L311).
