### ISSUE TITLE
Cucumber Routability scenarios testing for speeds are broken

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3036]
In https://github.com/Project-OSRM/osrm-backend/pull/3022 I implemented alternating oneways influencing speeds. For testing this I added some routability scenarios to [features/car/speed.feature](https://github.com/Project-OSRM/osrm-backend/blob/6cf99c886fcb42c4e417f5477ed2c9d2eebb5554/features/car/speed.feature#L10-L24) with lower speeds.

Playing with these routability checks, it looks like they're broken. The tests pass even if you change speeds to e.g. 0 or 9000.

For the speed comparison [here](https://github.com/Project-OSRM/osrm-backend/blob/master/features/step_definitions/routability.js#L39-L41) printing `outputRow[direction]` and `want` reveals they're the same: we're comparing the user's input with itself and not with what we get back from osrm.

**Comment by daniel-j-h** [comment]
Note: this is not specific to `bothw` speeds, all our speed tests are broken.

**Comment by MoKob** [comment]
The speed does not define whether we can or cannot route on an edge. Even on speed zero or 9000, you are simply very quick or stuck on that edge. We set edge cost to a minimum of 1, so you will never be reaching infinite speed.

Zero itself is assumed to be an invalid speed, though (https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/extraction_containers.cpp#L371), since we need to be able to do https://github.com/Project-OSRM/osrm-backend/blob/master/src/extractor/extraction_containers.cpp#L392.

I don't think that setting a speed to zero should be invalid, but right now it is. We shouldn't disable the possibility to route over these, though. We should just take really long.

**Comment by daniel-j-h** [comment]
All our tests are using the `forw`, `backw`, `bothw` columns with speed values, see e.g. the [maxspeed.feature](https://github.com/Project-OSRM/osrm-backend/blob/f456d7ff86f60dc44a1742d74b57db86f50374ef/features/car/maxspeed.feature#L54-L62) which leaves those tests effectively as broken.

**Comment by daniel-j-h** [comment]
@karenzshea can you take a look - this is fixed now, isn't it? (if so feel free to close it)

**Comment by karenzshea** [comment]
May this stay fixed, https://github.com/Project-OSRM/osrm-backend/pull/3039
