### ISSUE TITLE
Different durations returned for reverse and forward routes

### ISSUE THREAD

**Issue by karenzshea** [Project-OSRM/osrm-backend#3038]
I noticed this while logging cucumber tests for https://github.com/Project-OSRM/osrm-backend/issues/3036

Routing on a test case where a way is set to
- one road class type
- not a one way

Expected outcome is that a route between two ponits on the way in either direction should return the same duration, but this is not the case. All the cases I've seen so far only differ by `0.1s`.

Specifically this test, [speed.feature](https://github.com/Project-OSRM/osrm-backend/blob/6cf99c886fcb42c4e417f5477ed2c9d2eebb5554/features/car/speed.feature)

**Comment by karenzshea** [comment]
Example logged from cucumber (I haven't been able to produce on an real world route yet). Specifically note that time is pulled directly from the OSRM routed response in the internal cucumber call.

```
{ forw: 
   { query: 'http://127.0.0.1:5000/route/v1/car/10.898737978337776,1.0;10.916719337063185,1.0?steps=true&alternatives=false',
     json: { code: 'Ok', routes: [Object], waypoints: [Object] },
     status: 'x',
     route: 'w11,w11',
     summary: 'w11',
     time: 232.3,
     distance: 1999.8,
     speed: 30 },
  backw: 
   { query: 'http://127.0.0.1:5000/route/v1/car/10.916719337063185,1.0;10.898737978337776,1.0?steps=true&alternatives=false',
     json: { code: 'Ok', routes: [Object], waypoints: [Object] },
     status: 'x',
     route: 'w11,w11',
     summary: 'w11',
     time: 232.2,
     distance: 1999.8,
     speed: 31 },
  bothw: { status: 'x', time: 'diff', distance: 1999.8 } }
```

**Comment by daniel-j-h** [comment]
Just to be sure here: please copy the .osm.xml cucumber generates for these tests (check the tests/cache directory), run osrm-extract, contract, routed on it and manually verify those values are already wrong in osrm.

While the distance is the same, it looks like there is a tiny difference in time - could be rounding or floating point issue.

**Comment by karenzshea** [comment]
Confirmed that the above also reproduces
```
{
	code: "Ok",
	routes: [{
		legs: [{
			steps: [],
			summary: "",
			duration: 232.3,
			distance: 1999.8
		}],
		geometry: "_ibEctoaA?koB",
		duration: 232.3,
		distance: 1999.8
	}],
	waypoints: [{
		hint: "FgAAgBcAAIAQAAAAiAQAAAAAAAAAAAAAmw0AAAsAAAAMAACAMU2mAEBCDwAxTaYAQEIPAAAAAQF9c9oG",
		name: "w11",
		location: [
			10.898737,
			1
		]
	}, {
		hint: "FgAAgBcAAIAQAAAAiQQAAAAAAAASCQAAiQQAAAsAAAAMAACAb5OmAEBCDwBvk6YAQEIPAAIAAQF9c9oG",
		name: "w11",
		location: [
			10.916719,
			1
		]
	}]
}
```

```
{
	code: "Ok",
	routes: [{
		legs: [{
			steps: [],
			summary: "",
			duration: 232.2,
			distance: 1999.8
		}],
		geometry: "_ibEodsaA?joB",
		duration: 232.2,
		distance: 1999.8
	}],
	waypoints: [{
		hint: "FgAAgBcAAIAQAAAAiQQAAAAAAAASCQAAiQQAAAsAAAAMAACAb5OmAEBCDwBvk6YAQEIPAAIAAQF9c9oG",
		name: "w11",
		location: [
			10.916719,
			1
		]
	}, {
		hint: "FgAAgBcAAIAQAAAAiAQAAAAAAAAAAAAAmw0AAAsAAAAMAACAMU2mAEBCDwAxTaYAQEIPAAAAAQF9c9oG",
		name: "w11",
		location: [
			10.898737,
			1
		]
	}]
}
```

**Comment by MoKob** [comment]
Given the size of the involved edges here (`distance of 1999.8`), I would suspect floating point inaccuracies to be the issue here, restricted as a problem to the phantom node creation, though.

For context: if we compute a route for
`a --(1) -------- b ------(*)------ c -------- (2) --- d` from (1) to (2), with (*) representing an arbitrary sized set of edges within the graph, the items between `b` and `c` are simply added using integer math. The cost for `1-b` and `c-2` are computed using floating point math, though. We are adding two so called **phantom nodes**  with a computed weight.

Now assume `1` is `3` percent along the way from `a` to `b`. The cost from `1` to `b` is computed as `0.97 * |ab|`. However, depending on the different parameters, `0.97 * |ab|` does not have to be equal to `|ab| - 0.03 * |ab|`. Depending on which direction you are looking at the edge here, you might get different results.

As a first check, I would look at the phantom node creation and maybe replace the floating point math by integer math.

**Comment by danpat** [comment]
@karenzshea The exact math that @MoKob is talking about is here:

https://github.com/Project-OSRM/osrm-backend/blob/49a28b478cc8bcbc783a9dca004aabeedaa12491/include/engine/geospatial_query.hpp#L395-L403
