### ISSUE TITLE
Issues handling speeds on certain surfaces

### ISSUE THREAD

**Issue by karenzshea** [Project-OSRM/osrm-backend#3053]
https://github.com/Project-OSRM/osrm-backend/pull/3039 uncovered some hidden issues with how speed handling happens on certain surfaces.

This test - https://github.com/Project-OSRM/osrm-backend/blob/61bdb6521161062a011022adc098e2311245820d/features/bicycle/surface.feature#L25-L33
and https://github.com/Project-OSRM/osrm-backend/blob/61bdb6521161062a011022adc098e2311245820d/features/car/service.feature

Running them you'll see that they are off by 20s or ~10 km/h. It's been lightly investigated whether these are actually the speeds we want but it's more likely that there is something wrong with our handling of them.

**Comment by daniel-j-h** [comment]
Re. bike surface: this looks fine. [Here](https://github.com/Project-OSRM/osrm-backend/blob/b72dc8c0cf25bb0e703684c3b8264c19727025f4/profiles/bicycle.lua#L18) we're setting a default speed of 15 km/h but [here](https://github.com/Project-OSRM/osrm-backend/blob/b72dc8c0cf25bb0e703684c3b8264c19727025f4/profiles/bicycle.lua#L34-L35) we set track and path to 12 km/h by default. The asphalt surface also [gets 15 km/h](https://github.com/Project-OSRM/osrm-backend/blob/b72dc8c0cf25bb0e703684c3b8264c19727025f4/profiles/bicycle.lua#L77) default assigned.

And since the [surface speed calculation](https://github.com/Project-OSRM/osrm-backend/blob/b72dc8c0cf25bb0e703684c3b8264c19727025f4/profiles/bicycle.lua#L392-L395) simply takes the minimum surface speed and track speed, we always end up with the 12 km/h ignoring the surface speeds completely because they are higher (15 km/h).

I guess it's a deficiency in the model: surface speeds should probably be a factor of the track's speed. And not fixed values. This is a bigger change, for this issue just update the surface test and open a separate ticket.

cc @emiltin

**Comment by daniel-j-h** [comment]
Re. car service speeds: this is due to our speed scaling

    speed * .8 + 11

15 km/h => 23 km/h that @TheMarex probably forget to account for when [adding service tag support](https://github.com/Project-OSRM/osrm-backend/commit/315823cce1da9a4bb51d4090d04f63a1641c2967#diff-536181ef3a0659d04b372478750a01e9R12).

Maybe check service tags such as

http://wiki.openstreetmap.org/wiki/Tag:service%3Ddriveway

and in the wild

http://taginfo.openstreetmap.org/search?q=service%3D

(note: some service tags are getting used for railways)

and add some sensible dedicated [service speeds](https://github.com/Project-OSRM/osrm-backend/blob/b72dc8c0cf25bb0e703684c3b8264c19727025f4/profiles/car.lua#L42-L46).

**Comment by TheMarex** [comment]
Looking at the implementation in the profile the current behavior of only making it slower seems intended. Since the mentioned tests where already adapted I'm going to close here.

**Comment by emiltin** [comment]
yes the intention was to simply take the minimum af the various factors that might reduce the speed. combining surface+track+maxspeed etc would get too complicated.
