### ISSUE TITLE
Wrong continue on uturn

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#3082]
I would have expected a `type: turn, modifier: uturn` here. Maybe this has to do with combination of steps?

http://map.project-osrm.org/?z=16&center=38.875541%2C-76.792974&loc=38.874856%2C-76.803328&loc=38.877027%2C-76.801322&hl=en&alt=0

<img width="801" alt="screen shot 2016-10-18 at 08 22 23" src="https://cloud.githubusercontent.com/assets/25713/19484306/02bb6d00-950c-11e6-9c1a-750e1ebd5e35.png">

<img width="279" alt="screen shot 2016-10-18 at 08 22 35" src="https://cloud.githubusercontent.com/assets/25713/19484318/0b39e1d2-950c-11e6-89ac-8eeed10d09ed.png">

/cc @MoKob @daniel-j-h

**Comment by MoKob** [comment]
@freenerd since you are staying on the same road, a `continue` is actually the typical type you see for a `u-turn`. 

It is a problem that I already noted as a side-effect in https://github.com/Project-OSRM/osrm-backend/issues/3077. Currently a u-turn can be given correctly both by `turn + u-turn` as well as `continue + u-turn`.

**Comment by freenerd** [comment]
@MoKob thanks, makes sense. I'll solve this on the osrm-text-instruction side by issuing a `Make a uturn` instead.

**Comment by 1ec5** [comment]
Opened mapbox/api-documentation#300 because this is unintuitive behavior.
