### ISSUE TITLE
New Names are not surpressed on added ref

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#3086]
http://map.project-osrm.org/?z=12&center=36.183611%2C-96.300316&loc=36.153123%2C-96.205902&loc=36.216337%2C-96.318898&hl=en&alt=0

<img width="928" alt="screen shot 2016-10-18 at 08 50 03" src="https://cloud.githubusercontent.com/assets/25713/19485388/f14ed8fa-950f-11e6-8dc7-c99e33292424.png">

<img width="330" alt="screen shot 2016-10-18 at 08 50 27" src="https://cloud.githubusercontent.com/assets/25713/19485394/f36293fc-950f-11e6-8137-e5359423a584.png">

/cc @MoKob @daniel-j-h

**Comment by MoKob** [comment]
That is strange since:

https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/guidance/toolkit.hpp#L233

https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/guidance/toolkit.hpp#L227-L229

and https://github.com/Project-OSRM/osrm-backend/blob/master/include/util/guidance/toolkit.hpp#L223 check exactly this case.

Have you checked if there are unnamed segments in between?

**Comment by MoKob** [comment]
Ahh. I found it. Thats a rather simple issue to fix. The issue here is that the references are not conatined. US 412 is given with and without space, which screws up our logic.

To fix inclusion detection of references, we need to parse these create a uniform format, based on the `;` in the list of references.
