### ISSUE TITLE
Guidance Preprocessing invalidly uses `.distance` for distance

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3121]
Some functions (turn discovery and sliproad handler) use `.distance` of our node-based-edges in their computation to find out about the length of segments.

This field is only named distance, though, and actually refers to the routing weight. Doing so, we are actually dependent on the speed of the road, which is undesirable.
After all, a sliproad remains a sliproad, even if there is a traffic jam around it.

We see failures due to this in https://github.com/Project-OSRM/osrm-backend/pull/3075.

**Comment by daniel-j-h** [comment]
I was just about to close this, but over in https://github.com/Project-OSRM/osrm-backend/pull/3075 the test you added is failing:

https://github.com/Project-OSRM/osrm-backend/blob/a3719696fbea3e165bcccd6f44327d42a46a0dad/features/guidance/dedicated-turn-roads.feature#L64

with

    depart,on ramp left,arrive

(also https://github.com/Project-OSRM/osrm-backend/pull/3075 accidentally got closed by Github since the commit message in the pull request for this issue says it's resolving it)

**Comment by daniel-j-h** [comment]
For the record: this is the test which should confirm we're actually making a turn instead of a merge based on the maxspeed changes.

**Comment by MoKob** [comment]
The issue in #3075 that remains is not due to this issue. The actual issue is solved over in https://github.com/Project-OSRM/osrm-backend/pull/3143. I also pushed an update to the scenario you see errors in.
