### ISSUE TITLE
extractor:graph compress stage

### ISSUE THREAD

**Issue by eryalee** [Project-OSRM/osrm-backend#3155]
why only do compression the node of out degree of 2, the node's out degree of 1 also make sense? i mean that the node which has 1 out degree also can be compressed.

**Comment by danpat** [comment]
@eryalee The graph compression needs to retain the network topology.  Nodes of degree 1 represent the ends of cul-de-sacs (and other dead-end roads), and must be retained in order to keep the network topology complete.

The function `GetOutDegree()` is somewhat mis-labelled - it actually returns the degree of each node if the graph is considered undirected.  I.e. for intermediate nodes along a one-way road, `GetOutDegree()` will return `2`.
