### ISSUE TITLE
Cannot load Traffic CSV

### ISSUE THREAD

**Issue by zabuTNT** [Project-OSRM/osrm-backend#3166]
Hi,
I'm testing osrm for using it in a possible future project. I tried to load a csv traffic file but I receive an exception without details. I'm following the [ traffic wiki](https://github.com/Project-OSRM/osrm-backend/wiki/Traffic)

`osrm-extract mymap.osm.pbf -p profile.lua --generate-edge-lookup`

then 

`osrm-contract mymap.osrm --segment-speed-file ../datas/traffic.csv`

output:

```
[info] Input file: mymap.osrm
[info] Threads: 1
[info] Loading edge-expanded graph representation
[info] Opening mymap.osrm.ebg
[warn] [exception] Invalid argument

```

file .osrm.ebg exists in the folder.

PS: I compiled the old 5.3 version because of this issue #3156. I don't know if this can be a problem.

Thanks
---

I resolved with master branch, no more exceptions.... now my problem is with the node IDs, how can I obtain them in a correct/easy way? Any suggestions? 

> The from/to ids are OSM node IDs that are directly connected. To update the speed for an entire way, you must list each node pair along the way in the CSV file

now I use http://www.openstreetmap.org/way/<way_nr> .... but maybe there is an easy way.
I'm a newbie with OSM world.... sorry

**Comment by daniel-j-h** [comment]
#3156 was fixed in https://github.com/Project-OSRM/osrm-backend/pull/3160 please try latest master.

    Opening *.ebg

is the last logging output before parsing the csv file - can you verify your file conforms to

https://github.com/Project-OSRM/osrm-backend/wiki/Traffic

There is a ticket for reporting better error messages which @danpat speced out in https://github.com/Project-OSRM/osrm-backend/issues/3046. Without that in place you can do the following:

remove your build directory and compile with debug information

    cmake .. -DCMAKE_BUILD_TYPE=Debug
    make -j $(nproc)

    gdb -q --args ./osrm-contract map.osrm
    catch throw
    run

and get a backtrace with `bt` out of the system.

**Comment by daniel-j-h** [comment]
> I resolved with master branch, no more exceptions.... now my problem is with the node IDs, how can I obtain them in a correct/easy way? Any suggestions?

You can [Map Match](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#service-match) your traces and use the `annotations` feature to get OSM Node IDs back.

Check out this response example:
https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#example-2

Closing here as not actionable for us.
