### ISSUE TITLE
Location from NodeEdge in profile.lua

### ISSUE THREAD

**Issue by fijemax** [Project-OSRM/osrm-backend#3180]
Hello,

I need to access at  "location"  from each "node" in way_function in profile.lua script. We can't access since we're not using libosnmium's NodeLocationsForWays cache.
I would like to know if we could access again to location from a way in Lua script in a future version of OSRM ?

**Comment by daniel-j-h** [comment]
See the comment here:

https://github.com/Project-OSRM/osrm-backend/blob/ceddfada3dfae23b04829ff78fb4fbe0d3629cca/src/extractor/scripting_environment_lua.cpp#L200-L203

OSRM was started before there even was `libosmium` and the extractor is using `libosmium` now manually reading chunks in parallel. If we want locations in there (which we _do_ need at some point for example for country awareness or general point-in-polygon tests without the need for external I/O) we have to plug in the location cache somehow.

This is definitely on the todo-list - if you want to have a go at it we're more than glad to help you there.

**Comment by fijemax** [comment]
Hi,

Thank you for the answer. This confirms what I understood by reading the code. I try to plug a cache "NodeLocationsForWays" into LuaScriptingEnvironment without success for the moment.

**Comment by daniel-j-h** [comment]
Here's the extractor's entry point:

https://github.com/Project-OSRM/osrm-backend/blob/01a2c6647251facf7fdd86d6801a8cd004570f12/src/extractor/extractor.cpp#L109

You have to plug in a location cache in there, filling locations in the Node processing step. Then register the appropriate functions in the scripting environment.

This is where the parsing happens in parallel:

https://github.com/Project-OSRM/osrm-backend/blob/5e167b8745954dece49dd7502a2f5d247d0d1c1e/src/extractor/scripting_environment_lua.cpp#L262

Because you first have to cache all locations and only then want to process ways I think you need to break the parallel for loop to no longer go go over all objects at once.

**Comment by fijemax** [comment]
I try to plug in a cache but when i try to update the location on the nodeRef i have an exception who say : what():  id 3655224911 not found
I use a NodeLocationsForWays. It is filled juste after the LuaScriptingEnvironment creation. And passed as ref in LuaScriptingContext.

**Comment by daniel-j-h** [comment]
The `osmium` tool already has a `add-locations-to-ways` command which reads a pbf caching all locations and then attaching those locations to the corresponding ways.

Running this on your `.pbf` file before using it with osrm _should_ allow you to access a way locations already without any changes needed.

http://osmcode.org/osmium-tool/
http://docs.osmcode.org/osmium/latest/osmium-add-locations-to-ways.html

Posting here for searchability.

**Comment by danpat** [comment]
@fijemax not sure if you still care about this, but this https://github.com/Project-OSRM/osrm-backend/pull/4167 shows how to use the `osmium::handler::NodeLocationsForWays` to populate location values on the `osmium::Way` objects before they're passed to Lua.

**Comment by fijemax** [comment]
Hi @danpat,
We used the `osmium` tool with the `add-locations-to-ways` command to populate node location before they're passed to Lua. For the moment this works find for us.
Thank you for your help. I close this issue.
