### ISSUE TITLE
Make libosrm algorithm aware

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3208]
We want to specialize the query-side of OSRM to use different algorithms. Primarily that means the following classes need to know about what algorithm we want to use:
1. Everything in `engine/routing_algorithms/*` (different implementation for each base algorithm)
2. Everything in `engine/data_facades/*` (loads different datafiles for each algorithm)
3. Everything in `engine/plugins/*` (needs to know which data facade to pass to which algorithm and whether that algorithm exists for the specified algorithm)

There are two ways we can approach this: Runtime polymorphism or compile-time polymorphism. Sine this abstraction touches a lot of our performance critical functions (`RouteStep` for example) compile-time polymorphism is strongly preferred.

One pattern to do this is policies or some other derived form (skeleton class that uses template functions), template specialization, etc.

A first step might be to extend `RoutingBase` by a template parameter for an algorithm tag like `osrm::routing_algorithm::CH` and make the current implementation the template specialization for `RoutingBase<CH>`.

/cc @daniel-j-h @danpat @MoKob on ideas to implement this nicely.

**Comment by daniel-j-h** [comment]
Policy-based I/O writer we never merged: https://github.com/daniel-j-h/osrm-backend/blob/39383855dd6958a0de3b9981b2780b4a37ce4b56/io/osrm_writer.hpp as an example.

@MoKob is currently playing with a similar approach for geojson logger with arbitrary properties.

**Comment by MoKob** [comment]
## My Feedback on Template Approach

In total I would love to see some measurements to back up [this approach](https://github.com/Project-OSRM/osrm-backend/commit/8b57aa37ce531a836901af7ef75ca9eea63511be) to get rid of the virtual functions we currently use in the project. I feel that using templates simply to get rid of virtual function calls adds a lot of complexity and maintenance cost over a few virtual function calls. Sure, the templates don't require the virtual functions but code duplication can blow up our code, also leading to slowdown. 
Compared to the overhead of creating our JSON response, both seem to be completely negligible to me. Our algorithm currently requires at most a few milliseconds to produce results, the construction of the JSON and the Geometry costs a lot more. I think we are close to a 100 ms?

Also I don't see the reason why we want to bind the data of the algorithms to the datafacade at all. If the algorithm requires a specific set of data, the rest of the data we keep in memory should not depend on it. E.g. if we want to switch data specific to MLD, why do we need to reload all shared items. If we should end up offering multiple algorithms that share a lot of data, we would duplicate a lot, throwing away memory.
I am thinking of customisation, we would want a way of updating the cost an algorithm uses (e.g. base graph weights + MLD distance matrices). The names, turn lanes... all stay the same for all algorithms. 
Putting all of this in a single datafacade adds overhead that is unnecessary in my view, especially if we say that update timing is essential.
In addition, it increases storage overhead if we have to add all information (like the structure of the graph data) to all facades that may be shared in our engine.

Using object oriented design, MLD and CH should come with their own datasets that may require management/updates through the watchdog.

## Discussion Topics

Before updating everything to an increasingly complex template structure I would love to have a discussion on:

- How big are the benefits of templating the engine in terms of running time
- How big is the structural penalty that we pay to have this template structure in terms of
   - code complexity
   - maintainability
   - cost to implement extensions that may be necessary
- How do we share data between different algorithms? Currently we see one big datafacade for each algorithm in this Prototype. My proposal would include:
 - removing algorithm dependent items from the datafacades we currently have, keeping the same structure (without templating to base pointers, staying at virtual functions).
 - providing dedicated data for the algorithms, capsuled by algorithms.
 - moving logic that is related to MLD data to the MLD algorithm, following the principles of object oriented design that should keep data and functionality close together
 - make the watchdog/update processes call on functionality of the algorithms they manage instead of managing dedicated objects that the algorithms have to be templated for.

### Templates in  Datafacades 

From what I see [here](https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/datafacade/shared_memory_datafacade.hpp#L83) and [here](https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/datafacade/process_memory_datafacade.hpp#L45) essentially don't care about the difference between shared/internal memory. They require a block of memory (be it addressed via a `void` or a `char` pointer). 

The further information of how datafacades operate is not depending on where the memory comes from. I would suggest that we use allocator schemes here rather than virtual functions templates. (cc @danpat).

We could get rid of the virtual functions that we currently use and replace everything with the one-block facade for shared items and different one-block facades for the algorithms.
Is there a reason why we should implement different layouts here as well? The interface is only necessary, if we want to switch between different facades at runtime. Right now we only have one type that is supplied with memory in different ways.
We could get this to be only one memory-facade, if we simply write an allocator for the memory and supply it to the datafacade. Both shared-memory facade and internal memory facade right now only allocate memory and supply it to the Contiguous-Memory-Facade. As long as we don't see a situation for different layouts on the near horizon, I would suggest to get rid of the virtual functions here, further eliminating the needs for templatisation of the datafacades.

/cc @daniel-j-h @danpat @oxidase

**Comment by danpat** [comment]
Personally, I'd prefer to see a non-template approach, for all the usual C++ reasons (slow compile times, horrible error messages, hard-to-read code, hard to navigate duck-typing).  Given [devirtualization](http://lazarenko.me/devirtualization/), it's even possible there's little to no performance gain to templates, depending on our exact usage.

I honestly think though that what's most important here is that @TheMarex gets his thoughts on this written down.  We have many pieces to put together to get [MLD](https://github.com/Project-OSRM/osrm-backend/projects/3) working - if it turns out that the templated approach leads to particularly fugly and hard to grok code, it doesn't strike me as a hugely difficult refactor to un-templatize.  We've refactored before and we'll refactor again.  I'd like to record a link to https://github.com/Project-OSRM/osrm-backend/pull/3525 in case we want to refer back to that approach.

**Comment by danpat** [comment]
On a semi-related topic - @TheMarex I seem to recall a while ago that we decided against supporting both CH and MLD at the same time at runtime.  Is that still your intent?

**Comment by MoKob** [comment]
@danpat the refactor is of course a reasonable way to go. I am a bit harder on this, though, since I already did some refactor to get rid of unnecessary templates (as linked here) and was told to throw that away because of the work that will get done at some point.
So if it is possible to clean up our code first, then extend it in a way that would support everything that we want, I'd strongly prefer doing some clean-up first.
Cleaning up in a way that pulls templates through the entire code base only adds a lot of complexity instead of reducing it.

**Comment by oxidase** [comment]
I see as a compromise is cleaning up current interfaces with #3525 and than rebase #3208 onto it to have in revlog both cleanup and new template-based architecture commits with single isolated steps.

I am on the side of the compile-time parameters and moving run-time polymorphism closer to request entry point where it is really needed. Time benchmarks are really hard as in 2017 code optimizers are clever enough ([-fdevirtualization](https://github.com/Project-OSRM/osrm-backend/issues/3208#issuecomment-271770384) and LTO) and probably comparing now will show any difference. But later after hierarchy extension it could bring a performance drop as an optimizer will not be able to devirtualize or inline more complex code.

**Comment by MoKob** [comment]
@oxidase can you talk a bit more about what you see as possible situations where there is need for virtual functions at all. I think that we might be fine with a single virtual call for memory allocation for the datafacade (not using any template wrappers around them, but allocating memory using an allocation interface).

All algorithmic usage would be using no virtual functions/no templates at all, since an algorithm is tied directly to its data. We shouldn't be needing any templates to run them at all, as well as no virtual functions. I think that forcing the same interface on two different datasets for different algorithms would be unnecessarily complicated.

What I imagine would be a separation between a CH and MLD in total, apart from the actually shared data, which could be stored in the datafacade as it is done right now.
For the engine wrapper, here templates could actually be useful. I think that everything that we have to do is provide an `engine wrapper` around the defined algorithms, providing a single call interface to be switched between. Specialised forms of a CH, e.g. a core-CH, would simply get a `Engine<coreCH>` specialised template, handling all stuff around the data. The CH should know exactly which data to use though (just like a `value_type` in containers) so that we could let the engine take care of allocating whats needed, as long as the entries follow the same scheme / or we could use template specialisation to make the different wrappers work.

The engine and the watchdog container are, to what I see, the only entry points that don't have a `1:1+` connection between the data and the algorithm. For all algorithms sharing the same data, we can put the data into a common base class and simply get a derived class that is called directly. No virtual functions/templates involved.

**Comment by oxidase** [comment]
@MoKob let me explain how i see the current situation and what i think https://github.com/Project-OSRM/osrm-backend/tree/refactor/algorithm-aware is solving.
Briefly it is all about code reduction and lowering run-time cost due to vptr indirect calls.

At the moment there is only a parameter `config.use_shared_memory` that is checked at runtime and depending on its value different data facades with the same virtual interface can be used. It is legal approach but requires indirect calls via vptr tables that is pretty costly. Removing the abstract base class `BaseDataFacade` and using `ContiguousInternalMemoryDataFacadeBase` as a base for `ProcessMemoryDataFacade` and `SharedMemoryDataFacade` can solve this, but now the problem is in `Engine` where `std::shared_ptr<datafacade::BaseDataFacade>` must be changed to a final type either `ProcessMemoryDataFacade` or `SharedMemoryDataFacade`.
One possibility is to create two classes `EngineWithProcessMemoryDataFacade` with a member variable `shared_ptr<ProcessMemoryDataFacade> facade` and `EngineWithSharedMemoryDataFacade` with `shared_ptr<SharedMemoryDataFacade> facade`. Another one is to declare one templated class `Engine<FacadeType>` with `shared_ptr<ProcessMemoryDataFacade> facade`.

It does not look like a win, but later if more run-time parameters will be added like `config.routing_algorithm` the first approach will require to add 2*#algorithms classes like `EngineCHWithProcessMemoryDataFacade` etc, but the second approach will require adding a just a single parameter to `Engine` like `AlgorithmType` and use as `Engine<AlgorithmType, FacadeType>`.
The approaches are nearly the same, with instantiated templates it will be the same number of 2*#algorithms internally generated classes like `Engine<CH, ProcessMemoryDataFacade>`, but in the `Engine` source code will not multiplied.

> a separation between a CH and MLD in total, apart from the actually shared data, which could be stored in the datafacade as it is done right now.

On the algorithm implementation side there is also no big difference either to write explicitly `CHRouting`
or as a template specialization `Routing<CH>` that implements routing algorithm interface. So CH and MLD will be separated in template parameter specializations as `Routing<CH, DataFacadeT>` and `Routing<MLD, DataFacadeT>`.

I know debug messages for templates are hard to read due to functional programming nature of type deduction (basically, compiler output is an execution call stack of failed type derivation, where type is "computed"), but it should not be a reason not to use it. Let's make in complicated template error cases  comments like https://github.com/boostorg/spirit/blob/develop/include/boost/spirit/home/qi/nonterminal/rule.hpp#L295-L297 with explanations why type deduction is failing.

I would suggest to wait until @TheMarex will finish refactoring and publish the branch for review, but also think #3525 is must be merged before because CRTP is misleading and is not used in `BasicRoutingInterface`, unless someone will really use it for mixins or static-polymorphism in `BasicRoutingInterface` with CRTP.

**Comment by MoKob** [comment]
@oxidase I understand that from the initial point of view it would like we end up duplicating a lot of different algorithms. Your initial point, however, builds on the fact that we require the different datafacades.

My entire point is building on the fact that both datafacades are actually identical though. The only difference between the two is the allocation of memory.
What we have right now is `SharedDatafacade == SharedMemoryAllocator< ContiguousInternalMemoryDataFacadeBase>` and `ProcessMemoryDataFacade == ProcessMemoryAllocator< ContiguousInternalMemoryDataFacadeBase>` (Technically of course they are derived classes, but they just are like to different classes).

What I propose is to have:

```
class Allocator
{
   virtual char* getMemory();
}

class SharedMemoryAllocator : Allocator;
class ProcessMemoryAllocator : Allocator;

if (process.shared_memory)
 facade = ContiguousInternalMemoryDataFacadeBase(SharedMemoryAllocator());
else
 facade = ContiguousInternalMemoryDataFacadeBase(ProcessMemoryAllocator());
```

This completely removes the need for virtual functions in the datafacade (no optimisation problems for vpointers), apart from the one call to get memory of course, and does not require multiple classes for the engine.

The next part is that I don't have a problem with templating the engine, I have a problem with templating everything to the algorithm. The engine is actually a container, just like the data_watchdog. Both do the same, managing an algorithm and/or a dataset. What I have a problem with is templating the algorithms to the datafacade and the engine and possibly whatever to come.

The algorithm itself should be tied 1:1 to the data that it is using, not to anything else. Since we don't have multiple datafacades (if using my allocation approach), we don't need any templatisation at all for the algorithm and we still don't have any virtual functions, no duplications of classes.

Templates in general are not my problem, my problem is using them when they are not applicable. Any container that shows repetition for many types is fine. E.g. you wouldn't do a vector_int, vector_float but you do the `vector<int>`. Thats the case for general management in case of the engine. But the Algorithm should be the one to know about which data it needs. So if the engine needs to know about the data, it should access `MLD::data` and `CH::data` based on its template parameter (the algorithm). In my view we shouldn't create an `Engine<MLD,MLDSharedMemoryData>` to call `MLD<MLDSharedMemoryData>` but we should make the datafacades access an allocator and only do `Engine<CH>`/`Engine<MLD>`.
I would have to say though that having a common algorithm interface would only add a single virtual function call for all of these, and given the > 100 ms we currently spent in assembling the graph would be totally worth it to me to simply don't do any templates at all here as well. It kind of depends on the actual requirements of the engine in the end, though.

The main problems in the OSRM problems that I see is that we separate the data from the actual logic around the data. If a datafacade needs data, it should be managing it. If an algorithm needs it, the algorithm should manage its internal state. Simply putting everything to the outside introduces these problems that we now are talking about in the first place.

**Comment by oxidase** [comment]
@MoKob yeah, my answer was just about how i understand changes in the branch. 

But your point is about a general architecture decision: should an algorithm use a single fully specialized datafacade type or datafacade type can be a template parameter of the algorithm? 
Here i don't know requirements for routing algorithms to give direct answer whether template parameters will be useful or not in the future,  it is simply a trade-off between code flexibility with templates overhead and simple but rigid code. 

Your approach with allocator is good to remove virtual function calls. 
<details>
<summary>Here is almost the same code with one virtual destructor in base DataFacade</summary>
#include <iostream>
#include <memory>

class DataFacade
{
public:
    int GetData() const { return *data; }
    virtual ~DataFacade() {};
protected:
    DataFacade() : data{nullptr} {}
    int *data;
};

class HeapMemoryFacade : public DataFacade
{
public:
    HeapMemoryFacade() { data = new int{42}; }
    ~HeapMemoryFacade() { delete data; }
};

class LocalMemoryFacade : public DataFacade
{
public:
    LocalMemoryFacade() : local_data(64) { data = &local_data; }
    ~LocalMemoryFacade() {}
private:
    int local_data;
};

void action(std::shared_ptr<DataFacade> facade)
{
    std::cout << facade->GetData() << "\n";
}

int main()
{
    action(std::make_shared<HeapMemoryFacade>());
    action(std::make_shared<LocalMemoryFacade>());
}
<details>

**Comment by oxidase** [comment]
as per chat with @MoKob one potential problem is a "translation" of runtime parameters into compile-time template parameters that occurs here https://github.com/Project-OSRM/osrm-backend/blob/refactor/algorithm-aware/src/osrm/osrm.cpp#L21-L28
At the moment it is only one parameter with two values, but it will be extended and will require instantiation of all engines from a direct product of all parameters. Here is an example with 3x3 parameters http://coliru.stacked-crooked.com/a/f639a5e5ff68a882

This must be discussed before using templatization  of algorithms.
References:
* https://arxiv.org/abs/1306.5142
* http://stackoverflow.com/questions/38644146/choose-template-based-on-run-time-string-in-c

**Comment by TheMarex** [comment]
This landed as a variation of the template approach described above.
