### ISSUE TITLE
64bit node / edge ids

### ISSUE THREAD

**Issue by karme** [Project-OSRM/osrm-backend#322]
have seen some int overflow trying a world import using nearly all tracks

is the code ready for 64Bit node / edge ids? (is it sufficient to adjust typedefs.h)?

PS: i first thought there was already an issue for that one, but I didn't find it - sorry if i missed it.

**Comment by 4x4falcon** [comment]
As I'm having problems with id's > 32bit i gather that this is still open.

I have data with node id's commencing at 1000000000000 (decimal) and osrm-extract crashes, I'm assuming that this is the problem as I have not run with gdb.

I've looked at the code and changed typedefs.h to unsigned long however this creates lots of other errors when compiling, which I have not sorted through yet.

Are there any plans to change osrm to 64 bit ids. I know there becomes memory issues but osm data is about 12months away from going over 4294967295 based on current id of 3727297211 and that it's been 18 months since passing node id 2147483647.

If you can point me to all places that need changing would be great as it's hard to work out code that has virtually no comments, by just sorting through make errors.

Otherwise great work.

**Comment by TheMarex** [comment]
Yes this is still an issues. Relevant parts of the code are:

- The node id list https://github.com/Project-OSRM/osrm-backend/blob/bb1428eeb14889890977d514dee84b78d400acb0/extractor/extraction_containers.hpp#L70 
- The remapping from OSM ids to internal ids https://github.com/Project-OSRM/osrm-backend/blob/bb1428eeb14889890977d514dee84b78d400acb0/extractor/extraction_containers.hpp#L70
- The temporary edges that contain references to OSM ids https://github.com/Project-OSRM/osrm-backend/blob/bb1428eeb14889890977d514dee84b78d400acb0/extractor/internal_extractor_edge.hpp#L71-L72

The important thing to note is that we only need 64bit for _external_ OSM ids, we renumber them anyway in `osrm-extract` since we only use a small number of them. So we need to take care to not confuse them in `osrm-extract` (and only use 64bit where necessary, otherwise memory usage might explode)

@daniel-j-h want to take a look at this?

**Comment by 4x4falcon** [comment]
Thanks.  I'll see what I can find to get it to work.

Really like the routing and interface work just would like to get it to work with our data.

**Comment by danpat** [comment]
Done in 9005fe2f61aa5478c5bf0bef5ec76843af04f93e.

Note that this is just support for 64bit *node* IDs, not way or relation IDs.  It's also *not* support for >2^32 actual nodes, just node ID values higher than 2^32.
