### ISSUE TITLE
Prefer Continued Destination Signs

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3258]
on [this](http://map.project-osrm.org/?z=17&center=37.827629%2C-122.283905&loc=37.826353%2C-122.288518&loc=37.827879%2C-122.281737&hl=en&alt=0) route, we give two different destinations.

At the very first part, we have two destinations `MacArther Boulevard;San Pablo Avenue`, on the second turn we only have `San Pablo Avenue`. 

In cases like these, we should prefer sticking to a single destination rather than using `MacArther` on the first and `San Pablo` on the second turn.

This could be done in post-processing to check direction information that follows close after another for common strings and stick to these.

**Comment by daniel-j-h** [comment]
Is this a backend issue or should this be done on the client side? I remember @freenerd talking about implementing (or wanting to implement) destination consolidation for text instructions.

**Comment by MoKob** [comment]
Well. I kind of feel like at least this situation described (at some point) needs to be server side. When we handle destination lanes, we are supposed to find the correct one.

The turn described here is essentially a case where we would want to guide the driver into the correct destination lane to begin with (even though specified as destination tags only). So if we ever add support for destination lane tags, finding the correct lane could depend on handling this on the server.

Since we have to implement it at the server at some time, we should probably consider handling it on normal destination signs already.

**Comment by freenerd** [comment]
Companion ticket for frontend compilation https://github.com/Project-OSRM/osrm-text-instructions/issues/30

We do want to continue to emit everything that is on the destination sign (e.g. `MacArther Boulevard;San Pablo Avenue`) in the response though, so that the complete destination sign can be displayed visually in the client.

**Comment by daniel-j-h** [comment]
> We do want to continue to emit everything that is on the destination sign (e.g. MacArther Boulevard;San Pablo Avenue) in the response though, so that the complete destination sign can be displayed visually in the client.

This means we can't do it in the backend's post-processing then.

**Comment by MoKob** [comment]
Or we have to find a way how to incorporate destination lanes. The problem at the respective intersection is that the destination is only specified for the turn as a whole, not on a per lane basis but you need to select the correct lane.

**Comment by daniel-j-h** [comment]
cc @pratikyadav for context.

**Comment by TheMarex** [comment]
I think this is an `osrm-text-instructions` problem since the API response actually correctly contains `MacArther Boulevard, San Pablo Avenue` for the first off-ramp instruction, but `osrm-text-instruction` just seems to pick one of them and not check which one would make more sense.

Slicing the information off on the server side would just remove information for the client that might be useful for display purposes.

**Comment by TheMarex** [comment]
Closing in favor of https://github.com/Project-OSRM/osrm-text-instructions/issues/115
