### ISSUE TITLE
Size of tile depends on architecture

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3343]
Looking at the node-osrm tests, they fail because the size of a tile is no consistent over linux vs. OSX. This should not be the case since we are using protobuf, which should provide platform independent encoding.

https://travis-ci.org/Project-OSRM/node-osrm/jobs/177262797#L1688

/cc @danpat

**Comment by danpat** [comment]
Hmm. A quick test building `osrm-backend` on Linux (gcc5) and OSX (XCode8) gives me:

```
-rw-r--r--    1 danpat  staff  104013 Nov 21 12:55 linux.mvt
-rw-r--r--    1 danpat  staff  104013 Nov 21 13:24 osx.mvt
```

For the tile `/tile/v1/driving/tile(17059,11948,15).mvt`, a tile in Monaco that's generated during the `osrm-backend` tests.  Need to dig deeper here...

**Comment by TheMarex** [comment]
@danpat it might make sense to try this with our Mason build environment in OSRM.

**Comment by danpat** [comment]
Did a little more digging - I've reproduced the two different tile sizes:

```
-rw-r--r--   1 danpat  staff   114140 Dec  1 18:11 tile-osx.pbf
-rw-r--r--   1 danpat  staff   114111 Dec  1 18:14 tile-linux.pbf
```

However, using a vector-tile dumping tool, the layers and features decode identically.  Still researching.

**Comment by danpat** [comment]
Found it - it's different `std::unordered_map` iteration order on different platforms.  Because PBF uses variable-length encoding, adding features to the tiles in different orders leads to different sized tiles.

I've opened a PR that enforces consistent ordering of tile features, this eliminates the platform differences.  The tests have been updated to check the tile size, and it should be the same everywhere now.
