### ISSUE TITLE
Residential way is not available when destination or origination in residential district 

### ISSUE THREAD

**Issue by DavidLiuGitHub** [Project-OSRM/osrm-backend#3386]
There is the gate in many residential district entrance and it's also private, for example http://www.openstreetmap.org/node/1303860300, it will cause the residential way unreachable, pls see details below.

http://map.project-osrm.org/?z=18&center=33.576594%2C-117.721805&loc=33.576638%2C-117.723860&loc=33.577505%2C-117.722154&hl=en&alt=0
http://map.project-osrm.org/?z=18&center=33.576888%2C-117.721778&loc=33.576638%2C-117.723860&loc=33.577635%2C-117.722223&hl=en&alt=0

**Comment by MoKob** [comment]
@DavidLiuGitHub you are correct. It is a known issue and is somewhat by design. To correctly handle these cases (only allow access when the destination is within the gated area), we require a long standing issue #77. The problem here is that we don't want to route into these areas, unless they are the start/destination of the trip and can't implement this without messing up the time we estimate

We are currently in the process of finally implementing this (https://github.com/Project-OSRM/osrm-backend/pull/2399) and it will soon become possible.

**Comment by daniel-j-h** [comment]
By the way, we _do_ route inside those if you drop both markers inside the residential district:

![map](https://cloud.githubusercontent.com/assets/527241/20792486/50c1af54-b7c2-11e6-96cf-55040be45ac2.png)

http://map.project-osrm.org/?z=18&center=33.577686%2C-117.721199&loc=33.578252%2C-117.720818&loc=33.577469%2C-117.721381&hl=en&alt=0

What does not work is starting with markers outside and trying to move them inside the residential district.
