### ISSUE TITLE
Demo server assertion hit

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3401]
```
terminate called without an active exception	

in: osrm::util::Coordinate osrm::extractor::guidance::CoordinateExtractor::ExtractRepresentativeCoordinate(NodeID, EdgeID, bool, NodeID, uint8_t, std::vector<osrm::util::Coordinate>) const: is_valid_result(result)

[assert] /mnt/ebs/osrm/2016-12-04-173001/src/extractor/guidance/coordinate_extractor.cpp:368
```

Got this on Sun, 04 Dec 2016 19:50:05 GM.

/cc @MoKob

**Comment by danpat** [comment]
@TheMarex I'm pretty sure that https://github.com/Project-OSRM/osrm-backend/pull/3397 hadn't yet been merged when the last demo server build kicked off - @MoKob's fix probably wasn't part of that code.

A new build should start tonight using the latest code, we should get confirmation that it's fixed in a couple of days.

**Comment by TheMarex** [comment]
@danpat if you look at the date of the checkout `2016-12-04-17300` it is from Sunday, three days after this was merged.

**Comment by danpat** [comment]
@TheMarex oh, good point, I didn't notice that.

That raises another question - what happened to the extraction run after `2016-11-30-173001`?  Was `2016-12-04-173001` really the next time we tried?
