### ISSUE TITLE
osrm-routed slow on first startup  EC2

### ISSUE THREAD

**Issue by hanny2** [Project-OSRM/osrm-backend#3407]
Hello,

we are running OSRM (version 5.4) on an Amazon EC2 Instance (m4.2xlarge = 8 vCPU, 32 Gib Memory) with Ubuntu 16.04 and having the problem that on the first start of an instance (launched by an image), it takes 25 Minutes to start the osrm-routed service. We are only using a few smaller countries: Belgium, Netherlands, Luxembourg and Germany. So the .osrm files are pretty small like ~2GB only.
Once the initial start finished, the service will re-start in a few seconds. 

We have been inspecting everything with htop and iotop and the cpu and memory have no load at all, ~3GB ram used and 2-3% cpu. But the "IO>" column of iotop is like 99% with only 2-3MB/s disk reading the .osrm files.

We are using the "General Purpose SSD (gp2)" more about that here:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSVolumeTypes.html?icmpid=docs_ec2_console

So what is the difference between the first start of OSRM on a new Instance and a reboot? Maybe any temporary files that will be created on a new instance, or is there a io cap in Ubuntu 16.04?

**Comment by daniel-j-h** [comment]
25 minutes to start `osrm-routed` for these small countries is orders of magnitude too much.
Can you make sure your `.osrm` files are not on a network mount and you're not swapping?

Try a cold start and then use e.g. `dd` to read all `.osrm` files writing to `/dev/null` to check if reading from disk is slow. That is, try isolating the issue from `osrm-routed` first.

**Comment by hanny2** [comment]
There is only one system mount, but what we tested so far:

# 1. # Drop the cache - slow performance: 
echo 3 | sudo tee /proc/sys/vm/drop_caches 
3 

time dd if=/opt/osrm-backend/osrm/gebenelux-osrm.osrm of=/dev/null bs=8k 
207966+1 records in 
207966+1 records out 
1703657728 bytes (1.7 GB, 1.6 GiB) copied, 437.244 s, 3.9 MB/s 
real 7m17.247s 
user 0m0.704s 
sys 0m0.000s 

free -h 
          total used free shared buff/cache available 
Mem: 31G 6.4G 23G 16M 1.8G 24G 
Swap: 0B 0B 0B 


# 2. # With the cache - fast performance: 
time dd if=/opt/osrm-backend/osrm/gebenelux-osrm.osrm of=/dev/null bs=8k 
207966+1 records in 
207966+1 records out 
1703657728 bytes (1.7 GB, 1.6 GiB) copied, 0.278035 s, 6.1 GB/s 
real 0m0.279s 
user 0m0.012s 
sys 0m0.264s 


# 3. # Drop the cache again - now it is much faster then the first try (the way it should be)...: 
echo 3 | sudo tee /proc/sys/vm/drop_caches 
3 

free -h 
	 total used free shared buff/cache available 
Mem: 31G 6.4G 24G 16M 142M 24G 
Swap: 0B 0B 0B 

time dd if=/opt/osrm-backend/osrm/gebenelux-osrm.osrm of=/dev/null bs=8k 
207966+1 records in 
207966+1 records out 1703657728 bytes (1.7 GB, 1.6 GiB) copied, 12.6321 s, 135 MB/s 
real 0m12.637s 
user 0m0.000s 
sys 0m0.668s 

free -h 
	 total used free shared buff/cache available 
Mem: 31G 6.4G 23G 16M 1.7G 24G 
Swap: 0B 0B 0B

**Comment by daniel-j-h** [comment]
So it's definitely an AWS EC2 issue and not related to osrm-backend.
I'm closing this ticket already as not actionable for us.

Your box seems to have enough memory - what I would try is creating a ramdisk and already doing `osrm-extract` and `osrm-contract` there so you never will hit disk. Also check your `.stxxl` config.

We can't help you much with your EC2 I/O issues otherwise. Check mount points, maybe destroy and spin up some new boxes to counter noisy neighbour issues etc. - this is unrelated to osrm, though.

**Comment by hanny2** [comment]
I think it is related to amazon, I will try this
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-initialize.html

**Comment by jessetarot** [comment]
I spent a **long** time to diagnose the same issue, so maybe this will help someone:

EBS instances which are restored from snapshots are (behind the scenes) "lazy-loaded" from S3.
Therefore, the first read of each "block" is very slow, because the data comes over the network.

https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ebs-initialize.html
