### ISSUE TITLE
Weird highway restriction

### ISSUE THREAD

**Issue by ma-schmidt** [Project-OSRM/osrm-backend#3428]
I have a routing problem. From what I understand, the problem comes from the fact that OSRM imposes a restriction on an highway that should not happen. I understand that usually this is a matter of the quality of the OSM data, but I don't think it's the case here. When using another routing engine that uses the OSM data (mapzen), this highway restriction is not present. Furthermore, when looking at the OSM editor (iD editor) there is clearly a well-marked highway there.

Here is what the OSRM debugger sees:
![osrm-debug](https://cloud.githubusercontent.com/assets/5505580/21030411/4e5f0680-bd6c-11e6-908f-35d883492bb5.PNG)

As you can see, for the East-West highway (Katy Fwy), only the exits are captured.

Contrast this with the OSM editor:
![osm-debug](https://cloud.githubusercontent.com/assets/5505580/21030445/806305d2-bd6c-11e6-83d7-47f5f3bcd933.PNG)

This leads to obviously suboptimal routing, as can be seen here:
![direction](https://cloud.githubusercontent.com/assets/5505580/21030491/c7072766-bd6c-11e6-94f5-17230539110f.PNG)

While Mapzen, which also uses OSM data, produces this:
![mapzen_direction](https://cloud.githubusercontent.com/assets/5505580/21030626/acd4f7fa-bd6d-11e6-8eff-97aac73a6603.PNG)

I am relatively new to the OSRM project but will do my best to provide any further required information. If you want to replicate the problem, it was around the coordinates (29.778784, -95.447274)

**Comment by danpat** [comment]
@ma-schmidt The problem here is HOV (High Occupancy Vehicle) access.  The roads that are chopped out (you can see the missing sections in the debug map image) are tagged as `access=hov` and `hov=designated`.  This means they're High Occupancy *only* - single-driver cars are not permitted.

Our setup does not route over restricted roads like this.  If you run your own OSRM server, you can change this behaviour, but the OSRM demo server errs on the side of caution.

**Comment by ma-schmidt** [comment]
Awesome! Thanks a lot for your help. Simply changing the car profile with `local ignore_hov_ways = false` solved the issue.
