### ISSUE TITLE
Error while running a lot of osrm-routed processes with frequent data updates

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3455]
Test setup:
- 4 different datasets prepared with a core factor of 0.8
- 20 osrm-routed instances connected to shared memory with two threads each
- continuously sending batches of ca. 10 long-ish running requests
- Every second cycle in a new dataset

Observation:
```
[error] Error while attempting to allocate shared memory: No such file or directory, code 7
[warn] [server error] code: No such file or directory (at include/storage/shared_memory.hpp:257)
```

This is blocking using `cluster` with our node bindings. Probable cause is a race condition in the data update part that I missed during my rewrite.

/cc  @danpat @miccolis

**Comment by oxidase** [comment]
I have uploaded a script for stressed dataset rotation https://gist.github.com/oxidase/dfbb3c820604baf864fe3d5486c40837

At the first run it results in 
```
[assert] /home/miha/osrm-backend/include/engine/datafacade/shared_memory_datafacade.hpp:83
in: osrm::engine::datafacade::SharedMemoryDataFacade::SharedMemoryDataFacade(const std::shared_ptr<osrm::storage::SharedBarriers>&, osrm::storage::SharedDataType, osrm::storage::SharedDataType, unsigned int): storage::SharedMemory::RegionExists(layout_region)
terminate called without an active exception
```
that is slightly different but close.

**Comment by oxidase** [comment]
Just found the root cause for my issue: at https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/datafacade/shared_memory_datafacade.hpp#L65 if the following state occurs
```
     layout_region = 3 data_region=4 shared_timestamp=7328
     current_timestamp={3, 4, 7330}
```
a process deletes the current data region. If another process hits https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/datafacade/shared_memory_datafacade.hpp#L83
it will find that data for {layout_region=3, data_region=4, shared_timestamp=7330} was already removed.

It does not look like the original issue with the lock file, could be another bug

**Comment by TheMarex** [comment]
@oxidase yep the bug was indeed that a dataset in-use was removed. The timestamp check was not sufficient because we could get overtaken.
