### ISSUE TITLE
GetPhantomNodes using radius

### ISSUE THREAD

**Issue by eryalee** [Project-OSRM/osrm-backend#3472]
Given a GPS,when searching the nearest edge, we just use radius as a filter.Why not consider that  in searching process,cut tree node/leaf by radius filter that the nearest distance greater than given radius? i think it can reduce the search node number. many thanks.

**Comment by MoKob** [comment]
The structure used in the discovery is a so called `r-tree`. It does region based splitting, allowing for fast queries to find the closest way to a point location.

The GPS precision is used as an additional filter to select valid candidates in our search. Since we cannot assume a fixed GPS precision (many devices might query the service), we cannot optimise for a single GPS precision but have to use the more general approach for finding nearest segments.

Nevertheless, we always appreciate the input. For now, there is just nothing we can do about this.
