### ISSUE TITLE
[Mason] Failed to download

### ISSUE THREAD

**Issue by airotz** [Project-OSRM/osrm-backend#3502]
Hello,

I am trying to build the osrm-backend using Linux Mint 17 Qiana, which is based on Ubuntu 14.04. I am facing the following problem when cmake tries to download Mason:
```-- [Mason] Downloading package https://mason-binaries.s3.amazonaws.com/linux-i686/boost_libfilesystem/1.61.0.tar.gz...
CMake Error at third_party/mason/mason.cmake:118 (message):
  [Mason] Failed to download
  https://mason-binaries.s3.amazonaws.com/linux-i686/boost_libfilesystem/1.61.0.tar.gz:
  curl: (22) The requested URL returned error: 403 Forbidden

Call Stack (most recent call first):
  CMakeLists.txt:388 (mason_use)
```
Previously, cmake has warned me that:
```CMake Warning at CMakeLists.txt:276 (message):
  ENABLE_MASON and ENABLE_LTO/ENABLE_GOLD_LINKER may not work on all linux
  systems currently
```
I am stuck with this problem. Could somebody provide some advice?

Thanks in advanced.

**Comment by daniel-j-h** [comment]
> https://mason-binaries.s3.amazonaws.com/linux-i686/boost_libfilesystem/1.61.0.tar.gz

It seems like you're building on a 32 bit platform. There are no pre-built binaries for i686.

We only support x86_64 (with some experimental platforms which might or might not work). What you can do is instead of using mason use your package manager for dependencies:

https://github.com/Project-OSRM/osrm-backend/wiki/Building-on-Ubuntu#ubuntu-1404-enable_masonoff

Keep in mind: your setup is not great for osrm: you're on Ubuntu 14.04 which is quite outdated and you seem to be on a 32 bit architecture which we don't really support.

I'm already closing this as not actionable for us. Feel free to report back if you have further questions.
