### ISSUE TITLE
Support destination:street tag

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3541]
Support the `destination:street=` tag (and check if there are others we are mapping but missing out on).

http://taginfo.openstreetmap.org/search?q=destination

cc @pratikyadav @MoKob

**Comment by Zian** [comment]
Is this improvement supposed to also show the contents of the destination:street tag in the OSRM directions?

If you ask for a route from [Vons to FirstWatch](http://www.openstreetmap.org/directions?engine=osrm_car&route=32.93909%2C-117.23255%3B33.04905%2C-117.28431#map=13/32.9911/-117.2593&layers=N), step 10 says "Take the ramp on the right onto unnamed road" rather than something about exiting to Encinitas Boulevard.

I'm posting this as a comment to [avoid creating a "me too" post](https://github.com/Project-OSRM/osrm-backend/blob/master/CONTRIBUTING.md).

**Comment by danpat** [comment]
@Zian The problem here seems to be that the UI code on openstreetmap.org isn't displaying OSRM's `destination` field - the `I5 North` value is there, but the `name` field is empty (as expected), and the UI is interpreting this as "unnamed road".

This needs to be fixed on the openstreetmap.org interface - OSRM is returning the necessary information.
