### ISSUE TITLE
Improve osrm-contract performance - caching

### ISSUE THREAD

**Issue by torshie** [Project-OSRM/osrm-backend#3550]
My Linux server has 200G memory, when contracting a large road network, osrm-contract uses only about 200M memory, most data are put on disk.

The performance is relatively poor (compared with a simpler CH algorithm I implemented before). I haven't profiled osrm-contract, the poor performance is likely caused by stxxl, IMO.

Add an option for end-users, so the users can disable stxxl for better performance if large amount of memory is available.

I can provide some help in my spare time if needed, but guidelines maybe needed, because I'm not familiar with the code base.

**Comment by daniel-j-h** [comment]
Care to switch in a custom stxxl config with the memory fileio and report back?

http://stxxl.sourceforge.net/tags/master/install_config.html

> memory : keeps all data in RAM, for quicker testing

**Comment by TheMarex** [comment]
The out-of-memory storage should be even less then the process memory storage. `osrm-contract` only writes to disk exactly once at about 70% of the contraction phase to rebuild the graph and remove nodes that are already contracted. 200MB for `osrm-contract` is very unusual - for road networks like Europe/North-America we are talking about 30GB or more.

All graph data structures actually needed for contraction are kept in main memory. Are you sure you are talking about `osrm-contract` and not `osrm-extract`?

**Comment by torshie** [comment]
@daniel-j-h I did a quit & dirty hack: removed all stxxl dependencies in CMakeLists.txt, and replaced stxxl::vector with std::vector. Then recompiled osrm-contract, I didn't see any improvements. I seems my guess was wrong, stxxl wasn't the bottleneck, I'll do some profiling then report back later.

@TheMarex Yes, I'm talking about osrm-contract. I was contracting road network of a big city, so it's much smaller than Europe/North-America. 200M is reasonable in my case. 

BTW, according to my personal CH implementing experience, 30GB to contract a road network of a country is surprisingly small. My simpler CH algorithm needed about 150G+ memory to contract a graph of 54M edges + 20M nodes, time cost was 2.5 hours. My CH didn't build the edge expanded graph, so it's not exactly an apples to apples comparison

**Comment by daniel-j-h** [comment]
Thanks for following up and clarifying the issue - I'm interested to see what you can find. There is an open issue (https://github.com/Project-OSRM/osrm-backend/issues/3331) with contract being slow in some specific cases.

I talked to @MoKob about this the other day. His first guess was the way we come up with [node priorities](https://github.com/Project-OSRM/osrm-backend/blob/813e16b9b4a66da924b86c510fe95aaa0dae5ab1/include/contractor/graph_contractor.hpp#L740-L764) which might be suboptimal in situations like these grid-cities in Argentina with almost of of the streets being oneways:

http://www.openstreetmap.org/#map=17/-38.71872/-62.27810

Similarly Moscow seems to be tagged with side walks parallel to streets which might be a similar problem for the walk profile. Might be #3331 is running into this.

**Comment by torshie** [comment]
I have read the main contraction algorithm, mostly in methods `GraphContractor::Run()`, `GraphContractor::ContractNode<false>()` and `GraphContractor::Dijkstra()`.

One important rule is to make sure that during the contraction phase exactly one Dijkstra search is performed on each node (which is the starting node of this Dijkstra search). `GraphContractor::Run()` seems to perform Dijkstra search on some nodes more than once. Duplicated Dijkstra's search are very costly.

Here is a simple example. For a simple graph with 4 nodes: A, B, C & D, and 4 undirected edges: A-B, B-C, C-D, D-A. Let's assume nodes B& D are contracted first. When contracting node B, a Dijkstra search starting with node A will be performed, when contracting node D the (almost) same Dijkstra search will be performed again.

To me, the contraction algorithm has such unnecessary performance overhead, _I'm not 100% sure_, because the functions aren't easily understood. If it has, the solution could be:

- remove the `forbidden_node` parameter of `GraphContractor::RelaxNode()`.
- cache very Dijkstra searching result.
- implement different (easy) algorithm to check whether a shortcut arc is necessary.

**Comment by MoKob** [comment]
Can you elaborate a bit on where you get the conclusion of where to run the Dijkstra searches/how to cache them?

To me, it seems impossible to actually do this in a reasonable way, at least with out side-constraints like memory overhead and/or the accuracy of the checks prohibit such a caching.

To describe why I think this way, lets start of with the initial phase. If we assume an average degree of 4, we could be looking at 4*4 connections in the worst case. Lets make this even only 10 to account for some smaller intersections. For all of these we would need to cache if a shortcut ist required, and in the case of when it is, we would have to remember the weight. So our structure would do 10-16 times the number of nodes in terms of integers, which would add a considerable overhead in memory to cache.
Especially in first stages, every search algorithm is only looking at very short distances anyhow, so we usually do not spent a lot of time anyhow for the search.

Now when we are looking at later stages of the search, when the graph becomes denser and the distances larger, we are using a lot of overhead in the search. 

Lets now consider the following:
![contract](https://cloud.githubusercontent.com/assets/12932279/21888035/bba4d6a4-d8c2-11e6-979b-94e16e538172.png)

We first do two searches for the two nodes in the middle of the left graph and decide to contract the one with the red circle. In the next step, the one with the green circle has to be re-done, since we don't know about any of the new connections.

The one for the red circle could theoretically be cached, but we would have to do something else differently than now. Right now we do a search that does consider far less nodes (e.g. max 1000) for finding nodes to contract (since we have to throw away most of the search information anyhow, as explained in the above example) and only compute a more thorough search for the nodes we actually contract (to be sure to not add unnecessary shortcuts). By doing the full search for all nodes, we would actually end up doing more work than we currently do, since we cannot keep Dijkstra searches between contraction steps (the underlying graph changes) and we would do larger searches, if we would want to re-use the information that is in the first search.

However, that is not actually measured, so I could be off here. I'd be glad to hear if your approach could actually help to speed up our engine.

**Comment by torshie** [comment]
The conclusion is based on my testing and advices from an online course. The online course can be found here (lecture 6 & 7): https://ad-wiki.informatik.uni-freiburg.de/teaching/EfficientRoutePlanningSS2012

First, about my testing.

I have only worked on node based graphs, I didn’t do any graph compression, the graphs had like 2.5~3 average degree (directed edges), the road network data was proprietary not OSM. I have only kept the source code, the testing result is lost, so all following numbers are based on my memory.

I actually implemented both algorithms, after implementing the cache, the time cost of contracting road network of Beijing dropped from a few minutes (don’t remember exactly how long, between 5 and 10 minutes) to less than 30 seconds. The graph size was about 0.5M nodes, 1M+ edges.

The cache needs _really_ a huge amount of memory. I actually spent a significant amount of time optimising the algorithm for memory consumption, in order to contract the road network of the whole country (22M nodes, 54M edges). The program needed about 150G memory and 2.5hrs to contract such a graph, and the final graph had like 160M edges. A 2x ~ 3x edge increase, surprisingly, this number is consistent regardless graph sizes.

Now, back to osrm-contract. There shouldn’t be any difference between contracting a node based graph and a edge-expanded graph except the graph density. Edge-expanded graph may be denser. This density difference may or may not be important to performance, I have absolutely no experience on this. For osrm-contract, more memory == more data into stxxl container == more disk operations == very slow, so the situation is kind of complicated here.

My cache implementation was like this: for every starting node, save all settled nodes during Dijkstra search (max 100, it’s very small compared with the number 2000 in osrm-contract) and previous hops for all these nodes. Basically, with such a cache, I can get all shortest path from the starting node to all 100 settled nodes. Yes, that’s a lot. Cached result can be removed when the starting node is contracted.

Dijkstra searching was very fast at early stages of the contraction. It’s the last few thousand nodes that really slow things down. In my testing, contracting the last few thousand nodes took as long as contracting the 22M nodes already contracted (based on my memory ;p).

There is a significant difference between sparse graph Dijkstra search and dense graph Dijkstra search: Dijkstra search’s time complexity is `O(E + V * log(V))`, for sparse graph, `E` is at the same order of `V * log(V)`, but for dense graph `E` is at the order of `V^2`, which is much larger than `V * log(V)`. So, when `V` is a few thousands, `V^2` is about tens of millions! This is consistent with my testing result.

As explained above, in the final stages of the contraction every Dijkstra search is slow, and duplication is more significant when graph is denser, duplication should be avoided.

@MoKob, as for your example, you get the duplicated search part wrong. When contracting the node in the red circle (assume directed graph), we have to do 4 Dijkstra search (starting with the 4 nodes directly connected to the node in the red circle), so when contracting the node in the green circle, there are actually 3 duplicated Dijkstra search (starting with the 3 nodes below the green circle).

> since we cannot keep Dijkstra searches between contraction steps (the underlying graph changes) and we would do larger searches

Yes, we can, even if the underlying graph has changed. If we use the cached Dijkstra search results, some unnecessary shortcut arcs will be inserted (no required shortcut arcs would be missing), which won’t affect the correctness of our algorithm, just slow down osrm-routed (a little bit).

**Comment by MoKob** [comment]
@torshie you are fully correct. After thinking about your early approach over night, yes, there is a way to cache these results. We simply can extend the algorithm to look at further nodes, not caring about that a few nodes are already in the searched nodes that are not part of the graph anymore. I didn't consider simply re-using partly unnecessary data.

Thats some valuable feedback that could help us out a lot. It's probably not related to the graph hanging completely but could help us speed-up the contraction.

**Comment by MoKob** [comment]
So I tried to see how much this could bring to us.

From my first look at the numbers, the caching in the form you did is way off from what we can do on a server infrastructure. 150G in memory for such a small graph is just not feasible on a planet-wide scale. Also, I kind of have to say that 10 minutes in running time is quite long for such a small graph. I would assume our set-up to already be much faster than that.

These numbers aside, I think it could be feasible to do only local caching higher up in the hierarchy, either of a LRU basis or fixed for a small set of nodes. I will be looking into this further.

**Comment by MoKob** [comment]
From trying to implement a cache in our hierarchy, I have to say that many of our limitations don't justify this additional overhead. We would need a very large number of caches to make it work. Since we would need a cache entry for every combination of `source/forbidden node`, for every possible node `n` we would need `deg(n)` dijkstra searches to cache. Given the size we need to keep accuracy high for larger graphs (search space of 100 does work on small graphs, not on planet scope) and reduce shortcuts. The amount of memory to keep a reasonable cache hit rate up is just too large.
