### ISSUE TITLE
Handling `highway=*` + `area=yes`

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3560]
At the moment we filter out _all ways_ which have a `area=yes` tag:

https://github.com/Project-OSRM/osrm-backend/blob/c1f833c80ff4cb61047ae790dacfa20adf43c4f4/profiles/car.lua#L331-L337

There might be situations where a way has `highway=*` _and_ `area=yes`.
From sampling the data it looks like these are mis-taggings such as

https://www.openstreetmap.org/edit#map=19/52.66674/13.38223
http://www.openstreetmap.org/way/51469067#map=19/39.17375/-76.91567

I don't think we should handle these at all - or are there legit use cases for this?

@srividyacb @planemad

**Comment by planemad** [comment]
The areas are mapped for visual purposes rather than for routing. They can usually be ignored as the ways are almost always mapped with the area.

<img width="288" alt="screenshot 2017-01-12 16 36 24" src="https://cloud.githubusercontent.com/assets/126868/21887318/77778936-d8e5-11e6-927d-a40b32fadf59.png">

In some rare cases mappers terminate the way at the area, so the routing could break there. But this is not a common approach and is usually done by inexperienced mappers.

**Comment by emiltin** [comment]
For pedestrian and bike routing, area=* & highway=* is legit and quite common, and should be routed on. Eg. the main square in Copenhagen: http://www.openstreetmap.org/search?query=r%C3%A5dhuspladsen#map=18/55.67580/12.56940.

At the moment, routing will only happen along the edge of the area, which is suboptimal - preferably you would cross the area in the shortest possible, see#64.

**Comment by daniel-j-h** [comment]
@emiltin this is not about area routing (which requires a different approach).

The way with highway + area here http://www.openstreetmap.org/way/123204478
is nothing actionable for this ticket, since it requires area routing.

I'm closing this ticket as data issue and not related to area routing https://github.com/Project-OSRM/osrm-backend/issues/64.
