### ISSUE TITLE
Allow annotations parameter to accept specific fields

### ISSUE THREAD

**Issue by karenzshea** [Project-OSRM/osrm-backend#3563]
The `annotations` parameter currently accepts a boolean and returns all the fields `duration, distance, nodes, datasources`. It could be useful to accept requests for only specific fields, i.e. accept `annotations=duration` and only return a `{ duration: 10, 5, 20 }` in the returned annotations object.

Leaving `annotations=true|false` to return all fields will ensure the changes are only additive.

**Comment by daniel-j-h** [comment]
The use-case is to trim down the response size? Because we have the data at hand anyway. I guess you want to accept a list of those enums or a boolean as in `annotations=duration,distance`.

Let's spec out what needs to be done for this:
- [ ] For [RouteParameters](https://github.com/Project-OSRM/osrm-backend/blob/fd57c5b48bd289ecf15ffa7ea703f0461536f784/include/engine/api/route_parameters.hpp#L56) we need to extend the boolean annotations flag to an enum with all the fields you want to include. We need to keep the old constructor and boolean for backwards compatibility. Check the `GeometriesType` enum a few lines above
- [ ] For [RouteParametersGrammar](https://github.com/Project-OSRM/osrm-backend/blob/fd57c5b48bd289ecf15ffa7ea703f0461536f784/include/server/api/route_parameters_grammar.hpp#L57-L58) which parses the user input we need to extend the rules from a boolean to a boolean or a list of enum values (check the `.add()` a few lines above and the `GeometriesType` enum for how to do this)
- [ ] For the [route api](https://github.com/Project-OSRM/osrm-backend/blob/fd57c5b48bd289ecf15ffa7ea703f0461536f784/include/engine/api/route_api.hpp#L218-L253) we can then conditionally add specific annotation fields

Want to run this out @karenzshea?

**Comment by daniel-j-h** [comment]
Note: `speed` along the way would be great to have, too.

**Comment by danpat** [comment]
@daniel-j-h WIP here https://github.com/mapbox/api-directions/pull/896

**Comment by TheMarex** [comment]
Breaking out the speed addition to https://github.com/Project-OSRM/osrm-backend/issues/3664
