### ISSUE TITLE
Investigate alternatives to central shared memory control block

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3633]
Currently we have a central control block that contains the current shared memory region. We use a conditional variable to signal all `libosrm` instances that the data was updated. This has a major limitation on OSX which expects the _address_ of the mutex that guards the conditional variable to be the same over all client (even in different processes where the shared memory might be mapped to completely different regions!).

#3627 fixes this issue by introducing a fixed address mapping for the control block which also contains the mutex. But this has the downside that our DataWatchdog is now a singleton since we can only ever have one per process, otherwise the shared memory mapping conflicts for each instance of DataWatchdog (since it is fixed to be at the same address on OSX).

This should be addressed down the line by not relying on a central control block at all anymore. For this we should investigate alternatives such as message based IPC mechanism to propagate updates and discovery of shared memory segments over files.

Future design constraints should include the possibility of having multiple (named) datasets in shared memory.

/cc @oxidase @danpat

**Comment by oxidase** [comment]
Tried solutions:
- spinning checks: 
  - :-1: introduces delays in data updates
  - :+1: simplicity
* two semaphores with counting waiting threads
  - :-1: non-robust against crashed or killed processes
  - :+1: fixed memory usage; data update delays depend only on the context switch
* semaphores queue
  - :-1: limited number of waiters due to fixed queue size
  - :+1: data update delays depend only on the context switch; one semaphore is used by only one waiting process, if the processes is  killed the associated semaphore will be signaled and later can be reused.

Closed via #3648 with a queue of semaphores for non-Linux systems the hard limit is 128 Engine instances in OS. It is allowed to use shared memory control block in multiple multi-threaded processes.
