### ISSUE TITLE
Invalid Edge Duration Tag Is Invalid

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3677]
We store 30 bits for duration [here](https://github.com/Project-OSRM/osrm-backend/blob/35c981a99eafdb4ee42da45726cb7ecc1e831768/include/extractor/edge_based_edge.hpp#L34).

Our invalid tag still uses the 32 bit max value [here](https://github.com/Project-OSRM/osrm-backend/blob/35c981a99eafdb4ee42da45726cb7ecc1e831768/include/util/typedefs.hpp#L87).

Branches such as [this](https://github.com/Project-OSRM/osrm-backend/blob/35c981a99eafdb4ee42da45726cb7ecc1e831768/include/engine/api/table_api.hpp#L116) can never trigger.

**Comment by oxidase** [comment]
Trying to quickly fix, get to the problem that there is no compile-time distinction between weights and durations, so it is hard to trace some failing tests where `INVALID_EDGE_WEIGHT` instead of `MAXIMAL_EDGE_DURATION`. At the moment it works because values are equal and implicitly casted to `int`. Without #3601 there is no complete guarantee of the correct fix.

**Comment by TheMarex** [comment]
Looking at this again I think the original bug report was invalid: The branch does trigger. We just assume that everything that is not-invalid is below 30 bits. No normal edge should ever have that value, we filter them out in the `updater`.

**Comment by daniel-j-h** [comment]
Hm do you have the location for where we transform the 30 bit duration in the EdgeBasedEdge to a 32 bit type? Otherwise I don't see how a check for int32 max can ever trigger for a 30 bit duration value.
