### ISSUE TITLE
Demo Server Hit ElongateBy Same Mode Assertion

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3762]
The demo server just hit

```
[assert][139876473235200] /mnt/ebs/osrm/2017-02-26-173001/include/engine/guidance/route_step.hpp:151
in: osrm::engine::guidance::RouteStep& osrm::engine::guidance::RouteStep::ElongateBy(const osrm::engine::guidance::RouteStep&): mode == following_step.mode
```

Probably related to the post-processing refactor that came in after 5.6 four days ago: https://github.com/Project-OSRM/osrm-backend/pull/3495 - at first sight I can see three `ElongateBy` calls, one of them explicitly checks for same mode.

**Comment by MoKob** [comment]
I've reproduced the case in https://github.com/Project-OSRM/osrm-backend/pull/3766, its happening at the Ontario Airport. 

The problem is in us having only one instruction for roundabouts. At the exit, the mode change into the ferry is now suppressed. The problem (likely) happens [here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/guidance/post_processing.cpp#L180) where we elongate into the ferry, before we remove the roundabout exit [here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/guidance/post_processing.cpp#L209).

As long as we have only a single roundabout instruction, this process requires special treatment, replacing the roundabout-exit with a new instruction to notify driver / or update the mode in the enter roundabout instruction to reflect that the exit is going to be a different segment.

The two choices I see right now:

 -  use mode change in roundabout
     - if the exit road changes mode, transfer the mode into the `enter roundabout` instruction
     - make sure that elongateBy calls do not assert on roundabouts with mode changes
 - add new notification instruction
     - if the mode changes on the exit, transform it into a notification (technically two instructions for the same location)
     

To handle it more easily, we would need to switch to the `enter` + `exit` model which gives two instructions per roundabout.
