### ISSUE TITLE
Issues with the Windows Artifacts

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3810]
@skeleten on IRC tried to use `libosrm` on Windows and had issues using the artifacts we still build and push to http://build.project-osrm.org. The two issues are: we don't bundle the headers for the public libraries, so users have to pull headers out of the repo. themselves. And then it seems like there are some linker issues: https://gist.github.com/skeleten/03bcbd49875941da0be033da45cf5204

---

In addition, I just had a look at the files we publish:
- Luabind is no longer needed
- Protobuf is no longer needed
- OsmPbf is no longer needed
- Intel TBB lib is from 2014 and should probably be upgraded
- I think we require Boost 1.62+ now for Windows (cc @oxidase I think you investigated here)
- Is [Wiki page](https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation) in sync?

**Comment by skeleten** [comment]
Hello, 
sorry I had to go. However I fixed the linking issues; the problem was me trying to compile a `Debug` build while linking to the `Release` libraries. 
Changing the configuration to `Release x64` fixed my issues.

While compiling with Visual Studio it does require the `boost-1.62` libraries, which can be pulled from Nuget (which should be preferred over bundling them as far as I understand).
Pulling 1.63 (the newest available version on Nuget) does not work.

**Comment by duizendnegen** [comment]
@skeleten I'd be happy to help, for me building on Windows works without a problem. You are right that you need a Release (or RelWithDebugInfo) build.

Would be good to investigate dropping some unused libs & upgrading others, though.
