### ISSUE TITLE
Use After Move

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#3820]
Using the new clang-tidy [use-after-move](https://clang.llvm.org/extra/clang-tidy/checks/misc-use-after-move.html) checks - which detect undefined behavior by us accessing moved-from objects - from LLVM 4 (see https://github.com/Project-OSRM/osrm-backend/issues/2631) reveals the following two issues:

---

```c++
packaged_task<int()> task{[]{ return 1; }};
auto task2 = move(task);
task.reset();
```

> terminated by future_error: No associated state

http://en.cppreference.com/w/cpp/thread/packaged_task/reset
> std::future_error if *this has no shared state. The error condition is set to no_state.

- [Use](https://github.com/Project-OSRM/osrm-backend/blob/c6e9cc8024fc3a0bd6700eeb17f48c209d184abd/src/tools/routed.cpp#L358)
- [Move](https://github.com/Project-OSRM/osrm-backend/blob/c6e9cc8024fc3a0bd6700eeb17f48c209d184abd/src/tools/routed.cpp#L322)

This one is in the server and on the cleanup path.

---

Second one - could be bad

- [Use](https://github.com/Project-OSRM/osrm-backend/blob/c6e9cc8024fc3a0bd6700eeb17f48c209d184abd/src/engine/routing_algorithms/shortest_path.cpp#L358)
- [Move](https://github.com/Project-OSRM/osrm-backend/blob/c6e9cc8024fc3a0bd6700eeb17f48c209d184abd/src/engine/routing_algorithms/shortest_path.cpp#L313)

This one is in the shortest path code; we have to check the control flow here.

**Comment by danpat** [comment]
I think what @daniel-j-h is trying to say is that we have a few cases of undefined behaviour because of [use-after-move](https://clang.llvm.org/extra/clang-tidy/checks/misc-use-after-move.html) coding errors.

The first case above is probably not critical as it only occurs on `osrm-routed` shutdown, but the second case needs to be fixed, that could definitely lead to bugs, depending on what the compiler decides to do.
