### ISSUE TITLE
osrm-extract use too much memory

### ISSUE THREAD

**Issue by Pcosmin** [Project-OSRM/osrm-backend#3839]
I run osrm-extract on a file(merged 6 files with osmconvert) which has 6.5 GB. I don't figure out if is normal that this command to use approximative 45 GB of memory. 

I found this comment from DennisOSRM from Nov 18, 2013
"Make sure that you load the correct files. Right now, you will need around 48 GB of RAM to run the server on the planet-wide dataset." (https://github.com/Project-OSRM/osrm-backend/issues/802)

Why my osrm-extract use so much memory?

Thanks

**Comment by grudolf** [comment]
48 GB are needed to run the server on planet dataset, data preparation needs more.

In my case, osrm-routed uses 20 GB of memory to serve Europe dataset, while preparation steps (osrm-extract, osrm-contract) needed:

- 20 GB disk space for .pbf input file, additional 42 GB for output files
- 96 GB memory (I had 32 GB RAM and 96 GB swap)
- 120 GB disk space for stxxl swap

**Comment by daniel-j-h** [comment]
@Pcosmin don't rely on 3+ year old comments, a lot happened during that time. Just take a look at the releases and / or the changelog. Most features come with an increase in memory (and disk), so that is expected. Also note, the resource consumption depends on profile: the walk profile creates a much larger road network than the car profile for example.

Closing this as: yep, we need more resources than three years ago.

**Comment by Pcosmin** [comment]
Grudolf, thank you very much for your answer!
