### ISSUE TITLE
Port ManyToMany plugin to MLD

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#3902]
We want to be able to efficiently compute many to many queries even on MLD. There are two implementations possible here:

1. Port the current search bucket based approach to MLD:
    - Probably slow since the search space will be huge
    - No additional data needed

2. Implement GRASP:
   - Needs a special partition scheme to be fast
   - Possibly needs parallelization to be efficient
   - Needs a lot of memory for the naive implementation
   - Very fast queries possible (1:100k in 150ms sequential)

**Comment by oxidase** [comment]
Closing here as the first point is implemented. GRASP speed up is worth in case of one-to-all queries (1:10k and more) but it will also increase memory consumption due to introduction a downward graph G↓.

Feel free to open a research ticket about GRASP memory/performance trade-offs with respect to the current implementation.
