### ISSUE TITLE
Collapse Scenario Failure

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#3933]
The following route ([link](http://map.project-osrm.org/?hl=de&z=13&loc=-33.964473845748486,151.1381596326828&loc=-33.964874269496946,151.13710280042142)) exhibits an unwanted collapsing behaviour.

The intersection in question looks like this:

![map](https://cloud.githubusercontent.com/assets/527241/24923493/957ccf0c-1ea6-11e7-97ac-b70b9649ab16.png)

The instruction shown is a `turn straight` which is obviously not the case and should be a `turn left`.
The instructions leading up to the turn are:

`Suppressed` and `turn slight left`. The instruction turning onto the road itself, however, is a `merge slight right`, as visible in [this request](https://router.project-osrm.org/route/v1/driving/151.137382,-33.964527;151.137135,-33.964919?overview=false&alternatives=true&steps=true&hints=;).

I see the following possible reasons, since (straight + left == ok [link](https://github.com/Project-OSRM/osrm-backend/blob/d6ac924b945546ce5727ffefd2a78c4536fcc035/src/engine/guidance/collapse_turns.cpp#L68-L85)).

The most likely error is that merge isn't correctly considered to compute the [angle itself](https://github.com/Project-OSRM/osrm-backend/blob/d6ac924b945546ce5727ffefd2a78c4536fcc035/src/engine/guidance/collapse_turns.cpp#L50-L51).

Somewhat in the same league would be the the [scenario operator](https://github.com/Project-OSRM/osrm-backend/blob/d6ac924b945546ce5727ffefd2a78c4536fcc035/src/engine/guidance/collapse_turns.cpp#L175-L250).

Less likely would be the scenarios not to trigger  [here](https://github.com/Project-OSRM/osrm-backend/blob/d6ac924b945546ce5727ffefd2a78c4536fcc035/src/engine/guidance/collapse_turns.cpp#L382-L383), [here](https://github.com/Project-OSRM/osrm-backend/blob/d6ac924b945546ce5727ffefd2a78c4536fcc035/src/engine/guidance/collapse_turns.cpp#L401-L408), or [here](https://github.com/Project-OSRM/osrm-backend/blob/d6ac924b945546ce5727ffefd2a78c4536fcc035/src/engine/guidance/collapse_turns.cpp#L409-L419).

A final possibility I see is that some other scenario (like [here](https://github.com/Project-OSRM/osrm-backend/blob/d6ac924b945546ce5727ffefd2a78c4536fcc035/src/engine/guidance/collapse_turns.cpp#L382-L389)) might be screwing with the detection.

**Comment by oxidase** [comment]
The problem is in the magic constant `MAX_COLLAPSE_DISTANCE = 30` that is too small, changing to 32 "fixes" the problem 
![screenshot from 2017-04-12 11-39-48](https://cloud.githubusercontent.com/assets/4421046/24951560/1f3a281a-1f75-11e7-92f8-692b41903762.png)

but in general it is better to avoid hardcoded constants.

Here is the step-wise debugger output:

* at https://github.com/Project-OSRM/osrm-backend/blob/d6ac924b945546ce5727ffefd2a78c4536fcc035/src/engine/guidance/collapse_turns.cpp#L165
```
step_at_turn_location = (osrm::engine::guidance::RouteStep &) @0x7fffe80125e0: {name_id = 24, name = "President Avenue", ref = "A1", pronunciation = "", destinations = "", rotary_name = "", rotary_pronunciation = "", duration = 4.7000000000000002, distance = 62.733004685252183, weight = 4.7000000000000002, mode = 1 '\001', maneuver = {location = {151.137717, -33.964437}, bearing_before = 264, bearing_after = 258, instruction = {type = Turn (3), direction_modifier = SlightLeft (5)}, waypoint_type = osrm::engine::guidance::WaypointType::None, exit = 0}, geometry_begin = 2, geometry_end = 6, intersections = std::vector of length 1, capacity 1 = {{static NO_INDEX = 18446744073709551615, location = {151.137717, -33.964437}, bearings = std::vector of length 3, capacity 3 = {90, 255, 270}, entry = std::vector<bool> of length 3, capacity 64 = {0, 1, 1}, in = 0, out = 1, lanes = {lanes_in_turn = 0 '\000', first_lane_from_the_right = 255 '\377'}, lane_description = std::vector of length 0, capacity 0}}}
transfer_from_step = (const osrm::engine::guidance::RouteStep &) @0x7fffe8012700: {name_id = 8, name = "Princes Highway", ref = "A1", pronunciation = "", destinations = "", rotary_name = "", rotary_pronunciation = "", duration = 1.3999999999999999, distance = 19.965193155738895, weight = 1.3999999999999999, mode = 1 '\001', maneuver = {location = {151.137154, -33.964699}, bearing_before = 215, bearing_after = 188, instruction = {type = Merge (4), direction_modifier = SlightRight (3)}, waypoint_type = osrm::engine::guidance::WaypointType::None, exit = 0}, geometry_begin = 5, geometry_end = 7, intersections = std::vector of length 1, capacity 1 = {{static NO_INDEX = 18446744073709551615, location = {151.137154, -33.964699}, bearings = std::vector of length 3, capacity 3 = {15, 30, 195}, entry = std::vector<bool> of length 3, capacity 64 = {0, 0, 1}, in = 1, out = 2, lanes = {lanes_in_turn = 2 '\002', first_lane_from_the_right = 0 '\000'}, lane_description = std::vector of length 2, capacity 2 = {8, 8}}}}
```

* at https://github.com/Project-OSRM/osrm-backend/blob/d6ac924b945546ce5727ffefd2a78c4536fcc035/src/engine/guidance/collapse_turns.cpp#L35-L44

entry_step_entry_bearing = 270
entry_step_exit_bearing = 255
exit_step_entry_bearing = 210
exit_step_exit_bearing = 195

* at https://github.com/Project-OSRM/osrm-backend/blob/d6ac924b945546ce5727ffefd2a78c4536fcc035/src/engine/guidance/collapse_turns.cpp#L45-L49
entry_angle = 195
exit_angle = 195
total_angle = 255

* at https://github.com/Project-OSRM/osrm-backend/blob/d6ac924b945546ce5727ffefd2a78c4536fcc035/src/engine/guidance/collapse_turns.cpp#L77
entry_step.distance = 62.733004685252183

* at https://github.com/Project-OSRM/osrm-backend/blob/d6ac924b945546ce5727ffefd2a78c4536fcc035/src/engine/guidance/collapse_turns.cpp#L88
`use_total_angle = false`


* at https://github.com/Project-OSRM/osrm-backend/blob/d6ac924b945546ce5727ffefd2a78c4536fcc035/src/engine/guidance/collapse_turns.cpp#L166
`angle = 195`, but value must be 180 + 15 + 15 + 75 = 285 or 255 without entry and exit steps bearings

**Comment by MoKob** [comment]
@oxidase nice find. Thank you for digging into this.

> but in general it is better to avoid hardcoded constants.

You are correct, feel free to change that.
