### ISSUE TITLE
Routing criterion - Weight

### ISSUE THREAD

**Issue by OnlyMate** [Project-OSRM/osrm-backend#3935]
How does the selection of a "route" exactly work? I found the calculation of the weights in the code. But how does the _weight_ exactly work with the selection of the preferred route? 

I've got this test data:
<img width="889" alt="bildschirmfoto 2017-04-12 um 14 24 42" src="https://cloud.githubusercontent.com/assets/25883227/24957423/010c9dfc-1f8c-11e7-9c98-adc2b36610ee.png">

Note: The red ellipse is marked as **highway**. The green ellipses are marked as **bicycle**.

In the following _result_ sections I wrote the calculated weights from each segment on the streets.

# Scenario 1
### Profile
```lua
function way_function (way, result)
  result.forward_mode = mode.cycling
  result.backward_mode = mode.cycling

  local highway = way:get_value_by_key("highway")
  local bicycle = way:get_value_by_key("bicycle")

  result.forward_speed = 1
  result.backward_speed = 1

  if highway then
    result.weight = 1
  end

  if bicycle then
    result.weight = 1
  end
end
```
Note: highway and bicycle weight are the same

### Result
As expected the result looks like this:
<img width="400" alt="1_issue" src="https://cloud.githubusercontent.com/assets/25883227/24957686/ca924622-1f8c-11e7-8496-7fdaf4c90dbc.png">

# Scenario 2
### Profile
```lua
function way_function (way, result)
  result.forward_mode = mode.cycling
  result.backward_mode = mode.cycling

  local highway = way:get_value_by_key("highway")
  local bicycle = way:get_value_by_key("bicycle")

  result.forward_speed = 1
  result.backward_speed = 1

  if highway then
    result.weight = 2
  end

  if bicycle then
    result.weight = 1
  end
end
```
Note: highway weight changed!

### Result
<img width="400" alt="2_issue" src="https://cloud.githubusercontent.com/assets/25883227/24957851/7eed4536-1f8d-11e7-9ab1-289bafb5c4b8.png">

# Scenario 3
### Profile
```lua
function way_function (way, result)
  result.forward_mode = mode.cycling
  result.backward_mode = mode.cycling

  local highway = way:get_value_by_key("highway")
  local bicycle = way:get_value_by_key("bicycle")

  result.forward_speed = 1
  result.backward_speed = 1

  if highway then
    result.weight = 4
  end

  if bicycle then
    result.weight = 1
  end
end
```
Note: Highway weight changed!
### Result
<img width="400" alt="bildschirmfoto 2017-04-12 um 14 38 45" src="https://cloud.githubusercontent.com/assets/25883227/24958002/13752ff2-1f8e-11e7-9c33-cfb0f748d2be.png">

How does the selection of the route **exactly** works? Maybe just the code snippet let me understand the selection.

**Comment by danpat** [comment]
The `weight` is multiplied by distance, so the actual weight of a road depends on the weight you set, and the road's length.

Once that is done, OSRM uses Dijkstra's algorithm to find the route with the smallest total weight.

If there are two routes with exactly the same total weight, then you'll randomly get one of them, depending on the order the data gets pre-processed.

**Comment by daniel-j-h** [comment]
For reference here's the pipeline's schema from the wiki. It's missing the speed vs weight generalization.

![pipeline](https://cloud.githubusercontent.com/assets/1892250/19296198/1de51b4a-8ff7-11e6-8339-31eb6361338a.png)

**Comment by oxidase** [comment]
@OnlyMate in your profile `weight` in `way_function` specifies the weight value for the complete highway way http://www.openstreetmap.org/way/32896289. For three cases weights will be {1,2,4}.

The first step after the profile extraction computes [weight per segment](https://github.com/Project-OSRM/osrm-backend/blob/d6ac924b945546ce5727ffefd2a78c4536fcc035/src/extractor/extractor_callbacks.cpp#L134). Here the way has 25 segments, so weights per segment are {1/25, 2/25, 4/25}.

The next step is to create edges between intersections from segments with the [compressor](https://github.com/Project-OSRM/osrm-backend/blob/d6ac924b945546ce5727ffefd2a78c4536fcc035/src/extractor/graph_compressor.cpp#L16-L21). This will distribute weight  of the way proportionally to nodes number over edges. In your example only 17 segments out of 25 of the way are used, so weights for the first route will be {0.68, 1.36, 2.72}. 

For the second path the weight will be ~2.2 because it consist of three ways and two ways are used partially for ~60%.  

This makes the second way in the third case preferable (2.2<2.72).

**Comment by MichalPP** [comment]
all examples and profiles use forward/backward _rate in way_function and result.weight in segment_function. imho it makes a lot more sense than setting weight in way_function.

**Comment by oxidase** [comment]
@MichalPP you are right! `weight` in `way_function` has a special use case similar to `duration` for ways without well-defined speed values like ferries. Also such ways have no "intersections" and have no a problem with using a fraction of the original way weight.

**Comment by OnlyMate** [comment]
Okay, thank you all very much. Now I got it!
