### ISSUE TITLE
Reevaluate usage of OSRM's std_hash

### ISSUE THREAD

**Issue by karenzshea** [Project-OSRM/osrm-backend#3962]
As we have in https://github.com/Project-OSRM/osrm-backend/blob/c81baae1b9ae09dabfe4c09e37d97f907b735be2/include/util/std_hash.hpp

### Questions
- Wherever it's used, can it be replaced with [boost::hash](http://www.boost.org/doc/libs/1_63_0/doc/html/hash.html) ?
- If not why

cc @daniel-j-h

**Comment by daniel-j-h** [comment]
Can't tell why - even the golden ratio number for mixing is the same; make sure to cross-check against Boost 1.55, though. We still support this version for Trusty and boost-latest ppas.

http://www.boost.org/doc/libs/1_55_0/doc/html/hash/reference.html#boost.hash_combine

Good way to find out: rip it out then see what Travis has to say. We run on Trusty, so that should be fine.

**Comment by danpat** [comment]
@karenzshea I suspect at some point we had a `std::unordered_map<std::pair<int,int>,blah>` somewhere in our code - doesn't look like we do any more, so this is probably dead code.

Like @daniel-j-h said - try removing it and see if anything breaks :-)

**Comment by karenzshea** [comment]
We should keep this implementation around - while we're still on 14.04 ubuntu/1.54 boost, boost hash does _not_ magically work for everything, such as tuples, on certain compilers that we're supporting.
