### ISSUE TITLE
Trip plugin duration estimation differs from route plugin

### ISSUE THREAD

**Issue by HGuillemet** [Project-OSRM/osrm-backend#3973]
Trying to understand why some routes provided by the trip plugin don't look optimal, I found out that the estimation of duration is not always the same between the trip plugin and the route plugin. Is it normal behaviour ?
Example:
GET /route/v1/car/2.466751,48.917903;2.447353,48.938655;2.444008,48.929742;2.438023,48.926085;2.466751,48.917903
returns in routes[0].legs[*].duration the values: 419.4 376.8 122.3 224.6
while:
GET /trip/v1/car/2.466751,48.917903;2.447353,48.938655;2.444008,48.929742;2.438023,48.926085?overview=false&roundtrip=true&source=first
returns in trips[0].legs[*].duration the values: 419.4 340.8 122.3 224.6

(version used is 5.7.0 with contraction algorithm)

**Comment by daniel-j-h** [comment]
Yep, Route by default uses the `continue_straight` parameter from the profile if it's not set in the URL.

Compare

    curl 'http://router.project-osrm.org/route/v1/car/2.466751,48.917903;2.447353,48.938655;2.444008,48.929742;2.438023,48.926085;2.466751,48.917903' | jq '.routes[0]'
    curl 'http://router.project-osrm.org/trip/v1/car/2.466751,48.917903;2.447353,48.938655;2.444008,48.929742;2.438023,48.926085?overview=false&roundtrip=true&source=first' | jq '.trips[0]'

vs

    curl 'http://router.project-osrm.org/route/v1/car/2.466751,48.917903;2.447353,48.938655;2.444008,48.929742;2.438023,48.926085;2.466751,48.917903?continue_straight=false' | jq '.routes[0]'

See the docs about `continue_straight` and check the `car.lua` profile.

The Trip plugin is not able to handle `continue_straight` since it's directly consuming the distance table's output. Sorry about that - the behavior here is confusion and inconsistent indeed.

**Comment by chaupow** [comment]
Heyho @HGuillemet thanks for digging in and reaching out.
I haven't had time to look into this in detail but my guess is that the trip plugin uses other options/parameters than the route plugin such as `continue_straight` or others (which is inconsistent and not optimal...)

In `src/engine/plugins/trip.cpp l:88` the route is computed with the computed order of the trip so in theory it should be the same output as calling `route`... 🤔 

Is this blocking you in some way? I could look into this if needed, just very busy with other stuff at the moment 😞

**Comment by daniel-j-h** [comment]
Yep looks like we could at least adapt the route response even though we don't optimize based on it:

- [Here](https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/plugins/trip.cpp#L88) we currently always set `continue_straight=false`
- [Here](https://github.com/Project-OSRM/osrm-backend/blob/59b70c4d1113956f9351c344ad616cd71be9c930/src/engine/routing_algorithms/shortest_path.cpp#L227-L229) if the optional is not set we use the profile's default
- [TripParameters](https://github.com/Project-OSRM/osrm-backend/blob/59b70c4d1113956f9351c344ad616cd71be9c930/include/engine/api/trip_parameters.hpp#L49) which have a `continue_straight` member subclassing from `RouteParameters`

To solve this we have to pass the parameter's `continue_straight` to the `ShortestPathSearch`.

**Comment by HGuillemet** [comment]
Thanks for the quick feedback. The continue_straight parameter explains the difference indeed.
I haven't look deeply at the code of the trip plugin, but it seems difficult to make the weight of a step between 2 waypoints vary depending on the previous step. 
Anyway we can more or less assume than the optimal trip is one that limits the number of u-turns, even without continue_straight.

**Comment by daniel-j-h** [comment]
Closing here after some confusion (sorry about that).

The distance table api the trip plugin is using internally is unable to handle the `continue_straight` paramter (always `false`). And because we optimize _on that_ the subsequent route request has to have the same parameters (`continue_straight=false`) otherwise the returned route might potentially be almost completely different.

The fact that the trip plugin returns a different route than the route plugin by default is indeed a strange behavior but if you think about the underlying building blocks in play it makes sense.

**Comment by jcoupey** [comment]
For the record, a related discussion mentioning timing differences between table and route in relation with the `continue_straight` parameter (formerly `uturns`) occurred a while back at https://github.com/Project-OSRM/osrm-backend/issues/2213.
