### ISSUE TITLE
TurnPenalty - 16bit

### ISSUE THREAD

**Issue by OnlyMate** [Project-OSRM/osrm-backend#4009]
Is there a reason why the _TurnPenalty_ is only a 16 bit int? 
[Definition of TurnPenalty](https://github.com/Project-OSRM/osrm-backend/blob/0e39aa9488bff97cffda1d12fb18cdeb537e0c03/include/util/typedefs.hpp#L72)

I got a problem with this, because I work with a _properties.weight_precision = 3_
[Here](https://github.com/Project-OSRM/osrm-backend/blob/0e39aa9488bff97cffda1d12fb18cdeb537e0c03/src/extractor/edge_based_graph_factory.cpp#L498-L499) the _properties.weight_precision_ for _turn_penalty_ is used and I get this error: _boost::numeric::positive_overflow_

The same multiplier is used [here](https://github.com/Project-OSRM/osrm-backend/blob/0e39aa9488bff97cffda1d12fb18cdeb537e0c03/src/extractor/extraction_containers.cpp#L410).

**Comment by oxidase** [comment]
@OnlyMate the reason is only to reduce file sizes for planet-wide graphs. For with 3 decimal digits after comma the limit value  `properties.max_turn_weight` is 32.767. So turn penalties can be clamped in profiles. Other possibility is to redefine locally [`TurnPenalty`](https://github.com/Project-OSRM/osrm-backend/blob/c66f67ac0748216fb8b1d39c74b094308d0e1f9c/include/util/typedefs.hpp#L72)

**Comment by OnlyMate** [comment]
Thanks!
