### ISSUE TITLE
OSRM-backend returns zero distance between two points on routing.

### ISSUE THREAD

**Issue by mecoFarid** [Project-OSRM/osrm-backend#4017]
So, we have installed OSRM to our server and tested it for http://router.project-osrm.org/route/v1/driving/40.415225,49.855988;40.356182,49.828279?steps=true. Public demo server returns distance as expected. Unfortunately when requesting route from server distance:0 is returned. Server request form: http://our.host.server/route/v1/driving/40.415225,49.855988;40.356182,49.828279?steps=true

**Comment by danpat** [comment]
@mecoFarid More details please, we cannot possibly help debug your problem without more information.

What map did you use?
What profile?
Do you have logs for your processing commands?

**Comment by mecoFarid** [comment]
I just used Postman to request the route as JSON, not implementing it on any map tile provider yet. I don't have backend logs, unfortunately.

**Comment by danpat** [comment]
@mecoFarid No, I meant which `.osm` file did you use to generate your routing database with OSRM?

Without more information, there's not much we can help you with.

**Comment by danpat** [comment]
Based on the lack of response, I'm assuming this turned out to be client error.  My suspicion is that the coordinates are backwards.

As supplied, the two points are just to the east of Ukraine:

![screen shot 2017-05-10 at 4 06 13 pm](https://cloud.githubusercontent.com/assets/1892250/25924995/aa282d7e-359a-11e7-86fe-8e7cbd050aef.png)

When swapped, they are within the city of Baku, Azerbaijan:

![screen shot 2017-05-10 at 4 08 49 pm](https://cloud.githubusercontent.com/assets/1892250/25925064/fea41c96-359a-11e7-99a3-125c0d5fd39d.png)

If your copy of OSRM was prepared with a basemap from Azerbaijan, then the original (backward) coordinates would both probably snap to the same spot on the north-west corner, which would explain the zero length.

Closing here as not actionable by us.  Please re-open if you can supply more information that indicates it might be a problem inside OSRM.

**Comment by mecoFarid** [comment]
@danpat Yes, that was the problem. Sorry, I've been offline for some time.

**Comment by virattara** [comment]
In my case it isn't:
http://35.154.122.152:3005/simple?start=73.72420012950896,24.576599705782183&end=73.7232444,24.5821876;73.7365667,24.5832383;73.7011833,24.57227;73.7003267,24.57609;73.7000745,24.5764158;73.6999646,24.5752213;73.6998533,24.5745883;73.6971156,24.5796102

Sometimes 0, sometimes the correct distance.

**Comment by virattara** [comment]
In my case, somtimes 0, sometimes the correct value:
https://xxxx/route/v1/driving/76.810808,30.719047;76.774762,30.7328271

**Comment by Tanjona03** [comment]
Hi! Can you help me too because I have a same problem with routing  a map on osrm-backend.
It returns distance=0 while I used a map.xml
