### ISSUE TITLE
Question: How to install into AWS/ELB

### ISSUE THREAD

**Issue by neilRGS** [Project-OSRM/osrm-backend#4070]
Hi all.
I am rather new to AWS and Elastic Beanstalk and would very much appreciate it, if someone could point me in the direction of a How To. The AWS documentation seems very much aimed at specific types of installation, none of which appear to match what I want to do (I could be wrong, and am just misinterpreting, of course).
I know I need to create an ELB instance (security group and so on), and upload OSRM in a Docker container, but there seem to be some steps required before that(?) to create the Docker instance itself.

As you can probably tell, I am confused by all the partial information, and once I have done this, I will be more than happy to post up a finished procedure document for review, refinement and publishing, in order to help those with the same questions, who follow.

Many thanks in advance for any assistance.

Neil.

**Comment by daniel-j-h** [comment]
Hey, this is the wrong place to ask for AWS specifics. Wrt. osrm we do provide some Docker images you can make use of [here](https://hub.docker.com/r/osrm/). You can also have a look at how we build them [here](https://github.com/Project-OSRM/osrm-backend/tree/master/docker). Other than that you have to refer to the AWS docs and tools to get your box up and running.

Note: the demo server currently runs on a `r3.8xlarge` box for the planet, so that it can cycle in new data while it keeps running. I'm closing this already as not actionable for us.

**Comment by neilRGS** [comment]
Ok, thanks Daniel.
I'll continue to try and make sense of Amazon's awful documentation.
