### ISSUE TITLE
missing/broken files

### ISSUE THREAD

**Issue by mentinghfreightcenter** [Project-OSRM/osrm-backend#4117]
I've followed instructions to build OSRM on AWS using an m4.16xlarge EC2 instance (64 core, 256 GB RAM), along with a 100 GB swapfile on a 250GB SSD drive.

After running osrm-routed /data/north-america-latest.osrm, I get the following errors

```
[warn] Missing/Broken File: /home/ubuntu/osrm/north-america-latest.osrm.partition
[warn] Missing/Broken File: /home/ubuntu/osrm/north-america-latest.osrm.cells
[warn] Missing/Broken File: /home/ubuntu/osrm/north-america-latest.osrm.mldgr
```

When running a curl command, `curl http://127.0.0.1:5000/route/v1/driving/13.388860,52.517037;13.385983,52.496891?steps=true`, I get a JSON response with empty data, code:OK, 1 leg, 1 step, 0 duration, 0 distance

Afterwards, I asked my colleague to start from scratch and build OSRM on a brand-new EC2 instance of his own, and afterwards, he had the same exact problems I ran into. Apparently, these files do not exist after running the OSRM toolchain. Do I not have enough RAM (256 GB) or a large enough swap file (100 GB)?

**Comment by daniel-j-h** [comment]
These are just warnings useful in case you want to try out the new pipeline described in

https://github.com/Project-OSRM/osrm-backend/releases/tag/v5.7.0

If you only extract North America make sure your query coordinates are within the bounds of North America. Otherwise all coordinates will snap to the nearest location within North America which will likely be the same (e.g. on some island) and return distances and durations of zero.

Closing already as not actionable on our side. Feel free to report back if this works for you.
