### ISSUE TITLE
Node.js libosrm result -> v8 rendering blocks event loop

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#4121]
Our Node.js bindings use an asynchronous worker for handling all osrm plugin calls: we enqueue the worker in the libuv thread pool. Once the worker gets to run it dispatches to libosrm for the heavy lifting while the eventloop is unblocked (this is why we use async. workers in the first place). If everything went fine we get a C++ variant out of the async. worker calling libosrm. The translation from this variant type back to v8 types is what our [json render](https://github.com/Project-OSRM/osrm-backend/blob/a92674022a23b98b688c7d738006d33abebe4749/include/nodejs/json_v8_renderer.hpp#L13-L62) is for.

Unfortunately we do this libosrm variant -> v8 transformation (rendering) **blocking the eventloop** [here](https://github.com/Project-OSRM/osrm-backend/blob/a92674022a23b98b688c7d738006d33abebe4749/src/nodejs/node_osrm.cpp#L153).

The `HandleOKCallback` function no longer runs asynchronously but instead it already runs on the main thread / eventloop again.

I haven't benchmarked any of this but remember: even coordinates are arrays with two elements and there is a huge number of variant and v8 objects (which need to be allocated) involved. My guess is rendering from libosrm variant to v8 can take a substantial amount of time when the response is large (think: `steps=true` or a detailed GeoJSON geometry).

---

Now I don't know how to work around this limitation as it's not possible to interact with v8 in the `Execute` function (libuv-land). The translation from libosrm variant -> v8 objects need to happen somewhere - but maybe this should not block the eventloop?

**Comment by TheMarex** [comment]
>  but maybe this should not block the eventloop?

Interacting with the V8 engine has to happen synchronously (and since there is only one thread of execution blocking the event loop). The best bet we have is to make this overhead as small as possible.

One idea was to circumvent our internal variant serialization and push that to V8 (think `json_factory.hpp` just with V8 types). However this would also be work that needs to happen on the V8 main thread. We need to benchmark if going from dense C++ structs to V8 types is faster then going from JSON variant to V8 types.

It seems possible that going from C++ struct to V8 types could actually mean more work on the V8 thread, while decreasing the overall work. (improved latency, decreased throughput at utilization) The important part however is that we can parallelize node using `cluster` as soon as we hit the saturation of the main loop.

I think it is important to make the point that overall we should focus on increasing latency (how long does one request take) of the bindings, not throughput (moving work from serial bottle neck to parallel part), since we can fix the throughput by fanning out at the process level.

**Comment by daniel-j-h** [comment]
I was mainly just surprised to see `HandleOKCallback` working on the main thread without any options for us to create v8 objects in other ways (at least I haven't found any).

If you think about that in terms of throughput it could make sense to just render our result to a json string in the async. worker and then pass the string to Javascript having the user call `JSON.parse` on it oO

**Comment by daniel-j-h** [comment]
Closing as meh.
