### ISSUE TITLE
Datafacades assume data layout is in a contiguous memory block

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#4158]
Currently, it is only possible to implement alternative datafacades using the all-in-one-block structure described by the ContiguousInternalMemoryDatafacade.

If someone would want to implement an alternative storage approach - e.g. keeping data in individual files and `mmap()`-ing them, then our current inheritance structure makes this impossible - the algorithm-specific classes assume they're based on the ContiguousInternalMemoryDatafacade rather than the BaseDatafacade.

We should refactor this so that alternative storage can be implemented without needing to re-write the algorithm-specific subclasses.

**Comment by TheMarex** [comment]
I talked with @oxidase about this yesterday a little bit an we concluded the best option here would be a compile time switch, since we don't need the flexibility of switching this at run-time.

There are two methods to do this:

1. Go full template. This is undesirable on multiple levels and chances are we would never use this functionality.
2. Compile-time switch using a type alias. For external embedders of OSRM this should work just as well.
