### ISSUE TITLE
Adding Road-Bike for durations

### ISSUE THREAD

**Issue by kkocabiyik** [Project-OSRM/osrm-backend#4170]
Is there anyway to add Road bike durations to api like openrouteservice.org?
Thanks,
Kemal.

**Comment by daniel-j-h** [comment]
Do you want an additional profile on the demo server?

http://map.project-osrm.org/

We only run he car profile because 💸. But you can run your own profile or modify a default profile, see

- https://github.com/Project-OSRM/osrm-backend/tree/master/profiles
- https://github.com/Project-OSRM/osrm-backend#quick-start
