### ISSUE TITLE
Mismatch between turn lane indications and step instruction modifiers

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#4188]
The second step of this route indicates that you should "slight left at the fork", but the lane indications for that spot indicate "straight".

http://map.project-osrm.org/?z=16&center=52.237248%2C10.524752&loc=52.236749%2C10.521855&loc=52.240192%2C10.527885&hl=en&alt=0

![screen shot 2017-06-21 at 2 23 46 pm](https://user-images.githubusercontent.com/1892250/27407476-4498edc2-568d-11e7-928a-3d0c526356ed.png)

![screen shot 2017-06-21 at 2 21 23 pm](https://user-images.githubusercontent.com/1892250/27407449-2b034fb0-568d-11e7-8560-dbbb2c6a611a.png)

These instructions could be interpreted as contradictory - do we go left or do we go straight?

Looking at the satellite imagery for this location, it's a subtle thing - you *do* take the left-hand branch of the fork, but it's a 1 degree angle, so basically you go straight.

Is this as good as we can do?  Is there a better way to represent this scenario?

**Comment by MoKob** [comment]
@danpat this looks like a simple question of wording to me. At least in my personal feeling, I would assume `keep left` to be the instruction of choice when a road forks, just as well as `keep right`.

I'd assume that `keep right` on the right lane would be a perfect fit, since the arrows also mark it as such.
My general assumption would be that the lane markings are a visual aid and should reflect what is on the map.

![screen shot 2017-06-27 at 09 56 25 2](https://user-images.githubusercontent.com/12932279/27576906-f82ba268-5b1e-11e7-9822-49fa2e90f8b2.png)
[link](https://www.mapillary.com/app/?lat=48.9974621&lng=8.4105437&z=17&pKey=YmriadM3MYi4oZ4fPUbirQ&focus=photo&x=0.48589002261214376&y=0.5609586284352577&zoom=0&menu=false)

The above image is one of my favourite examples in Karlsruhe which often catches cars.

The arrows on the lanes are `left | straight;right` so we have one lane for going `left`, one for going `straight` and `right`.

Simply based on that knowledge, how would you drive to the road turning slightly to the left? Most people would probably assume the `left` arrow. That takes you down to another road, though, which is turning left even more strongly.

![screen shot 2017-06-27 at 09 58 17 2](https://user-images.githubusercontent.com/12932279/27577061-9928a904-5b1f-11e7-8b52-f12011c51e44.png)
[link](https://www.openstreetmap.org/export#map=19/48.99724/8.41078)
All three other turns are done from the right lane (slight left, slight right, right).

So I think in terms of mismatching between turn instructions and lanes, there is only so much we can do.

In the example you linked, we could think about a few solutions:

 - different wording for forks / symbols
    - change `keep [left/right] at the fork` to `keep [left/right]`
    - use a less strong symbol for forks (e.g. dedicated fork symbol over left arrow)
 - use different turn instruction for forks on ramps
    - add a new instruction type / or meta-information to distinguish forks on ramps from other forks
    - do the first solution, but only on motorway_links

I have seen a few of these cases pop up, and all of them were connected to motorway ramps. What is your take, should we think about dedicated handling for these? What would be, in a perfect world, the instruction/lane combination you would have expected?

**Comment by danpat** [comment]
Mysteriously, the API response here has changed since this ticket was written:

![screen shot 2017-07-05 at 12 05 14 pm](https://user-images.githubusercontent.com/1892250/27880552-3c18118a-617a-11e7-9f2b-ce5147bdde96.png)

and the "slight left" instruction has been collapsed.  I can't see any relevant data edits in OSM - @oxidase @MoKob @TheMarex anyone know what we changed that would've affected this behaviour?

**Comment by danpat** [comment]
Ok, I've tracked down why we're not seeing the "keep left at the fork" - the intersection node in question was moved in this changeset:

https://www.openstreetmap.org/node/740063445/history

Red = old intersection position, green = new intersection position

![screen shot 2017-07-12 at 11 02 20 am](https://user-images.githubusercontent.com/1892250/28132457-c14eeea6-66f1-11e7-86de-caffa351a2bb.png)

If I'm reading this right, It looks like this drops the turn angle below `MAXIMAL_ALLOWED_NO_TURN_DEVIATION` (currently set to 3 degrees), and we no longer assign the fork instruction type.
