### ISSUE TITLE
Don't suggest u-turns from lanes that might cross straight-through traffic

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#4189]
This route indicates that u-turn maneuvers are valid from all lanes, which is wrong and dangerous:

http://map.project-osrm.org/?z=18&center=52.149544%2C9.938298&loc=52.150074%2C9.938040&loc=52.149857%2C9.938255&hl=en&alt=0

(Note: were not showing lane info for u-turns on the `osrm-frontend` GUI, so the data isn't visible, see below)
![screen shot 2017-06-21 at 2 30 45 pm](https://user-images.githubusercontent.com/1892250/27407679-3dcb3ea4-568e-11e7-84a9-8de96ff5bd66.png)

![screen shot 2017-06-21 at 2 31 43 pm](https://user-images.githubusercontent.com/1892250/27407762-93647cae-568e-11e7-842c-ed11e61a348d.png)

The OSM data for these ways only has `lanes=2`, there are no `turn:lanes` tags.  We should not suggest turning across potentially `straight` lanes in any situation.  If there are no `turn:lanes` data, we should issue only edge-hugging turn maneuvers.

**Comment by MoKob** [comment]
@oxidase and I are currently looking into that issue. The highlighted problem isn't really the problem though. The maneuver itself does not offer turn lanes (which could only be found on intersection[0]). The `intersection[2]` array highlighted here is the segment after the uturn when already traveling north again.

The problem is a combination of no-lanes being available (data issue) on the roads entering the intersection as well as us not detecting these lanes correctly.

![27407679-3dcb3ea4-568e-11e7-84a9-8de96ff5bd66](https://user-images.githubusercontent.com/12932279/27431527-20cb7606-574d-11e7-8bb2-559097bb8eca.png)

We already mapped the turn lanes and are now looking into exposing the correct lanes for this intersection.
