### ISSUE TITLE
Add back .npmignore

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#4193]
In https://github.com/Project-OSRM/osrm-backend/commit/addf4d90e93b969edbaed17270ac12da8d644c83 the .npmignore got removed for the benefit of using .gitignore.

This leaves us with some data that is not needed in the published npm module:

```
$ du -sh test
5.2M	test
$ du -sh features
1.6M	features
```

Not huge, but given the 71 MB of the unpacked data on Mac OS X, this is 10% overhead.

**Comment by MoKob** [comment]
With this whitelist missing, if you have local data available that shows up as `untracked` in `git status` you can see and also possibly add invalid data to the package.

I've encountered due to a 1.1GB package, including lots of pngs and osm files, only showing the following error:

```
npm ERR! toString failed

npm ERR! A complete log of this run can be found in:
```

Would love to get the explicit whitelist back.
