### ISSUE TITLE
routing on waterways

### ISSUE THREAD

**Issue by benjaboater** [Project-OSRM/osrm-backend#4197]
Hello, I have been researching methods to route boat travel along waterway=river which, in map editor contains a routable element, but adding a start and destination on a river simply routes you via streets nearby. I looked at issue 980 and an expert advised that routing on rivers is possible, but not in open waters. How do I actually create a route on waterways?

**Comment by emiltin** [comment]
you need to create a new lua profile. you would check for the relevant OSM tags, e.g waterway=* and then set the mode and speed.

routing across open water areas is not possible with osrm yet, however as a workaround you can make osrm route along the edges of such areas. for example, if natural=water  and water=lake then you could set mode and speed.

a problem you might run into is connectivity. if the waterways are not connected at nodes, routing between them will not be possible.

**Comment by daniel-j-h** [comment]
Closing here. Area routing with all its issues is ticketed in https://github.com/Project-OSRM/osrm-backend/issues/64.

**Comment by benjaboater** [comment]
Hi, I spent some time trying to figure out how to make a new LUA profile
but I am not a software developer and don't really understand how to do
this. I was hoping it could just be a transit mode I can select here, at
OSM's main webpage. Is this possible?

[image: Inline image 1]

**Comment by daniel-j-h** [comment]
Sadly not, you have to adapt e.g. the [car.lua](https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua) profile and parse the waterway related OpenStreetMap tags.

**Comment by benjaboater** [comment]
Thanks for the advice Daniel. I see what to modify in the LUA file, but
what do you do with an LUA profile after you have modified it? I don't
understand where the LUA interacts with the mapping and routing engine. Do
I upload a modified LUA somewhere?

OSM and OSRM would be the only product available that could build routes on
inland waterways if this was possible.

**Comment by danpat** [comment]
@benjaboater The lua profile is used to filter OSM data when loading the map into OSRM -> the lua profile decides which OSM ways are included in the routing data, and what travel speeds they have.  The `car.lua` script filters OSM for roads and drivable ways, the `foot.lua` profile includes everything you can walk on.

None of the Lua scripts we ship with OSRM will include waterways.  To achieve waterway routing, you'd need to develop a Lua script that recognizes OSM waterway ways/ferry routes/etc.

The Lua script is used when you use the OSRM pre-processing tool `osrm-extract` - it's not something you can just upload to the demoserver.  You will need to run your own OSRM server, the easiest way to do this is to follow the instructions here using the pre-build Docker images for OSRM:

https://hub.docker.com/r/osrm/osrm-backend/

To be honest, I don't like your chances of success.  There are two major hurdles that I can see:

  - OSRM routes along ways.  Water bodies that are drawn as lines might work OK, but water bodies that are drawn as polygons .... OSRM will route on the outlines, not across the empty space in a straight line.  [This ticket on area routing describes the problem](https://github.com/Project-OSRM/osrm-backend/issues/64).  Ferry routes work OK for this because they're mapped separately across water bodies.
  - Connectivity.  In order to find a route between two points, there must be a continuous connected path.  I don't know if anyone has reviewed OSM data to see if waterways are connected properly everywhere - I suspect not.  If you need to do something complex like move between water and land, then you're in for a lot of difficulty.

**Comment by F3L1X79** [comment]
I'm facing the same problem. Just out of curiosity @benjaboater , how did you manage this - in the end?

**Comment by benjaboater** [comment]
There is one product that can auto-route on waterways. Navionics. This is
what I use.

**Comment by bencevans** [comment]
osmAnd have a routing profile available at https://github.com/osmandapp/OsmAnd-resources/blob/863d8ea7f095aba443fab4bf47cdb694aa2d93a1/routing/routing.xml#L1718-L1769

I'm struggling to port it over though as don't find the lua profiles ever so clear. An example of **very** basic conditions on how to accept a way or disregard it and create a "weighting" would be appreciated.

**Comment by benjaboater** [comment]
I’m not a developer, so I just bought Navionics app and it just works. Best
$5 ever.

**Comment by bencevans** [comment]
Had another crack at this yesterday and managed to get a very basic boat profile together!

* https://github.com/onthecut/osrm-canal (Code)
* https://map.onthecut.net (OSRM Frontend)
* https://api.map.onthecut.net (OSRM Backend)

It's currently very primative and the time is completely out so shall endeavour to update the profile in line with the [OsmAnd profile](https://github.com/osmandapp/OsmAnd-resources/blob/863d8ea7f095aba443fab4bf47cdb694aa2d93a1/routing/routing.xml#L1718-L1736).

**Comment by yohanboniface** [comment]
Hi @bencevans is your osrm-canal profile available somewhere ? The link above is 404. Thanks :)
