### ISSUE TITLE
Could NOT find Lua: Found unsuitable version "5.2.3". Using Lua 5.2.3

### ISSUE THREAD

**Issue by mloskot** [Project-OSRM/osrm-backend#4227]
I'm building the current master branch on [Bash on Ubuntu on Windows](https://msdn.microsoft.com/en-us/commandline/wsl/about):

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 14.04.5 LTS
Release:        14.04
Codename:       trusty
```

The Lua look-up and results seem quite confusing, perhaps due to _too strict_ (?) version matching:
```
$ mkdir build
$ cd  build
$ cmake ..
-- Could NOT find Lua: Found unsuitable version "5.2.3", but required is exact version "5.2" (found /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so)
-- Could NOT find Lua: Found unsuitable version "5.2.3", but required is exact version "5.1" (found /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so)
-- Found Lua: /usr/lib/x86_64-linux-gnu/liblua5.2.so;/usr/lib/x86_64-linux-gnu/libm.so (found suitable version "5.2.3", minimum required is "5.2")
-- Using Lua 5.2.3
```

Is this log expected?

------

There is similar issue report in #3018 but with differences:
* builds plain Ubuntu Linux 14.04, not WSL
* cmake log says _"Lua 5.1 or 5.2 was not found."_

**Comment by daniel-j-h** [comment]
Finding the correct Lua version with CMake is a bit ugly,

https://github.com/Project-OSRM/osrm-backend/blob/359ab2b56e9af367ff993b46b94c41ae6584d5b3/CMakeLists.txt#L502-L524

the idea should be to prefer Lua 5.2 and if not found try out Lua 5.1 - but never use Lua 5.3 (their garbage collector has changed in a way so that on larger datasets you will see way higher memory consumption).

Backstory is here: https://github.com/Project-OSRM/osrm-backend/issues/2926

**Comment by mloskot** [comment]
@daniel-j-h Right, the version matching is tricky (CMake `find_package` could accept a version range or pattern). 

The CMake output is just confusing, eventually the build is "Using Lua 5.2.3". Since it is not a compilation breaker, I'm closing the issue.
