### ISSUE TITLE
Extract step for planet file running for over 10 days!

### ISSUE THREAD

**Issue by amit1rrr** [Project-OSRM/osrm-backend#4247]
Hey guys, I am setting OSRM for planet file on an ec2 r4.large instance (memory optimized). I have attached the screenshot of my extract progress so far which is running for over 10 days now. I have 150gb of swap space and 16gb of ram on the machine. Currently both are over 90% utilized. Running top always shows minimal CPU utilization. I have a few questions:

1. Is this much time normal for planet extracts? Is there a way to run things in parallel?
2. Should I have given more swap space? Can I increase it now? Will it speed up things? FYI - for most time swap utlization was fluctuating between 40% to 70% and it's over 90% for last 2 days.
3. Any ideas on how many more steps are left? approx eta? Please refer to screenshot.
4. Once the OSRM is running would the APIs be too slow? Is API latency proportional to size of extract? I am interested in match and route APIs.

Any guidance would help. Thanks.

<img width="1174" alt="screen shot 2017-07-07 at 12 44 29 am" src="https://user-images.githubusercontent.com/1350490/27928661-b95deadc-62ad-11e7-826b-bed8f8ef4125.png">

**Comment by amit1rrr** [comment]
Attached output `top` and `free -m` commands. Interestingly they show different swap utilization.

<img width="1174" alt="screen shot 2017-07-07 at 12 44 29 am" src="https://user-images.githubusercontent.com/1350490/27929176-77c3ccde-62af-11e7-8e2c-7d4f82408ba7.png">



<img width="610" alt="screen shot 2017-07-07 at 12 59 19 am" src="https://user-images.githubusercontent.com/1350490/27929212-9b88f324-62af-11e7-8db9-063941f97e83.png">

**Comment by danpat** [comment]
@amit1rrr In order to process `planet.osm.pbf` without swapping out, with the `car.lua` profile, you'll need about 180GB of RAM and 350GB of disk space.

With 16GB of RAM, the processing tools are going to be swapping heavily, and it's going to take an extremely long time for the job to complete.  It's known to be so much slower that I don't know of anyone that's ever bothered to wait.

Your best bet is to rent some time on a very large AWS instance for pre-processing - an r3.8xlarge should be able to process the planet file fully in <24 hours (this is what the OSRM demo server runs on).

As long as you stick to a similar OS/CPU, you can move the datafiles to a smaller machine for running `osrm-routed` later on.  Moving data between Linux/Windows is not really tested, so YMMV.

If you don't need to actually do routing/matching on the whole planet, I would suggest grabbing a smaller regional extract from http://download.geofabrik.de/

As long as all your data fits in RAM, there's not a huge effect on routing performance for large datasets - it's more related to the length of the route you request.

**Comment by amit1rrr** [comment]
Thanks for quick response. Yeah, I should get much higher RAM, run extract and make AWS AMI out of it. Then spin up smaller instance to run it. I can probably make that AMI public as well (of course it won't have most up to date data in future but should be good for few months). 

"As long as all your data fits in RAM, there's not a huge effect on routing performance ... "

All data means 350 GB of data in RAM in case of planet file, even after extraction step? How is the internal architecture - 

I probably need 30 countries at the moment. But my list keeps increasing every week and there is no way to append new countries in OSRM setup. So I want to setup planet and have everything done once.

**Comment by danpat** [comment]
@amit1rrr Another option you could consider is using a hosted service.  I work for Mapbox, we sponsor OSRM development, and our Directions API is powered by OSRM behind the scenes.  Maintaining an reliable, planet-scale OSRM server can be a bit of a pain.

Nothing actionable for the OSRM team on this ticket, closing.

**Comment by danpat** [comment]
Also note that `osrm-extract` is just the first of 2 required pre-processing steps.  The `osrm-contract` phase needs less memory, but is very CPU intensive.

**Comment by amit1rrr** [comment]
I want to decide which instance size to run osrm-routed once the extraction is done. Does the data need to fit entirely in RAM? I am assuming as I run queries against OSRM it will fetch from disk and keep the data in RAM. So if my major queries are only about 10% streets in OSM (major cities on the planet) then would this setup run fine on a machine with 16gb or 32gb RAM?

**Comment by amit1rrr** [comment]
@danpat Is there a hosted version of match API that MapBox offer? Is it possible to tweak the profiles (car.lua) in this hosted offering?

**Comment by daniel-j-h** [comment]
Yes there is: https://www.mapbox.com/api-documentation/#map-matching

No you can't modify the profile; it's customized and you can even use the traffic endpoint.
