### ISSUE TITLE
Make `osrm-extract` mostly in-memory

### ISSUE THREAD

**Issue by TheMarex** [Project-OSRM/osrm-backend#4248]
Currently we are storing a lot of data on disk using stxxl to curb memory consumption during `osrm-extract`. This is is very slow, uses large parts of the disk and we can't use parallelism.

The goal is to switch to in-memory algorithms for everything inside `ExtractionContainers` but don't increase **peak** memory usage. This would enable parallelization and cut down on our disk use. 

Our peak memory consumption at the moment is the infamous EBGF, as long as we stay below that we are fine.

I ran out a quick prototype to assess the feasibility:

On Bayern our peak memory usage changes from  `1706` MB to `2088` MB. The in-memory usage of `ExtractorCallbacks` is split up as follows:

```
used_node_id_list:48MB
all_nodes_list:1085MB
all_edges_list:334MB
name_char_data:1MB
name_offsets:1MB
restrictions_list:0MB
way_start_end_id_list:34MB
```

The interesting part here is the `all_nodes_list` which I think can be easily refactored to decrease by about 30%, making this peak-memory-consumption neutral.

**Comment by daniel-j-h** [comment]
The outcome of this would be ripping out stxxl as a dependency completely without the user noticing, right? Which also means processing datasets that do not fit into memory won't be possible anymore. This is fine for our use-case but I feel like this should be made explicit and deserves at least a changelog entry.

**Comment by TheMarex** [comment]
I'm not sure if we will be able to remove the dependency completely, we use it as buffer in a couple of other places as well.

**Comment by oxidase** [comment]
@daniel-j-h i have created an experimental PR to make some measurements. It is also possible to set a memory limit for a process, so if an extraction process does not fit into memory it will use system swapping.  In https://github.com/Project-OSRM/osrm-backend/pull/4252#issuecomment-313660560  extraction performance is similar to STXXL because of disk I/O. But if extraction process fits into memory it can use fast multi-core sorting.

So, on Linux the overhead  is only in using cg as
```
 cgexec -g memory:osrm ./osrm-extract ...
```
Also I have no idea about other systems.

**Comment by TheMarex** [comment]
I checked with https://github.com/Project-OSRM/osrm-backend/pull/4249 the peak memory usage of `osrm-extract` on increases to 1723MB (increased by 1%) making to absolutely feasible now.

**Comment by daniel-j-h** [comment]
STXXL is optional and off by default since 5.9 now. Sweet! ✨
