### ISSUE TITLE
Deprecate `UseLane` instruction

### ISSUE THREAD

**Issue by daniel-j-h** [Project-OSRM/osrm-backend#4260]
We're currently emitting a `UseLane` instruction when the user has to take specific lanes but otherwise keep going straight (think: lane anticipation triggers).

Now that we have the `intersections` array in the `RouteStep` we can deprecate the `UseLane` instruction and have our clients figure out lane details on their own.

Tasks:
- [ ] remove `UseLane`
- [ ] adapt `docs/http.md`
- [ ] add changelog entry
- [ ] ticket removal for v6

**Comment by daniel-j-h** [comment]
Blocked by: https://github.com/Project-OSRM/osrm-backend/issues/4261 distance and duration in the intersections array. Otherwise clients only have the `(lon, lat)` for deciding if and when to announce an intermediate intersection.

**Comment by MoKob** [comment]
@daniel-j-h can you elaborate why you consider #4261 as blocking? I would say that our current process isn't optimal. But I would say that #4268 should be mergable. Adding information to the intersections would only be a bonus to make it easier to distinguish for the client.

Actual durations will be determined on device, anyhow. For that reason, I would consider #4261 as an additional feature, but not as blocking.

Also: capturing from #4267: We should think about doing the same for new-name and put the name and its relation into the intersection. This would allow full visual representation and reduce verbosity of the engine.

**Comment by daniel-j-h** [comment]
How can clients determine the distance and duration between intersections along the route if we remove `UseLane`? All clients have is the coordinate for the intermediate intersection - but no way of knowing when to announce it ahead of time, no? cc @1ec5 for context.

**Comment by MoKob** [comment]
Well. Let me turn that question around. Without constant re-routing, how can we determine the duration? We can do it with distance, but distance does not necessarily describe the best way to announce a turn.
So if we agree that the main announcement should be the turn and `use lane` should only be used as a visual cue, we only need to see whether we passed a coordinate, which should be possible to deduce. The device needs to handle this anyhow, right now.

**Comment by 1ec5** [comment]
> How can clients determine the distance and duration between intersections along the route if we remove `UseLane`? All clients have is the coordinate for the intermediate intersection - but no way of knowing when to announce it ahead of time, no?

Correct, a client currently has to assume that the user will travel at the current rate (i.e., the instantaneous speed from a GPS reading) from the current location to the end of the step.

**Comment by MoKob** [comment]
@1ec5 so you need the distance, right? If the distance is part of the output, we should be fine. So we still want #4261, at least for distance. But I guess we could potentially go without the duration?

**Comment by 1ec5** [comment]
If the navigation SDKs were to implement a replacement for the existing `use lane` step, they would already be able to [calculate the distance](https://github.com/mapbox/mapbox-navigation-ios/blob/master/MapboxCoreNavigation/Geometry.swift#L206-L221) between each intersection using the intersection coordinates.

The duration between each intersection could be more interesting: as part of calculating the time left until the maneuver, we could divide those calculated distances by the durations provided by OSRM to determine whether the user will likely speed up or slow down between the current location and the maneuver point. Note that we can’t simply sum the durations to find the time left until the maneuver, because these durations will’ve been minutes or hours old by the time the user reaches the step.

I’m intrigued by how the `use lane` instruction’s location is currently determined. https://github.com/mapbox/api-directions/issues/1055#issuecomment-313954367 says it’s based on duration, but [`anticipateLaneChange()`](https://github.com/Project-OSRM/osrm-backend/blob/6e49941e3866f676a7733a536dc5805770645dda/src/engine/guidance/lane_processing.cpp#L83) appears to be much more sophisticated. How much of a difference do we expect heuristics like `lanes_fan_in` to make? Avoiding lane changes at curves sounds like a good idea, one that doesn’t seem straightforward to implement on the client side. But again I have no intuition about how much of a difference it makes compared to a simple “time to maneuver” heuristic like the ones we currently use for voice alerts in the navigation SDKs.

**Comment by MoKob** [comment]
@1ec5 the use-lane instruction itself, in the current state, can be present at any intersection that does not contain a maneuver. E.g. if you just pass by an exit on the motorway or if you cross any intersection.

Whether or not we emit it only depends on whether a subset of lanes is considered rather than the full set.
So if you go straight and see `straight | straight | right` as lanes and we consider both straight lanes valid choices, we don't say anything.
If we consider only one of these two lanes a valid choice, then `use lane` is emitted.
This was a compromise back when we looked into potentially supporting live-view like screens and didn't have the intersections array.

The heuristics you mention only determine what kind of lanes we consider valid at the point of the maneuver. The assumptions in `anticipateLaneChange()` are that we want to be in the correct lane for a turn, if we only have a short time to prepare for the maneuver.

So if you have turn right at `x` and turn left at `y` and `dt(x,y) < 10s`, then we want to ensure that turn right at `x` ends up on the correct lane for `y`, if multiple lanes are available. So its mostly time of maneuver heuristics, but restricting the lanes we offer.
