### ISSUE TITLE
Exits: Use comma instead of semicolon as separator

### ISSUE THREAD

**Issue by freenerd** [Project-OSRM/osrm-backend#4270]
(Found by @1ec5 in https://github.com/mapbox/MapboxDirections.swift/pull/149)

To stay consistent with multiple names and destinations, exits https://github.com/Project-OSRM/osrm-backend/pull/4215 should use comma `,` as separator instead of `;` semicolon.

**Comment by daniel-j-h** [comment]
We need arrays for these in a new API badly (https://github.com/Project-OSRM/osrm-backend/issues/3329). I don't think there can be multiple names - and if so we use them as is; destination is the only place where we use a comma and that's more of a bug than a feature:

https://github.com/Project-OSRM/osrm-backend/blob/5b5a907023a08a10daef649139fea08259ace610/profiles/lib/destination.lua#L11

https://github.com/Project-OSRM/osrm-backend/blob/df3c39cef51acd8d55287d51cd37bbad39b6f68c/include/extractor/extraction_helper_functions.hpp#L121-L135

https://github.com/Project-OSRM/osrm-backend/blob/5b5a907023a08a10daef649139fea08259ace610/profiles/lib/handlers.lua#L30-L53



---

What we can do now is either gsub `;` to `,` and have an inconsistency between

    destination, exits

and

    name, ref, pronunciation

or not to change it to a comma and consider the comma in `destinations` a bug that we can't fix at the moment because of API compatibility.

**Comment by freenerd** [comment]
Agreed with using arrays so much!

The inconsistency with destination vs. others slipped my mind. Let's stick with the semicolon since it's closer to OSM.

Fixed downstream https://github.com/Project-OSRM/osrm-text-instructions/pull/126
