### ISSUE TITLE
Support conditional via way turn restrictions

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#4342]
As a followup to https://github.com/Project-OSRM/osrm-backend/pull/4255, we need to add support for via way turn restrictions that are conditional based on time.

This requires adding support for via-ways to the updator ([here](https://github.com/Project-OSRM/osrm-backend/blob/0affec8f1732e9d3cb56bff4f4d08da42f250943/src/updater/updater.cpp#L482-L547)). The main here is that we have multiple turns that can be identified here.

A via way (as discussed [here](https://github.com/Project-OSRM/osrm-backend/issues/2681#issuecomment-313080353)) requires the addition of an additional node.

`a - b - c - d` creates `ab`, `bc`, bc_2`, and `cd`, if there is a restriction via `bc`. We need to ensure that our mappings for these turns is consistent with the addition of nodes.

**Comment by MoKob** [comment]
With the newly added support for via-way restrictions, we should add support for conditional via-way restrictions as well. These are necessary to support restrictions like `no u-turn during rush-hour`.

Such restrictions are currently handled by applying an ultra-high penalty for specific turns. Right now we re-construct which edges to add a penalty to by using the first node along the geometry. This does not work with via-ways introduced into the mix, since multiple OSRM nodes now can have the same geometry.

We have essentially two choices how to handle the conditional via-ways. Either, we generate a via-way restriction that allows all turns at first and penalise the outgoing edge:

![via-penalty](https://user-images.githubusercontent.com/12932279/28923866-d2a3a9e2-785f-11e7-9469-9b96dcc3d831.png)

Let's say we have a conditional u-turn restriction from `a` to `c`. Since the restriction is not always active, we need to apply a penalty when it becomes active. However, based on the in/out geometry alone we cannot distinguish between `v_b` to `c` which is allowed and `v_a` to `c` which isn't.

The same thing holds true, if we keep the restriction shapes in addition to the original turn and penalise the turn onto the non-duplicated way when the via-way restriction becomes active:

![in-mapping](https://user-images.githubusercontent.com/12932279/28924200-2dc9936c-7861-11e7-8e6e-7aff7bcfb5c5.png)
(the second example omits unrelated turns)

In this scenario we cannot determine between the turn from `a` to `v_a` or to `v_b`.

To handle via-way conditionals, we need to provide a direct access to the correct penalty to update when the condition becomes active.

**Comment by MoKob** [comment]
Handled in https://github.com/Project-OSRM/osrm-backend/pull/4384
