### ISSUE TITLE
osrm-contract using testbot.lua as profile fails/freezes

### ISSUE THREAD

**Issue by lamaux** [Project-OSRM/osrm-backend#4356]
I try to process Geofabrik's `bayern-latest.osm.pbf`, using `testbot.lua` as profile. The extract step works fine, but contract freezes at 90%. 
When I use `car.lua` instead there is no problem at all (< 10 min for extract and contract).

What makes me wondering is that the problem is not at extract where the lua-file is included but in the contract step, which does not directly depend on the lua-file.

I also tried `schleswig-holstein-latest.osm.pbf` which is 80% smaller, but the same problem comes up.
The server has 164 GB of RAM (Ubuntu 16.04).

**Comment by lamaux** [comment]
After some time playing around with the testbot.lua-profile I noticed that the contract-process does not freeze but takes much more time than when using the car.lua-profile.

It's a bit confusing, because the wiki calls the testbot-profile a "minimal profile" and recommends it as starting point when working with profiles.

**Comment by MoKob** [comment]
@lamaux the problem here is that minimalistic profile doesn't line up with contraction hierarchies.
Certain road networks can lead to an explosion in workload for the contract process. Since the testbot profile imposes much less of a hierarchy to the network than the car profile does, the contraction will take longer.
This still doesn't change the fact that the car profile lists a lot of advanced features that could be confusing when getting into writing your first profile.
If you are just starting out, I could recommend you use MLD as your algorithm.

You can run `osrm-extract data/map.osm && osrm-partition data/map.osrm && osrm-customize data/map.osrm` and then `osrm-routed -a MLD data/map.osrm`.
The MLD algorithm is much less sensitive to the implicit hierarchy of the road classes.
