### ISSUE TITLE
osrm-extract resulting error "no such exec instance found in daemon" v5.7.0

### ISSUE THREAD

**Issue by sophia-xll** [Project-OSRM/osrm-backend#4371]
Hello everyone. I use v5.7.0 using  stxxl file with the following configuration:
disk=/data/a,400000,memory

My computer is Linux system,128G memory,300G swapfile and 21T free space.
Data is 31G planet.osm.pbf .Docker images is osrm/osrm-backend:v5.7.0.

When  run "osrm-extract -t 16 -p /opt/car /data/planet.osm.pbf " for more than 18 hours. It represent as follow:

![a](https://user-images.githubusercontent.com/25217255/28956750-22bbe55e-7921-11e7-99d7-7d82c7e715ff.png)

What can I do? Thanks for any answer.

**Comment by oxidase** [comment]
Hi @sophia-xll, 
`osrm-extract` was killed by kernel OOM because 128GB is not enough to process planet.osm.pbf with `car.lua` profile and at least 160GB required.

In 5.9 release we optimized memory consumption and disabled STXXL usage by default. Here i showed
RSS memory usage for 5.9 release and places where memory  hits 128GB limit for 5.7 and 5.9 releases
![process local csv file](https://user-images.githubusercontent.com/4421046/28958534-fbdb24ba-78f6-11e7-901f-912785c0dbc4.jpg)

We plan to reduce memory usage below 128GB for car profile in  #4288 but it is not a goal for 5.10 and 5.11 releases.

**Comment by sophia-xll** [comment]
Although memory is 128G ,I append 300G swapfile Virtual Memory ,and it works looks well before,like:
[STXXL-ERRMSG] External memory block allocation error:392167424 bytes requested,132120576 bytes free.Trying to extend the external memory space... ok,after9398.59s.

Why Sorting edges by renumbered killed?

**Comment by oxidase** [comment]
@sophia-xll  it is really hard to say without stack traces as problem occurs in [`stxxl::sort`](https://github.com/Project-OSRM/osrm-backend/blob/5.7/src/extractor/extraction_containers.cpp#L445-L449) call.

Also STXXL will use 400GB RAM memory with the stxxl file
```
disk=/data/a,400000,memory
```
so probably it fails to allocate some internal buffers.

You can try to use `syscall` parameter instead of `memory` https://stxxl.org/tags/1.4.1/install_config.html

**Comment by sophia-xll** [comment]
@oxidase Thanks for your quick reply.
