### ISSUE TITLE
Do not emit merge on ramps with same reference

### ISSUE THREAD

**Issue by MoKob** [Project-OSRM/osrm-backend#4410]
<img width="364" alt="screen shot 2017-08-15 at 10 05 22" src="https://user-images.githubusercontent.com/12932279/29307246-5b408c26-81a1-11e7-9806-8e232107dd15.png">

https://www.openstreetmap.org/#map=19/36.99010/-122.02132

<img width="744" alt="screen shot 2017-08-15 at 10 06 21" src="https://user-images.githubusercontent.com/12932279/29307292-942b09da-81a1-11e7-987c-93a73e947d55.png">

Currently we announce a merge instruction here, which just shouldn't be there. Both highways use `CA 17` at this location, which should just be a suppressed instruction.

**Comment by miccolis** [comment]
@MoKob is this something that could be addressed in a downstream consumer?

**Comment by oxidase** [comment]
Fixed in 5.17.0. The new instruction in OSRM is `Continue straight onto Cabrillo Highway (CA 1)` instead of `Merge right onto CA 1` 
![screenshot from 2018-04-25 16-10-05](https://user-images.githubusercontent.com/4421046/39251286-332671be-48a3-11e8-82ff-142a2d50855e.png)

The instructions are suppressed at https://hey.mapbox.com/directions/#14.97/36.9892/-122.0179?coordinates=-122.019139,36.993785;-122.022584,36.989118

![screenshot from 2018-04-25 16-05-20](https://user-images.githubusercontent.com/4421046/39251102-c3ecd658-48a2-11e8-850d-d849ab8f8922.png)
