### ISSUE TITLE
Does not calculate route (debug case)

### ISSUE THREAD

**Issue by yusufumac** [Project-OSRM/osrm-backend#4461]
Following query does not work although i double checked underlying data is correct. Also, i checked Mapzen and Graphhopper car profiles can be able to calculate the road correctly. Any help would be appreciated.

https://router.project-osrm.org/route/v1/driving/29.140854477882385,41.19784179879946;29.139052033424377,41.197668233317806?overview=false&alternatives=true&steps=true&hints=;

http://map.project-osrm.org/?z=18&center=41.197785%2C29.142185&loc=41.197842%2C29.140854&loc=41.197668%2C29.139052&hl=en&alt=0

![image](https://user-images.githubusercontent.com/12373614/29915032-32babcfa-8e43-11e7-95d1-df65f2b52480.png)

![image](https://user-images.githubusercontent.com/12373614/29915066-4e381874-8e43-11e7-9c95-0d5e3ee552f0.png)

**Comment by daniel-j-h** [comment]
Check the debug map pink is disconnected components:

http://map.project-osrm.org/debug/#12.75/41.2184/29.0704

You need to figure out what disconnects the road network here.

**Comment by yusufumac** [comment]
Hi Daniel, thanks for answering. Looking at the map you provided , i couldn't see pink showing disconnected components, only red grids assumably showing tiles. Is there any resource/tool that i look for identifying/solving connectivity problems other than debugging page in wiki?

p.s As an outsider view, i found it quite challenging to debug cases like these. I tried to export data to pgsql, try modifying some data and building the binaries in my server, but couldn't be able to work it out. I think, we need some tools/clear directives on this. Best.

**Comment by daniel-j-h** [comment]
You need to check where the component is disconnected from the road network. Then take a look at the OpenStreetMap tagging and figure out why it disconnects the route. Or maybe the ways are just not connected at all.

In your example have a look here:
- http://map.project-osrm.org/debug/#14.1/41.2260/28.8568
- https://www.openstreetmap.org/edit#map=15/41.2275/28.8513

There are ways missing from the routable street network. It's because some ways there are tagged with `construction=` and we don't route over ways under construction. [This](https://www.openstreetmap.org/way/397767209#map=15/41.2269/28.8454) is one example.

Here is an Overpass Turbo query for all construction and proposed ways in that area:

http://overpass-turbo.eu/s/roq

**Comment by daniel-j-h** [comment]
Closing as data problem; hope you could figure out what needs to change upstream in OpenStreetMap.
