### ISSUE TITLE
OSRM Accuracy

### ISSUE THREAD

**Issue by hellracer** [Project-OSRM/osrm-backend#4503]
Hi All,

If really sorry if this has been asked before but I would like to ask how can I improved the accuracy of the OSRM, i'm using leaflet-routing-machine library to produce the attached image below, 

It was clear that whenever the vehicle passing through flyover the algorithm is not working as expected. I already try a couple of things the might improved the situation as follows

a. I store the pair of coordinates in the database using decimal(10,6) precision.
b. Increase the frequency of the GPS to send its data.

After the said changes the result still not satisfying, your input is highly appreciated and please see attached image below.

![untitled](https://user-images.githubusercontent.com/3840828/30425769-c00e332c-997c-11e7-934b-5277a1e2de27.png)

**Comment by danpat** [comment]
The problem here is snapping of input coordinates - when there are two roads that are parallel, and only differ in height, like this:

<img src="https://en.wikipedia.org/wiki/Overpass#/media/File:Mohakhali_flyover_003.JPG"/>

then OSRM doesn't always snap to the actual road you want - it'll depend on the coordinate you supply, and how the geometry has been drawn in OSM (exact positioning of the roads), and if the roads are identically placed, the snapping could be random based on the order the RTree was constructed during data processing.

To fix this, we'd need to:

  - store the height/level of each road in this scenario
  - require the user to supply the desired altitude
  - preferably snap to edges that are closer in altitude

It might be possible to have a heuristic that does preferable snapping using speed, based on the assumption that overpass/flyovers like this have only 2 levels, and one goes fast and one goes slow.  If the requester has some idea of which road they should be on, then supplying a name hint (like the experimental https://github.com/Project-OSRM/osrm-backend/pull/4441) could work, but it requires the client to somehow know the road name, which could be very difficult.

@hellracer there's currently no way to fix this problem, we would need to add altitude support to OSRM.

**Comment by hellracer** [comment]
@danpat can we expect #4441 to be merge soon?

**Comment by danpat** [comment]
@hellracer No, not without a more compelling argument for it.  It was written as an experiment after a brainstorming session, I didn't intend on merging it without a much more thorough investigation of the performance/logic impact.

**Comment by daniel-j-h** [comment]
Closing as not actionable.
