### ISSUE TITLE
routing in part of freeway moves to a different road

### ISSUE THREAD

**Issue by d8ehera** [Project-OSRM/osrm-backend#4511]
I have a custom osm file that routes well between points except a part of a highway in I5 in oregon.  
It routes to a different highway.  

I am not sure how to debug this osm file and see what is wrong. 

![image](https://user-images.githubusercontent.com/6908437/30517418-6339a332-9b2c-11e7-9fdb-0b3804e4afa4.png)

re-drawn to 
![image](https://user-images.githubusercontent.com/6908437/30517419-850000c4-9b2c-11e7-8270-4c1503a100a6.png)

This happens only at the boundary conditions on the state.

 Is there a way to  debug this at https://github.com/Project-OSRM/osrm-frontend  and see why that part of I-5 is not routable?

**Comment by danpat** [comment]
@hapi100 yes, you can use the `/debug/` folder on `osrm-frontend` to see the routing data - edges with speeds assigned will be coloured.  Isolated regions of the network will be outlined in pink.  If a road is only visible in the background layer (not as a coloured line), it means that the Lua script has filtered it out and it's not routable/snappable.

**Comment by hapi100** [comment]
@danpat , I am doing this on my custom osrm file... that has additional links information...

Backend:
sudo docker run -t -p 5000:5000 -v /root:/data my_osrm:latest osrm-routed /data/gn_osrm_network_201601_Oregon.osrm &


Frontend:
docker run -p 9966:9966 osrm-frontend &

that gives me 
...
[0000] info  Server running at http://172.17.0.2:9966/ (connect)
[0000] info  LiveReload running on 35729
[0002] 1340ms     1.7MB (browserify)

So I can go to http://172.17.0.2:9966/debug to see my osm file routing/speeds on default map? 

How do I change the default IP 172.17.0.2 to some other ip that the server is on?

**Comment by danpat** [comment]
@hapi100 Because the `osrm-frontend` webserver is running inside a docker container, you'll probably want to point your browser at:

http://127.0.0.1:9966/debug/

The 172.17.0.2 is the internal network address inside the docker container, so it won't be accessible from your browser.

Before you start up the frontend, edit the file `osrm-frontend/debug/index.html`, and edit the line that reads

```
            "tiles" : ["http://router.project-osrm.org/tile/v1/car/tile({x},{y},{z}).mvt"]
```

and replace it with:

```
            "tiles" : ["http://localhost:5000/tile/v1/car/tile({x},{y},{z}).mvt"]
```

Now launch the osrm-frontend container, and point your browser at:

http://127.0.0.1:9966/debug/

and you should be looking at a map of the internal data model that your OSRM instance has.  Note that roads are only visible from zoom-level 12 and higher (look in the address bar, you'll see a number from 0-22 that changes as you zoom in/out), so make sure you're zoomed in sufficiently for the area you want to examine.

**Comment by hapi100** [comment]
Thanks @danpat I was able to setup the debug mode.  Doing the same scenario, it does show me the same error condition. I can see maxspeeds of 90km/hr, and the pink lines,
![image](https://user-images.githubusercontent.com/6908437/30543050-a3b49808-9c4f-11e7-8af3-a72b1878f70a.png)

But when i route it on that I-5 freeway, I get the route on another freeway. Is there a way to see on backend the routing that happens? I have noticed this routing error only on the state border. 
 
![image](https://user-images.githubusercontent.com/6908437/30543119-df214698-9c4f-11e7-9d41-46ac28a4ba75.png)

Maybe I am missing something...Is it possible that I can send the osm file and you can check?

**Comment by MoKob** [comment]
@hapi100 you are seeing behaviour linked to small components, which behave especially worse in case of oneways (see https://github.com/Project-OSRM/osrm-backend/issues/4236 for an explanation).

In your case, you should be able to do short segments between on the highway (as long as there is no bridge or or other change in the way). You will not be able to see a route as long as start/end are not connected in both directions.

To avoid such a behaviour at borders, you can consider increasing the cut-out you use for navigation, ensuring that highways do not end suddenly at the border.

**Comment by hapi100** [comment]
@MoKob , I still cannot do a short segment on I-5 for all the way till 

![image](https://user-images.githubusercontent.com/6908437/30544569-e7d8317a-9c54-11e7-8f8b-99fa196d5753.png)

But I can route on the other freeways that start on the border ....

![image](https://user-images.githubusercontent.com/6908437/30544624-1e74e96c-9c55-11e7-9444-20cd6d4693fb.png)

**Comment by hapi100** [comment]
Is there a way to trace the route in the backend  and see why it is not routable on that part of the freeways?

Or any other options to make it routable @danpat  or @MoKob ?

**Comment by MoKob** [comment]
You can look at the debug map. You will see a pink line around the road, just as in https://github.com/Project-OSRM/osrm-backend/issues/4511#issuecomment-330212553. If end-points are in different small components, you will not be able to route on it.

It is not possible without modifcations to the code to route onto a small component from a different small component or a large component. Snapping will not return a location within the component.

**Comment by danpat** [comment]
One possible workaround is to do:

`osrm-extract --small-component-size 2147483646 -p profiles/car.lua yourmap.osm.pbf`

This causes isolated network components to need to be much larger before they're classed as small components.  The default size is 1000 nodes.

This would probably fix the snapping behaviour for this case, but it would make other locations behave strangely where the current snapping behaviour is the right thing to do.  Give it a go and see :-)

**Comment by MoKob** [comment]
@danpat at highways at the end of the map this will not work, since oneways break into own components, no matter how big the size is.

**Comment by danpat** [comment]
Correction:

`osrm-extract --small-component-size 0 -p profiles/car.lua yourmap.osm.pbf`

This would remove all small components and do what I intended, I had my logic backwards.

**Comment by hapi100** [comment]
Thanks @danpat and @MoKob , let me try that will let you know.

**Comment by hapi100** [comment]
This works ... i need to test a bit more on other segments.

![image](https://user-images.githubusercontent.com/6908437/30611831-9428b5de-9d50-11e7-8c54-7f3c48b493ab.png)


Thanks again and appreciate your time.

**Comment by danpat** [comment]
@hapi100 For an explanation of the "small component" snapping behaviour, take a look at this blog post:

https://blog.mapbox.com/robust-navigation-with-smart-nearest-neighbor-search-dbc1f6218be8

by setting the component size to 0, you effectively disable this logic.  We implemented this as a way to try to better interpret the users intent - if you drop a marker on a park that's mostly disconnected from the road network, and the other end of your route is across the city, you *probably* want to start the route on the road where there is actually more likely to be a connected path to the destination.

Setting the component size to 0 means we will snap to the closest edge in all cases, which might lead to more "No route founds" if your coordinates are near disconnected sub-graphs.

Your case is a bit special because you've snipped the road graph at the border - normally, one-way-roads-to-nowhere and oneway-roads-from-nowhere are data errors, so they're not a scenario we're likely to add perpetual support for handling nicely.

**Comment by hapi100** [comment]
@danpat that makes sense. for us, I am actually calling the nearest api first to get the lat/long for start and end location, and then  calling the routing api to route it. 

I tested other segments and border conditions and it works.

**Comment by danpat** [comment]
@hapi100 Unless you're doing something to verify that the `nearest` coordinate is correct, you might as well just pass your original coordinates to the `route` API - it performs the same nearest check anyway.  Especially with this modification to the small component size, the `nearest` call probably doesn't add any value.
