### ISSUE TITLE
via-way no_straight_on breaks no_u_turn

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#4518]
[ron_cowan_parkway.osm.zip](https://github.com/Project-OSRM/osrm-backend/files/1312301/ron_cowan_parkway.osm.zip)

This OSRM file has a `no_straight_on` relation:

![image](https://user-images.githubusercontent.com/93564/30565817-afbe65c8-9c97-11e7-8278-1bcca34bb777.png)

This relation appears to prevent the the following `no_u_turn` relation from working:

![image](https://user-images.githubusercontent.com/93564/30565855-d3e3e5f4-9c97-11e7-8ca8-442e0392a264.png)

Testing this locally, the `no_straight_on` relation works:

![image](https://user-images.githubusercontent.com/93564/30565903-f4ba5a10-9c97-11e7-9f0b-494a9da47061.png)

But the `no_u_turn` relation does not:

![image](https://user-images.githubusercontent.com/93564/30565913-05c06b4c-9c98-11e7-8682-9d50f162b2ca.png)

**Comment by MoKob** [comment]
The problem here is that the two relations together form an implicit multi-via-way restriction.

![named](https://user-images.githubusercontent.com/12932279/30589405-86639844-9d3a-11e7-9c54-1df4c674b16c.png)

The not working restriction for `no_uturn` is conceptually the same as saying from `A` via `B` and `D` to `F`.

The `no_straight_on` is telling OSRM that coming from `A` and via `B` that `C` isn't allowed, but `D` sure is.
Due to the created path from the `no_straight_on`, we can bypass the restrictions from the `no_u_turn`.
To add the `no_uturn` restriction into the mix, we would now need to detect that `A` via `B` to `D` is allowed and disallow `B` to `D` and only allow `B` to `E`, making it implicitly to a multi via-way restriction (via `B` and `D`).

I would consider this bad modelling, though. Instead of two interacting via-way restrictions, a single via-way restriction can model the required restrictions.
The, in my view, better modelling would be a single via-way restriction of the form:

 from `B`, via `D`, to `E`: `only_left_on`.

**Comment by MoKob** [comment]
Via-way restrictions are also tracked over https://github.com/Project-OSRM/osrm-backend/issues/4439 as a feature-request for multiple via points.

**Comment by MoKob** [comment]
I have to correct myself. The proposed modelling wouldn't work and the original modelling is correct. The support is missing due to the implicit multi-way restriction needed. This requires an implementation of #4439 to be fixed.

**Comment by Andygol** [comment]
According to this recommendation https://desktop.arcgis.com/en/arcmap/latest/extensions/network-analyst/turns-in-the-network-dataset.htm#GUID-5BC5E313-1444-4471-954F-9D1068FAD01A 

>The first or last edge (any exterior edge) in the turn cannot be an interior edge of another turn.

we have incorrectly modeled no-U-turn restrictions, where the same way plays different roles for the TRs:
- `to`-way for one no-U-turn and 
- `from`-way for another no-U-turn,
- `via`-way for `no_straight_on` and `no_u_turn` TRs

All interior ways should have only role `via` but in the example we have a mix of roles for one interior edge.

![screencast 2017-11-14 13-42-07](https://user-images.githubusercontent.com/369696/32778326-26af727c-c942-11e7-95c1-30e99c889cef.gif)

for right modeling, there is required that no-U-turn TRs will have 3 `via`-members
![screencast 2017-11-14 13-42-07](https://user-images.githubusercontent.com/369696/32779077-11d20754-c945-11e7-9fdd-82aa9c5abd0a.png)
