### ISSUE TITLE
Two "straights" out of an intersection

### ISSUE THREAD

**Issue by willwhite** [Project-OSRM/osrm-backend#4559]
Both [this maneuver](https://www.mapbox.com/get-directions/#19.39/38.94594/-77.00854?coordinates=-77.00787211076515,38.94619960086291;-77.00853782347191,38.9459351500378) and [this maneuver](https://www.mapbox.com/get-directions/#19.39/38.94602/-77.00856?coordinates=-77.00787211076515,38.94619960086291;-77.00855933111943,38.94601599881415) are `straight`. The second one is a turn. Do we do any disambiguation?

It is difficult to see the labels for the debug tiles:

![image](https://user-images.githubusercontent.com/93564/31019184-e1aa4b02-a4fc-11e7-95c4-5887b00e2d24.png)

/cc @danpat @miccolis @oxidase @MoKob

**Comment by oxidase** [comment]
Fixed in #4426 should be fixed in 5.13 release
![screenshot from 2017-09-29 16-27-16](https://user-images.githubusercontent.com/4421046/31020425-42fe26e0-a533-11e7-97bf-f87aaa33e2c2.png)
and
![screenshot from 2017-09-29 16-27-44](https://user-images.githubusercontent.com/4421046/31020432-48dcaa78-a533-11e7-872d-dce0381220ff.png)

**Comment by willwhite** [comment]
@oxidase that's good news. Shouldn't this instruction be "Turn right onto Rock Creek Church Rd Northwest", however, since it's a slip road?

**Comment by oxidase** [comment]
@willwhite i don't know exactly if it is unimplemented collapsing in post-processing or incorrect instruction type in pre-processing.

@MoKob Please could you point where can be the issue. Here is the annotated path https://gist.github.com/oxidase/3e8b8dc6ca38a7cf39984b98288ccc06 with two instruction `{type = Turn (3), direction_modifier = SlightRight (3)}` at https://www.openstreetmap.org/node/647087545 and `{type = EndOfRoad (8), direction_modifier = Right (2)}` at https://www.openstreetmap.org/node/49731194

**Comment by MoKob** [comment]
Based on the modelling (short road, only turn, shortening a different turn), I would say that this should be a sliproad, which would make this the responsibility of the sliproad handler in pre-processing.

**Comment by oxidase** [comment]
@MoKob the sliproad handler fails at [`findObviousTurn`](https://github.com/Project-OSRM/osrm-backend/blob/088d4edc6b761d2642a9b1ab7d85b701d3165fb2/src/extractor/guidance/sliproad_handler.cpp#L340)  because for [the target intersection](https://www.openstreetmap.org/node/49731194) no ovbious turn is detected. I would postpone fixing the issue till #4426 will be merged.

**Comment by MoKob** [comment]
@oxidase even with #4426, going to a near 90 degree turn for both left and right is a tricky choice to classify as obvious, even though it is the only possible turn. I can add this to my cases to look at, I don't find it clear that the turn to the right should be considered `obvious` from the view of the handler.

As long as we do not extend the handlers reach to look farther back/forth and to realise that this could be a sliproad, the turn itself would usually require an announcement. Compare https://github.com/mapbox/directions-feedback/issues/586 for a similar local view that requires announcement.

This kind of results in a chicken/egg problem. Requiring findObvious in sliproad while findObvious would need to know that the road itself is most likely a sliproad. As a result, I would like to see if we can find a way to detect a sliproad while not making this a task for findObvious.

**Comment by oxidase** [comment]
Fixed in 5.17.0 
![screenshot from 2018-04-25 15-32-45](https://user-images.githubusercontent.com/4421046/39249028-f5a16a1a-489d-11e8-89b1-b0c653558d3a.png)
and
![screenshot from 2018-04-25 15-32-36](https://user-images.githubusercontent.com/4421046/39249039-fba206ea-489d-11e8-8428-22bcb74a32f2.png)
