### ISSUE TITLE
osrm-extract --parse-conditional-restrictions=0 flag still generates restrictions

### ISSUE THREAD

**Issue by mloskot** [Project-OSRM/osrm-backend#4620]
I'm using OSRM 5.12.0

In https://github.com/Project-OSRM/osrm-backend/pull/3841#issuecomment-337261750 I asked for clarification about relation between extract and contract steps, and requirement of GeoJSON file with timezones.

@karenzshea explained in https://github.com/Project-OSRM/osrm-backend/pull/3841#issuecomment-337268288 the GeoJSON file is optional and it is required only if `.osrm.restrictions` file is present.
Then, to disable the conditional turn restriction application by running `osrm-extract` with `--parse-conditional-restrictions`  option.

There are a few issues:

1. GeoJSON file is *not* really optional. It is required indirectly though, by presence of some intermediate file, which is required by default now.

2. AFAICT, use of the suggested option has no effect and `.osrm.restrictions` file is still generated that makes the contraction step require GeoJSON file with timezones.

3. The suggested alternative solution by removing the `.osrm.restrictions` file is not a solution, but a hack, especially from OSRM API usage point, not really helpful..

4. Apparently, `--parse-conditional-restrictions` controls corresponding flag in `ExtractorConfig`:

```
osrm::ExtractorConfig config;
config.parse_conditionals = false;
...
osrm::extract(config);
```

and, obviously, that does not have any effect either, as in 2.

Any chance to get that situation clarified?

**Comment by karenzshea** [comment]
I revisited the code handling conditional restrictions and sorry for being misleading in my hasty previous answer.

Thanks for catching that conditional restriction handling is not disabled by default in the extract and contract configurations.

Can you try using the changes in this branch https://github.com/Project-OSRM/osrm-backend/tree/conditionals/disable and let me know if it yields expected behaviour? I've disabled the relevant options by default, and also (bonus) made the `.osrm.restrictions` file optional as I'd previously thought.
