### ISSUE TITLE
Inconsistent address detection

### ISSUE THREAD

**Issue by dhnguyen92** [Project-OSRM/osrm-backend#4660]
Hi,

I have some problem with address detection/completion of OSRM. 

My input address is "langemarckstraße 272, essen, 45309, Germany", and the output is None. 

If I remove the zip code and country: "langemarckstraße 272, essen", we get the correct output address which is "272, Langemarckstraße, Schonnebeck, Stadtbezirk VI, Essen, Regierungsbezirk Düsseldorf, North Rhine-Westphalia, 45309, Germany". 

And if I set the input address to "272, Langemarckstraße, Schonnebeck, Stadtbezirk VI, Essen, Regierungsbezirk Düsseldorf, North Rhine-Westphalia, 45309, Germany" again, the output is None.

You can check this on http://map.project-osrm.org

Can you fix it?

**Comment by danpat** [comment]
@dhnguyen92 OSRM itself doesn't understand addresses - on the `map.project-osrm.org` interface, we send the address to https://nominatim.openstreetmap.org/, and it converts the address to a latitude/longitude that we then use to find a route.

It sounds like the problem here is with Nominatim, you might want to open a ticket there.
