### ISSUE TITLE
Cannot find route between Britain and Isle of Man

### ISSUE THREAD

**Issue by Mekapaedia** [Project-OSRM/osrm-backend#4667]
I've been playing around with OSRM to make large trips and routes and it has been working excellently - I can build long multistage routes of 120+ waypoints throughout Eurasia without issue.

However, I have an oddly specific issue that goes beyond my code ([I've checked with the OSRM demo map as well](http://map.project-osrm.org/?z=9&center=53.799029%2C-3.249207&loc=53.405472%2C-2.980539&loc=54.149774%2C-4.477902&hl=en&alt=0)) - OSRM cannot find a route between Britain and the Isle of Man. I thought it might be an issue with the underlying OSM data (no connection) but [Graphhopper-based](https://www.mapquest.com/directions/from/great-britain/liverpool-282414276/to/isle-of-man/douglas-282411021) [services](https://graphhopper.com/maps/?point=Liverpool%2C%20United%20Kingdom&point=Douglas%2C%20Isle%20of%20Man&locale=en-GB&vehicle=car&weighting=fastest&elevation=true&use_miles=false&layer=Omniscale) can find a route and correctly return the transit time. I've also used [the OSM inspector and it does have motorcar=yes](https://www.openstreetmap.org/way/22772385#map=9/53.7966/-3.3646) in all the ferry routes (4 or so) from Britain to the Isle of Man.

I thought since Graphhopper doesn't process turn restrictions it might be this so I turned it off in the profile (I'm using the standard car.lua with slightly higher U-turn cost) but it still doesn't find a path.

I'm also having an issue where there is a bridge on the A591 that OSRM deems impassable, but I think that's something to do with my profile as the demo server doesn't have this issue (not related but not a issue I think).

**Comment by danpat** [comment]
The problem here is that the road the ferry connects to in Douglas is marked as `highway=service` and `access=destination`.

The `car.lua` profile generally eliminates roads with `access=` tags, *unless* they're on the `profile.restricted_highway_whitelist` - and `highway=service` is not.

The reason for this is ... unclear to me.  Anyone happen to remember why we don't have service roads on the `restricted_highway_whitelist` ?

**Comment by oxidase** [comment]
@danpat it is similar to #4632, so  `service` tag was not included in the first commit cc3a4899a2ee3837a80f171ef482568118ce18c4

**Comment by Mekapaedia** [comment]
I can confirm that adding services roads to the profile has fixed this, thanks! Extraction and contraction took about 2 days, and there is a slight slowdown, but overall is still serviceable with ~120 points on 64GB of ram.

**Comment by danpat** [comment]
@oxidase @TheMarex do you think we should consider including service roads in the `restricted_highway_whitelist` ?

**Comment by oxidase** [comment]
@danpat yes, i will open a PR

**Comment by oxidase** [comment]
@danpat looking at  [SF](https://overpass-turbo.eu/s/sSw) and [Berlin](https://overpass-turbo.eu/s/sSx) tags, more opinions are needed, because of high density of  `["access"="destination"]["highway"="service"]` ways in Germany. 

Adding these ways to routing graph reconnects islands and  allows to route to many parking  places and fix many [parking places detours](http://map.project-osrm.org/?z=17&center=48.081190%2C11.615531&loc=48.080702%2C11.614523&loc=48.080702%2C11.611390&hl=en&alt=0)

**Comment by 1ec5** [comment]
FYI, there’s also a [`service`](https://wiki.openstreetmap.org/wiki/Key:service#Highways) tag that allows us to differentiate between types of service roads. [`service=emergency_access`](https://wiki.openstreetmap.org/wiki/Tag:service%3Demergency_access) is probably still worth disallowing, while [`driveway`](https://wiki.openstreetmap.org/wiki/Tag:service%3Ddriveway) and [`parking_aisle`](https://wiki.openstreetmap.org/wiki/Tag:service%3Dparking_aisle) may well be desirable at the beginning or end of a route. To give a sense of scale, 3&nbsp;762&nbsp;km of driveways and 2&nbsp;401&nbsp;km of parking alleys have been explicitly tagged as such [in Ohio](https://wiki.openstreetmap.org/wiki/Ohio/Statistics#Pathway_statistics) as of the beginning of this month.

/cc @karenzshea
