### ISSUE TITLE
can't match gps coordinates

### ISSUE THREAD

**Issue by wangzi6578** [Project-OSRM/osrm-backend#4733]
hello,
i use 4700 gps coordinates to match service but there are 1100 pairs points return null,i thoght some methods to fix this and it failed. so i wonder how could i fix it and is there some wrong to lead this

**Comment by TheMarex** [comment]
Some of your trace points might get removed because they are outliers or blobs. Try [`tidy=true`](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#match-service), this should clear up your trace a little.
You might want to be closer to at most 0.2 samples / sec for good results, any higher sample rate will rather hurt then help.

Otherwise emitting `null` is expected behavior for unmatched points.
