### ISSUE TITLE
highway=pedestrian multipolygon breaks car routing

### ISSUE THREAD

**Issue by systemed** [Project-OSRM/osrm-backend#4735]
...at least, that's my guess for what's going on here:

http://www.openstreetmap.org/directions?engine=osrm_car&route=51.50218%2C-0.07270%3B51.49279%2C-0.08015#map=16/51.4974/-0.0804

This should really go down Tower Bridge Road (highway=trunk) rather than around the back streets.

A segment of Tower Bridge Road (http://www.openstreetmap.org/way/380116500) is also a part of a multipolygon relation (http://www.openstreetmap.org/relation/5660722) tagged as highway=pedestrian, area=yes. OSRM appears unwilling to route over any edge of this multipolygon.

The debug tiles are currently down but the link would be http://map.project-osrm.org/debug/#16/51.4965/-0.0823 .

**Comment by TheMarex** [comment]
I think this is actually caused by a `vehicle=delivery` tag on that segment. This would cause OSRM to make this edge as invalid for traffic that just passes through. Do you think that tag is outdated?

You can see that we [route over the segment](http://www.openstreetmap.org/directions?engine=osrm_car&route=51.49653%2C-0.08212%3B51.49611%2C-0.08276#map=19/51.49633/-0.08246) if you start on it, which is the behavior we use for streets with restricted access (`private`, `designated`, `delivery` etc)

**Comment by systemed** [comment]
Oh, that's interesting. What a weird tag. I'll remove the tag and see if that fixes it - thanks for spotting.
