### ISSUE TITLE
API returns incorrect distance when calculating route between large number of waypoints

### ISSUE THREAD

**Issue by a6datta** [Project-OSRM/osrm-backend#4778]
Google returns around 60 miles for the same route whereas OSRM returns almost double. 
This is my request string.is there anything I am doing wrong?

http://localhost:5000/route/v1/driving/51.472444,-0.490567&loc=51.472067,-0.490116&loc=51.471955,-0.490305&loc=51.472425,-0.491831&loc=51.47459,-0.492684&loc=51.474373,-0.495774&loc=51.473814,-0.5017&loc=51.473238,-0.507633&loc=51.475251,-0.504842&loc=51.480924,-0.502883&loc=51.486303,-0.498194&loc=51.492441,-0.494697&loc=51.499008,-0.495166&loc=51.505627,-0.500102&loc=51.51182,-0.50206&loc=51.518485,-0.499209&loc=51.525337,-0.498467&loc=51.532164,-0.499368&loc=51.543461,-0.505233&loc=51.546514,-0.513212&loc=51.549645,-0.5219&loc=51.554802,-0.52774&loc=51.560041,-0.531028&loc=51.565764,-0.533665&loc=51.57187,-0.535452&loc=51.578529,-0.535805&loc=51.584674,-0.534026&loc=51.590869,-0.53326&loc=51.596922,-0.531698&loc=51.603229,-0.529649&loc=51.609132,-0.527906&loc=51.615191,-0.526434&loc=51.621384,-0.525154&loc=51.628308,-0.520769&loc=51.634627,-0.514074&loc=51.63996,-0.506127&loc=51.646306,-0.500043&loc=51.653885,-0.496263&loc=51.66157,-0.494405&loc=51.668701,-0.490726&loc=51.672125,-0.480607&loc=51.673333,-0.468005&loc=51.677948,-0.457324&loc=51.683876,-0.448596&loc=51.691965,-0.447054&loc=51.700062,-0.444038&loc=51.706061,-0.43586&loc=51.711497,-0.427348&loc=51.714096,-0.416703&loc=51.714106,-0.404107&loc=51.715474,-0.390968&loc=51.716443,-0.378555&loc=51.714009,-0.367479&loc=51.710845,-0.35669&loc=51.709396,-0.343429&loc=51.710669,-0.330209&loc=51.711948,-0.317347&loc=51.710393,-0.304821&loc=51.711002,-0.292192&loc=51.715471,-0.282476&loc=51.715118,-0.269877&loc=51.709926,-0.261105&loc=51.704968,-0.251386&loc=51.699469,-0.242393&loc=51.692408,-0.237199&loc=51.686994,-0.230104&loc=51.684309,-0.219098&loc=51.685601,-0.207715&loc=51.685881,-0.196331&loc=51.684003,-0.185145&loc=51.685512,-0.174182&loc=51.687867,-0.162709&loc=51.68533,-0.150951&loc=51.687823,-0.138553&loc=51.688483,-0.125388&loc=51.690365,-0.113468&loc=51.691103,-0.101847&loc=51.689623,-0.089316&loc=51.688049,-0.077592&loc=51.684013,-0.067611&loc=51.682909,-0.054936&loc=51.682829,-0.042288&loc=51.682387,-0.030695&loc=51.680922,-0.018876&loc=51.680625,-0.006257&loc=51.680796,0.005782&loc=51.678711,0.016866&loc=51.678171,0.028752&loc=51.68078,0.039896&loc=51.684744,0.050362&loc=51.687493,0.062499&loc=51.688688,0.074926&loc=51.689565,0.08642&loc=51.689016,0.097465&loc=51.685253,0.104867&loc=51.681701,0.112995&loc=51.680712,0.121204&loc=51.679714,0.12812&loc=51.677435,0.123027&loc=51.670927,0.118702&loc=51.664201,0.113429&loc=51.657381,0.106834&loc=51.650404,0.099499&loc=51.644443,0.091133&loc=51.638955,0.081924&loc=51.632847,0.072987&loc=51.626186,0.065403&loc=51.618304,0.062639&loc=51.613399,0.05554&loc=51.603631,0.049217&loc=51.598494,0.046397&loc=51.594416,0.040245&loc=51.589078,0.039393&loc=51.584249,0.040117&loc=51.583517,0.040092&loc=51.583173,0.040115&loc=51.582621,0.040239&loc=51.58136,0.040815&loc=51.580621,0.041285&loc=51.580258,0.041518&loc=51.57975,0.041918&loc=51.57917,0.042335&loc=51.578611,0.042752&loc=51.578332,0.04295&loc=51.577875,0.043238&loc=51.577422,0.043546&loc=51.577111,0.043742&loc=51.577021,0.043784&loc=51.57523,0.044638&loc=51.576278,0.03914&loc=51.576806,0.033668&loc=51.576,0.029187&loc=51.575406,0.027563&loc=51.574417,0.024624&loc=51.57255,0.023678&loc=51.570117,0.023539&loc=51.569631,0.023546&loc=51.558741,0.025256&loc=51.555131,0.025297&loc=51.554428,0.024495&loc=51.554323,0.022561&loc=51.55514,0.02107&loc=51.554483,0.019395&loc=51.553941,0.018194&loc=51.553938,0.018036&loc=51.553718,0.017629&loc=51.553681,0.017492&loc=51.553173,0.017017&loc=51.552157,0.017851&loc=51.55039,0.018886&loc=51.549034,0.019775&loc=51.549297,0.022;51.549826,0.024557&hl=en&alt=0

**Comment by oxidase** [comment]
@a6datta OSRM uses the nearest edge snapping to find locations of via nodes. If noisy GPS locations are used to find a route then some detours are possible because snapped nodes can be on ramps or side roads
http://map.project-osrm.org/?z=14&center=51.700811%2C-0.255518&loc=51.472444%2C-0.490567&loc=51.472067%2C-0.490116&loc=51.471955%2C-0.490305&loc=51.472425%2C-0.491831&loc=51.474590%2C-0.492684&loc=51.474373%2C-0.495774&loc=51.473814%2C-0.501700&loc=51.473238%2C-0.507633&loc=51.475251%2C-0.504842&loc=51.480924%2C-0.502883&loc=51.486303%2C-0.498194&loc=51.492441%2C-0.494697&loc=51.499008%2C-0.495166&loc=51.505627%2C-0.500102&loc=51.511820%2C-0.502060&loc=51.518485%2C-0.499209&loc=51.525337%2C-0.498467&loc=51.532164%2C-0.499368&loc=51.543461%2C-0.505233&loc=51.546514%2C-0.513212&loc=51.549645%2C-0.521900&loc=51.554802%2C-0.527740&loc=51.560041%2C-0.531028&loc=51.565764%2C-0.533665&loc=51.571870%2C-0.535452&loc=51.578529%2C-0.535805&loc=51.584674%2C-0.534026&loc=51.590869%2C-0.533260&loc=51.596922%2C-0.531698&loc=51.603229%2C-0.529649&loc=51.609132%2C-0.527906&loc=51.615191%2C-0.526434&loc=51.621384%2C-0.525154&loc=51.628308%2C-0.520769&loc=51.634627%2C-0.514074&loc=51.639960%2C-0.506127&loc=51.646306%2C-0.500043&loc=51.653885%2C-0.496263&loc=51.661570%2C-0.494405&loc=51.668701%2C-0.490726&loc=51.672125%2C-0.480607&loc=51.673333%2C-0.468005&loc=51.677948%2C-0.457324&loc=51.683876%2C-0.448596&loc=51.691965%2C-0.447054&loc=51.700062%2C-0.444038&loc=51.706061%2C-0.435860&loc=51.711497%2C-0.427348&loc=51.714096%2C-0.416703&loc=51.714106%2C-0.404107&loc=51.715474%2C-0.390968&loc=51.716443%2C-0.378555&loc=51.714009%2C-0.367479&loc=51.710845%2C-0.356690&loc=51.709396%2C-0.343429&loc=51.710669%2C-0.330209&loc=51.711948%2C-0.317347&loc=51.710393%2C-0.304821&loc=51.711002%2C-0.292192&loc=51.715471%2C-0.282476&loc=51.715118%2C-0.269877&loc=51.709926%2C-0.261105&loc=51.704968%2C-0.251386&loc=51.699469%2C-0.242393&loc=51.692408%2C-0.237199&loc=51.686994%2C-0.230104&loc=51.684309%2C-0.219098&loc=51.685601%2C-0.207715&loc=51.685881%2C-0.196331&loc=51.684003%2C-0.185145&loc=51.685512%2C-0.174182&loc=51.687867%2C-0.162709&loc=51.685330%2C-0.150951&loc=51.687823%2C-0.138553&loc=51.688483%2C-0.125388&loc=51.690365%2C-0.113468&loc=51.691103%2C-0.101847&loc=51.689623%2C-0.089316&loc=51.688049%2C-0.077592&loc=51.684013%2C-0.067611&loc=51.682909%2C-0.054936&loc=51.682829%2C-0.042288&loc=51.682387%2C-0.030695&loc=51.680922%2C-0.018876&loc=51.680625%2C-0.006257&loc=51.680796%2C0.005782&loc=51.678711%2C0.016866&loc=51.678171%2C0.028752&loc=51.680780%2C0.039896&loc=51.684744%2C0.050362&loc=51.687493%2C0.062499&loc=51.688688%2C0.074926&loc=51.689565%2C0.086420&loc=51.689016%2C0.097465&loc=51.685253%2C0.104867&loc=51.681701%2C0.112995&loc=51.680712%2C0.121204&loc=51.679714%2C0.128120&loc=51.677435%2C0.123027&loc=51.670927%2C0.118702&loc=51.664201%2C0.113429&loc=51.657381%2C0.106834&loc=51.650404%2C0.099499&loc=51.644443%2C0.091133&loc=51.638955%2C0.081924&loc=51.632847%2C0.072987&loc=51.626186%2C0.065403&loc=51.618304%2C0.062639&loc=51.613399%2C0.055540&loc=51.603631%2C0.049217&loc=51.598494%2C0.046397&loc=51.594416%2C0.040245&loc=51.589078%2C0.039393&loc=51.584249%2C0.040117&loc=51.583517%2C0.040092&loc=51.583173%2C0.040115&loc=51.582621%2C0.040239&loc=51.581360%2C0.040815&loc=51.580621%2C0.041285&loc=51.580258%2C0.041518&loc=51.579750%2C0.041918&loc=51.579170%2C0.042335&loc=51.578611%2C0.042752&loc=51.578332%2C0.042950&loc=51.577875%2C0.043238&loc=51.577422%2C0.043546&loc=51.577111%2C0.043742&loc=51.577021%2C0.043784&loc=51.575230%2C0.044638&loc=51.576278%2C0.039140&loc=51.576806%2C0.033668&loc=51.576000%2C0.029187&loc=51.575406%2C0.027563&loc=51.574417%2C0.024624&loc=51.572550%2C0.023678&loc=51.570117%2C0.023539&loc=51.569631%2C0.023546&loc=51.558741%2C0.025256&loc=51.555131%2C0.025297&loc=51.554428%2C0.024495&loc=51.554323%2C0.022561&loc=51.555140%2C0.021070&loc=51.554483%2C0.019395&loc=51.553941%2C0.018194&loc=51.553938%2C0.018036&loc=51.553718%2C0.017629&loc=51.553681%2C0.017492&loc=51.553173%2C0.017017&loc=51.552157%2C0.017851&loc=51.550390%2C0.018886&loc=51.549034%2C0.019775&loc=51.549297%2C0.022000&hl=en&alt=0

To reduce noise the map matching service can be used as
```
curl -s 'http://router.project-osrm.org/match/v1/driving/-0.490567,51.472444;-0.490116,51.472067;-0.490305,51.471955;-0.491831,51.472425;-0.492684,51.47459;-0.495774,51.474373;-0.5017,51.473814;-0.507633,51.473238;-0.504842,51.475251;-0.502883,51.480924;-0.498194,51.486303;-0.494697,51.492441;-0.495166,51.499008;-0.500102,51.505627;-0.50206,51.51182;-0.499209,51.518485;-0.498467,51.525337;-0.499368,51.532164;-0.505233,51.543461;-0.513212,51.546514;-0.5219,51.549645;-0.52774,51.554802;-0.531028,51.560041;-0.533665,51.565764;-0.535452,51.57187;-0.535805,51.578529;-0.534026,51.584674;-0.53326,51.590869;-0.531698,51.596922;-0.529649,51.603229;-0.527906,51.609132;-0.526434,51.615191;-0.525154,51.621384;-0.520769,51.628308;-0.514074,51.634627;-0.506127,51.63996;-0.500043,51.646306;-0.496263,51.653885;-0.494405,51.66157;-0.490726,51.668701;-0.480607,51.672125;-0.468005,51.673333;-0.457324,51.677948;-0.448596,51.683876;-0.447054,51.691965;-0.444038,51.700062;-0.43586,51.706061;-0.427348,51.711497;-0.416703,51.714096;-0.404107,51.714106;-0.390968,51.715474;-0.378555,51.716443;-0.367479,51.714009;-0.35669,51.710845;-0.343429,51.709396;-0.330209,51.710669;-0.317347,51.711948;-0.304821,51.710393;-0.292192,51.711002;-0.282476,51.715471;-0.269877,51.715118;-0.261105,51.709926;-0.251386,51.704968;-0.242393,51.699469;-0.237199,51.692408;-0.230104,51.686994;-0.219098,51.684309;-0.207715,51.685601;-0.196331,51.685881;-0.185145,51.684003;-0.174182,51.685512;-0.162709,51.687867;-0.150951,51.68533;-0.138553,51.687823;-0.125388,51.688483;-0.113468,51.690365;-0.101847,51.691103;-0.089316,51.689623;-0.077592,51.688049;-0.067611,51.684013;-0.054936,51.682909;-0.042288,51.682829;-0.030695,51.682387;-0.018876,51.680922;-0.006257,51.680625;0.005782,51.680796;0.016866,51.678711;0.028752,51.678171;0.039896,51.68078;0.050362,51.684744;0.062499,51.687493;0.074926,51.688688;0.08642,51.689565;0.097465,51.689016;0.104867,51.685253;0.112995,51.681701;0.121204,51.680712;0.12812,51.679714;0.123027,51.677435;0.118702,51.670927' | jq '.matchings[].distance'
78391.09999999999

curl -s 'http://router.project-osrm.org/match/v1/driving/0.118702,51.670927;0.113429,51.664201;0.106834,51.657381;0.099499,51.650404;0.091133,51.644443;0.081924,51.638955;0.072987,51.632847;0.065403,51.626186;0.062639,51.618304;0.05554,51.613399;0.049217,51.603631;0.046397,51.598494;0.040245,51.594416;0.039393,51.589078;0.040117,51.584249;0.040092,51.583517;0.040115,51.583173;0.040239,51.582621;0.040815,51.58136;0.041285,51.580621;0.041518,51.580258;0.041918,51.57975;0.042335,51.57917;0.042752,51.578611;0.04295,51.578332;0.043238,51.577875;0.043546,51.577422;0.043742,51.577111;0.043784,51.577021;0.044638,51.57523;0.03914,51.576278;0.033668,51.576806;0.029187,51.576;0.027563,51.575406;0.024624,51.574417;0.023678,51.57255;0.023539,51.570117;0.023546,51.569631;0.025256,51.558741;0.025297,51.555131;0.024495,51.554428;0.022561,51.554323;0.02107,51.55514;0.019395,51.554483;0.018194,51.553941;0.018036,51.553938;0.017629,51.553718;0.017492,51.553681;0.017017,51.553173;0.017851,51.552157;0.018886,51.55039;0.019775,51.549034;0.022,51.549826;0.024557,51.549297' | jq '.matchings[].distance'
17383.60000000001
```
(the map-matching query is split into two parts due to a 100 nodes limit at router.project-osrm.org, but the limit can changed by `--max-matching-size` parameter of a local `osrm-routed` server).

The total distance of the matched route is `(78391+17383)/1609 ~ 59.52` miles. 

More information about the match service at http://project-osrm.org/docs/v5.10.0/api/#match-service

**Comment by a6datta** [comment]
It worked. Thanks

**Comment by oxidase** [comment]
Happy routing!
