### ISSUE TITLE
Profile issue on the router.project-osrm.org

### ISSUE THREAD

**Issue by qpi** [Project-OSRM/osrm-backend#4868]
It seems on the OSRM project's router sever's profile is hardcoded. Whatever mode is passed to the API the response is always "driving"
For example these two requests have fully the same response, the mode everywhere is driving:

`http://router.project-osrm.org/route/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?overview=false&steps=true`

`http://router.project-osrm.org/route/v1/walking/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219?overview=false&steps=true`

Moreover in the API documentation the mentioned profiles (car,bike,foot) are not existing, because from the source code and from the example requests it is obvious that driving/cycling/walking are in use.

**Comment by danpat** [comment]
@qpi yes, this is a holdover from `osrm-routed` behaviour - the `<profile>` part of the URL is ignored by the routing engine.

We should modify the demoserver so that it returns an error code (perhaps 404 Not found, or 501 Not Implemented).  Note that this would be specific to `router.project-osrm.org`, local installs of `osrm-routed` or `osrm-routed.js` would continue to ignore the `<profile>` part of the URL.

**Comment by qpi** [comment]
@danpat so it means that the walking and cycling is not implemented? Because in the source I saw a lot of lines with these modes. Is it possible somehow to produce walking routing? Because the walking routing is mandatory for my thesis for the university and I wanted to use router.project-osrm.org to calculate the TSP routing for me.

**Comment by danpat** [comment]
@qpi The demoserver at `router.project-osrm.org` only has a dataset for the `car` profile.

If you need to get walking directions, you will need to run OSRM yourself, and generate a dataset processed using the `foot` profile.

The easiest way is to use the published Docker images, see the instructions here: https://github.com/Project-OSRM/osrm-backend#using-docker

I'm leaving this ticket open until we update the demoserver only serve up results for the `car` profile so folks don't get confused.

**Comment by daniel-j-h** [comment]
Check

https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server

for details on the demo server.

**Comment by slavanap** [comment]
@daniel-j-h, Could you also share a Dockerfile (or set of commands) that you use to prepare .osrm file for demo server? I launched my own server but it gives different results with the demo server for the same queries.

**Comment by chaupow** [comment]
@slavanap the dockerfile is not what makes the big difference. The demo server is fed with a constant stream of traffic speed updates to give better ETAs and routes. 

The way, how traffic is updated is described [here](https://github.com/Project-OSRM/osrm-backend/wiki/Traffic) but the data itself is not public.

**Comment by slavanap** [comment]
@chaupow Is the team going to make this data public? Because there's significant difference in results -- in NY, for instance -- for routes duration values (24m for local instance, 38m for public server).

**Comment by danpat** [comment]
@slavanap No, there are no plans for this data to be made public.

**Comment by vinayrachapalli** [comment]
hey @danpat, My local server giving the same result for all the profiles, even if I change the profile name in URL, which part of the code I need to change to work correctly, pls help me. - Thanks

**Comment by vinayrachapalli** [comment]
When I extracted, forcing it to use **foot** profile(-p profile/foot.lua), Whatever the profile I mention in URL(../v1/<profile>), It always giving the result of **walking** mode. Immediately I extracted with **car** profile(-p profile/car.lua), Whatever the profile I mention in URL(../v1/<profile>), It always giving the result of driving **mode**. Is it because the extracted files written by foot are overwritten by car? 

How to make it work, so that I'm able to run all the profiles
