### ISSUE TITLE
How does OSRM estimate "duration" when in route/match API?

### ISSUE THREAD

**Issue by zyrgit** [Project-OSRM/osrm-backend#4903]
Sorry to ask again, but I want to know how does OSRM estimate duration between two nodes. Specifically, when curl "http://router.project-osrm.org/route/..." with annotations=true, it can return nodes, distance, and duration. I want to know the source of such duration estimation. I know that by specifying --segment_speed_file to feed into OSRM we can manually change duration, I just want to know what servers of "http://router.project-osrm.org" use to do travel time/speed calculation? Many thanks!

**Comment by daniel-j-h** [comment]
If you set up your own osrm routing engine you will get speed estimations based on OpenStreetMap tags and geometries. Check out the profiles (e.g. `profiles/car.lua`) for how we come up with specific values.

For real-time traffic you need to collect your data from some source.

Closing here since this is not actionable on our side.

**Comment by Raghuvaranpulijala** [comment]
@daniel-j-h how to get better durations as they are varying greatly with actual durations .iam using route and table service .
