### ISSUE TITLE
Customize fails due to segmentation fault

### ISSUE THREAD

**Issue by econ24** [Project-OSRM/osrm-backend#4931]
I am working on a project that routes over a network generated from elevation data. I pull elevation tiles from Mapzen's tiles located on AWS. I parse the .png images and create a node for every pixel and an edge to all adjacent (vertically, horizontally, and diagonally) nodes. I have a simplification routine that grabs nodes within squares of increasing sizes and compares the height of all interior nodes to the average height of all nodes. If all nodes in the interior are within a threshold, I condense all interior nodes to a single node and create edges from this single node to the square's side nodes. This results in a single node with a lot of edges: square_size * 4 - 4 edges, with maximum square size being 64. This can significantly reduce the total number of nodes and edges, depending on the underlying terrain. Unfortunately, OSRM customize runs into problems and randomly seg-faults. It seems to be a problem with a node being contained within so many ways; if I run the build steps (extract, partition, customize) on an OSM file generated from a non-simplified graph there is no problem.

**Comment by danpat** [comment]
@econ24 Rather than us try to guess where the problem is, can you supply some sample data, and an invocation command we can use to reproduce the problem?  The smallest possible sample that triggers the crash would be the most useful, and the profile you've made, and the `gitsha` or version of OSRM you're using that triggers the crash.

Here are the next steps you can take on your own that would be helpful:

  1. Run all the tools (osrm-extract, osrm-partition, osrm-customize) with the `--threads 1` option and see if it still crashes.  Disabling parallel work will make the problem easier to reproduce if it still occurs.
  2. Try doing a debug build of OSRM (pass `-DCMAKE_BUILD_TYPE=Debug`) and re-run the tools - this will enable assertions and might give us a more useful error message.
  3. Upload some data that we can use to reproduce the crash (data, profile, exact OSRM version (gitsha)).

**Comment by econ24** [comment]
Thank you for the reply. Sorry for the lack of useful information, I've never had to do this before.

1. I tried --threads 1 and it still crashed.
2. I am using OSRM 5.16.2 installed with Node 8.9.4 and NPM 5.6.0.
3. I uploaded my custom profile. I had to append .txt so I could drag-n-drop it. I will work on creating an OSM that fails and is small enough to upload. The current OSM file is 148 megs.

[test_profile.lua.txt](https://github.com/Project-OSRM/osrm-backend/files/1776716/test_profile.lua.txt)

**Comment by danpat** [comment]
@econ24 Great, thank you.  You won't be able to upload arbitrary files to github, but feel free to email a whatever sample you can make to me at daniel@mapbox.com.  OSM XML files usually gzip pretty well.

Another way to shrink the file (I'm assuming you have OSM XML data) is to convert it to OSM PBF format (for example using http://osmcode.org/osmium-tool/).

**Comment by econ24** [comment]
Here is the OSM of a single tile at zoom 13 that failed customization.

[SMALL_GRAPH.osm.gz](https://github.com/Project-OSRM/osrm-backend/files/1776739/SMALL_GRAPH.osm.gz)

**Comment by danpat** [comment]
For anyone following along, the map is structured like this: <img width="784" alt="screen shot 2018-03-02 at 2 40 22 pm" src="https://user-images.githubusercontent.com/1892250/36925403-b116b9cc-1e27-11e8-9ba3-e1c26fd4aa63.png">

**Comment by danpat** [comment]
@econ24 Looks like the total duration for some of your edges is exceeding the maximum that OSRM allows space for (6553.5 seconds) on single edges:

There are some warnings printed during `osrm-contract` that hint at this:

```
[warn] Edge weight large -> 1418169077 : 56221 -> 68451
[warn] Edge weight large -> 1418169077 : 56221 -> 68452
[warn] Edge weight large -> 1418169077 : 56221 -> 68453
[warn] Edge weight large -> 956389046 : 56222 -> 68455
[warn] Edge weight large -> 956389046 : 56222 -> 68456
[warn] Edge weight large -> 956389046 : 56222 -> 68457
[warn] Edge weight large -> 642710319 : 56223 -> 68459
[warn] Edge weight large -> 642710319 : 56223 -> 68460
[warn] Edge weight large -> 642710319 : 56223 -> 68461
[warn] Edge weight large -> 642710319 : 56223 -> 68462
```

and running `osrm-contract` and `osrm-customize` in debug mode trigger these assertions, which hint at the same thing:

`osrm-contract`:
```
[info] initializing node priorities...[assert][0x7fffe6fdd3c0] /Users/danpat/mapbox/osrm-backend/include/util/query_heap.hpp:238
in: void osrm::util::QueryHeap<unsigned int, unsigned int, int, osrm::contractor::ContractorHeapData, osrm::util::XORFastHashStorage<unsigned int, unsigned int, 65536> >::DecreaseKey(NodeID, Weight) [NodeID = unsigned int, Key = unsigned int, Weight = int, Data = osrm::contractor::ContractorHeapData, IndexStorage = osrm::util::XORFastHashStorage<unsigned int, unsigned int, 65536>]: !WasRemoved(node)
libc++abi.dylib: terminating
```

`osrm-customize`:
```
osrm-customize SMALL_GRAPH.osrm
[info] Loaded edge based graph: 2552176 edges, 69388 nodes
[info] Loading partition data took 6.54092 seconds
[assert][0x700001f30000] /Users/danpat/mapbox/osrm-backend/include/util/query_heap.hpp:238
in: void osrm::util::QueryHeap<unsigned int, unsigned int, int, osrm::customizer::CellCustomizer::HeapData, osrm::util::ArrayStorage<unsigned int, int> >::DecreaseKey(NodeID, Weight) [NodeID = unsigned int, Key = unsigned int, Weight = int, Data = osrm::customizer::CellCustomizer::HeapData, IndexStorage = osrm::util::ArrayStorage<unsigned int, int>]: !WasRemoved(node)
libc++abi.dylib: terminating
Abort trap: 6
```

I'm not sure why, but some simple changes to your profile should fix it - let me try a couple of changes.

On another note - we should probably have better error handling on this case, rather than requiring deep debugging.

**Comment by danpat** [comment]
@econ24 The problem is that gradient-based speed values are *waaaaay* too slow, and are causing enormous times to transit various edges.

Looking at one example:

```
  <way id='14616' visible='true' version='1'>
    <nd ref='410' />
    <nd ref='14507' />
    <tag k='dy' v='1165.4453125' />
    <tag k='dx' v='484.672457837' />
    <tag k='oneway' v='no' />
    <tag k='highway' v='path' />
  </way>
```

Your formula for `forward_speed` is:

```
result.forward_speed = 6 * math.exp(-3.5 * math.abs(dy / dx + 0.05))
```

which for this way, gives:

```
$ lua
Lua 5.2.4  Copyright (C) 1994-2015 Lua.org, PUC-Rio
> dx = 484.672457837
> dy = 1165.4453125
> print(6 * math.exp(-3.5 * math.abs(dy / dx + 0.05)))
0.0011144944348153
```

i.e. 0.001 km/h (or 0.3mm/second).  Some of the lines in your sample data are around 500m long, so their duration your lines are 500m are in the order of 1,628,824 sec, which is more than OSRM is capable of storing.

Try adjusting your formula to keep the values in some more human-friendly ranges (OSRM is designed around walking/driving speeds, and the limits are in these ranges).  The default walking speed of 5km/h (1.3m/s) is a good baseline.

**Comment by econ24** [comment]
I see. That function is Tobler's Hiking function, its range is (0, 6] km/h, with max 6 reached at approx. -3 degree slope. dy is the elevation difference between nodes. There must be a large cliff there or something? I suppose I can make ways impassable if the result of that function is too small. Thanks for the help!

**Comment by danpat** [comment]
No problemo.

Leaving this ticket open however - we should have cleaner/better error handling for when edge durations/weights exceed our ability to store them.

**Comment by SiarheiFedartsou** [comment]
Stale.

**Comment by codeReaper2001** [comment]
> [@econ24](https://github.com/econ24) Looks like the total duration for some of your edges is exceeding the maximum that OSRM allows space for (6553.5 seconds) on single edges:
> 
> There are some warnings printed during `osrm-contract` that hint at this:
> 
> ```
> [warn] Edge weight large -> 1418169077 : 56221 -> 68451
> [warn] Edge weight large -> 1418169077 : 56221 -> 68452
> [warn] Edge weight large -> 1418169077 : 56221 -> 68453
> [warn] Edge weight large -> 956389046 : 56222 -> 68455
> [warn] Edge weight large -> 956389046 : 56222 -> 68456
> [warn] Edge weight large -> 956389046 : 56222 -> 68457
> [warn] Edge weight large -> 642710319 : 56223 -> 68459
> [warn] Edge weight large -> 642710319 : 56223 -> 68460
> [warn] Edge weight large -> 642710319 : 56223 -> 68461
> [warn] Edge weight large -> 642710319 : 56223 -> 68462
> ```
> 
> and running `osrm-contract` and `osrm-customize` in debug mode trigger these assertions, which hint at the same thing:
> 
> `osrm-contract`:
> 
> ```
> [info] initializing node priorities...[assert][0x7fffe6fdd3c0] /Users/danpat/mapbox/osrm-backend/include/util/query_heap.hpp:238
> in: void osrm::util::QueryHeap<unsigned int, unsigned int, int, osrm::contractor::ContractorHeapData, osrm::util::XORFastHashStorage<unsigned int, unsigned int, 65536> >::DecreaseKey(NodeID, Weight) [NodeID = unsigned int, Key = unsigned int, Weight = int, Data = osrm::contractor::ContractorHeapData, IndexStorage = osrm::util::XORFastHashStorage<unsigned int, unsigned int, 65536>]: !WasRemoved(node)
> libc++abi.dylib: terminating
> ```
> 
> `osrm-customize`:
> 
> ```
> osrm-customize SMALL_GRAPH.osrm
> [info] Loaded edge based graph: 2552176 edges, 69388 nodes
> [info] Loading partition data took 6.54092 seconds
> [assert][0x700001f30000] /Users/danpat/mapbox/osrm-backend/include/util/query_heap.hpp:238
> in: void osrm::util::QueryHeap<unsigned int, unsigned int, int, osrm::customizer::CellCustomizer::HeapData, osrm::util::ArrayStorage<unsigned int, int> >::DecreaseKey(NodeID, Weight) [NodeID = unsigned int, Key = unsigned int, Weight = int, Data = osrm::customizer::CellCustomizer::HeapData, IndexStorage = osrm::util::ArrayStorage<unsigned int, int>]: !WasRemoved(node)
> libc++abi.dylib: terminating
> Abort trap: 6
> ```
> 
> I'm not sure why, but some simple changes to your profile should fix it - let me try a couple of changes.
> 
> On another note - we should probably have better error handling on this case, rather than requiring deep debugging.

Hello, this looks exactly like what I’m running into as well.
In my case, during osrm-customize I’m using extremely small segment speeds (e.g. 0.0001 km/h), which leads to very large per-edge durations and then the same crashes/assertions you described.

I understand that this is caused by edge weights exceeding what OSRM can represent internally, but I’d like to understand the root cause more precisely: In which part of the code does it cause the segment fault? 🙏
