### ISSUE TITLE
trip: request and response coordinate mismatch

### ISSUE THREAD

**Issue by nikkatalnikov** [Project-OSRM/osrm-backend#4934]
Using OSRM with kubernetes 
https://github.com/peter-evans/osrm-backend-k8s

The data is from http://download.geofabrik.de/europe/ukraine-latest.osm.pbf

For given request to local docker container:

`curl '0.0.0.0:5000/trip/v1/driving/30.477762,50.425559;30.481464,50.428939?roundtrip=false&source=first&destination=last&geometries=geojson' | python -m json.tool`

the response is

```
{
    "code": "Ok",
    "trips": [
        {
            "distance": 679.9,
            "duration": 64.3,
            "geometry": {
                "coordinates": [
                    [
                        30.477129,
                        50.425393
                    ],
                    [
                        30.475833,
                        50.42745
                    ],
                    [
                        30.477364,
                        50.428004
                    ],
                    [
                        30.481481,
                        50.428905
                    ]
                ],
                "type": "LineString"
            },
            "legs": [
                {
                    "distance": 679.9,
                    "duration": 64.3,
                    "steps": [],
                    "summary": "",
                    "weight": 64.3
                }
            ],
            "weight": 64.3,
            "weight_name": "routability"
        }
    ],
    "waypoints": [
        {
            "hint": "ZroAgPX0N4AJAAAAQQAAAAAAAAAUAAAACQAAAEEAAAAAAAAAFAAAAI8AAABJC9EBMW4BA8IN0QHXbgEDAAAfFVxpABQ=",
            "location": [
                30.477129,
                50.425393
            ],
            "name": "\u0421\u043e\u043b\u043e\u043c\u2019\u044f\u043d\u0441\u044c\u043a\u0430 \u0432\u0443\u043b\u0438\u0446\u044f",
            "trips_index": 0,
            "waypoint_index": 0
        },
        {
            "hint": "aDwAgGWkNoAQAAAADgAAAAAAAAAAAAAAEAAAAA4AAAAAAAAAAAAAAI8AAABJHNEB6XsBAzgc0QELfAEDAACPBFxpABQ=",
            "location": [
                30.481481,
                50.428905
            ],
            "name": "\u041c\u0435\u0445\u0430\u043d\u0456\u0437\u0430\u0442\u043e\u0440\u0456\u0432 \u0432\u0443\u043b\u0438\u0446\u044f",
            "trips_index": 0,
            "waypoint_index": 1
        }
    ]
}
```

please, note that waypoint location mismatches request coordinates.

**Comment by chaupow** [comment]
I think the reason here is snapping. Here is a screenshot of your coordinates (used the demo server for this)

<img width="583" alt="screenshot 2018-03-06 11 23 51" src="https://user-images.githubusercontent.com/804027/37027252-1f78b580-2131-11e8-9fa2-7a38c07a0a87.png">

As you can see, one of the coordinates is not part of a road and not routable. OSRM matches a coordinate `A` to the closest node on a routable road `A'` and routes from there. I think the waypoint that is return here is the one that is matched (`A'`,  not `A`) and therefore the location is not exactly the same as the input coordinate

Here a vizualization of the four coordinates:
<img width="675" alt="screenshot 2018-03-06 11 35 31" src="https://user-images.githubusercontent.com/804027/37027767-8cd13ca0-2132-11e8-9158-18106e232cbb.png">


Can you double check if it solves your problems? Feel free to reopen this issue if your have follow-up questions 👋

**Comment by nikkatalnikov** [comment]
Thank you, this is helpful info.

The question, however, stands. 
Is there proper way to describe `A` to `A'` relation?
A transformation map e.g. per requested `A` the waypoint `A1` has been resolved?

**Comment by danpat** [comment]
@nikkatalnikov The `waypoints` array in the response is in the same order as the coordinates you supplied in the URL.  `waypoints[0]` describes where OSRM snapped the first coordinate, etc.

**Comment by nikkatalnikov** [comment]
thank you very much for your response.
