### ISSUE TITLE
[Question] How to run osrm-backend on windows?

### ISSUE THREAD

**Issue by ifle** [Project-OSRM/osrm-backend#4941]
How to run osrm-backend on windows?
Is there official support of windows?
We should deploy osrm server on azure. Are there anybody any experience?
Thanks

**Comment by ccort** [comment]
I downloaded the Windows binaries (v5.16.0) from here: http://build.project-osrm.org/ and they work well enough in my test system (Win 7).

**Comment by ifle** [comment]
I already use it on azure in Service Fabric. Works well. 
v15.6.0 is not latest version. Unfortunately orsm team does not support windows officially and ignored windows user needed.

**Comment by ccort** [comment]
Check this out [Quickstart](https://github.com/Project-OSRM/osrm-backend/wiki/Running-OSRM#quickstart).

That happens because osrm-routed by default assumes a CH compilation but what you did was the MLD one, so you need to: `osrm-routed --algorithm=MLD franche-comte-latest.osm` and it should work, the alternative is to compile the maps with CH (osrm-extract -> osrm-contract)

**Comment by matt439miller** [comment]
input file washington.lates.osm.pbf not found!
