### ISSUE TITLE
How to extract graph from .osrm.edges?

### ISSUE THREAD

**Issue by leiii** [Project-OSRM/osrm-backend#4985]
Hi,
I'm a researcher in urban studies, I find this project is really helpful to match GPS data to OSM. I was wondering if there was anyway to extract graph data (e.g. edge-edge pairs) from .osrm.edges files? Since I should use other packages (e.g. NetworkX in Python) to do further analysis.  

Thanks!

**Comment by danpat** [comment]
Hi @leiii - no, there isn't anything built in.

A little while back, @TheMarex prototyped https://github.com/Project-OSRM/osrm-backend/pull/3151 for exporting the node-based-graph in GeoJSON format (with node connectivity information), but we kind of bailed on that.  The branch is now quite old and might not work with current `master`.

It also has the downside that because it's the node-based-graph, it doesn't contain any information about turn restrictions - all turns are possible.  For that, you'd need either the turn restriction data in some readable format, or an export of the *edge-based-graph*, which is a line-graph of the node-based graph where edges represent possible turns, and nodes represent roads.

I've often thought that it might be useful to be able to export the graph in [GraphViz](https://www.graphviz.org/) DOT syntax or something, but have never really had a use-case for it.

**Comment by leiii** [comment]
Hi @danpat 
Thanks for your quick reply. I'll look at the #3151 .

**Comment by zifeo** [comment]
@danpat I’m also interested in this. Is there an example where the line-graph is loaded? I’m happy to give a try if it isn’t too complicated.
@leiii Did you find an alternative?

**Comment by leiii** [comment]
@zifeo I used osmnx package in Python instead.

**Comment by zifeo** [comment]
@leiii That’s indeed a good solution. How does the graph relate with the one of osrm, especially taking into account the simplification done on both sides? It would be so useful to be able to export OSRM graph into OSMNX.

**Comment by leiii** [comment]
@zifeo OSMNX also has simplification function: https://github.com/gboeing/osmnx-examples/blob/master/notebooks/04-example-simplify-network.ipynb

**Comment by danpat** [comment]
Looking at the "simplify network" function in OSMnx - OSRM does this and calls it "graph compression" (search the code for graph_compressor).  We do the same thing - remove all nodes with degree=2.

We then construct the line graph from that, then generate either the CH graph for routing, or partition the line-graph and create the overlay cell structure for the MLD routing algorithm.

@leiii Can you describe what exactly you want to get out of this?  The data structures in OSRM are pretty specific to what it needs to do - I suspect that maybe using OSM data directly might be more what you need.

If you add `annotations=nodes` to a `/match` request, you'll get the OSM node ID values back, which should make it straightforward to link to another copy of the graph for further analysis.

**Comment by SiarheiFedartsou** [comment]
Stale.
