### ISSUE TITLE
OSRM using highways with vehicle=private;delivery

### ISSUE THREAD

**Issue by dooley** [Project-OSRM/osrm-backend#5000]
Not sure if this is a bug in OSRM or in the tagging? This route
http://map.project-osrm.org/?z=16&center=48.208166%2C8.632497&loc=48.205892%2C8.621950&loc=48.206185%2C8.626081&hl=en&alt=0
should not be possible, because both 
https://www.openstreetmap.org/way/335537708#map=18/48.20610/8.62437
https://www.openstreetmap.org/way/35415299#map=17/48.20666/8.62647
highway=service are tagged with vehicle=private;delivery so they should not be used.

From discussion in https://forum.openstreetmap.org/viewtopic.php?id=61898

**Comment by TheMarex** [comment]
@dooley we allow access to `access=private` roads if the starting/end point is placed on it ("if you are already on a private road you are probably allowed to use it"), so this is intended behavior. You can observe this by changing the start point a little bit so that it does not start on the private road:

http://map.project-osrm.org/?z=15&center=48.207701%2C8.636391&loc=48.205892%2C8.621950&loc=48.206293%2C8.626059&hl=en&alt=0

**Comment by dooley** [comment]
@TheMarex that is not the case (access=private). See the new route: http://map.project-osrm.org/?z=18&center=48.206395%2C8.625676&loc=48.206039%2C8.622685&loc=48.206296%2C8.627416&hl=en&alt=0 

Start and destination are both on public accessible highways (not limited in any manner). In my opinion that's a bug in the car profile.

**Comment by dooley** [comment]
@TheMarex Good find! I changed that road and we'll see if that was the problem. If ok, i'll close this issue.

**Comment by dooley** [comment]
It's fine now - ticket closed.

http://map.project-osrm.org/?z=18&center=48.206012%2C8.625783&loc=48.206039%2C8.622685&loc=48.206303%2C8.627433&hl=en&alt=0
