### ISSUE TITLE
Libosrm startup time

### ISSUE THREAD

**Issue by mecjack** [Project-OSRM/osrm-backend#5047]
Hi together,

i I have successfully complied the example project [](https://github.com/Project-OSRM/osrm-backend/tree/master/example) with cmake/make from another folder.   So I go the osrm-example binary which I can run for routing. 
The problem is the startup time until the actual routing starts, where the heavy lifting is performed. 
It takes about 3 seconds and that in may case is not good. 
With the http API where a server runs, it responds imediately. 
Because I need good performance I need libosrm, but how can I avoid having a startup time? Is there any other service which I can compile? Or should I do myself a socket listen before the heavy lifting to trigger the work?

Help is very appreciated!
Marcel

**Comment by daniel-j-h** [comment]
Thanks for moving this conversations from private messages to this tracker.

You can use `osrm-datastore` to pin the required data into shared memory once. And then let `osrm-routed` attach to the shared memory segment instead of having to load the required data every time on startup. See:

https://github.com/Project-OSRM/osrm-backend/wiki/Configuring-and-using-Shared-Memory

**Comment by mecjack** [comment]
Cool thanks, shared memory would definitely be a good way to go. Will have to check how I can integrate it. 
But since I resolved installing the node bindings, I will first check this out to see the performance.

Cheers Marcel

**Comment by daniel-j-h** [comment]
Closing as not actionable on our side. Shared memory should help you; good luck and happy routing!

:tada: :car:
