### ISSUE TITLE
Set points on ferry route

### ISSUE THREAD

**Issue by KushnirDV** [Project-OSRM/osrm-backend#5075]
How to set up file car.lua, user to can to set points on ferry route.
Thanks for help.

**Comment by danpat** [comment]
The code that controls this is here:

https://github.com/Project-OSRM/osrm-backend/blob/3b4e2e83ef85983df1381dbeacd0ea5d4b9bbbcb/profiles/lib/way_handlers.lua#L74-L91

Because `car.lua` doesn't define `profile.allowed_start_modes`, only the `profile.default_mode` travel mode is considered a start point.

What you should do is add a snipped like this to `car.lua`:

```
    allowed_start_modes = Set {
      default_mode,
      mode.ferry
    },
```

after `default_mode` is defined, inside the `return` clause of the `setup()` function.

**Comment by KushnirDV** [comment]
Thanks a lot for quick answer

**Comment by KushnirDV** [comment]
I added the snippet  to `car.lua`

```
    allowed_start_modes = Set {
      default_mode,
      mode.ferry
    },
```
When I started to make extract for Denmark, then I got this error:
```
[info] SCC run took: 0.185713s
[info] Building r-tree ...
[info] Constructing r-tree of 2918787 segments build on-top of 2792039 coordinates
terminate called after throwing an instance of 'osrm::util::exception'
  what():  There are no snappable edges left after processing.  Are you setting travel modes correctly in the profile?  Cannot continue.src/extractor/extractor.cpp:822
Aborted (core dumped)
```
When I restore default settings for `car.lua`, then extract of Denmark was success.

Could you possibly to give me any hint what to do?
Thanks for attention.

**Comment by KushnirDV** [comment]
Resolved
I changed from `default_mode` to `mode.driving`
And I can put the points on ferry routes
Thanks

**Comment by danpat** [comment]
@KushnirDV ah, sorry, that was my mistake.  I've updated my original comment so that future folks needing this have a valid code snippet.
