### ISSUE TITLE
Using local tiles service

### ISSUE THREAD

**Issue by Sozhia** [Project-OSRM/osrm-backend#5078]
Hello everybody.
Is there anywayt to use my own local tiles server with osrm? Could somebody helpme?
Thanks a lot.
SO: Windows 7
Tiles: MS4W

**Comment by danpat** [comment]
@Sozhia OSRM calculates routes on OSM-format XML or PBF files - the usual way to do this is to download an extract from somewhere like GeoFabrik or the OSM website itself.

OSRM cannot calculate routes on "tiles".

In order to calculate routes on arbitrary map data, you must first transform the data you have into something that looks like OSM data.  I've heard of people doing this for some commercial map sources, but as far as I know, none of that work is public.

**Comment by daniel-j-h** [comment]
Stale.
