### ISSUE TITLE
OSRM-extract sorting edges by start takes a while

### ISSUE THREAD

**Issue by phenric** [Project-OSRM/osrm-backend#5089]
Hi,

I'm extracting the **planet OSRM** and everything seems good except that it's about 24 hours that the process is stopped with _Sorting edges by starts_.
When I prompt _ls -lh_ the file planet.map.osrm.pbf sized 40GB and the file planet.map.osrm sized 12GB.

Also, I allocate 300 GB with swapon on the hard disk and I have 8 threads.

Is it normal ? Should I restart the process ? Is there any solution to not restart from the beginning ?

Thanks for your help and continue with this great project ! 👍

**Comment by danpat** [comment]
@phenric OSRM is very sensitive to the difference between real RAM and swap.  The data structure that's being sorted during the step you seem stuck on is not using a disk/memory optimized sort algorithm, so it's very likely causing heavy swapping during the sort, and this will be *significantly* slower than a RAM-only version.

Normally, folks use machines with sufficient RAM to hold all data structures (you'll need 200-300GB 
 of RAM to process the planet without swapping), and you can expect the planet to profess in something like 12 hours, depending on which profile you use and how big your machine is.  Allowing the code to use swap will likely be hundreds of times slower, due to the mostly random access nature of the graph data structures.

There's no way to re-start the process unfortunately.  You need a bigger box.  I'd recommend 200GB of RAM, and an SSD where possible.  Things will be even worse if you use a spinning disk.

**Comment by phenric** [comment]
@danpat You're right, it was the problem. I stopped the process and I will look for some others external solutions like Graphhopper.

Thx for your reply

**Comment by danpat** [comment]
Note that once you have the planet processed, the runtime RAM requirements are lower - around 40-50GB for the planet.  It's not uncommon to temporarily rent a larger server to process the data quickly.  Services like Linode, Amazon Web Services and others make this pretty easy, but it will cost a few dollars.
