### ISSUE TITLE
I/O error when starting north-america-latest.osrm

### ISSUE THREAD

**Issue by JacobCoblentz** [Project-OSRM/osrm-backend#5097]
I'm using v5.18.0, and I've run OSRM as follows:

osrm-extract north-america-latest.osm.pbf -p profiles/foot.lua
osrm-contract north-america-latest.osrm

osrm-routed north-america-latest.osrm

the server fails with the error:

"[error] I/O error occurred: north-america-latest.osrm.cell_metrics : /mld/metrics/duration/exclude.meta (possible cause: "Success") (at include/storage/tar.hpp:67)"

Any clue what's going on?

**Comment by oxidase** [comment]
@JacobCoblentz `.osrm.cell_metrics` is created by `osrm-customize` and is a part of an MLD data set. If you did not run `osrm-partition` and `oarm-customize` then probably files `north-america-latest.osrm.partition`, `north-america-latest.osrm.cells`, `north-america-latest.osrm.cell_metrics`  are stale and can be removed.

**Comment by danpat** [comment]
Hmm.  We're defaulting to CH as the routing algorithm:

https://github.com/Project-OSRM/osrm-backend/blob/master/src/tools/routed.cpp#L126-L129

why would the code even care to look for `.cell_metrics` in this case?

**Comment by oxidase** [comment]
@danpat Data loading is implemented in such a way that `osrm-datastore` loads both datasets if they are present because the algorithm type is not specified. 

 `osrm-routing` reuses storage code at https://github.com/Project-OSRM/osrm-backend/blob/e5d8319c43b454642079f66b930ac73803840e2b/src/storage/storage.cpp that does not  use `config.algorithm` parameter.
