### ISSUE TITLE
Small variations in the speeds over certain road segments

### ISSUE THREAD

**Issue by Rohanramesh97** [Project-OSRM/osrm-backend#5145]
Hello.

I have been trying to create a new profile just to try to get the hang of how the lua files are processed. I encountered in various parts of the map that the speeds over certain road segments are higher or lower that the speed given by the lua. For example, in the following picture, the lua has speed on motorways set to 60 km/hr, but when I display the speeds on the map, I find small changes to this speed:

![image](https://user-images.githubusercontent.com/40250280/42789824-005347ba-892d-11e8-8a39-6d49dbf5b3d3.png)

I just wanted to know why this happens and how I would be able to remove this from the processing of the ways. 

Thanks!!

**Comment by danpat** [comment]
@Rohanramesh97 The TL;DR is - it's an issue of rounding and precision in the map display, not necessarily what's happening under the covers.

OSRM calculates routes based on *duration*, not speed.  Internally, the total time to traverse each edge is stored, not the travel speed.  When we display the debug map, we calculate the length of each segment (straight line between two coordinates), and reverse-engineer the speed that was applied.  Because the total section length is only stored to 0.1 sec precision, and coordinates are limited to [6 decimal places of precision](https://en.wikipedia.org/wiki/Decimal_degrees) (about 10cm), you'll see some rounding/precision artifacts on the debug map.

A few observations:

  1. The length-weighted mean of all the segments on a section (between two intersections) should match the original speed assigned in Lua.  It's just the display that's a bit wonky.
  2. Most of a route traverse complete edges, so it's only the total duration that matters, not the individual segment variation.
  3. The map display is more prevalent for very short segments - this is due to the 0.1s precision limit on section duration.
