### ISSUE TITLE
unable to docker run

### ISSUE THREAD

**Issue by naveed-butt** [Project-OSRM/osrm-backend#5160]
Hi,
I am trying to setup an image of the osrm-backend on my docker. I am unable to run docker using the below commands (as mentioned in wiki)
```
docker run -t -v ${pwd}/data osrm/osrm-backend:v5.18.0 osrm-extract -p /opt/car.lua /data/denmark-latest.osm.pbf
docker run -t -v ${pwd}:/data osrm/osrm-backend:v5.18.0 osrm-contract /data/denmark-latest.osrm
docker run -t -i -p 5000:5000 -v ${pwd}/data osrm/osrm-backend:v5.18.0 osrm-routed /data/denmark-latest.osrm
```
I have already fetched the corresponding map using both wget and Invoke-WebRequest. Every time I run the first command from the above, it gives the error...

> [error] Input file /data/denmark-latest.osm.pbf not found!

I have tried placing the downloaded maps in the corresponding location as well. Can anyone tell me what I am doing wrong here ?

**Comment by danpat** [comment]
@naveed-butt It looks to me like you've got a typo in `-v ${pwd}:/data` in two of those commands.  The colon `:` is necessary.

Check the docs for the `docker run` command on the Docker website here: https://docs.docker.com/engine/reference/commandline/run/

**Comment by naveed-butt** [comment]
Hi @danpat , I have already answered this one in the StackOverflow answer in the comments [here](https://stackoverflow.com/q/51738516/217757)... This was a typo and I tried that with a colon as well. Please reopen the issue and it would be great if you could guide me on what is wrong here...

**Comment by danpat** [comment]
@naveed-butt The problem is you're not running docker correctly, this is not an OSRM problem.

The wiki article is written assuming you're using `bash` on a Linux box.  You're using Powershell, so some of the shell expansion behaviour may be different.

You've written `${pwd}` instead of `$(pwd)`.  You'll also need the `pwd` command to work on Windows.

Overall, you're going to need to adapt the Wiki page to Powershell/Windows - it's written for Linux.

I don't use Windows and I've never used Powershell, so I can't help you.

**Comment by naveed-butt** [comment]
Hi @danpat 

If you can't help, can you please re-open this issue so someone else can help here?

**Comment by danpat** [comment]
@naveed-butt The problem here isn't OSRM, it's how you're using Docker and powershell.  If someone else knows exactly what syntax you need, then they're free to add to this closed ticket, but as this isn't a problem with OSRM itself, the ticket will stay closed.
