### ISSUE TITLE
Why different results?

### ISSUE THREAD

**Issue by GosuUnDeadGhost** [Project-OSRM/osrm-backend#5166]
Hello! 

I make a request in the DEMO and in my system and get different answers. For some reason, my system goes all the way to the street

https://router.project-osrm.org/route/v1/driving/27.60078907012939,53.902454534854485;27.58495330810547,53.907950300003854?overview=full&alternatives=true&steps=false&hints=;

Here's what I get for the DEMO:

http://prntscr.com/kic5x2

My system:
http://prntscr.com/kic6qh

It turns out that my system for some reason bypasses this part of the road. Tell me, because of what this can happen? Maybe you need some more information - write, I'll send it all !!!

**Comment by jcoupey** [comment]
Maybe this is related to running on different OSM extracts, e.g. if there is a connectivity issue in your data that has been fixed in the extract used by the demo. You can check this kind of problem by running `osrm-frontend` locally on your OSRM instance, using the [debug tiles](https://github.com/Project-OSRM/osrm-frontend#changing-backends) feature.

**Comment by TheMarex** [comment]
Also note that the demo server uses traffic information on-top of the regular static weighting.

**Comment by daniel-j-h** [comment]
Indeed. Check guarantees in https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server.
