### ISSUE TITLE
ERROR INPUT FILE NOT FOUNT

### ISSUE THREAD

**Issue by nyoakaway** [Project-OSRM/osrm-backend#5206]
Hi, I'm getting the error "[error] Input file /data/argentina-latest.osm.pbf not found!" when executing the command extract! The C: folder is already shared in Docker and the command I'm calling is "docker run -t -v /c/osrm:/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/argentina-latest.osm.pbf"

Does anyone know what can it be?

**Comment by kkarakk** [comment]
I have the same issue, can the startup document be made more descriptive? i am a docker noob admittedly

**Comment by danpat** [comment]
@kkarakk The problem is that the issue above is specific to Windows - and none of the folks who wrote the startup document use Windows to test.

If you can figure out what needs to change in the doc, we can ammend it, but ideally, someone with Windows would vet the changes to ensure they work.

The instructions in the doc work just fine on Linux/macOS.

I *suspect* the issue is how the Docker `-v` parameter works - but I don't know how it expects paths to be constructed.

**Comment by kkarakk** [comment]
Yup,if you look at osrm on stack overflow there are two other people with the same issue on Windows(and unanswered status)

**Comment by kkarakk** [comment]
@danpat i figured it out, you have to give docker permission to access shared drives in docker desktop(Shared drives tab) even if you've done it before coz of  [this unfixed bug](https://github.com/docker/for-win/issues/1712) and then instead of using relative path i used absolute path. So in the end my  command looked like(In powershell) 

```
D:\Docker> docker run -t -v D:/Docker:/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/india-l
atest.osm.pbf
```

where india-latest.osm.pbf was inside D:/Docker:/data and i ran the command from the same location. i couldn't get relative path to work, will need to do some more research on that

**Comment by Nimrod51** [comment]
I'm facing the **exact** same error as you, despite iteratively trying to enable the shared drive, resetting credentials numerous times. The command I'm trying is this: `docker run -t -v C:/OSRM:/data osrm/osrm-backend osrm-extract -p /opt/car.lua /data/australia-ocean-latest.osm.pbf` and I'm still getting the error: `[error] Input file /data/australia-ocean-latest.osm.pbf not found!` - is there anything I'm missing? I've also tried using absolute paths in the last argument, but nothing is working

**Comment by kkarakk** [comment]
@Nimrod51  did you see the image i linked? you have to give access to docker to mount C drive("make it available to docker"). have you given it access? try running through https://rominirani.com/docker-on-windows-mounting-host-directories-d96f3f056a2c

**Comment by Nimrod51** [comment]
Thanks @kkarakk, I looked at the docker logs and the problem wasn't at mounting the C: drive (surprisingly), it was a path issue. Once I entered the command `docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /**data**/data/australia-oceania-latest.osm.pbf` then everything worked. It's something to do how the image folder structure also has a `data` folder. In summary, to run this just 1) create a folder and within it another folder called `data` and put the input OSM data in it, and 2) run the command I wrote above in the main folder.

**Comment by satvug** [comment]
I had the exact same problem, (the input file error), on Windows 10, using Batch.
I solved it by using this command:

docker run -t -v "%cd%":/data osrm/osrm-backend osrm-extract -p /opt/bicycle.lua /data/sri-lanka-latest.osm.pbf

inside this folder:
C:\docker\data

Notice the "%cd%" instaed of "${PWD}" on Linux
Hope this helps!
