### ISSUE TITLE
Add external restrictions to OSRM backend

### ISSUE THREAD

**Issue by cachuco** [Project-OSRM/osrm-backend#5216]
Is it possible to add external conditional restrictions to OSRM?. For example, during the next week a street (from nodeID A to nodeID B) will be closed to traffic. So I want to add a restriction access:no during that period.

We have tried to add it with the format of conditional restrictions of OSM to the file * .osrm.restrictions but it does not seem to respect them.

I am using OSRM-Backend via docker.

**Comment by danpat** [comment]
@cachuco In order to trigger the conditional restriction handling, you need to do the following:

  1. Inject an OSM `access:conditional=` tag on the way in question.
  2. Run `osrm-extract` with the `--parse-conditional-restrictions` flag
  3. Run `osrm-contract` with the `--time-zone-file` and `--parse-conditionals-from-now` arguments.

Step 3 is important - due to the nature of the routing algorithm used in OSRM, restrictions cannot be turned on-and-off on the fly, instead you must re-create the routing graph.  The `--parse-conditionals-from-now` flag specifies the time at which the conditionals will be evaluated.

Of course, if you simply add `access=no` to a way, access will be disabled, you do not need the "conditional" access handling feature.

There are basically two approaches you could take to inject external data:

  1. Construct artificial OSM "changesets" and merge them with your .pbf file using `osmium`
  2. Modify `car.lua` and add some hard-coded logic there to set flags on various way IDs when they are processed.

All options required you to re-process the data, there is no shortcut by modifying the processed files.

**Comment by cachuco** [comment]
Thanks @danpat for your explanations, I understand that modify *.osrm.restriction and restart OSRM is not a solution. 

I currently do the steps 2 and 3, but I have doubts about how to do step 1.

How inject an OSM restriction? its necessary to generate a new *.pbf and merge with official *.pbf, or or through car.lua. There is some example in the documentation, I do not find anything similar.

**Comment by danpat** [comment]
Take a look at:

https://wiki.openstreetmap.org/wiki/OsmChange

this describes the format of OSM changesets.  You can construct an artificial one of these that modifies the tags on the ways you care about.  You can them use `osmium apply-changes` to apply that changeset to your `.pbf` file:

https://docs.osmcode.org/osmium/latest/osmium-apply-changes.html

**Comment by cachuco** [comment]
Thank you @danpat, I go to try it.

**Comment by fwk1010** [comment]
This means that it is not real time to handle tag like access:conditional=no @ (06:00-20:00) on running,right? @danpat 
It seems must be feed osm data again and then re-create the routing graph.

**Comment by laerciokonzen** [comment]
We have any way to set the ```access=no``` live on OSRM? 
In our case, we have a bridge that is under construction and need to be diverted temporarily.

**Comment by frodrigo** [comment]
Using MLD you can change the cost of a way.
