### ISSUE TITLE
The tile service is really meant for debugging OSRM's view of the OpenStreetMap road network only and is not a fully-fledged tile renderer.

### ISSUE THREAD

**Issue by carlosen14** [Project-OSRM/osrm-backend#5225]
_Originally posted by @daniel-j-h in https://github.com/Project-OSRM/osrm-backend/issues/4713#issuecomment-348916707_

I was looking for information to deploy a server to create the tile service to not depend on Mapbox service (https://api.tiles.mapbox.com/v4/{id}/{z}/{x}/{y}.png). 

Actually i have the map extracted as needed, and i am working with the NodeJS bindings and the route and trip services.

Any hint to start with the tile service? 

Related to tile service, i have this
```javascript
Travel.get('/tile/:id/:z/:x/:y', (req, res, next) => {
  console.log('URL ' + req.protocol + '://' + req.get('host') + req.originalUrl)
  let x = req.params.x
  let y = req.params.y
  let z = req.params.z
  if (isNaN(x) || isNaN(y) || isNaN(z)) {
    next(new Error('Se recibieron parámetros inválidos'))
    return
  }
  console.log(`tile > ${x}, ${y}, ${z}`)
  OSRM.getInstance()
    .then(osrm => {
      return new Promise((resolve, reject) => {
        osrm.tile([x, y, z], function (err, response) {
          if (err) {
            console.error('1 > error ', err.message)
            console.error('1 > error ', err)
            reject(err)
          } else {
            // res.end(response, 'binary')
            resolve(response)
          }
        })
          .then(response => {
            res.send(response)
          })
          .catch(err => {
            // Here is printed the error
            console.error('2 > error ', err.message)
            console.error('2 > error ', err)
            next(err)
          })
      })
    })
    .catch(err => {
      console.error('3 > error ', err.message)
      console.error('3 > error ', err)
      next(err)
    })
})
```
Example request is x: 1811, y: 3489, z: 13
The error is "Tile x coordinate must be unsigned integer"

Any hint to solve this? Or is there something else to do?, 

also is this service a full feature to use as my own map service? Or it is just a debugger like Daniel J. H. said?

Thanks.

**Comment by danpat** [comment]
@carlosen14 OSRM's tile server won't give you tiles that make for a very good map.  The structure of the geometries and the properties on the features, are, as @daniel-j-h said, designed for debugging OSRM, not rendering a useful map.  Important things like road classes are missing, and features are broken into individual, 2-coordinate lines, not continuous linestrings, which will lead to very bad label placement (probably unusably bad).

However, if you still want to take a look at them, it sounds like your bug is that you need to put a `parseInt` call around the input URL parameter, like: `var z = parseInt(req.params.z)`.

**Comment by carlosen14** [comment]
Thanks for your answer, it was very clear, just a doubt.. So, do you really recommend to continue using another external web service to get the tiles? 

By the way, i wasn't able to see the tiles generated by my own service, i think now it is because of some header request missing, but that's another story.

**Comment by danpat** [comment]
@carlosen14 Yes - if you want decent cartography in the background map, you should use an external service.  OSRM is really only designed to calculate the route path, and the turn-by-turn instruction data.  Many things that you'll want on the basemap are missing from OSRM's data, because it doesn't need those things to do its primary function.
