### ISSUE TITLE
cmake --build . terminal stops working

### ISSUE THREAD

**Issue by raquelgdes** [Project-OSRM/osrm-backend#5236]
Hello! I'm new to Ubuntu. I'm trying to build OSRM and the terminal stops working, it gets blocked whenever I run the cmake --build . command, I already tried the sudo make install or just the make command but the result is always the same, it gets blocked at 0% building and I have to power off the virtual machine.
Someone can help me? Thank you!

**Comment by danpat** [comment]
@raquelgdes Try doing `VERBOSE=1 cmake --build .` - this will give you more info about where it might be stuck.

Off the top of my head, the only thing I can think is that your VM might not be sufficiently provisioned with RAM/CPU to build quickly.  Are you able to open a second terminal into the same machine and use `top` to look at which processes are consuming resources?

Compiling C++ projects can require significant amounts of RAM - OSRM is no exception here.  It's been a while since I've built it on a "small" machine, but I'd guess that if you have 1GB or less of RAM available, the compiler will either fail, or be very very slow.
