### ISSUE TITLE
Restricting border crossings?

### ISSUE THREAD

**Issue by tim-myth** [Project-OSRM/osrm-backend#5238]
How would one go about restricting national border crossings? Is such s thing even possible?
For example:
http://map.project-osrm.org/?z=6&center=41.975827%2C-75.212402&loc=46.879232%2C-96.929228&loc=44.310583%2C-69.779663&hl=en&alt=0 

This route originates in the U.S., crosses into Canada, and terminates in the U.S.

**Comment by daniel-j-h** [comment]
You can modify the profile to put high weights onto these crossings. Check out how we currently penalize e.g. gated communities (destination tags).

**Comment by Bahmer** [comment]
I'm trying to restrict border crossing as well but have not been able to get it to work.  I've tried only loading the Canada pbf file but then I get a NoRoute error (Impossible route between points) when routing from southern Ontario (I think it is trying to route through the U.S. but can't since the data is not there).  I had it working at one point using Canada only and result.barrier = true where barrier == "border_control" but with the latest version of OSRM and the latest pbf files, setting the barrier tag no longer seems to work.  I have also tried the same, blacklisting border_control, with the North America pbf file but it still routes through the U.S.  I looked at the destination tag references in the lua files but have not been able to figure out how to apply that to an international border.  Any help with this would be greatly appreciated.

**Comment by danpat** [comment]
OSRM has the "location dependent data" feature - a geojson file with properties that are accessible during processing, but it'd need a bit of work to make it work for border crossings.  It's currently only used for left/right driving side.

  1. You'd need a GeoJSON file for countries - those are available, but we don't have one handy.  As @nilsnolde pointed out, Valhalla effectively builds something like this from the raw OSM data.
  2. The turn function where you'd need to apply the penalty I don't believe is passed the location dependent data currently - that would need to get fixed.
