### ISSUE TITLE
osrm-routed - Dataset is not compatible 

### ISSUE THREAD

**Issue by KeMilin** [Project-OSRM/osrm-backend#5279]
Hello.

I try to install osrm locally, on a windows system.

So, I have followed these steps:

1.	I have downloaded binaries from http://build.project-osrm.org/ ;
2.	I have put OpenStreetMap data for my region into the extracted osrm directory ;
3.	In the command prompt :
a.	cd C:\Users\Kévin\Desktop\OSRM\osrm_Release
b.	osrm-extract –p profile.lua franche-comte-latest.osm.pbf
c.	osrm-partition  franche-comte-latest.osm
d.	osrm-customize franche-comte-latest.osm
e.	osrm-routed franche-comte-latest.osm

But, at the end, I have the following error: 
←[31m[error] [exception] Dataset is not compatible with CH←[0m

I will be grateful for any help,

Thanks,

Kévin

**Comment by systemed** [comment]
Check the syntax of each command you're issuing.

1. osrm-partition, osrm-customize and osrm-routed require that you pass the .osrm file, not the .osm file
2. You're using MLD (i.e. partition/customize) rather than CH. You need to specify that in the --algorithm flag to osrm-routed, or it'll assume that you're using CH.

**Comment by KeMilin** [comment]
It works.
Thanks a lot for your help.

Kévin
