### ISSUE TITLE
driving with short walking ?

### ISSUE THREAD

**Issue by IntegrysIT** [Project-OSRM/osrm-backend#5284]
Is it possible to create a custom profile using driving with short walking allowed?
For example ... we have to delivery items to lots of destinations ... among these we have points A and B (see picture).
We can go driving ... for about 2km (that means about 25 minutes in that specific place with traffic), or simply cross the road (about 1 minute).
We need a profile that allow a walking for max (for example) of 200 meters ... when it's possible of course, not climbing mounting nor flying over canions not even wading a river :D 
How can we do it?
![driving_walking](https://user-images.githubusercontent.com/32899531/49001072-de60bd80-f15b-11e8-9b0f-0df0d4dfa0fe.png)

**Comment by emiltin** [comment]
The bike profile allows pushing of bikes (e.g. across stairs and against oneways), when it saves significant time, which is similar to what you want.

However, it assumes you bring your bike with you, and continue on bike after walking from A to B. For car routing, carrying you car is probably not convenient... So I guess you would return by foot to A before continuing in the car. I'm not sure that can be enforced in OSRM.

Another solution: deliver by bicycle, it's often faster in a city with traffic :-)

**Comment by danpat** [comment]
You could, of course, combine the car and foot profiles into a single profile that uses car speed/mode for most roads, and foot for a limited subset of only-walkable things (footpaths, tracks, pedestrian bridges, etc).  I think in *most* circumstances this would get you a route that you want.  You'd have to spend some time integrating `car.lua` and `foot.lua` to make this work.

One problem I can forsee is that OSRM, like @emiltin points out, assumes that you "take your bike with you".  It's quite possible that it'll emit a route that goes "foot->car->foot->car->foot" because it finds a shortcut that's doable by foot in the middle.  This obviously makes no sense as you can't carry your car, and would require some fairly deep modifications in OSRM to enforce only a single "foot->car->foot" set of transitions.

I do think this is a great idea - "multi-modal" routing is definitely challenging.
