### ISSUE TITLE
Routing in Switzerland to Supercharger goes one exit too far

### ISSUE THREAD

**Issue by Felger** [Project-OSRM/osrm-backend#5288]
[This route](http://map.project-osrm.org/?z=12&center=46.794184%2C6.791267&loc=46.820805%2C6.939126&loc=46.832031%2C6.858108&hl=en&alt=0) takes one exit further than required.  A similar route can be found on [Google Maps](https://goo.gl/maps/BkVit7UMiWL2) without driving past the destination to the next exit.

**Comment by danpat** [comment]
The problem here is the tunnel - the coordinate you've supplied is closer to the tunnel than any of the surface streets.  If you slightly move the coordinate, it'll snap to the parking lanes in the supercharger lot and you'll get the expected route.

There's an old ticket that discusses this problem:  https://github.com/Project-OSRM/osrm-backend/issues/1263

We should consider better heuristics to try to get the snapping right - e.g. given several candidate snapping nodes, which one does the user *probably* want?

**Comment by danpat** [comment]
I'll also note that Google can be forced to make the same mistake by slightly moving the destination coordinate to a spot that's directly over the tunnel, but not on any of the parking-lot roads.
