### ISSUE TITLE
Stopover on highway=service

### ISSUE THREAD

**Issue by dooley** [Project-OSRM/osrm-backend#5333]
With OSRM car profile it is not possible to use a stopover on a highway=service? 

Example: [https://routing.openstreetmap.de/?z=18&center=51.475524%2C7.216261&loc=51.475476%2C7.215394&loc=51.475439%2C7.215673&loc=51.475225%2C7.215244&hl=en&alt=0&srv=0](url) 
I don't see any reason for "NoRoute" from OSM data. Any hints welcome ;-)

**Comment by danpat** [comment]
@dooley The problem here is the default `continue_straight` behaviour with the Car profile.

The issue looks to be basically the same as https://github.com/Project-OSRM/osrm-backend/issues/5320

The road where your waypoint is terminates at a railway station, and there are some oneway-to-nowhere roads at the end (the pink bits in this image) where it's impossible for the path to escape:

<img width="416" alt="screen shot 2019-01-04 at 11 22 19 am" src="https://user-images.githubusercontent.com/1892250/50706604-27394b00-1013-11e9-9e39-05bad21b724e.png">

If you add `continue_straight=false` to the request URL, the routing engine will allow a u-turn at the waypoint, and a path will be found.

**Comment by dooley** [comment]
@danpat Yes, adding that parameter does work for my problem. Thanks!
[http://routing.openstreetmap.de/routed-car/route/v1/driving/7.215325,51.475707;7.215726971626282,51.475459285991015;7.214606,51.475783?overview=false&alternatives=true&steps=true&continue_straight=false](url)
