### ISSUE TITLE
Rerouting because of a blocked path

### ISSUE THREAD

**Issue by bryanibit** [Project-OSRM/osrm-backend#5346]
I met a situation, where there was a **blocked** path, which I did not know before. So I'd like to add a big **cost** to the blocked path and **rerouting** once more. Make sure that the blocked path will not be a choice for routing. I am not clear OSRM can achieve that. Thank you!

**Comment by danpat** [comment]
@bryanibit Currently the only way to do to do this would be to re-process the routing data, either importing an updated `.osm.pbf` with the blockage mapped, or to load some fake traffic data, and set the travel speed to 0 for the segment that you have discovered is blocked.  OSRM doesn't support per-query on-the-fly adjustment of single edge weights, due to the acceleration graphs that it uses to speed up queries.

**Comment by bryanibit** [comment]
Could you please give me some advices about dynamically rerouting as adjusting osm dataset? I don't care much about time cost instead of functionality. Usually my osm dataset just shows a small area.

**Comment by danpat** [comment]
@bryanibit OSRM cannot do ths on a per-request basis.  You would need to build a system to submit blockages, and re-build your dataset.

See https://github.com/Project-OSRM/osrm-backend/wiki/Traffic for a description of how to generate traffic data, which you could use to set travel speeds to 0 on the roads you want to close.

There are some older tickets that describe the feature you're asking for: https://github.com/Project-OSRM/osrm-backend/issues/892

Some other routing services support this, see https://github.com/Project-OSRM/osrm-backend/issues/5155#issuecomment-409257695 for example.

**Comment by bryanibit** [comment]
Thank you for your reply! I will close this issue.
