### ISSUE TITLE
Missing file and library mode

### ISSUE THREAD

**Issue by rgugliel** [Project-OSRM/osrm-backend#5359]
Hello,
When you start the web server with `osrm-routed` and a file is missing, then you get a precise information (via Log::Warning)

However, when you use the libosrm, then you get only the general message:
```
"Required files are missing, cannot continue.  Have all the "
                              "pre-processing steps been run?"
```
and you don't know which file is missing.

I'm wondering it could be worth file to change 
``` 
bool IOConfig::IsValid()
```
to something like
```
bool IOConfig::IsValid(vector&<string> missingFiles)
```
(or equivalently, change the return type of the `IsValid` method). That way, we could add that to the exception text that is thrown by OSRM.

What do you think?

If you think the idea is fine, I'll try to do it and open a PR.

Thanks.

Rafael

**Comment by danpat** [comment]
@rgugliel Not a bad idea.

In order to not break ABI compatibility, we'll want to add a *new* function here - the return type isn't included in function resolution (see https://en.cppreference.com/w/cpp/language/adl).

My suggestion would be to add a new method called `vector&<string> GetMissingFiles()` - this could be *after* `IsValid()` returns false, and the error message could be augmented if the list is non-empty.

**Comment by rgugliel** [comment]
OK; will do, thanks.

**Comment by rgugliel** [comment]
https://github.com/Project-OSRM/osrm-backend/pull/5360
