### ISSUE TITLE
Turn restriction not work some time

### ISSUE THREAD

**Issue by mostafa-j13** [Project-OSRM/osrm-backend#5380]
When we have way with id >2^32 turn restriction is not work on this way

**Comment by danpat** [comment]
Currently, the largest way ID in the public OSM database is about [565140676](https://www.openstreetmap.org/stats/data_stats.html), which fits within 2^30.  We've got a way to go before we run out of space for way IDs.  We added support for >2^32 node IDs back in December 2015, but it'll be quite a while before ways hit the same threshold.

I'm guessing you're using your own dataset?  If so, you should renumber your data so that the way ID values are less than 2^32.
