### ISSUE TITLE
back turn problem

### ISSUE THREAD

**Issue by ivantrouvetout** [Project-OSRM/osrm-backend#5395]
I have a route problem with this example

http://map.project-osrm.org/?z=12&center=49.966681%2C3.149128&loc=49.980495%2C3.121319&loc=49.980395%2C3.121592&loc=49.950391%2C3.117456&hl=en&alt=0

![image](https://user-images.githubusercontent.com/10398391/54023798-31540300-4196-11e9-9feb-698f06494318.png)

**Comment by danpat** [comment]
By default, the `car` profile has `continue_straight=true`, which forces this kind of route.

The map.project-osrm.org website doesn't have a way to change that parameter, but if you make the API request manually with this:

https://router.project-osrm.org/route/v1/driving/3.121319,49.980495;3.121592,49.980395;3.117456,49.950391?overview=false&alternatives=true&steps=true&hints=;;&continue_straight=false

it turns out like this:

<img width="451" alt="screen shot 2019-03-08 at 7 00 22 am" src="https://user-images.githubusercontent.com/1892250/54036217-de675500-416f-11e9-904c-4da78c31b820.png">

Feel free to submit a pull request to the `osrm-frontend` website that allows this flag to be changed :-)

**Comment by ivantrouvetout** [comment]
thank 
the default settings would they have changed ?

**Comment by ivantrouvetout** [comment]
the problem come rather from the data it is obvious that the other route is much shorter(faster)

http://map.project-osrm.org/?z=13&center=49.975293%2C3.133593&loc=49.980495%2C3.121319&loc=49.980395%2C3.121592&loc=49.953098%2C3.125439&hl=en&alt=0
![image](https://user-images.githubusercontent.com/10398391/54111456-2a223480-43e4-11e9-8b22-eab574119c69.png)
