### ISSUE TITLE
Routing Service cannot disable pinning coordinate to nearest segment.

### ISSUE THREAD

**Issue by JasonCromer** [Project-OSRM/osrm-backend#5399]
When using the Routing Service, it will still produce a route, even if I set the origin or destination in the ocean. 
For example, if I set the origin coordinate in the ocean, and the destination somewhere in San Francisco, it will pin the origin location to the closest segment to the point in the ocean, and treat that as the pseudo-origin.
This is troublesome when creating Hexbins, as it will include points from the ocean as valid Hexbin features, when they should be excluded from the routing.
Is there functionality or a flag to exclude this behavior in the Routing Service?

**Comment by danpat** [comment]
Try adding `radiuses=500;500` - this will limit the distance a point will be snapped to 500m.  It defaults to `unlimited`.

Also note that you can look in the response for the `waypoints` objects - they have a `.distance` property that describes how far the point was moved from the one supplied in the API request.  Instead of using *input* coordinates for determining hexbins, you could use `waypoints[].location` to determine which hexbin the route belongs to.

**Comment by JasonCromer** [comment]
Thanks for the insight @danpat. This works perfect. 
Will do, I'll check out the table service as well. I feel like your description should be added to the OSRM docs for `radiuses`, since its not super clear!
