### ISSUE TITLE
Why unit of weight/duration is 100ms? 

### ISSUE THREAD

**Issue by wangyoucao577** [Project-OSRM/osrm-backend#5400]
When I read code, I found that the unit of `weight/duration` seems `100ms` instead of `seconds`. 

I found below comments from code: 
https://github.com/Project-OSRM/osrm-backend/blob/e86d93760f51304940d55d62c0d47f15094d6712/include/util/typedefs.hpp#L81
`using TurnPenalty = std::int16_t; // turn penalty in 100ms units`

Also, I found a lot of hardcoded codes multiply `weight/duration` by `10`, e.g. 
https://github.com/Project-OSRM/osrm-backend/blob/e86d93760f51304940d55d62c0d47f15094d6712/src/extractor/graph_compressor.cpp#L253
```c++
                    node_duration_penalty = extraction_turn.duration * 10;
                    node_weight_penalty = extraction_turn.weight * weight_multiplier;
```

https://github.com/Project-OSRM/osrm-backend/blob/a1e5061799f1980c64be5afb8a9071d6c68d7164/src/extractor/extraction_containers.cpp#L397
```c++
            edge.weight = std::max<EdgeWeight>(1, std::round(segment.weight * weight_multiplier));
            edge.duration = std::max<EdgeWeight>(1, std::round(segment.duration * 10.));
```

I think use the `100ms` unit is a little strange. Why did this? 

Moreover, I wrote down a document [How OSRM Calculate Weight and Duration](https://github.com/Telenav/open-source-spec/blob/master/osrm/doc/how_osrm_calculate_weight_and_duration.md) when I reading codes. FYI. Please let me know if anything not correct, thanks!

**Comment by danpat** [comment]
@wangyoucao577 This is done because OSRM uses [fixed point arithmetic](https://en.wikipedia.org/wiki/Fixed-point_arithmetic) for duration and weight calculations.  

The decision to do it this way pre-dates my participation in the project, but if I had to guess, I'd say it was a performance choice - historically, integer math was faster than floating point math on most CPUs (although the reality of that on modern hardware is [complicated](https://stackoverflow.com/questions/2550281/floating-point-vs-integer-calculations-on-modern-hardware)).

I don't know that any deep justification for this choice has ever been given.  It would certainly be possible to use a `float` type instead, but it would likely come with a myriad of subtle changes to behaviour, due to floating point precision behaviour.  I cannot say whether the changes would be significant or not. 🤷‍♂️

**Comment by wangyoucao577** [comment]
Thanks @danpat for the quick reply. It makes sense due to historically chosen. Agree with no need to change to `float` by now. 
For the `multiply 10` part, especially for `duration * 10`, I think it'll be better to use macro/simple function instead. There're too many hardcodes in repo by now. I'll try to create PR when I have time.
