### ISSUE TITLE
Restrict uturns for `route` endpoint

### ISSUE THREAD

**Issue by ben-hudson** [Project-OSRM/osrm-backend#5423]
Is it possible to generate routes without u-turns using OSRM?

I understand the `continue_straight` parameter only applies to waypoints.

For example:
http://router.project-osrm.org/route/v1/driving/-73.71206,45.602297;-73.71094,45.601264?continue_straight=true

I would like to find a route between these points that does not have u-turns.

**Comment by danpat** [comment]
Due to the way OSRM builds it's routing graph, it doesn't see this route as two u-turns, but rather as 4 left hand turns.

There are several earlier tickets on this issue, but nobody has really had time to dive into it and come up with a reasonable fix yet.

https://github.com/Project-OSRM/osrm-backend/issues/4368

**Comment by ben-hudson** [comment]
Okay, thanks!

**Comment by ben-hudson** [comment]
Hi, I'd like to put together my own solution for this. Is it possible to penalize turns that are made in quick succession?

I'll be starting from the [truck profile](https://github.com/Project-OSRM/osrm-profiles-contrib/tree/master/5/21/truck-soft).

**Comment by danpat** [comment]
@ben-hudson Using the *current* routing algorithms in OSRM, no, it's not possible to penalize turns that are made in quick succession.  There is no simple change to the profiles you can make to achieve this.

In order to do it, you'd need to do one or more of the following:

  1. If using the CH algorithm, modify the contraction step to become aware of this kind of penalty - this would be a non-trivial change.
  2. Finish up the implementation of A* over on this branch https://github.com/Project-OSRM/osrm-backend/tree/algorihm/astar

Neither of these are particularly low-hanging fruit and will require some real development effort to get working properly.

**Comment by ben-hudson** [comment]
Thanks for your reply.
If I implemented A*, is the idea that  this allow me to write a heuristic that penalizes turns made in quick succession?

From #4366 what about using the same methods as in via-way restrictions to penalize u-turns? I'm less concerned about graph size for my application -- unless this approach would make it *really* large.

**Comment by danpat** [comment]
Yeah, the reasons that u-turn penalties aren't implemented is related to the multi-via-way turn restriction difficulty.

It's fairly straightforward to imagine and implement at query time (i.e. using A*), but you'd lose out on most of OSRM's performance by doing that.

In order to work with OSRMs "speedup graphs" (CH and MLD), one way to picture what needs to be done is that intersections need to get "expanded" so there is one distinct edge for each possible path through the intersection itself - you'd replace the internals of the intersection with a series of point-to-point direct edges.  The bigger the area you want to include in your "quick succession" radius, the more edges would need to be generated.  It could be quite large if you have several complex intersections close to each other.

**Comment by ben-hudson** [comment]
I like the idea of expanding the intersections. Would this happen in `osrm-extract` or `osrm-contract` or afterward?

I can imagine that for larger interchanges the graph size would increase a lot.

**Comment by danpat** [comment]
It would need to happen in `osrm-extract`, probably during the `edge_based_graph_factory`.

**Comment by ben-hudson** [comment]
For the A* approach, would the (simplest) flow be `osrm-extract` -> `osrm-routed --algorithm=AStar extracted.osrm`?

I'd like to experiment in Python. I found [this](https://github.com/Septima/Project-OSRM/wiki/OSRM-normalized-file-format) for the file format of the .osrm files. Which files are used by the router? Is the .osrm file enough, or are the other files (.names, .restrictions, etc.) also used?
