### ISSUE TITLE
Why OSRM implemented Contraction Hierarchies and MLD instead of A* or something?

### ISSUE THREAD

**Issue by rachha** [Project-OSRM/osrm-backend#5443]
I'm going through the OSRM implementation; they implemented routing algorithms CH and MLD. I wanted to know the motivation behind it to use these algorithms. This question not supposed to post here, but I didn't get any responses in [StackOverflow](https://stackoverflow.com/questions/55898305/why-osrm-implemented-contraction-hierarchies-and-mld-instead-of-a), so.

**Comment by danpat** [comment]
@rachha OSRM was originally build by @DennisOSRM, I believe alongside his research work into CH networks.  Initially, it *only* had a CH implementation.  Since then, many features have been added, including the MLD graph.  Nobody needed A*, so it was never added.  🤷‍♂ 

@TheMarex worked on a proof-of-concept A* implementation here - https://github.com/Project-OSRM/osrm-backend/tree/algorihm/astar, but it never made it into the mainline.
