### ISSUE TITLE
Routing via API (OSMAnd app)

### ISSUE THREAD

**Issue by mds08011** [Project-OSRM/osrm-backend#5461]
Can anyone help me understand why routing via the API is different than the routing I see on the demo website?

I use the Android app OSMAnd for driving navigation which uses the OSRM API for routing.  However, the route I see in the app seems like a very simplified version of what I see on the OSRM demo website despite using the same parameters.  For example, the OSRM demo website says “Take Exit 9 towards Main Street”, while OSMAnd states “turn slightly right” for the same action.

I wrote up an extensive [bug report](
https://github.com/osmandapp/Osmand/issues/6674) on OSMAnd’s repo replicating the issue on OSRM and OSMAnd.  The developer looked into it but could not find anything amiss: 

https://github.com/osmandapp/Osmand/issues/6674#issuecomment-473396670
> I checked the source code and it is also visible in the logs but URL is correct:
> https://router.project-osrm.org/route/v1/driving/
> So I have no idea why routing is different for API and the website

**Comment by danpat** [comment]
@mds08011 If the OSMAnd app is hitting the same API endpoint as the demo, then I'd suggest it's a problem with OSMAnd, and not with OSRM.  I'm going to close this ticket because there's nothing obvious to do on the OSRM side of things, but I'll chime in on that OSMAnd ticket - maybe the OSMAnd app isn't a) passing the correct URL parameters, or b) properly parsing the response.

**Comment by mds08011** [comment]
Thanks, I appreciate it!
