### ISSUE TITLE
compilation error

### ISSUE THREAD

**Issue by suresh-s** [Project-OSRM/osrm-backend#5480]
I am getting following error when i call make
[  0%] Building CXX object CMakeFiles/UTIL.dir/src/util/geojson_debug_policies.cpp.o

/usr/bin/locale:1:1: error: source file is not valid UTF-8

**Comment by riiaraj** [comment]
Has this issue been solved?

**Comment by suresh-s** [comment]
No.  This issue haven't been solved

**Comment by danpat** [comment]
A quick google search found https://stackoverflow.com/questions/62617618/usr-bin-locale-source-file-is-not-valid-utf-8

This seems to hint at an include-path problem on your system, which is leading to `/usr/bin/locale` somehow being included in your source code instead of the usual `/usr/include/locale.h`

Your original report was pretty slim on details, so nobody bothered to dig any deeper.  I do not know why `/usr/bin/locale` would be included on your system - have you been messing with `CPLUS_INCLUDE_PATH` environment variables or anything like that?  What platform are you on?  What compiler are you using?  These are likely key to understanding what's messed up on your system.

I don't think this is an OSRM-specific problem.  I would guess that the simple example program shown in the above link likely triggers a similar issue.
