### ISSUE TITLE
Error calculating nearest point

### ISSUE THREAD

**Issue by samani** [Project-OSRM/osrm-backend#5497]
Hello, i am using current master version with docker, when i want to test find nearest point to street, it is return a wrong point...
use file: **iran-latest.osm.pbf**

**Local test:**
http://localhost:5000/nearest/v1/car/32.634809552048196,51.66475413367153
**Web test:**
http://router.project-osrm.org/nearest/v1/car/32.634809552048196,51.66475413367153

Response local:
{"waypoints":[{"nodes":[1273121377,1273121322],"hint":"X5gGgOHCBoAAAAAAXwAAAAAAAAAKBwAAAAAAAKeJg0IAAAAAeamcRAAAAABfAAAAAAAAAAoHAABtAgCATH6oArQ7XwK69_EBclcUAwAAjwm7mvMa","distance":1614761.630971,"location":[44.596812,39.795636],"name":""}],"code":"Ok"}

Response Web:
{"waypoints":[{"nodes":[2276512235,2276512236],"hint":"aZE3inKRN4o8AAAA9QAAAFgOAAAAAAAATDdRQnY9UkOir0VFAAAAADwAAAD1AAAAWA4AAAAAAAD6qQAAmfzxAV9WFAO69_EBclcUAxIAfwwdU4oz","distance":91.52877070260675,"name":"","location":[32.636057,51.664479]}],"code":"Ok"}

My local return 1614761.630971 and https://router.project-osrm.org return 91.52877070260675
Note: 91.52877070260675 is the right answer!
my local return a very distant point

**Comment by danpat** [comment]
OSRM takes coordinates in longitude,latitude order in the URL - it looks like you have them reversed, as latitude,longitude.

lon,lat = 32.634,51.664

is somewhere in northern Ukraine.

The reason the OSRM demoserver returns 91.5 m is because we support the map globally, and can snap to roads in Ukraine.  Because your own server only has Iran data, it is 1614km to the nearest road that OSRM knows about.
