### ISSUE TITLE
Unexplainable detour in routing result

### ISSUE THREAD

**Issue by RhinoDevel** [Project-OSRM/osrm-backend#5504]
This:

http://map.project-osrm.org/?z=16&center=54.456256%2C9.334409&loc=54.455633%2C9.332608&loc=54.456667%2C9.330570&loc=54.458918%2C9.340814&hl=en&alt=0

Shows a detour to the west after the second stop.

This does not happen in (e.g.) GoogleMaps and there is no turn restriction
(I took a look with OpenStreetMap Editor: https://www.openstreetmap.org/edit?editor=id&relation=1156157#map=16/54.4566/9.3328).

In addition, if I remove the last stop, there is no detour.

API call:

https://router.project-osrm.org/route/v1/driving/9.332608,54.4556326;9.33057,54.4566672;9.3408144,54.458918?overview=false&alternatives=true&steps=true&hints=Y48Sh26PEofXAAAAAAAAAAAAAAAvAAAAPLknQgAAAAAAAAAAa7ASQdcAAAAAAAAAAAAAAC8AAADCqgAAgGeOAFHtPgOAZ44AUe0-AwAA7wVm15qL;C48Sh0v4AoA6AAAAAAAAAEcAAAB_AAAAcSZ8QgAAAAB1OJpCm7YJQzoAAAAAAAAARwAAAH8AAADCqgAAil-OAFvxPgOKX44AW_E-AwIAbwRm15qL;Jz0Zh1c9GYcAAAAAmAMAAOkDAAAAAAAAAAAAAKKpzEKcod5CAAAAAAAAAACYAwAA6QMAAAAAAADCqgAAjoeOACb6PgOOh44AJvo-AwEALwtm15qL

**Comment by danpat** [comment]
By default, the `car` profile (which the demoserver exposes), has `continue_straight=true` enabled for waypoints.  Because your middle waypoint is in the middle of an uninterrupted road, OSRM won't suggest you do a u-turn at that location.  Instead, it continues past the waypoint and finds a spot where it can do a u-turn.

If you add `&continue_straight=false` to your API call URL, the route won't do the detour and will u-turn at the middle waypoint.

**Comment by RhinoDevel** [comment]
@danpat: Thanks for the explanation!
