### ISSUE TITLE
OSRM first suggested route is longer and slower than the second one

### ISSUE THREAD

**Issue by safe-bug** [Project-OSRM/osrm-backend#5506]
Hello,
I have a problem with OSRM routes. Sometimes when I get a route, the first suggested route is longer (distance) and slower (time) than the second one, why OSRM do that? The first one should be a better one. 
This is an example on the demo map:

https://map.project-osrm.org/?z=13&center=38.910203%2C-77.005148&loc=38.913075%2C-76.951675&loc=38.928701%2C-77.057762&hl=en&alt=0

![Screenshot from 2019-08-03 15-42-41](https://user-images.githubusercontent.com/5261029/62411309-277be200-b606-11e9-8193-482d42befa0c.png)
![Screenshot from 2019-08-03 15-42-50](https://user-images.githubusercontent.com/5261029/62411310-277be200-b606-11e9-9991-ed37ed92c4be.png)

**Comment by rdvelazquez** [comment]
Speaking in rough, untechnical terms: 
- OSRM calculates the preferred route based on the _weight_ * distance of each road/turn and
- OSRM calculates the travel time based on the _speed_ * distance for each road/turn. 

The weight and speed of roads are typically proportional but they are not necessarily the same. A route that is slightly longer (in both distance and travel time) may be selected by OSRM over a shorter route because the longer route involves less turns and more highway driving. I think that is the case with the example that you are showing above.

Obviously, one of the OSRM core developers could explain this a lot better but I just thought I'd provide a brief reply as this issue's been open for a while.
