### ISSUE TITLE
Osrm routing response returns long distances

### ISSUE THREAD

**Issue by skthon** [Project-OSRM/osrm-backend#5521]
I am trying to get the route distance between two coordinates which are just 3.5kms away from each other. (38.905594437419346,-75.87934669114266) & (38.8964389684041,-75.84294618114441)

Osrm route api chooses a different road instead of the highway and it returns distance as 14kms. 
But when i interchange the starting and destination points it gives the correct distance and routes through the highway road.

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=38.9146%2C-75.8933%3B38.8970%2C-75.8559#map=14/38.9194/-75.8660

**Comment by danpat** [comment]
The south-east bound lane there has `construction=trunk` - by default, OSRM won't route over construction zones.

It could be argued that OSRM *should* route over `highway=trunk, construction=trunk` because it's not marked as `highway=construction`, but the tagging scheme isn't super clear hear about whether vehicles are permitted in these construction zones or not.  OSRM errs on the side of caution and tries not to route people down roads that may not be accessible.
