### ISSUE TITLE
CORS is blocking request

### ISSUE THREAD

**Issue by truebaj** [Project-OSRM/osrm-backend#5537]
Hi,

We have deployed osrm-backend and osrm-frontend in docker following your instructions.
We are testing and server fails when we make two request in an interval of 5 seconds. If we make request with a delay of 6 seconds request works fine but if we make request more frequently (less than 5 seconds between request) we get this responses:

Access to fetch at 'http://127.0.0.1:5000/nearest/v1/driving/-3.8779163360595694,43.4592739663795' from origin 'null' has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header contains multiple values '*, *', but only one is allowed. Have the server send the header with a valid value, or, if an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled. 

GET http://127.0.0.1:5000/nearest/v1/driving/-3.8779163360595694,43.4592739663795 net::ERR_CONTENT_DECODING_FAILED 200 (OK) 

Uncaught (in promise) TypeError: Failed to fetch 

We haven't seen anything about this on issues and wiki. Anyone can help me?

**Comment by danpat** [comment]
This sounds like you have some kind of bizarre kind of client-side request handling bug.

OSRM only sets a single hard-coded value `Access-Control-Allow-Origin`, here:

https://github.com/Project-OSRM/osrm-backend/blob/f1a4b70a5638decfa08fdd460a8da63c6e38796c/src/server/request_handler.cpp#L101

 so I don't know how it's possible for your client to be seeing `*, *` as the value for this header.  I don't think the bug lies within the `osrm-backend` code anywhere.
