### ISSUE TITLE
Route made by OSRM use not optimal detour

### ISSUE THREAD

**Issue by Puchaczov** [Project-OSRM/osrm-backend#5587]
From: `Dąbrówki, Maroko, Maroko­‑Nowiny, Rybnik, Silesian Voivodeship, 44-210, Poland`
To: `Tenneco Automotive Eastern Europe Sp. z o.o., Ligota Zabrska, Gliwice, Górnośląsko-Zagłębiowska Metropolia, Silesian Voivodeship, Poland`

Observable at page `http://map.project-osrm.org`, use those two addresses above. 

![RouteOSRM](https://user-images.githubusercontent.com/6973258/67848696-7225d100-fb05-11e9-8692-a99cb5455287.png)
 
OSRM chose to leave `Rybnicka` route (DK 78) and go through Gliwice through Żarnica (Zernitz). On the other hand Google looks to be better here and leads through DK 78.

It should leads through DK 78 as it's more optimal.

**Comment by danpat** [comment]
There appears to be a very small section with a problem here:

<img width="682" alt="Screen Shot 2019-10-30 at 7 36 50 AM" src="https://user-images.githubusercontent.com/1892250/67867723-113bd000-fae8-11e9-95d8-11335fbba928.png">

**Comment by danpat** [comment]
The problem appears to be these two restriction relations:

https://www.openstreetmap.org/relation/8368239

I'm not sure I even understand the mapper's intent here - but regardless, the way this is mapped basically forbids north-east bound travel at this node.

I think this restriction should be removed.

I'd also be tempted to suggest that https://www.openstreetmap.org/relation/8368240 be replaced with a `no_left_turn` restriction onto the sliproad, rather than using an `only_` type.

**Comment by Puchaczov** [comment]
Thank, I have already modified OSM metadatas so they reflect the ability to go straigth.
