### ISSUE TITLE
Distance matrix in C# with Osrm

### ISSUE THREAD

**Issue by Shira-Cohen** [Project-OSRM/osrm-backend#5625]
I want to use osrm library to calculate the time matrix. How can I do it in dot.net? Which package do I need to download? and how do I combine some maps for it? I didn't find any example that explains it

**Comment by danpat** [comment]
I'm not a C# developer, but from what I can see, you basically have two options:

  1. Write C# wrapper around OSRM C++ library interface.  This SO question mentions a thing called `DllImport`: https://stackoverflow.com/questions/2958416/call-c-library-from-c-sharp that I'm not familiar with.

  2. Run OSRM as a separate process, and interact with it over the HTTP interface

We don't ship a C# managed library interface that you can use directly.

**Comment by Shira-Cohen** [comment]
thank to your answer,
but I didn't succeed to use OSRM in C++,
there is no package in NuGet and also I didn't succeed to use it like a reference to a project
I know how to use it with docker, but not in C++
I would appreciate any help or explaination how to do it.

**Comment by danpat** [comment]
OSRM is a C++ project.  Unless you're willing to contribute C# language bindings and a NuGet package configuration, I'm not sure there's much we can do to help.

There are some outdated instructions for building OSRM on Windows here https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation, but to be honest, not that many people are using Windows with it, so getting help is a bit difficult.

I would suggest if you can't get the C++ interface working, you should use a HTTP client from your C# code and interact with a separate Docker container running the `osrm-routed` HTTP process.

**Comment by sheldonreddy** [comment]
@danpat just to provide further information in respect of the instructions for building OSRM on windows [Found here](https://github.com/Project-OSRM/osrm-backend/wiki/Windows-Compilation,) - It still works as off 1 week ago.

@Shira-Cohen in order to perform your desired operation, I would suggest running OSRM within a docker container with the latest available Docker image from Docker Hub. Then create an application in C# which queries the OSRM Docker Instance with coordinate pairs and use the response to build your Distance-Time matrix.
