### ISSUE TITLE
can't extract indonesia-latest.osm.pdf in docker

### ISSUE THREAD

**Issue by shekkoirala** [Project-OSRM/osrm-backend#5659]
After running: 
docker run -t -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/indonesia-latest.osm.pbf

It stops after this with no error 

[info]   motorcar
[info]   motor_vehicle
[info]   vehicle
[info] Parse relations ...
[info] Parse ways and nodes ...
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4
[info] Using profile api version 4

**Comment by danpat** [comment]
You're probably running out of RAM - the docker system logs almost certainly have an "OOM Killer" message.

Try increasing the amount of memory that the container is allowed to use - for Indonesia, I suspect you'll need 16+GB at least.

**Comment by shekkoirala** [comment]
should i increase the memory of the container when running? like this using -=16g

docker run -t -m=16g -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/indonesia-latest.osm.pbf


and also, i was able to extract the file in another server but the problem is, it is not extracting certain files like .osrm.datasource_names, .osrm.cell_metrics, etc  4, 5 files are missing in extracting. Whats the issue here?

**Comment by EltonRst** [comment]
I was having the same problem when extracting the map of Brazil, the problem was really lack of memory. I dedicated 9GB to the extraction and apparently it worked.

`docker run -t -m=9g -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/brazil-latest.osm.pbf`

Thank's for the tips !

**Comment by EltonRst** [comment]
I had the same problem when extracting the map of Brazil, the problem was really lack of memory. I dedicated 22GB and 24 Cores to the extraction and it worked.

`docker run -t -m=22g -v "${PWD}:/data" osrm/osrm-backend osrm-extract -p /opt/car.lua /data/brazil-latest.osm.pbf`

The size of the brazil-latest.osm.pbf file is similar to indonesia-latest.osm.pbf so it should work.

Thank you for the tips !
