### ISSUE TITLE
Match service: gaps despite clean gps trace (probably map problem)

### ISSUE THREAD

**Issue by JackCaster** [Project-OSRM/osrm-backend#5669]
I collected some GPS coordinates when driving around Boston. The match service recovered the path almost perfectly, except in two segments. 
![image](https://user-images.githubusercontent.com/18400141/74173121-88acef80-4bff-11ea-85da-b53819b34b92.png)
I downloaded the maps from Geofabrik so I checked whether there was an error in the map, but it [does not look so](http://tools.geofabrik.de/map/#17/42.3623/-71.0764&type=Geofabrik_Standard); the path is connected:
![image](https://user-images.githubusercontent.com/18400141/74173318-ee997700-4bff-11ea-9213-8cba4b564cb8.png)
The only map that shows that the road is not connected is the [OSM FR Hot](https://mc.bbbike.org/mc/?num=2&mt0=mapnik&mt1=osmfr-hot):
![image](https://user-images.githubusercontent.com/18400141/74173490-2d2f3180-4c00-11ea-9e31-4ef14c038274.png)
This would explain the gaps in my match. But I do not think that map is included in the Geofabrik massachusetts-latest.osrm map (v. Feb 2020, [link](http://download.geofabrik.de/north-america.html))

Do you know what is causing the gaps in the match? How can I go about debugging the problem?

I am running osrm-routed (v5.22.0) from the official docker image using the massachusetts-latest.osrm map (v. Feb 2020) and the MLD algorithm.

**Comment by danpat** [comment]
The problem is the `construction=trunk` tag there - by default, OSRM will exclude roads like that from routing.

https://github.com/Project-OSRM/osrm-backend/blob/714719c3776c5985a8881cba32f48f8a4de5a70a/profiles/lib/way_handlers.lua#L640-L647

I would recommend you comment out this line for map-matching scenarios:

https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L136

If you have a GPS trace that traverses a construction zone, we don't want a *routing* decision to cause the match to fail.

**Comment by JackCaster** [comment]
Awesome! Good catch, it worked:
![image](https://user-images.githubusercontent.com/18400141/74177396-a1b99e80-4c07-11ea-8327-42419c276532.png)
Are there other tweaks in car.lua that I can make to improve the match post-hoc, that is, after I collected the GPS trace? I see there are some penalties for traffic lights and such, for example.
