### ISSUE TITLE
find_package cannot find Boost

### ISSUE THREAD

**Issue by Mohammadabd** [Project-OSRM/osrm-backend#5687]
I have built osrm-backend successfully on my mac machine, but when CMake example I get multiple warning related to boost such as 
```
Target "osrm-example" links to target "Boost::regex" but the target was not found.  Perhaps a find_package() call is missing for an IMPORTED target, or an ALIAS target is missing?
```
and then when running build it throws error and fails

```
ld: library not found for -lBoost::regex
```
How to get around this issue? I have boost already installed. Thanks
```
ls /usr/local/Cellar/boost/
1.72.0
```

**Comment by Mohammadabd** [comment]
FIX:
in `./example/CMakeLists.txt` add 
`find_package(Boost 1.52.0 COMPONENTS filesystem system thread iostreams chrono date_time regex REQUIRED)`

**Comment by mjjbell** [comment]
This is happening because [FindBoost](https://cmake.org/cmake/help/latest/module/FindBoost.html) changed (I think in cmake `v3.11`) to use [Imported Targets](https://cmake.org/cmake/help/latest/guide/importing-exporting/index.html) for library component variables, rather than file paths to the Boost libraries.

`cmake` uses these targets when linking (e.g. `target_link_library`) and knows how to correctly substitute the values. However, the OSRM pkg-config file that we generate doesn't do this, and ends up writing the actual target symbols, hence the errors trying to link `Boost::<component>`

The example works when OSRM is built with older versions of cmake (CI is using `3.7.2`) as you get the old behaviour of writing file paths to `libosrm.pc`.

To fix this for newer cmake versions, I think we need to add a `file(GENERATE...` step to the [pkg-config creation](https://github.com/Project-OSRM/osrm-backend/blob/master/CMakeLists.txt#L807), which has the information needed to make the imported target substitutions, as suggested here:  https://cmake.org/pipermail/cmake/2018-December/068812.html
