### ISSUE TITLE
[Question] Why there is no scale_factor for route service?

### ISSUE THREAD

**Issue by ifle** [Project-OSRM/osrm-backend#5698]
Why there is no scale_factor for route service?

**Comment by danpat** [comment]
Because nobody has written that code yet.

The scale factor is provided as a convenience on the table service because for large results (millions or billions of entries), it saves the caller from doing an iteration over the results themselves.

For the route service, there are only a handful of numbers to scale - so nobody has bothered implementing the feature.

**Comment by ifle** [comment]
How to use both table and route services in case of using of scale_factor parameter?

**Comment by danpat** [comment]
I mean, it's just a simple multiplication - you can just multiply all the route service time values by your scale factor in your own code.

**Comment by ifle** [comment]
I see. Thanks

**Comment by SiarheiFedartsou** [comment]
Stale.
