### ISSUE TITLE
Wrong routing?

### ISSUE THREAD

**Issue by P-mir** [Project-OSRM/osrm-backend#5727]
I use the routing service to find the path between two points but the path found seems incorrect.

here is a plot of the initial points and the resulting points after passing them to the OSRM API:
https://imgur.com/a/9VOujEs

As you can see it should be trivial to link the two points, but OSRM proposes to do a round trip, which is quite strange. I tried to change the order of the point but the result is identical.

Here is a minimal example in python to reproduce the query :

```
import requests
r = requests.get('http://router.project-osrm.org/route/v1/driving/' + '4.266815,50.878032;4.257543,50.879889' + '?continue_straight=false&annotations=true&overview=full', params={"geometries":"geojson"})
infos = r.json()
response = infos['routes'][0]['geometry']['coordinates']
print(response)
```

Is it bug that should be fixed?

**Comment by danpat** [comment]
You need to do two things:

  1. Swap the points - you've got the east-most point first, which makes it the start point.
  2. The west-most point is past the off-ramp:

<img width="710" alt="Screen Shot 2020-04-29 at 7 19 50 am" src="https://user-images.githubusercontent.com/1892250/80607091-ec1e1080-89e9-11ea-8c4d-e3872c574fe1.png">

  Because the motorways are oneway, there's no other option than to do the long round-trip.  You've essentially missed the exit that would make the route trivial, and you have to go the long way instead.

  If you want the route selection to be a bit more fuzzy in this kind of scenario (i.e. try a few of the other nearby potential start points, assuming the GPS position has some error), you can try using the `/match` service instead.  It should work for this scenario.

**Comment by P-mir** [comment]
I looked at the west-most point in google Map and there there the truck did not passed the intersection yet, same when I plot the point using leaflet (my previous link). Could it be that the OSRM map is not up to date?

https://www.google.com/maps/place/50%C2%B052'47.6%22N+4%C2%B015'27.2%22E/@50.8790733,4.2589431,17.88z/data=!4m5!3m4!1s0x0:0x0!8m2!3d50.879889!4d4.257543

**Comment by danpat** [comment]
The OSRM map at router.project-osrm.org is at most a couple of days old from OpenStreetMap.  Here's a screenshot of what the router currently thinks the geometry looks like at this location:

<img width="937" alt="Screen Shot 2020-04-29 at 3 47 40 pm" src="https://user-images.githubusercontent.com/1892250/80654354-e1d33500-8a30-11ea-8e60-4685874deff2.png">

You might want to check OpenStreetMap and see if the location the road splits is mapped properly.

**Comment by P-mir** [comment]
OK, thank you for your answers, it's very helpful.
