### ISSUE TITLE
Search & Replace Maxspeed-value in OSM-file

### ISSUE THREAD

**Issue by MoodyJerup** [Project-OSRM/osrm-backend#5765]
Hello,

I want to make alter all the max-speed tags in an OSM-file to match truck-speedlimits.

Is there a way to open an OSM file and search & replace for instance alle the maxspeed-values?

**Comment by nilsnolde** [comment]
It's a little random to ask this here, I'd recommend a more general forum, like https://gis.stackexchange.com. 

Don't think any generic OSM software caters for custom stuff like that. Since there's no use case in public OSM data. And it might sorta violate their license, at least if you publish the changed (or corrupted? ;)) data in any way, so be careful.

As for a solution, you could probably write fancy bash pipelines or just resort to the power of osmium's bindings and use e.g. Python to read the PBF and write it again, only altering the `maxspeed` tag.

**Comment by danpat** [comment]
I would also suggest that just doing the tagging in OSM itself with `maxspeed:truck` (https://wiki.openstreetmap.org/wiki/Key:maxspeed#Vehicles).  You can them modify the OSRM `car.lua` profile to look for the `maxspeed:truck` tag instead of plain `maxspeed`.

**Comment by MoodyJerup** [comment]
Thanks both of you. Good answers.
Danpat, I have tried to alter the car.lua man times without any luck. I can only decrease the speed by changing speed-reduction from 0.8 to 0.6.

Can you show an example of how I make use of the maxspeed:truck tag?
