### ISSUE TITLE
Using non-OSM maps like HERE streets Shapefile with OSRM

### ISSUE THREAD

**Issue by bklis** [Project-OSRM/osrm-backend#5780]
Hi,
Wondering if anyone had a chance converting non-OSM maps with OSRM? 

We're currently trying to convert Shapefile from HERE Streets data using number of libraries: ogr2osm, osmosis, osmconvert, osrm-extract and osrm-contract.

Below is the process that we're following: 
HERE Streets.shp -> ogr2osm -> osmosis -> osmconvert -> osrm-extract with car.lua -> osrm-contract -> compress (.tar.gz) -> OSRM Server

We feel we are close to being able to make it work with HERE data, but really need some help to get over the last hurdle as we’re currently having some problems while running osrm-extract command:
![Capture](https://user-images.githubusercontent.com/68376053/87663052-2088a980-c75b-11ea-8638-1b2f8ae91b68.PNG)

We believe that something must have gone wrong while running osmosis part that could have generated incorrect Streets.osm file from original shapefile, which might be the reason for osrm-extract command error? Has anyone came across similar error or can advise from the log file what has gone wrong? Any suggestions would be much appreciated. Thanks

**Comment by nilsnolde** [comment]
#shamelessplug

We solved this a while ago and offer commercial services to convert HERE/TomTom street networks to OSM, including (turn) restrictions/speeds etc. I won't put the link here, but you can reach me on nils@gis-ops.com.

**Comment by danpat** [comment]
@bklis The issue is that your converted OSM file has no tags that the `car.lua` script recognizes.

What you need to do is not just convert shape/geometry into OSM _format_, but you need to ensure that the HERE road properties are converged into their OSM equivalents (things like `highway=motorway`, etc).  None of the tools you're using will do that for you.  They may place *HERE* properties in the OSM format, like `FRC=0`, but OSRM doesn't understand those.

The error at the end "There are no edges remaining after parsing" indicates that OSRM didn't find any ways with recognizable tags.

You have two options:
  - add a step that knows how to map the HERE road properties into OSM recognizable tags, or
  - re-write `car.lua` so that it uses the HERE tags that are generated by your pipeline
