### ISSUE TITLE
Wrong instructions are generated for incomplete roundabouts

### ISSUE THREAD

**Issue by safe-bug** [Project-OSRM/osrm-backend#5805]
Hello
I have an issue with the instructions that are generated for incomplete roundabouts, although it has the tag "junction=roundabout" but it just generates "turn right/left" instructions.[ This is an example of the issue ](http://map.project-osrm.org/?z=18&center=35.767162%2C51.476615&loc=35.766372%2C51.476226&loc=35.768313%2C51.473790&hl=en&alt=0&srv=0)

How can I fix it?

**Comment by danpat** [comment]
I believe (but I'm not 100%, I don't have time to go digging in the code), that roundabouts need to form a complete loop in order to be properly recognized as roundabouts by OSRM.  OSRM needs to be able to estimate the radius.

<img width="584" alt="Screen Shot 2020-08-19 at 6 26 02 AM" src="https://user-images.githubusercontent.com/1892250/90640492-e3de2100-e1e4-11ea-89b1-0500acf13732.png">

The mapping here is bad - the south side of the traffic island is not connected, so it doesn't form a circle.

**Comment by safe-bug** [comment]
@danpat Thanks for your reply. I've changed the exits and the roundabout shape into a normal roundabout but the result is the same.
