### ISSUE TITLE
passing more coordinates then supported by the url

### ISSUE THREAD

**Issue by knownasilya** [Project-OSRM/osrm-backend#5806]
At the moment APIs like http://project-osrm.org/docs/v5.22.0/api/#table-service use the url and GET to pass the coordinates to create a distance/duration matrix, but the URL has a hard/varied limit across browsers. A better approach would be to allow a POST request with a JSON body like `{ "coordinates": [...] }` to make a request.

**Comment by Shkarface** [comment]
You can encode the coordinate pairs using the [encoded polyline](https://developers.google.com/maps/documentation/utilities/polylinealgorithm) so instead of `?[lng lat]` you send in `?`polyline(ENCODED)`

I think body parsing is not implemented in the core c++ http server, and it's not worth the hassle since you can just use the node bindings and write an api around it.
