### ISSUE TITLE
Updating OSRM

### ISSUE THREAD

**Issue by SoulExtinction** [Project-OSRM/osrm-backend#5808]
Hi,

Not an issue, but wanted to know if OSRM is having an update feature? I have installed OSRM via docker. But I need the map data to be up to date. So is there any setup for this? If yes, please guide me with an URL or something.

**Comment by wangyoucao577** [comment]
By contrast to the engine only docker, we did a little more in our [fork](https://github.com/Telenav/osrm-backend):        
- osrm-backend docker image with binaries and scripts;    
- compile map data in container, then export compiled data;   
- osrm-backend-within-mapdata docker image that package binaries, scripts and data together, so that you're able to launch it by one command;    
- Github actions to pipeline build and compile data together.    

Refer to https://github.com/Telenav/osrm-backend/tree/master/docker-orchestration and https://github.com/Telenav/osrm-backend/blob/master/.github/workflows/autobuild-osrm-backend.yml for more details.    

With above, you can create your own pipeline: build docker image from source code, compile latest data with latest engine docker, deploy the new engine/data in your deployment env.       
Then what you only need to is run the pipeline to update engine/data.
