### ISSUE TITLE
Trip service does not respect 'continue_straight_at_waypoint' setting

### ISSUE THREAD

**Issue by murphy-paul** [Project-OSRM/osrm-backend#5842]
Hi,

I have recently started to work with the Trip Service in OSRM and noticed that the calculated route is making u-turns at some undesired locations. Reading the documentation I noticed that 'continue_straight' parameter is only available for the route service. I tried to change the setting 'continue_straight_at_waypoint' in the profile (car.lua) but this did not work.

Is there anyway to have the trip service respect the `continue_straight_at_waypoint`?

Thanks for advance for any info.

![trip_vs_route](https://user-images.githubusercontent.com/1569533/94569991-3db31b80-0266-11eb-8066-135a1a42c6c4.png)

Example requests

[info] 29-09-2020 14:13:21 4.36803ms 172.17.0.1 http://localhost:3000/ Mozilla/5.0(X11;Linuxx86_64)AppleWebKit/537.36(KHTML,likeGecko)Chrome/85.0.4183.83Safari/537.36 200 /route/v1/driving/-7.71001,52.36323;-7.70854,52.36389;-7.71382,52.36413?overview=full&steps=true
[info] 29-09-2020 14:13:21 28.3561ms 172.17.0.1 http://localhost:3000/ Mozilla/5.0(X11;Linuxx86_64)AppleWebKit/537.36(KHTML,likeGecko)Chrome/85.0.4183.83Safari/537.36 200 /trip/v1/driving/-7.71001,52.36323;-7.70854,52.36389;-7.71382,52.36413?overview=full&steps=true

**Comment by danpat** [comment]
Not without a bunch of work.  The main issue is that the optimizer just uses simple A->B distances.  However, in reality, for most waypoints, you can depart/arrive from at least 2 directions.  Our solver doesn't consider these options.

What you can do is take the *order* returned by the `trips` service, then re-submit the waypoints in that order to the `route` service and add the `continue_straight` option there.

Because the order wasn't calculated considering approach/departure direction, the route you get once you apply `continue_straight` may no longer be the best ordering.

**Comment by murphy-paul** [comment]
Thanks for the timely response @danpat .
