### ISSUE TITLE
Lite version of OSRM instance

### ISSUE THREAD

**Issue by KushnirDV** [Project-OSRM/osrm-backend#5879]
Is it possible to disable some not used data to get more lite (less size at least 2 times) OSRM instance? 
We use only rute and nearest API services. The reasson is to boot two backend OSRM entities on our server. 
Will thankful for your answer.

**Comment by akashihi** [comment]
I guess you are asking if you can decrease dataset size?

**Comment by jcoupey** [comment]
Related to #5838 (scoped more specifically on potentially removing the guidance dataset).

**Comment by danpat** [comment]
@KushnirDV if you use `steps=true` in your Route API response, then *all* the data is used.

There are some files generated during `osrm-extract` that can be deleted, but I don't have a handy list.  One way to get the actual list of used files is to use `strace` and look for `open()` syscalls to get all the filenames that are used by routing.

If the issue is *memory* consumption, then you can use the `--mmap` option to lazy-load data from disk.  If you perform a warmup routine with a typical set of queries, this can help you use just the minimum RAM needed for fast queries.

**Comment by KushnirDV** [comment]
You are doing a realy good job.
I will compile OSRM version higher than 5.20 to be able to use --mmap and will start generetion a new routing.

The main reason to have two instance is possibility to switch bettwen routing with higway and without.
Thanks for fast and helpfull support.
