### ISSUE TITLE
Shortest path between two OSM nodes

### ISSUE THREAD

**Issue by HumamHelfawi** [Project-OSRM/osrm-backend#5886]
I want to compute shortest path between OSM node [1765878706 ](https://www.openstreetmap.org/node/1765878706)& [1765878672](https://www.openstreetmap.org/node/1765878672). Using OSRM, I am getting this result:
![image](https://user-images.githubusercontent.com/28831420/99570936-b8d1bc00-29e3-11eb-97f2-681bc935aa88.png)

Why the shortest path was not simply like this:
![image](https://user-images.githubusercontent.com/28831420/99571657-a3a95d00-29e4-11eb-8851-86747cbec554.png)

Any hint is much appreciated.

**Comment by danpat** [comment]
You're seeing a manifestation of https://github.com/Project-OSRM/osrm-backend/issues/4465

When you supply a coordinate that is equidistant from several edges, the one chosen to start the route on will be somewhat random.

When there are one-ways involved, this may force a seemingly unnecessary detour, as in your case.  The edge being chosen is the south-bound one, and there is no other way to go.

There are two possible fixes here:

  1. You workaround the issue by slightly moving your start coordinate in the desired direction, or by using the `bearings=` parameter to filter out the southbound candidates.  This can be done on a case-by-case basis, but isn't easy to do for the general case.
  2. Someone implements multi-start routing in our core routing algorithms, so that all equidistant snapping points are considered as starting candidates.  This is a much larger effort.

**Comment by SiarheiFedartsou** [comment]
Point 2 seems to be implemented in https://github.com/Project-OSRM/osrm-backend/pull/5953
