### ISSUE TITLE
oneway tag prevents correct routing from nearest available street

### ISSUE THREAD

**Issue by LordSnyder** [Project-OSRM/osrm-backend#5888]
Dear community,

we are trying to use the osrm router for indoor routing purposes and we are struggeling with an issue about picking up the nearest street for routing. The screenshot illustrate the problem:

![givenSelNode](https://user-images.githubusercontent.com/28800988/99646113-5f53a680-2a50-11eb-8f6f-78fe2a8dde7f.png)

The route starts at the start point of the oneway route (EW_N2_Aus), where the drawing of the road is in a correct direction so this should be not the problem.
Then I get this route here:  
Waypoint	Lat.	Long.	Duration	DistanceWaypointNames
FW_NOR_A_8	53.5797	8.55573	3.6	18.7
EW_N3_3	53.5799	8.55557	17.7	123.6

If I remove the oneway tag, this route is then correctly recognised:

Waypoint	Lat.	Long.	Duration	DistanceWaypointNames
EW_N2_Aus	53.5797	8.55573	7.9	6.3
FW_NOR_A_8	53.5797	8.55571	4.3	23.8
EW_N3_3	53.5799	8.55557	17.7	123.6

From the source code I obtain the conclusion that the phantom nodes are changed, which is done in include/engine/geospatial_query.hpp 
`GeospatialQuery::NearestPhantomNodeWithAlternativeFromBigComponent(const util::Coordinate input_coordinate,
                                                      const double max_distance,
                                                      const Approach approach,
                                                      const bool use_all_edges) const`
but instead of taking the correct location (53.579744, 8.555730) it switches to 53.579731, 8.555676).

I also attached a minimal OSM map example that this shall be reproducible: 
[Karte_minExample.zip](https://github.com/Project-OSRM/osrm-backend/files/5565780/Karte_minExample.zip)

Thank you for your suggestions and ideas.

**Comment by NguyenSen** [comment]
@danpat can you help him

**Comment by danpat** [comment]
If the map is just like the image, then the oneway road is not [strongly connected](https://en.wikipedia.org/wiki/Strongly_connected_component)  - there is no way to get _onto_ that oneway from anywhere else.

Because of this, OSRM treats it like an isolated island, and our snapping logic will move the origin point until it can be sure it's on the same network as the destination point.

I would call this bad map data - your oneway is impossible in the real world, there must be a way to get onto it.

(also as a side note - the negative ID values in your example `.osm.xml` file aren't well supported - you should change those to be positive to avoid issues).
