### ISSUE TITLE
matching restricted roads

### ISSUE THREAD

**Issue by zehavi11** [Project-OSRM/osrm-backend#5916]
Hi,
I need to find the exact way that someone was driving even if it was illegal. for example:
![image](https://user-images.githubusercontent.com/72856831/102330062-c8680480-3f91-11eb-9e0d-7c01049d7bc6.png)
and the route I get is different probably because OSRM knows that there is a one way road along the route:
![image](https://user-images.githubusercontent.com/72856831/102330175-e7ff2d00-3f91-11eb-831d-0d773b7a07ec.png)

can I somehow tell OSRM to ignore road restrictions?

**Comment by frodrigo** [comment]
No, you cannot use the same profile but ignoring global restrictions (one way, foot only...). But you can match gain foot profile to access all the network. The car matching on foot network will be of lower quality, as restriction help on matching.

**Comment by VersusF** [comment]
Hello, I'm having the same problem, using the match service with foot profile it does not ignore the `oneway` tag, creating improbable paths. Here is a simple example, where the first line is made of the GPS points, the second one is the result of the match algorithm.
```
MULTILINESTRING(
(10.990341 45.41752500000001,10.989932999999999 45.417653,10.988913999999998 45.41785999999999,10.988291999999998 45.418079000000006,10.987321 45.418251999999995,10.986397999999998 45.41855699999999,10.98592 45.41858000000002),
(10.990335 45.41752700000001,10.990194000000002 45.41728499999999,10.989852 45.417382,10.989993 45.41761600000001,10.990339000000002 45.41753299999999,10.988994000000002 45.41522999999998,10.987688 45.415639,10.988076999999999 45.416346000000004,10.988988 45.417839000000015,10.989624 45.418274999999994,10.988754 45.41894500000001,10.988356 45.418699000000004,10.986870000000001 45.41838299999998,10.988272000000002 45.418037999999996,10.988999000000002 45.417858999999964,10.989624 45.418274999999994,10.988754 45.41894500000001,10.988356 45.418699000000004,10.986870000000001 45.41838299999998,10.98733 45.41827000000001,10.988999000000002 45.417858999999964,10.989624 45.418274999999994,10.988754 45.41894500000001,10.988356 45.418699000000004,10.986870000000001 45.41838299999998,10.986367 45.418487999999996,10.985922 45.41858500000001)
)
```

which can be tested on [wkt-playground](https://clydedacruz.github.io/openstreetmap-wkt-playground/).

The request to get the path is the following:
`/match/v1/foot/10.990341,45.417525;10.989933,45.417653;10.988914,45.41786;10.988292,45.418079;10.987321,45.418252;10.986398,45.418557;10.98592,45.41858?overview=simplified&annotations=nodes&geometries=geojson`

Gps points: 
![image](https://user-images.githubusercontent.com/31687181/168038292-7c4c0bf1-bea5-47b8-9c3f-ce5c8746fcad.png)

Computed path:
![image](https://user-images.githubusercontent.com/31687181/168038463-228eb29c-54c2-4526-a3e2-a96eb25bc1fb.png)

I'm using the foot profile because my ultimate goal is to detect if a bike or an electric scooter is going in forbidden ways, such as wrong way or pedestrian areas

**Comment by frodrigo** [comment]
On your own server ? have you builded the data with the foot profile ? 
The foot parameter in your URL is ignored by the server.

**Comment by nilsnolde** [comment]
fwiw, it's possible to ignore any one-ways/turn/access restrictions per request with valhalla. it's not documented (yet), but there's a costing option `"ignore_oneways": true` (or `ignore_restrictions` for turn restrictions, `ignore_access` for access restrictions). so you could this all in one graph instead of 3 for bike, scooter and foot.
