### ISSUE TITLE
Wrong routing after adding mutually exclusive car and truck restrictions

### ISSUE THREAD

**Issue by ftrebien** [Project-OSRM/osrm-backend#5925]
After [this change](https://overpass-api.de/achavi/?changeset=96933112), OSRM stopped computing the correct route and started computing this incorrect route instead:

![](https://user-images.githubusercontent.com/3969479/103695423-4b6df080-4f7b-11eb-8133-a5203d9c8143.jpg)

The [new route](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=-29.74516%2C-57.09115%3B-29.74935%2C-57.07345) leads drivers through a path that is only allowed for trucks.

Also, before [this change](https://www.openstreetmap.org/changeset/96768804) from a single _only_straight_on_ restriction to two _no_u_turn_ restrictions [here](https://www.openstreetmap.org/node/1789240117), OSRM was refusing to route through this interchange when crossing towards Brazil.

**Comment by mjjbell** [comment]
Sorry If I'm misunderstanding - the change applies`hgv=no` to the inner loop road, whilst the outer loop road has `hgv=designated`. Wouldn't this be the expected behaviour?


 
--

**Comment by mjjbell** [comment]
Yes, I was misunderstanding 😄 
It looks like the roads have been edited a few times recently, so I'm not sure which version of the data is currently deployed.

Nevertheless, the reason cars are not routed via the inner loop is due to a [height restriction of 2.4 metres](https://www.openstreetmap.org/way/167537535), which is lower than that being used by the [fossgis routing profile](https://github.com/fossgis-routing-server/cbf-routing-profiles/blob/master/car.lua#L42).

You can see in the debug tiles that the [road is not accessible](https://routing.openstreetmap.de/debug/car.html#17/-29.74944/-57.08755) to cars with this profile.

**Comment by ftrebien** [comment]
Oh, I didn't notice that. That height limit is correct according to local signage, so I guess it can't be helped without causing problems elsewhere.

**Comment by GitBenjamin** [comment]
@mjjbell 
[5.24.0](https://github.com/Project-OSRM/osrm-backend/blob/master/CHANGELOG.md#5240)
Where is the branch of this change  `FIXED: Reduce copying in API parameter constructors` ?
The link in the changelog.md seems to be wrong !

**Comment by mjjbell** [comment]
> @mjjbell [5.24.0](https://github.com/Project-OSRM/osrm-backend/blob/master/CHANGELOG.md#5240) Where is the branch of this change `FIXED: Reduce copying in API parameter constructors` ? The link in the changelog.md seems to be wrong !

Off-by-one error: #5926
