### ISSUE TITLE
Gaps = split option unrightfully splits input track in case of a series of identical GPS points

### ISSUE THREAD

**Issue by ghost** [Project-OSRM/osrm-backend#5943]
Hi, I'm using the `gaps = split` option in my request and have the following situation:

<img width="601" alt="Screen Shot 2021-01-20 at 15 44 01" src="https://user-images.githubusercontent.com/40352112/105190519-5f4a5280-5b36-11eb-8488-de1d0b1edc09.png">

As you can see, the map matched trajectory (red line) is split between GPS point B and C. This seems unrightfully since the time difference between these points is 21 seconds and thus <60s. In fact, looking at the much larger time difference between point A and B, it seems the trajectory should've been split between these points instead.

However, when looking more closely to the corresponding points in the dataframe two things become clear. Firstly, all points highlighted in yellow correspond to GPS point B, since their lat, lon values are identical. Secondly, the time difference between all consecutive GPS points never exceeds the 60 seconds timestamp gap and therefore should never have been split. 

<img width="703" alt="Screen Shot 2021-01-20 at 15 43 52" src="https://user-images.githubusercontent.com/40352112/105190514-5ce7f880-5b36-11eb-8552-2372b9f9c6d7.png">

My assumption is that the OSRM map matching algorithm only uses the first GPS point of a series of identical GPS points (GPS point 3643 in the example above) and compares this timestamp to the timestamp of the first following _non_ identical GPS point (GPS point 3654), hence the split.
How do I make sure that OSRM doesn't split the map matched trajectory in these cases? This is how I plot these GPS points:

```
m = folium.Map(location=df[['latitude','longitude']].mean(), 
               zoom_start=14, 
               min_zoom=12, 
               max_zoom=19,
               control_scale=True)
for _, row in df.iterrows():
    lat, lon = row['latitude'], row['longitude']
    folium.CircleMarker(
        location=(lat, lon),
        popup=f"({lat:.4f}, {lon:.4f})",
        tooltip=row['datetime'],
        radius=4,
        fill=True,
        fill_opacity=0.5
    ).add_to(m)
m
```

**Comment by danpat** [comment]
When you supply timestamps, OSRM changes how it detects gaps:

https://github.com/Project-OSRM/osrm-backend/blob/master/src/engine/routing_algorithms/map_matching.cpp#L187-L198

In this case, because your GPS updates aren't moving, you create a situation where suddenly the vehicle goes from 0km/h (apparently), to moving >300m in 19 seconds.

I would suggest simply not supplying timestamps if you want to match the whole path.  Generally, my observation is that using timestamps leads to matches with more gaps, as it makes the algorithm more sensitive to bad data in the input.  Not using timestamps somewhat loosens the approach and can match over bad input data, which is what people usually want it to do in the first place.

**Comment by robbertwynn** [comment]
The problem is however, that my GPS data sometimes contains inexplicable large jumps:

<img width="1103" alt="Screen Shot 2021-01-20 at 16 53 47" src="https://user-images.githubusercontent.com/40352112/105200417-1a2b1e00-5b40-11eb-926f-8011ade856d8.png">

In these situations I would prefer OSRM to use the timestamps and split the map matched trajectory. Is it possible to increase the default timestamp gap of (> 60s) that is used for the `gaps = split `option?

**Comment by danpat** [comment]
Have you tried just removing the timestamp?  The gap in your example there should result in a split match, it looks long enough.

**Comment by robbertwynn** [comment]
I removed the timestamps, but the large gap does not result in a split match, it reroutes it. 

![Screen Shot 2021-01-21 at 08 46 16](https://user-images.githubusercontent.com/40352112/105319694-83a14000-5bc5-11eb-82cc-2fd808609c3a.png)

Why would you expect it to result in a split if the timestamps are removed? Is there another some sort of built in split algorithm that doesn't take timestamps into account to determine a split? 

I'm running my request with the following options: 
```
options = {'overview': 'full', 
'tidy': 'true', 
'gaps': 'split'}
```
