### ISSUE TITLE
Question about continue straight option.

### ISSUE THREAD

**Issue by Rougree** [Project-OSRM/osrm-backend#5963]
Hi guys,

I have a question about the `continue straight` option. I don't see the utility of `continue straight` if you don't request with `approaches = curb`, since there are only u-turns if you are on the wrong/other side of the street.

**Comment by danpat** [comment]
Perhaps the option isn't useful for *you*, but what if, say, you have a very long vehicle that is difficult to make u-turns with, but it doesn't matter which side of the street you arrive on?

**Comment by Rougree** [comment]
But there will never be u-turns, if it does not matter on which side you leave or arrive, right? @danpat

**Comment by danpat** [comment]
The `car` profile defaults `continue_straight` to `true`.  The other profiles (bike, foot) default it to `false`.

So you're right, the car profile will not generate u-turns at waypoints if you're generating data with `car.lua`.  But that's not always what everyone wants, so you can change it per request.

**Comment by Rougree** [comment]
Yes, by default `approaches = unrestricted`. So, if you don't say anything about `bearings` it does not matter if `continue_straight = True or False`. It will return the same result.

**Comment by danpat** [comment]
Ok, I'm very confused, but I think you haven't thought through all the possible scenarios.  Definitely for *some* routes, adding `continue_straight=true` will have no effect, because the shortest path is already to continue straight.  But there are location layouts where it would be faster to make a u-turn at a waypoint, and the `continue_straight` option is there to define whether you want to allow that or not.

Here are a few examples, and how the route will change:

![bitmap](https://user-images.githubusercontent.com/1892250/108724467-353fd380-74da-11eb-9283-3b96bc86e937.png)

**Comment by Rougree** [comment]
Ah I get it thanks! My thoughts were with only two locations, not three... With two locations is does not matter of course, but with three or more you are right! Thanks again.

**Comment by danpat** [comment]
For future readers: `continue_straight` only applies to middle waypoints, not the origin and destinations.

**Comment by dooley** [comment]
@danpat In your overview the last one ("Route will go out...") is not correct?
Shouldn't this be "approaches = unrestricted; curb; curb"?

**Comment by danpat** [comment]
@dooley yep, looks like I fat-fingered that.
