### ISSUE TITLE
Need new home for publishing binary modules

### ISSUE THREAD

**Issue by danpat** [Project-OSRM/osrm-backend#6013]
https://github.com/Project-OSRM/osrm-backend/pull/6012 removes the AWS access keys for publishing to the Mapbox S3 `mapbox-node-binaries` bucket.  Old binaries are still available, but TravisCI will no longer be able to push new ones there.

The reason for this token revocation is https://about.codecov.io/security-update/

We should update our build scripts to push somewhere new - possibly to GitHub Packages?

New releases with published binaries will be blocked until this is fixed somehow.

**Comment by mjjbell** [comment]
It looks like `node-pre-gyp` only supports publishing to S3: https://github.com/mapbox/node-pre-gyp#host
If there isn't alternative S3 hosting available, we could investigate creating a module for publishing to Github Packages similar to https://github.com/bchr02/node-pre-gyp-github

**Comment by akashihi** [comment]
I can talk back to Wolt and try to organize S3 hosting there

**Comment by mjjbell** [comment]
> If there isn't alternative S3 hosting available, we could investigate creating a module for publishing to Github Packages similar to https://github.com/bchr02/node-pre-gyp-github

On further investigation, Github Packages only provides a replacement for the registry component, and doesn't offer anything that would replace S3 for the platform-dependent binary hosting.

I've made #6030 that uses Github Releases for hosting. Inspired by this [comment](https://github.com/mapbox/node-pre-gyp/issues/134#issuecomment-69281215), rather than use the plugin mentioned above, it's possible to integrate it into the existing `node-pre-gyp` usage and Travis builds with minimal changes.
