### ISSUE TITLE
The API uses sometimes points far away from the actual given coordinates

### ISSUE THREAD

**Issue by madal3x** [Project-OSRM/osrm-backend#6066]
Good day,

i am trying to query for coordinates that may be islands, and many times when that happens the island coordinate is replaced by a land one, and the distance is calculated against that. For example:

http://router.project-osrm.org/table/v1/driving/6.21418,53.40468;6.22868,53.49142?sources=0&annotations=distance,duration

Gives the destination with a distance of 8611m.

And more examples, some of which are approximated correctly on the island, but many still are approximated far off on the land:

http://router.project-osrm.org/table/v1/driving/6.21418,53.40468;6.183333,53.383333;6.170831,53.393069;6.17208,53.37956;6.2,53.363889;6.29719167,53.34914444;6.12641,53.46173;6.116667,53.35;6.166667,53.483333;6.16666667,53.48333333;6.231944,53.489167;6.33527778,53.35675;6.22868,53.49142;6.1309,53.47698;6.16027,53.48899;6.146525,53.486839;6.13333,53.48333;6.133333,53.316667;6.2527,53.50248;6.05699,53.45316;6.05,53.45;6.393056,53.3625;6.30943,53.5072;6.038889,53.47;6.41186667,53.36782778;6.05231,53.30803;6.233333,53.256667;6.393889,53.509722;6.138889,53.255556;6.4,53.516667;6.40926,53.5189;6.449722,53.320833;5.960769,53.32175;6.45722222,53.31;6.41715833,53.27631111;5.93333,53.46667;6.2146845,53.4092096;6.2151,53.4093;6.2145256,53.4094675;6.211605,53.4093881;6.2115831,53.4093851;6.2115592,53.4093816;6.2121397,53.4094982;6.2105858,53.4091872;6.212245,53.4095355;6.2106108,53.4091947?sources=0&annotations=distance,duration

I tried the first one using the Route API and i receive the same destination point which is 8611m far.

Thank you

**Comment by madal3x** [comment]
A few other examples where the approximated point is further from the coordinate, and on a Maps application it can be seen that there are closer roads than the one approximated:

First column are coordinates requested and the second column are the coordinates approximated:

10.48333, 46.88333 - 10.477694, 46.886565
10.478176, 46.870009 - 10.476655, 46.885816
10.452778, 46.883056 - 10.459604, 46.882404
10.55, 46.9 - 10.516263, 46.888278 
10.566667, 46.883333 - 10.516257, 46.888227


The request: /table/v1/driving/10.50126,46.88859;10.48333,46.88333;10.478176,46.870009;10.452778,46.883056;10.55,46.9;10.566667,46.883333?sources=0&annotations=distance,duration

Also, i noticed that the distances to the approximated points seem different on the demo server than on my local machine, with the docker images, with only one country used, and with the car profile but with weight_name = distance. Some being still high, over 1-2km, the distances to the approximated points seem lower on the demo server.

**Comment by danpat** [comment]
We move the coordinates to a location where routes can be formed.  There's a blog post that describes this behaviour here:

https://blog.mapbox.com/robust-navigation-with-smart-nearest-neighbor-search-dbc1f6218be8

**Comment by madal3x** [comment]
Ok, but i think if there is no route, like in the case with the island, then i guess it would be more appropriate to return the fact that there is no route, instead of approximating a coordinate given with another point which is 8km far.

And in the second series of examples only with inland coordinates, taking the first:

10.50126,46.88859 to 10.48333,46.88333
the API approximates the destination point as 10.477694, 46.886565 whereas Google for instance takes the closest road to the point.

this is google's approximation, which takes the closest road to the destination point
https://www.google.com/maps/dir/'46.88859,10.50126'/46.88333,10.48333/@46.8893146,10.4824998,15z/data=!3m1!4b1!4m7!4m6!1m3!2m2!1d10.50126!2d46.88859!1m0!3e0

and this is the route returned by the API displayed on Google:
https://www.google.com/maps/dir/46.88859,+10.50126/'46.886565,10.477694'/@46.8910425,10.4806417,15z/data=!3m1!4b1!4m10!4m9!1m3!2m2!1d10.50126!2d46.88859!1m3!2m2!1d10.477694!2d46.886565!3e0

**Comment by danpat** [comment]
@madal3x You've got a few different issues mixed up here.

For this Google route, you're trying to get to:

https://www.openstreetmap.org/way/62073106

which is labelled as `highway=track` - OSRM does not route cars over those by default (see https://wiki.openstreetmap.org/wiki/Tag:highway%3Dtrack, specifically "The tag highway=track is used for minor land access roads that are not considered part of the general-purpose road network".  If the roads in this area are more open than this, then you should consider updating the tagging in OSM.

Alternatively, you can setup your own OSRM service and allow routing on `track` roads.

**Comment by madal3x** [comment]
I have set up locally an OSRM service, can you tell me please how i could make it so that it allows routing on track roads, and perhaps other types of roads that could improve the accuracy of the coordinates used?

Thank you

**Comment by danpat** [comment]
You need to insert a speed value for `track` here:

https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L156

then re-process your datafiles.

**Comment by madal3x** [comment]
Ah that's really nice, will do that then. And i guess regarding the island situation, if the approximated point is at 8km, or a similar bigger distance, then it would be safe to conclude that there is no route.

**Comment by madal3x** [comment]
Hi @danpat,

I tried adding track to speeds and rerun the docker commands, then i tried adding track to restricted_highway_whitelist, then i tried making access_tag_blacklist similar to the bicycle value, and still i got the same result for the _table_ api, though with _nearest_ i get a closer point for some reason.

/table/v1/driving/10.50126,46.88859;10.432572,46.86215?sources=0&annotations=distance,duration
returns
source: 10.501637, 46.888322
destination: 10.468886, 46.860024 (2778m far)

while
/nearest/v1/driving/10.432572,46.86215
returns
10.447757, 46.85767 (1260m far)

Google's return for the queried route:
https://www.google.com/maps/dir/46.88859,+10.50126/46.86215,+10.432572/@46.8788245,10.431931,13z/data=!3m1!4b1!4m10!4m9!1m3!2m2!1d10.50126!2d46.88859!1m3!2m2!1d10.432572!2d46.86215!3e0

Google's return for the OSRM API returned route:
https://www.google.com/maps/dir/46.888322,+10.501637/46.860024,+10.468886/@46.8818756,10.4680491,14z/data=!4m10!4m9!1m3!2m2!1d10.501637!2d46.888322!1m3!2m2!1d10.468886!2d46.860024!3e0

**Comment by madal3x** [comment]
The above results are with weight_name=distance. While using the default weight_name=routability it returns the same route as Google.

**Comment by danpat** [comment]
To debug this, you can try using the debug map tool:

https://github.com/Project-OSRM/osrm-frontend/blob/gh-pages/debug/index.html

modify that file and change this line:

https://github.com/Project-OSRM/osrm-frontend/blob/gh-pages/debug/index.html#L128

to say `http://localhost:8080/` instead of `https://router.project-osrm.org/`.  Then open `index.html` from your local filesystem in your browser, and you should be able to see a map.  The brightly colored lines on the map are the roads that OSRM has imported into the routing graph.  If you can see roads on the _background_ map but not with a brightly colored overlay, then OSRM has filtered them out during processing.

Roads that are highlighted in bright pink are disconnected from the rest of the road network.

Use this map to try to identify whether where you want to route to is:

  1. Simply not imported at all due to tags that OSRM doesn't like
  2. Imported, but somehow disconnected

In either case, this will help you identify problem OSM ways, then you can go and take a look in OSM itself to see how they are tagged.  There may be `barrier=` gates and other things that block access to the specific location you want.

Another way to try to understand why the routes don't go to where you expect would be to use the OSRM frontend (https://github.com/Project-OSRM/osrm-frontend/) to interactively browse your route.  It can often be quite enlightening to place your points at the expected location, then move them around to see how they snap/change to other nearby ways.

One thing I sometimes do with `osrm-frontend` is to place the source/destination very close to each other, then slowly drag the destination marker along the route I _expect_ to be taken.  When the route starts to deviate from the expected path, that pinpoints the location where sometimes something is not quite right (like, there's incorrect tagging of a turn restriction, or a barrier, or some other kind of thing mapped that affects routing that you didn't know about).

**Comment by madal3x** [comment]
I see, thank you for your answer, i will try and debug this way. Though, not knowing enough i guess, i find it strange that with weight_name=routability it takes points closer to the ones requested than with weight_name=distance, and there are sometimes differences in the kilometers range between the two weight types. How i see it is that it should take the closest routable points regardless of the chosen weight algo.

**Comment by emmexx** [comment]
I have a similar situation as the OP but with my own data.
The network has many "islands" and sometimes osrm proposes a path that is far away from the start and end waypoints.
You can check it here: [http://www.bicitalia.org/yourls/bpo](http://www.bicitalia.org/yourls/bpo)
The start and end points are on disconnected ways.
I would expect the route to be on one of the 2 ways where the waypoints are, not on another way.
There must be something in the osrm algorithm that is not taking account of the "distance" between the waypoints and the ways.
