### ISSUE TITLE
where does osrm store nodes and edge data in the source code.

### ISSUE THREAD

**Issue by shubham121297** [Project-OSRM/osrm-backend#6091]
where does osrm store nodes and edge data in the source code. Like in which file of Project-OSRM
/osrm-backend.which file contains the graph ?

**Comment by mjjbell** [comment]
The graph representation appears in OSRM source code in many places and in many forms, so without knowing what you're doing it might not be helpful. 
I'd suggest taking a look at these two wiki pages to understand the OSRM concepts:
- https://github.com/Project-OSRM/osrm-backend/wiki/Graph-representation
- https://github.com/Project-OSRM/osrm-backend/wiki/Processing-Flow

**Comment by shubham121297** [comment]
thank you for your response @mjjbell .I want to find out the variable or data structure in which the edges are stored .I want to make changes in that ds to show the information like until which date the particular edge is blocked or is to be avoided ,(if any edge due to natural disaster, or some sports event is blocked) and return that information in the response in route leg objects. And make an application so that if any route contains that edge ,i will show its information binded in a popup to that edge.I guess you can get me now.

**Comment by shubham121297** [comment]
@mjjbell ,@danpat waiting for your response.Thanks.

**Comment by mjjbell** [comment]
If I understand correctly, you want to annotate the returned route with additional context (as opposed to say, using external data sources to alter the routing results).

You can already use `annotations=nodes` to annotate the [route result](https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#route-service) with the OSM node IDs for each coordinate on the route.

#5968 adds the same functionality for OSM ways, so that could act as a starting point for your use-case with edges. You could then match these way IDs to your external dataset for displaying information in your app.
