### ISSUE TITLE
Wrong OSRM routes

### ISSUE THREAD

**Issue by alinmindroc** [Project-OSRM/osrm-backend#6092]
Hello,

I have a few examples for which OSRM gives a wrong route:

1. Wrong roundabout - route takes street with one way in wrong direction. Changing the vehicle type even to foot here gives a wrong route. [Link](https://map.project-osrm.org/?z=16&center=38.649891%2C-9.161568&loc=38.652960%2C-9.166940&loc=38.652980%2C-9.165210&hl=en&alt=0&srv=0)
![1](https://user-images.githubusercontent.com/3214239/128169998-77d12a3d-6658-4000-8f50-eb9467763958.png)

2. Wrong route on highway - it should just go straightforward. Changing the vehicle type to bicycle / foot here gives the correct route. [Link](https://map.project-osrm.org/?z=15&center=-1.257705%2C36.879086&loc=-1.263360%2C36.879360&loc=-1.267250%2C36.880190&hl=en&alt=0&srv=0)
![2](https://user-images.githubusercontent.com/3214239/128170389-08939af6-c297-4c73-b591-b6b23612f203.png)

3. Unexpected detour. Changing the vehicle type to bicycle / foot here gives the correct route. Moving the destination a slight bit to the north gives the correct route for car too. [Link](https://map.project-osrm.org/?z=18&center=44.450969%2C26.097194&loc=44.449720%2C26.096263&loc=44.450310%2C26.096010&hl=en&alt=0&srv=0)
![3](https://user-images.githubusercontent.com/3214239/128170401-f0c2e85c-390a-4f92-a11d-07171e08c15e.png)

I found some similar issues that were caused by wrong tags in OSM maps, but I can't say with certainty if in these cases the tags on the map are wrong.

**Comment by danpat** [comment]
For (1) - your coordinate is closest to the outgoing road from the roundabout - and that road is a oneway - OSRM has no choice here.  It's more obvious if you can zoom your map in a bit more:

<img width="503" alt="Screen Shot 2021-08-04 at 7 47 02 AM" src="https://user-images.githubusercontent.com/1892250/128202301-a3d14050-21c4-4609-be7e-05865aa9a781.png">

Same deal for (2) - zoom in your map a bit more, it's obvious what OSRM is doing:

<img width="393" alt="Screen Shot 2021-08-04 at 7 48 27 AM" src="https://user-images.githubusercontent.com/1892250/128202542-29dc8e58-e971-4353-88a6-d2655b4842aa.png">

And same again for (3) - your coordinate is slightly to the east of the intersection, so that's where OSRM routes to:

<img width="626" alt="Screen Shot 2021-08-04 at 7 51 01 AM" src="https://user-images.githubusercontent.com/1892250/128202980-161cafe8-6345-49ba-9d5e-33431b533ad6.png">

Overall, I would class these as "working as intended".

For cases (1) and (3) - some routing engines snap to intersections when the coordinate is within X meters - it's not like the road geometry is accurate below that level anyway.

For case (2) - the only fix here is to move the coordinate to the correct place - it's squarely on the service road beside the motorway.  The reason that switching to bike/foot "fixes" things is that they don't allow routing on certain road classes _at all_, so are forced to snap to somewhere else.

**Comment by alinmindroc** [comment]
Thanks!

I actually didn't expect the point to be so far from the intersection in cases 1 and 3. 
May I know what viewer you use to zoom that much? I used osm.org and it only allows a level much lower than in your screenshots.

**Comment by SiarheiFedartsou** [comment]
Closing as stale. Feel free to re-open though.
