### ISSUE TITLE
OSRM HTTP Call Questions

### ISSUE THREAD

**Issue by elemenopyunome** [Project-OSRM/osrm-backend#6101]
**Intro:** 
Hey all, couple quick questions here on a project (not for work related stuff just my personal messing around).  
  
**Environment:** 
SDL or GLFW (not sure on what I want yet), C++. Desktop application with GUI and overlay

**Questions:**
_1. I'm trying to pass in an address (not lat and long) for a start and another address for a destination so I can pass it into /route/v1 endpoint and get back some directions, mainly to be used to move a little car across the .mvt file (which I'll need to return on the initial request. Still don't know how to specify exact MVT files needed if you know that!)   
2. Looking for an easy to pull down an MVT file and a C++ library that I can extract layers out of the file to generate a object to overlay on top of the actual graphic GUI itself._ 

**Conclusion:**
If anyone knows how to do any of the above items, some info would be helpful while I continue spending my nights trying to piece this together. Thanks!

**Comment by elemenopyunome** [comment]
So I've been browsing the issues list with some filters and I came across another user who wrote:
@dhnguyen92 OSRM itself doesn't understand addresses - on the map.project-osrm.org interface, we send the address to https://nominatim.openstreetmap.org/, and it converts the address to a latitude/longitude that we then use to find a route.  
  
So is the above actually true for my use case then? So I should be doing the same to pass in an address and get back the lat and long for my first question above (see question 1)

**Comment by danpat** [comment]
Yes - in order to convert human readable address string into a point on a map, you need to "geocode" it - do a search in a database that is specialized for converting addresses into lon/lat values.  Nominatim is one such system, there are many others.

For parsing/reading/writing Mapbox Vector Tiles (MVT) in C++, you can take a look at https://github.com/mapbox/vtzero - it's a header-only vector tile encoding/parsing library.

Neither of these questions seem very related to OSRM HTTP calls, so I'm going to close this ticket, I don't think there's much else to be added here.
