### ISSUE TITLE
Wrong marker place after making a request by using api

### ISSUE THREAD

**Issue by Wh1teStr1pe** [Project-OSRM/osrm-backend#6116]
The problem is that after making a request with coordinates by using api, marker moves to the closest building. If I use osrm maps, the behavior is similar. How can I prevent it? My goal is to send a request and get the exact location of a marker corresponding to coordinates. Could you help me with that issue?

**Comment by jcoupey** [comment]
It's not really clear what you mean by "osrm maps", and since you mention a marker it looks like you're rather referring to the frontend.

In order to help better understand your problem, could you share a precise API request or link where you'd spot the coordinate that "moves"?

**Comment by Wh1teStr1pe** [comment]
For example, I have a [route](https://map.project-osrm.org/?z=17&center=56.826412%2C60.597078&loc=56.825289%2C60.591701&loc=56.828396%2C60.597496&hl=en&alt=0&srv=1) like on the first screenshot, the final distanation is near to the mall, but if get coordinates from url and put it to the gap of an end point, I'll get another result, the marker will be on the closest building as you can see on the second screenshot. I see the same behavoir if I use requests to osrm api. As a result I have wrong timing data because of different route.

![Снимок экрана 2021-09-03 в 18 39 32](https://user-images.githubusercontent.com/66954477/132016078-5e424914-93ba-4823-bc12-2aacf83b2aac.png)

![Снимок экрана 2021-09-03 в 18 40 54](https://user-images.githubusercontent.com/66954477/132016098-7fc8301d-cba6-4b23-bbef-747b8367db3c.png)

**Comment by jcoupey** [comment]
The red markers materialize the coordinates sent in the requests. If the coordinates are close but different, they may snap to different parts of the routing network (see gray dotted line on the second screenshot). In that case, getting different routes is normal.

**Comment by Wh1teStr1pe** [comment]
Is there any solution to prevent this behavoir and get exact point ?

**Comment by Wh1teStr1pe** [comment]
The point is that I didn't change the coordinates, I've just got coords from url and put it to the end point's gap and got another result

**Comment by jcoupey** [comment]
Ah OK, now I get it. This is because there is a reverse geocoding step taking place when you put coordinates in the "end" box. This is not related to OSRM per say but to the frontend behavior.

If you lookup the underlying OSRM request sent (network panel in your browser's dev tools), you'll see that end coordinates sent to OSRM are actually slightly different in the two situations:

https://routing.openstreetmap.de/routed-bike/route/v1/driving/60.591701,56.825289;60.597496,56.828396?overview=false&alternatives=true&steps=true

https://routing.openstreetmap.de/routed-bike/route/v1/driving/60.591701,56.825289;60.596591,56.828329?overview=false&alternatives=true&steps=true
