### ISSUE TITLE
Support foot routing along `highway=corridor`

### ISSUE THREAD

**Issue by quincylvania** [Project-OSRM/osrm-backend#6142]
The [`highway=corridor`](https://wiki.openstreetmap.org/wiki/Tag:highway=corridor) tag is used for walking routes through buildings, but doesn't appear to be supported in the OSRM foot profile.

Buildings can be key links in multimodal scenarios, such as routes through train stations, airports, ferry terminals, and bus depots. One example is [the corridor](https://www.openstreetmap.org/way/834409229) that connects the Bahamas to the North American routing network. Indoor routes are also common in cities, where people often cut through malls, lobbies, and concourses.

**Comment by mjjbell** [comment]
There's no lack of support, the path in question just lacks [access](https://wiki.openstreetmap.org/wiki/Key:access) tags, so it won't be included in any routing graph.

Here's an example of a `highway=corridor` (with access that is probably too permissive) being used for routing through a train station:

https://map.project-osrm.org/?z=18&center=37.600184%2C-122.386580&loc=37.599910%2C-122.386365&loc=37.600432%2C-122.386451&hl=en&alt=0&srv=2

<img width="586" alt="Screenshot 2021-10-05 at 16 15 53" src="https://user-images.githubusercontent.com/1063186/136052346-3552840d-0e5c-49b1-86a0-f1dca8cd4654.png">
<img width="656" alt="Screenshot 2021-10-05 at 16 15 45" src="https://user-images.githubusercontent.com/1063186/136052365-4c792224-a658-4a6c-8e32-8e611dc200a4.png">

**Comment by quincylvania** [comment]
Oh okay, that makes sense. I thought OSRM had routed on these before but figured I misremembered. Searched "corridor" in this repo and didn't see it in the data/code. I guess it's implicitly supported as a generic `highway` value? Thanks.

**Comment by mjjbell** [comment]
Looking at the lua code, if the `highway` value is not in the foot profile's speed list, it falls back to using access tags and assigns the default speed.
https://github.com/Project-OSRM/osrm-backend/blob/eb3bf5cfe3b14bb778cb84b9b0ec66785fdbe1e4/profiles/lib/way_handlers.lua#L277-L286

By adding  `corridor` to the speeds list in the foot profile, it should be picked up without requiring an access tag change in OSM.
https://github.com/Project-OSRM/osrm-backend/blob/eb3bf5cfe3b14bb778cb84b9b0ec66785fdbe1e4/profiles/foot.lua#L75-L78

Perhaps it's not been added by default because `corridor` usually implies an internal or private path that isn't useful for routing.
