### ISSUE TITLE
Electric bike profile

### ISSUE THREAD

**Issue by TiesWestendorp** [Project-OSRM/osrm-backend#6193]
Electric bikes are very prevalent (and becoming even more so) in the EU. Could an e-bike profile be added to OSRM to accommodate this? I'm not aware of all the intricacies of OSRM profiles, and so I'm not sure whether a bike profile simply having a higher maximum speed will suffice.

**Comment by techieshark** [comment]
+1 for this; I understand Mapbox uses OSRM (maybe?) so this could help a lot of people.

Also see this thread: https://twitter.com/Jonathan_Maus/status/1484254523174502403

**Comment by datendelphin** [comment]
Regarding the multiple speeds: OSRM is not really good in in tweaking routing for individuals, because the tweaking can't be done on the fly (trade-off with speed). The graph has to be recalculated from scratch. While an ebike profile or setting is definitely doable and welcome, and also making the speed tweak able, that will be prohibitively expensive to let the end user choose.

**Comment by TiesWestendorp** [comment]
Tweakable speed isn't what I'm after, just reasonable parameters for a generic ebike profile.
