### ISSUE TITLE
Wrong car routing, avoiding a bridge near Annecy, France

### ISSUE THREAD

**Issue by letypequividelespoubelles** [Project-OSRM/osrm-backend#6221]
### Start and end points

[Start and End point](https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=45.8927%2C6.1111%3B45.8985%2C6.1070#map=16/45.8956/6.1093)

### Actual and expected routes
OSMAnd and OSRM take the same (wrong) route, but it is expected to take [this bridge](https://www.openstreetmap.org/way/97414625). It's not a data issue, because Graphhoper has the right expected routing.

**Comment by scaidermern** [comment]
Maybe because https://www.openstreetmap.org/way/601521830 and https://www.openstreetmap.org/way/8407641 have no maxspeed set? Depending on the implicit maxspeed of the routing engine this route could appear faster than staying on the main road. On the other hand, driving through a roundabout is typically pretty slow...

**Comment by datendelphin** [comment]
I agree. This is because of the missing max speed. See http://routing.openstreetmap.de/debug/car.html#18.07/45.89624/6.11042 there you can see the two segments in red are missing max speed information and because those are classified as trunk, have a quite high default weight and max speed.

**Comment by letypequividelespoubelles** [comment]
ok, modified the trunk to trunk_link. Will add speed limit next time I'l go there. Thanks !
