### ISSUE TITLE
Getting 502 error

### ISSUE THREAD

**Issue by amih77** [Project-OSRM/osrm-backend#6236]
Hello, I'm getting 502 error code in response to the following request:
`http://router.project-osrm.org/route/v1/driving/55.354505,25.2228282;55.41277565,25.2777802?steps=false&overview=full`
is it a known issue?

**Comment by darksherman** [comment]
It came back up as I was typing, you all should try again. :)

**Comment by anjali2701** [comment]
I am getting the the same error. Any idea how to resolve this?

**Comment by RedHoodBoi** [comment]
> I am getting the the same error. Any idea how to resolve this?
> 
> Its down from last few hours

It's an error on their side. We(users) cannot do anything

**Comment by jcoupey** [comment]
> Any idea how to resolve this?

The easiest way to have a reliable service is to run your own instance. From the [demo server wiki page](https://github.com/Project-OSRM/osrm-backend/wiki/Demo-server): "_We provide no guarantees wrt. uptime, latency, or data updates_".

**Comment by datendelphin** [comment]
The memory seems to be getting full. OSM has grown too much ;) Maybe I can rebalance it a bit. It will take a while

**Comment by danpat** [comment]
@datendelphin Have you tried running with the `--mmap` option?  That should mean that infrequently used parts of the routing files never get loaded into RAM, maybe buying you a bit of breathing room...

**Comment by datendelphin** [comment]
Good idea @danpat
Drawback is that requests get a lot slower. Actually, that also happened to me without mmap, due to swapping. And that breaks the "dispatcher" which sorts requests to the region instances: all workers are then occupied with waiting, leading to the observed bad gateway message. So it unfortunately does not solve my immediate problem.
I think it works again for now, thought there will be a few interruptions again to finish the reorganisation. And I need to drop a profile or get more servers quite soon it seems.
