### ISSUE TITLE
Ubuntu 22.04 Server - Unable to build from source - TBB library not found

### ISSUE THREAD

**Issue by barbyj** [Project-OSRM/osrm-backend#6248]
Following the steps to build osrm-backend from source for linux I've been unable to get it going.

In the CMake step it errors out as per screenshot attached.

I've tried manually installing TBB in /usr/local/lib, setting environmental veriables for TBB_INSTALL_DIR and the ARCH type however no dice.

Same build process seems to work using 18.04 but wanting LTS with the latest OS is our goal here.

Any help would be really appreciated.

Thanks!
![Screenshot 2022-05-20 114656](https://user-images.githubusercontent.com/89234533/169432396-8a3a2150-8b71-4213-b2a2-78ab3e92448a.png)

**Comment by danpat** [comment]
Try building with `cmake -DENABLE_MASON=ON` - this will use a pre-built TBB library that's known to work, rather than system-installed libraries.

I do know that tbb has deprecated some of the interfaces we originally used, so it's likely that the FindTBB cmake rules no longer work for newer versions of TBB.

PRs to fix it welcome - we haven't done much of a platform refresh in a long time, it might be time to update everything.

**Comment by barbyj** [comment]
> Try building with `cmake -DENABLE_MASON=ON` - this will use a pre-built TBB library that's known to work, rather than system-installed libraries.
> 
> I do know that tbb has deprecated some of the interfaces we originally used, so it's likely that the FindTBB cmake rules no longer work for newer versions of TBB.
> 
> PRs to fix it welcome - we haven't done much of a platform refresh in a long time, it might be time to update everything.

Solved my issue! Thanks for the quick response!
