### ISSUE TITLE
no route found for occasional AtoB cases in many-to-many queries

### ISSUE THREAD

**Issue by dwcorne** [Project-OSRM/osrm-backend#6250]
Sometimes, depending on the mix of other locations in the table/matrix query,  there will be no sensible journey distance returned between certain pairs of locations.  This seems to be because the 'buffer' around the set of locations is not large enough.  For example the problem A-to-B will typically be located close to each other near the edge of the  bounding box of the set of locations,  facing each other across a railway line or canal.  So, the error seems to happen because the area searched for routes doesn't go far enough outside the box to find nodes that take it across the canal.   I'm wondering if there is a way to control the size of this buffer? Or otherwise force OSRM to try harder in such cases?

**Comment by danpat** [comment]
Can you cite a specific example?

The usual situation that causes this is isolated network pockets - where your coordinates end up snapping to some edges that are _not_ connected to the rest of the routing network (islands with roads but no ferry connections are an example of this).  They are scattered all throughout the map, usually as a result of mapping errors, or restricted access rules (gates, barriers, `access=private`, etc).

The way OSRM tries to resolve this is:

  1. It takes your coordinate and snaps it to the nearest edge.
  2. If that edge is known to be on an isolated network ("small component" if you search the code), it'll also snap the coordinate to the nearest edge on the "big component" - the main road network.
  3. Once all coordinates are snapped, the code selects the snapped locations that will generate routes - if all coordinates snapped to the same "small component", then that will be used.  Otherwise, the snapped location on the "big component" will be used for all candidates.

The logic for this is common across all services (`/route`, `/table`, etc), and lives here:

https://github.com/Project-OSRM/osrm-backend/blob/master/include/engine/plugins/plugin_base.hpp#L107-L164

The only situation where "no route" will be calculated is when coordinates snap to disconnected "big component" - e.g. one coordinate in Europe, one coordinate in the USA.  The threshold for detecting whether an isolated network is part of the "big component" or an isolated "small component" defaults to 1000 nodes - if an edge can access >1000 other edges by exploring outwards, then it's considered "big component".

Again, a specific example would be helpful in determining exactly how the behaviour above is playing out for your requests.

**Comment by dwcorne** [comment]
Thanks @danpat  - it's actually very tricky to come up with a specific example -  the behaviour I see emerges after the the specific table request that led to it is long gone ...  

But I think there is  better question for me to ask:  given the collection of sources and destinations in a table/matrix request,  how much of the map is searched ?   E.g. if the northwestmost source is in Glasgow and the southeastmost is in Falkirk, then I'm fairly sure that nodes in London will be utterly ruled out. I suspect that, given the sources/dests in the query, a portion of map is loaded up which extends outwards a bit, far enough to be fairly confident of capturing all the necessary edges. That's the bit I'm interested in, and wondering how to influence.

**Comment by danpat** [comment]
@dwcorne OSRM will search as far as necessary to find a connection.  There's no concept of "giving up" - if OSRM returned a "NoRoute" or "null" result, it means it exhaustively searched the routing graph as it sees it, and no end-to-end connection was found.  Those null results mean there is no connectivity between the selected start and end locations, which is why how the start/end locations are chosen becomes so critical and we have the surprisingly complex logic for it.

If I'm understanding what you're saying, you're thinking of a case where we selectively load some of the map based on the coordinate locations, then for _some_ routes, it happens that the connectivity actually flows through the part of the map we didn't load.  That's not how OSRM works, the entire routing graph is available and is considered for each request.

**Comment by dwcorne** [comment]
OK thanks for the help, this has to be due to different snapping outcomes for different requests, as you suggested in the  first place @danpat .  I searched that a bit and indeed the logic is elaborate.  This clearly points towards the fact that the best way to avoid this for my use-cases is to shift the troublesome co-ordinates a bit to place them unambiguously on the large component.
