### ISSUE TITLE
Api requests

### ISSUE THREAD

**Issue by jpanoyev** [Project-OSRM/osrm-backend#6305]
Hi there, Is there any solution to increase api requests? I want to get 3500+ requests per second.

**Comment by handcath** [comment]
The node bindings can easily achieve that especially if you add worker threads.

Instead of thinking about it, in terms of number of requests per second, it is best to first to think about it, in terms of what cause variability in the number of ms it takes to return a response.
You'll find that two of the request parameters will greatly impact the overall performance of OSRM when used as a library, for customisation and performance.
1. Complexity of the route requested, kind of a given really.
2. What annotation objects and geometry you want OSRM to return. As an example, and from experience, requesting speed on a per node basis doubles the time it takes for OSRM to return a json response vs requesting just the nodes.

OSRM is flexible enough that you can unleash your creativity and architect an application built for speed. The node bindings will allow you to do that in spite of the inherent limitations of node js.
