### ISSUE TITLE
OSRM denies straight route

### ISSUE THREAD

**Issue by ctudorache** [Project-OSRM/osrm-backend#6320]
Straight route should be possible in this case: [example](https://map.project-osrm.org/?z=18&center=49.817446%2C24.043279&loc=49.816551%2C24.044888&loc=49.815880%2C24.045205&hl=en&alt=0&srv=0)

I cannot find any reason why OSRM denies the straight route through node: [5029643462](https://www.openstreetmap.org/node/5029643462)

Can someone please take a look? Thank you!

![image](https://user-images.githubusercontent.com/1257535/185757198-7f0135ab-15ac-4fcd-908b-455beb561b54.png)

**Comment by SiarheiFedartsou** [comment]
Looks like the main problem is not in routing itself, but in initial waypoint snapping. For some reason waypoint was snapped on the side road, but not on most "obvious" place.

**Comment by SiarheiFedartsou** [comment]
> Looks like the main problem is not in routing itself, but in initial waypoint snapping. For some reason waypoint was snapped on the side road, but not on most "obvious" place.

I played with it a bit and it looks like there is something wrong with the whole this part of the road:

<img width="1109" alt="Screenshot 2022-08-21 at 15 21 30" src="https://user-images.githubusercontent.com/266271/185792916-526a452e-a1eb-4d37-950b-655b4dd7a832.png">

We basically do not snap to this road in between nodes https://www.openstreetmap.org/node/5029643462 and https://www.openstreetmap.org/node/386665199

**Comment by systemed** [comment]
Maybe `construction=secondary` on https://www.openstreetmap.org/way/867966024 ?

**Comment by mjjbell** [comment]
The [debug map](https://map.project-osrm.org/debug/car.html#16.14/49.81419/24.04529) shows that many of the roads in the vicinity are not routable.

![image](https://user-images.githubusercontent.com/1063186/185793683-a2c86731-b5c8-4028-afa2-f2f0fdbf4d26.png)

OSRM is trying to be helpful by avoiding the isolated purple roads (i.e. a disconnected one-way road doesn't make much sense).

The fix is to figure out what the data issue is (sounds like some construction tags), so that all these roads become routable again.

**Comment by SiarheiFedartsou** [comment]
> OSRM is trying to be helpful by avoiding the isolated purple roads (i.e. a disconnected one-way road doesn't make much sense).

But may it impact to waypoint snapping? I mean as I can see in this particular case we do not even snap to this road, but I thought that at the moment snapping and routing are completely separated things and as soon as we chose some way to snap we never change it. That's why in this case I would expect that waypoint to be snapped to the road nearest to input location.
<img width="1109" alt="Screenshot 2022-08-21 at 15 21 30" src="https://user-images.githubusercontent.com/266271/185794549-3a0fe1c9-f8ff-4b4a-86d8-3252879489b4.png">

> OSRM is trying to be helpful by avoiding the isolated purple roads (i.e. a disconnected one-way road doesn't make much sense).

Or do you mean we are doing this on the snapping stage?

**Comment by mjjbell** [comment]
Yes it impacts snapping. It will move all waypoints into the same strongly connected component. The purple/pink outlines in the debug map are showing small components that are not strongly connected to the rest of the network.

Whilst in this case, there is a path from start to end input location, there wouldn't be in the reverse direction, and at the time of snapping it doesn't know this, so it's moving the waypoint to somewhere it has better guarantees of finding a route.

IMO this is probably the right behaviour still. Ending a route down a one-way road indicates something is wrong, which is the case here - the tags need fixing.

**Comment by ctudorache** [comment]
Thank you @mjjbell @SiarheiFedartsou for analysing and clarifying this issue!

Now it makes sense.

We will try to fix the map tags to enable correct routing in that area.
