### ISSUE TITLE
No matching error

### ISSUE THREAD

**Issue by audreyrain** [Project-OSRM/osrm-backend#6321]
Hi, 

I'm trying to compute distances between "codes communes" in a data frame A and "codes communes" in a data frame B. I checked that on a map those codes communes are close to each other. However when I'm computing distances with the metricOsrmTable function, the following error appears : 

`Calcul en cours - étape 1 [=======================] 100%  1s
Calcul en cours - étape 1 [=======================] 100%  1s
Aucun point n'a été trouvé à moins de 1e+06 km à vol d'oiseau
[WARNING] Aucun couple n'a été calculé.
Vérifiez que les filtres ne soient pas trop restrictifs
ou que les sources et les destinations ne soient pas trop éloignées.`

I also checked that coordinates are in the same format. 

Thanks !

**Comment by jcoupey** [comment]
The debug/error output you share is not issued by OSRM but by your own code, where the `metricOsrmTable` function lives. We can't debug this without access to this code.

In order to help, could you narrow down the exact request that your own code is sending to OSRM when you hit the error, along with the OSRM response? You can spot the request in the logs if you're running `osrm-routed`.

**Comment by jcoupey** [comment]
Closing as stale, feel free to reopen with new input.

**Comment by audreyrain** [comment]
Hello Julien,


Sorry for not answering and thanks for your answer, I finally managed to do what I wanted to.


Best,


Audrey

________________________________
De : Julien Coupey ***@***.***>
Envoyé : jeudi 15 septembre 2022 10:49:42
À : Project-OSRM/osrm-backend
Cc : Audrey Rain; Author
Objet : Re: [Project-OSRM/osrm-backend] No matching error (Issue #6321)


Closing as stale, feel free to reopen with new input.
