### ISSUE TITLE
OSRM shuns a particular OSM way

### ISSUE THREAD

**Issue by jengelh** [Project-OSRM/osrm-backend#6365]
# Observed

https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=51.48984%2C9.87727%3B51.49023%2C9.87690#map=18/51.49032/9.87817

![1](https://user-images.githubusercontent.com/8861948/189984567-49df860e-cf7a-493f-8308-11d8fb76dc8a.png)

# Expected to see instead

https://www.openstreetmap.org/directions?engine=graphhopper_car&route=51.48984%2C9.87727%3B51.49023%2C9.87690#map=18/51.49027/9.87735

![2](https://user-images.githubusercontent.com/8861948/189984553-3522f2d4-c083-43c3-9348-9e6123aaee42.png)

There is something about OSM way 498828745 that OSRM doesn't like, but I can't tell what.

**Comment by mjjbell** [comment]
This is what OSRM is seeing

https://map.project-osrm.org/debug/car.html#17.04/51.49074/9.87768
![image](https://user-images.githubusercontent.com/1063186/189993013-265ed7ed-67b0-4164-8514-bb11632f9896.png)

The roads from/to that way are not accessible, I believe it's due to the `proposed` tag. The profile[ treats it as not routable](https://github.com/Project-OSRM/osrm-backend/blob/96f5780f06e6f55013762c879c361d647036bd72/profiles/lib/way_handlers.lua#L652).



So similar to #6320, the end input location is on a one-way road with no exit, which indicates something is not quite right. OSRM therefore snaps to somewhere accessible instead, hence the long route around.

Removing the proposed tag from the adjacent ways should fix this problem (assuming the roads are now complete).

**Comment by jengelh** [comment]
Found https://github.com/Project-OSRM/osrm-backend/issues/6141
I can understand when OSRM decides to ignore ways with construction=*, but doing the same for proposed=* is just quite wrong.

Sure, you don't want to route over highway=proposed proposed=primary.

But highway=primary proposed:highway=secondary c/would indicate a change in classification, and is not supposed to negatively affect routing today.

**Comment by mjjbell** [comment]
I see. It could be that the usage has changed since this was added to the profile, and now this is worth revisiting.
I'll run an overpass query to understand the current usage.

**Comment by mjjbell** [comment]
Forgot to follow-up. I ran a query to see what would be exposed if the profile included `proposed` tags that are missing `highway=proposed` or any reference to construction.

https://overpass-turbo.eu/s/1m7f

Broadly, the categories are:
- Ways where it appears they've forgotten to remove the proposed tag ([example](https://www.openstreetmap.org/way/461966507#map=19/50.26299/8.64199))
- In-progress ways that are currently tagged as inaccessible to normal traffic ([example](https://www.openstreetmap.org/way/542221951))
- Proposals to change in highway type for already accessible ways (similar to the issue above).

Overall it looks like strictly following the [proposed tag guidelines ](https://wiki.openstreetmap.org/wiki/Key:proposed) will lead to better routing and won't have major downsides.

In any case, the profile used by the OpenStreetMap website is [in a separate repo](https://github.com/fossgis-routing-server/cbf-routing-profiles), so making a change to the default repo behaviour doesn't mean it will make it onto the site. You might want to make a request over there too.
