### ISSUE TITLE
No bike routing possible ? 

### ISSUE THREAD

**Issue by 0709wiwiwi** [Project-OSRM/osrm-backend#6371]
https://lists.openstreetmap.org/pipermail/osrm-talk/2022-September/002048.html

**Comment by jcoupey** [comment]
The way [near your start point](https://www.openstreetmap.org/way/146498944) is not part of the routing graph for the bike profile. You can see this when looking at [the debug map](http://routing.openstreetmap.de/debug/bike.html#16.66/51.05079/4.00190).

Now this happens because the bike profile used for the demo server explicitly excludes `tracktype=grade4` ways [here](https://github.com/fossgis-routing-server/cbf-routing-profiles/blob/16453fa5ded78671560dba15e124ea5bac6d52d3/bike.lua#L204). Note that this is a different choice than the default profile so you'd get a different behavior if running your instance locally.

**Comment by jcoupey** [comment]
Closing as answered here **and** over the mailing list. Please avoid cross-posting like this in the future.

**Comment by 0709wiwiwi** [comment]
Hi Julien.
OSRM may be a fast router, but to handle this request that fast either as job  finished ? 
You share why it is not allowed to route.The devil may know why this restrictive choice ?
I ask for a solution or a change so that it can and will thus route like other routers.
The intention is not to fake openstreet map data this in function of that osrm router.
I (gps user) likes the osrm demo router and just would like to include this road in a simple new design. 

By the way, this stretch of road is part of a cycle track publication by the local tourist board.
https://www.routeyou.com/nl/user/view/456385/toerisme-berlare
https://www.routeyou.com/nl-be/route/view/9594315/recreatieve-fietsroute/kapelletjesroute
According to osrm info, RouteYou uses this engine ? Or would it be GraphHopper after all ? 
 
RouteYou web.
Matching an import record track usinjg routeyou web uses "osm direct" (no rules) to even the manual profile.
This way, routing through everything always succeeds, because of this, cycle tracks not always run optimal.
A design with osrm is more precise, but it should just be a bit more tolerant even with grade 4 and grade 5.
Please Sir.

**Comment by jcoupey** [comment]
> to handle this request that fast either as job finished

To be honest, closing this ticket fast was more related to cross posting. I spent some time looking at your example, explaining things and gathering useful links in my response but then it felt like I just wasted this time since you got a similar answer from the mailing list.

> it should just be a bit more tolerant even with grade 4 and grade 5

This is a matter of taste, and there is a wide variety of different choices that various cyclists would do in various situations. A bike profile tries to capture **one** option that looks sensible from the perspective of the person tuning it.

Again, as I pointed out, the default profile *would* route through grade 4 tracks so if your run your own instance of the backend and frontend, you'd get a better route from your point of view. You could additionally further tune the profile to your liking.

Now if you think the demo server profile should be adjusted, this is not directly related to the OSRM backend and you should discuss it in the dedicated repo hosting the demo profiles, see [previous link](https://github.com/fossgis-routing-server/cbf-routing-profiles/blob/16453fa5ded78671560dba15e124ea5bac6d52d3/bike.lua#L204).

**Comment by nilsnolde** [comment]
This repo has nothing to do with the public server profiles. You can try your luck here: https://github.com/fossgis-routing-server/cbf-routing-profiles/issues. To be fair, it's debatable if `track4` is fit for general cycle access, really very subjective/personal choice. Ideally a router would let you choose the max softness/track a user wants to route on, not even Valhalla offers that though AFAIK
