### ISSUE TITLE
v5.26.0 configuration

### ISSUE THREAD

**Issue by LeoAlle** [Project-OSRM/osrm-backend#6406]
Hi, how can I change my OSRM version from 5.27.0 to 5.26.0?

**Comment by SiarheiFedartsou** [comment]
Could you clarify please? How do you use it at the moment? As Docker image? node package? Why do you want to downgrade btw?

**Comment by LeoAlle** [comment]
Cause I still continue to get an error "Invalid Routing Response" when I'm trying to solve instances with 500 or more jobs to do.

**Comment by jcoupey** [comment]
@LeoAlle you need to be more specific in your questions and responses in order to get proper help.

> I still continue to get an error "Invalid Routing Response" when I'm trying to solve instances with 500 or more jobs to do.

For example this does not really make any sense in the OSRM context as you're mentioning errors in a downstream project without even a link to [the actual discussion](https://github.com/VROOM-Project/vroom/issues/801). People don't like to play guesses on bugtrackers. ;-)

**Comment by LeoAlle** [comment]
Ok I'm sorry @jcoupey. Thanks for the tip.

**Comment by SiarheiFedartsou** [comment]
@LeoAlle do you still need any help from our side?
