### ISSUE TITLE
Including 2 OSM files in a local server

### ISSUE THREAD

**Issue by fgoerlich** [Project-OSRM/osrm-backend#6463]
Hi,
I have been able tu set-up a local osrm-backend (from the [Docker images](https://hub.docker.com/r/osrm/osrm-backend/)) for `spain-latest.osm.pbf` and works fine, at least for car.
However Spain is in two files, the previous one and Canary Islands, which are in separate file, `canary-islands-latest.osm.pbf`.

It is not clear to me how I can set-up a (single) local server for the whole Spain (two OSM files).
Can you tell me how this can be done?
I cannot install the full Europe because of memory restrictions, but even if this would be the case Canary Islands are not covered by the Europe OSM file from [Geofabrik](https://download.geofabrik.de/europe.html).

Two addtional questions related two the above are:

1. If I send a query to the local server with coordinates from Canary Islands (which is not on the server), I have observed that, in a `Table` service, distance and time is returned as 0, but `code` is returned as `"Ok"`. How can I configure the local server to return `NULL` or `NA` and `code` `NOT FOUND`, or something similar.
2. According to the documentation in the [API](http://project-osrm.org/docs/v5.24.0/api/#), the profiles are `car`, `bike` or `foot`. Hovewer the examples use `driving` instead of `car`: `curl 'http://router.project-osrm.org/table/v1/driving/13.388860,52.517037;13.397634,52.529407;13.428555,52.523219'`. We have check that with `car` in the query works, and returns sensible results. Is this correct? If not, we have not found in the [API](http://project-osrm.org/docs/v5.24.0/api/#) information or examples about the the correct option for profiles `bike` and `foot`.

Many thanks in advance for your help.

**Comment by SiarheiFedartsou** [comment]
I think it shouldn’t be a big deal to modify osrm-extract to be able to accept multiple .osm.pbf files as an input. If you want to make a PR I will be happy to help :)

When it comes to question 1 I don’t remember if we actually have any settings here, but most likely it is caused

**Comment by jcoupey** [comment]
The usual way to use several OSM extracts in a single OSRM server is to merge them before-hand and apply the pre-processing pipeline to the resulting file. Among others, osmium is a great tool for this, see example in the [osmium merge man page](https://docs.osmcode.org/osmium/latest/osmium-merge.html).

> I think it shouldn’t be a big deal to modify osrm-extract to be able to accept multiple .osm.pbf files as an input.

Not sure this would be such a wise move since it would mean writing and maintaining extra code for just this purpose with all the potential edge cases you can imagine, e.g. for adjacent countries a lot of objects are present in both file, etc. Also this would make OSRM responsible for any bug related to handling multiple files while we have efficient tools designed just for this.

On the other questions:

1. This happens because no error is returned by OSRM, the far-away coordinates are just snapped to the nearest nodes in the extract, usually the same nodes hence the 0 distances. You can play around with this using the `radiuses` parameters. If the distance between the original point and the snapped one is too high, you'll then get an error.
2. That part of the URL is just a placeholder that has no influence on the results (try using `foo` or `bar`). What really matters is which profile you used to run the data preparation pipeline. If you want several profiles, you need to run several servers. In that case you could use the placeholder at a higher level to proxy the request to the relevant OSRM server.
