### ISSUE TITLE
Refactor codebase to use std::optional instead of boost::optional

### ISSUE THREAD

**Issue by SiarheiFedartsou** [Project-OSRM/osrm-backend#6551]
# Description

We migrated to C++17 and can start using std::optional from standard library instead of boost::optional.

The main problem here is Boost.Spirit library which doesn’t support std::optional(see https://github.com/Project-OSRM/osrm-backend/pull/6429#issuecomment-1296207761).

**Comment by Kaushik-Iyer** [comment]
Can I work on this?

**Comment by Kaushik-Iyer** [comment]
Can I try to work on this? Which part of the codebase should I be looking at?

**Comment by nilsnolde** [comment]
GSoC has an application process, which we will follow. We’ll make an announcement as soon as that starts.

**Comment by code-sparsh** [comment]
I might be able to work on this. Is it available?

**Comment by nilsnolde** [comment]
It is. Do you want to be assigned?

**Comment by code-sparsh** [comment]
Yes, I want to be assigned.

**Comment by 97littleleaf11** [comment]
oops, I already have some progress on this issue

**Comment by 97littleleaf11** [comment]
@nilsnolde sorry for my previous misguiding comment. @code-sparsh It's fine that you take this issue! I will find another issue to work on later. Actually I haven't dig into the `Boost.Spirit` yet.

**Comment by code-sparsh** [comment]
@97littleleaf11 Oh okay. If you already have some progress, it's fair that you take the issue because I haven't started yet. 

Regarding the Boost.Spirit, I did some research on it. I think it would require some extra workarounds to be able to support std::optional. That might add some extra boilerplate to the code. I don't know if that's feasible or not, because I am just a beginner in this.

**Comment by 97littleleaf11** [comment]
@code-sparsh Thanks for your information! Yeah, someone might add a boilerplate for std::optional like this https://github.com/boostorg/spirit/issues/270#issuecomment-376114135 . Also need to check the correct overloading func. I haven't made it and found it's a little bit beyond my ability. If would be fine that you can take this.

**Comment by mugr1x** [comment]
Hello, I also have some progress on this issue. Can I submit a PR ?

**Comment by SiarheiFedartsou** [comment]
> Hello, I also have some progress on this issue. Can I submit a PR ?

Sure, why not? :)

**Comment by mugr1x** [comment]
Now I found out that boost::spirit::x3 works well with std::optional (and has only minor modifications needed for working). However is it intentional that one implements a whole CSV parser instead of linking against something like libcsv3 ?
Anyway, I also want to apply for Google summer of code. I  also think should talk to a potentional menter before.
@SiarheiFedartsou Can we possibly chat, you know about what exactly you need for the project idea and if it would be a good fit ?
