### ISSUE TITLE
How can I avoid highways or tolls

### ISSUE THREAD

**Issue by jiang01yi** [Project-OSRM/osrm-backend#656]
Hi,
Is there any option in GUI or API that I can choose to avoid highways or tolls, which are exact same as google?
Thanks.

**Comment by mahasheikhignite** [comment]
@TheMarex can you please help me how can i add toll=yes in UAE data set. I didn't able to find the file in which i can change the data.
Thanks in advance.

**Comment by tikky** [comment]
Hello I've seen this original post from 2013. As per 2021 is there an option to set in routing to avoid tolls and/or avoid highways?

**Comment by nilsnolde** [comment]
Nope, not on a per request basis. OSRM is still trading off flexibility for amazing speed. If you need high flexibility you should consider other options, like Valhalla, Graphhopper or ORS.

**Comment by frodrigo** [comment]
No. The answer now is yes you can to it on class defined here
https://github.com/Project-OSRM/osrm-backend/blob/master/profiles/car.lua#L119
The use the exclude class from the API.

**Comment by nilsnolde** [comment]
My apologies, that’s great!

**Comment by TimMcCauley** [comment]
If OP is asking for dynamic parameters on request basis then @nilsnolde is definitely right

**Comment by nilsnolde** [comment]
Thanks @TimMcCauley, was about to rewrite our last article;) thought I made the distinction clear in my answer..

**Comment by datendelphin** [comment]
I'm confused. It can be done on a request basis. It should even work for the demo service at the moment:
https://routing.openstreetmap.de/routed-car/route/v1/driving/9.722707271575928,50.852030054475705;9.859371185302734,50.89041934249497?overview=false&alternatives=true&steps=true&exclude=motorway
should exclude motorways. The demo server has toll, motorway and ferry currently enabled as excludeable. Am I missing something?

**Comment by TimMcCauley** [comment]
Sorry @frodrigo @nilsnolde  @datendelphin! I wasn't aware OSRM offers this. It would be interesting to see if the exclude flags have an impact on the computation times as it uses separate logic 61c430c0983cdc0f4b679925f7d4f069acca6a69

**Comment by jcoupey** [comment]
It's not flexible in the sense that you can put in *any* combination of exclude flags on a per-request basis. You have to decide the possible options you want to allow before preparing the data (see above profile link).

Then the contraction phase is basically duplicated for each combination, so the impact would be more on data preparation time (`osrm-contract`) and memory usage. I would not expect any change in computing time for routing requests.

**Comment by Okrisssss** [comment]
Hi all, sorry probably for the stupid question, but can someone help me to understand what am I doing wrong?
What have to be done in order to exclude ways that have tolls. I've added in path params exclude=toll ->
(http://127.0.0.1:5000/table/v1/driving/10.7726875,55.331026;11.2965103,55.3755964?exclude=toll)
and adjusted the "car.lua profile",
 **uncommented the row -- 'toll',**    **-- uncomment this to avoid tolls**
 But I still receive the route with toll.
 
Is it possible that no route won't be returned  if route contains only one way  that has a toll?
In my example I need to find a route  from point 10.7726875,55.331026; to 11.2965103,55.3755964. and in this case we have only one route across the toll bridge, so logically no routes should be returned with "exclude=toll", please correct me if I'm wrong.

Will appreciate for the help.

**Comment by Cactustory** [comment]
@Okrisssss
I have the same problem.
