### ISSUE TITLE
Right way to update osrm from new osm file

### ISSUE THREAD

**Issue by skulaga-angelsit** [Project-OSRM/osrm-backend#6623]
Hello, i have generated osrm files, but a dont now how update its from new version of osm file.
What is the correct way to do this?
I dont want delete osrm files and generate new, a want update only changed data from new version osm file.

**Comment by jcoupey** [comment]
There is no diff update mechanism in OSRM to incorporate new OSM data. Such a process would probably be very hard to implement due to the  built-in preprocessing steps that OSRM applies, and would probably require to redo most of the work anyway.

Generating new files is the only option to incorporated OSM changes. If you're interested in updating speeds (not the network), you may consider using the traffic feature.

**Comment by skulaga-angelsit** [comment]
thank's
