### ISSUE TITLE
Unable to find route for specified source and destination with OSRM

### ISSUE THREAD

**Issue by thpoiani** [Project-OSRM/osrm-backend#6624]
Hello OSRM Team,

I am testing the routing capabilities of your OSRM engine and have encountered an issue. I am unable to find a route for the following parameters:

Source: `1.394596,51.359921`
Destination: `1.432446,51.347744`
Profile: `Car`

https://map.project-osrm.org/?z=15&center=51.353946%2C1.413780&loc=51.359986%2C1.394753&loc=51.347741%2C1.433223&hl=en&alt=0&srv=0

However, I am able to find this route using other routing engines such as Graphhopper and Valhalla.
https://www.openstreetmap.org/directions?engine=graphhopper_car&route=51.3600%2C1.3948%3B51.3477%2C1.4332
https://www.openstreetmap.org/directions?engine=fossgis_osrm_car&route=51.3600%2C1.3948%3B51.3477%2C1.4332

Could you please help me understand why this route is not available in OSRM and what I can do to resolve the issue?

Thank you for your assistance.

**Comment by systemed** [comment]
If you look at the debug map (https://map.project-osrm.org/debug/#18/51.35990/1.39460), you can see that your start point is close to an isolated section of road - https://www.openstreetmap.org/way/993059775

This section of road is tagged in OSM as `highway=service` and so OSRM will happily route over it. However, the roads that connect it to the outside world are tagged with `motor_vehicle=no`, so OSRM won't go on those.

It's possible that your start point is 'snapping' to this isolated section and is then unable to get out. I suggest you fix the OSM data so that https://www.openstreetmap.org/way/993059775 is also tagged with `motor_vehicle=no`, then wait a couple of days for the OSRM instance to update, and see if that fixes it.
