### ISSUE TITLE
bicycle routing not available on demo map

### ISSUE THREAD

**Issue by anarcat** [Project-OSRM/osrm-backend#668]
there seems to be some support in OSRM for bicycle routing (e.g. #12), unfortunately it doesn't seem to be active on the main map at http://map.project-osrm.org/

**Comment by daniel-j-h** [comment]
The demo server only runs the car profile. For other profiles you have to extract and prepare the files differently --- this is possible, and then the API will return correct results for that profile.

There is no plan to support additional profiles on the demo server at this point in time, due to the nature of the demo server being.. well, a demo server.

Here are some API providers that run additional profiles:
https://github.com/Project-OSRM/osrm-backend/wiki/Websites-and-projects-using-OSRM

**Comment by liotier** [comment]
Meanwhile I have become a huge fan of Cycle.travel, which happens to run OSRM with a very nicely tuned cycling profile.

**Comment by systemed** [comment]
@liotier Thanks! Pleased to say I'll be moving cycle.travel to OSRM 4.9.x in the next few weeks.
