### ISSUE TITLE
Excluding points on Route API call

### ISSUE THREAD

**Issue by MrCanan** [Project-OSRM/osrm-backend#6680]
Hi,

I get my route detail (Route API call), and detect points (parsing to get their coordinates and Nearest API call) I want to do not have on my route
> But I do not find how to make a new Route API call with my excluding points, to have an alternative Route

Is it possible to do it? If yes, how? If not, is it a plan for future release?

Best regards

**Comment by jcoupey** [comment]
The way OSRM works is that a lot is done in pre-processing (the `osrm-extract` etc. steps) so that routing queries are then very fast. The drawback is that it is not possible to exclude any arbitrary way from the graph dynamically at request level. For this you'd actually have to go through all the pre-processing steps to re-generate a new graph which does not make sense for a simple route adjustment.

If you need that level of flexibility, you probably want to use another routing engine that sets a different trade-off between flexibility and performance, for example Valhalla.

**Comment by MrCanan** [comment]
Hi,

Thank you for explication
> So I will have a look at Valhalla

Best regards
