### ISSUE TITLE
No route is provided

### ISSUE THREAD

**Issue by iaroslavzif** [Project-OSRM/osrm-backend#6741]
Hello!

I don't understand why the OSRM is not offering a route on some ways...I checked that [access tags](https://www.openstreetmap.org/way/4485702#map=19/59.33692/18.05501&layers=D) and it should work....

https://map.project-osrm.org/?z=18&center=59.336783%2C18.056325&loc=59.336106%2C18.053606&loc=59.336834%2C18.055800&hl=en&alt=0&srv=0

![Captură de ecran din 2023-11-20 la 14 09 13](https://github.com/Project-OSRM/osrm-backend/assets/111109027/510ada7e-8627-43eb-8523-b86cf4b4baea)

Thank you!

**Comment by jcoupey** [comment]
The debug graph flags the portion of route for the destination as a connected component of its own (pink borders), see http://map.project-osrm.org/debug/car.html#17/59.33677/18.05532 though I don't see anything wrong with the data itself at way level: https://www.openstreetmap.org/way/4485702. There are a few other ways with the same behavior around.

**Comment by iaroslavzif** [comment]
Hi @jcoupey !

Thank you for stepping in. Indeed it looks that due to the "pedestrian" which is not part of the routing graph we are not offering the chances to route on that one way segment...i just think that there are a lot of similar cases....something maybe should be done....

**Comment by jcoupey** [comment]
I don't think there is much actionable on the OSRM side here as this is more of a data problem. The current tagging states that it's possible to drive to Walligatan 16 but not get out of the street afterward.

In order to know what to change, someone with local knowledge would have to answer how cars are supposed to drive away if they're allowed to enter this street.
