### ISSUE TITLE
GPX files #question

### ISSUE THREAD

**Issue by itzortzis** [Project-OSRM/osrm-backend#6981]
I have successfully deployed the OSRM backend on my server. It works just like a charm!

The Question: is there any way to add GPX files in order to include custom routes

**Comment by jcoupey** [comment]
No sure what you mean by "add GPX files". If you want to use traces to match them on the road network you should check out the `match` endpoint https://github.com/Project-OSRM/osrm-backend/blob/master/docs/http.md#match-service.

**Comment by itzortzis** [comment]
@jcoupey thanks a lot for your prompt response! 
I don't think this is what I am looking for. I want to add custom routes (GPS points) that are not included in the current network.

**Comment by jcoupey** [comment]
In that case you'll have to convert your "own roads" to something OSRM understands, which is the OpenStreetMap format. Theoretically you could preprocess the OSM files you're using and add anything you want. You just need to make sure that:

- your roads follow the tagging scheme for OSM in order to be pickup up by OSRM during `osrm-extract` (see routing profile);
- the overall connectivity of the resulting road network is good, i.e. your own roads have common nodes with nearby existing roads.

This being said: if you have GPX traces giving hints at missing roads in OSM, you should consider contributing those directly to OSM. You'd then spare yourself a lot of work and improve the map for everyone.

**Comment by itzortzis** [comment]
Contributing directly to OSM was my initial idea. Though, I don't know the exact procedure for my "own roads" to be published and included in the .pbf file (used to deploy the OSRM backend). Since it is possible, I will study the OSM documentation to understand the pipeline. 

Thanks again for your advice!

**Comment by jcoupey** [comment]
As soon as missing roads are added to OSM they'll be available in any data extract after your contribution. Geofabrik for example has daily extracts so you should be able to see the result in your OSRM instance pretty quickly after re-processing the data.

**Comment by jcoupey** [comment]
Closing as answered.
