### ISSUE TITLE
No turn indication

### ISSUE THREAD

**Issue by smurfix** [Project-OSRM/osrm-backend#879]
Sometimes you get a fork in the road where both ways' direction is "straight ahead", which is nonsense. For instance, a route which turns right at 49.4765272, 11.1726058

![image](https://f.cloud.github.com/assets/236571/1972149/ed7a7388-8342-11e3-83f9-f88708097e70.png)

The code should show "slight right" for this one. Maybe follow both ways for a bit and see which diverges more from the original direction?

**Comment by MoKob** [comment]
<img width="859" alt="screen shot 2016-03-21 at 14 33 16" src="https://cloud.githubusercontent.com/assets/12932279/13920167/ed09a016-ef71-11e5-9d7a-89119c96fc66.png">

These instances should only happen in the rarest cases since our 4.9 release. With the upcoming 5.0 and ongoing, the set of arbitrary instructions should be reduced even further.
