### ISSUE TITLE
Setting Precision for the route geometry format

### ISSUE THREAD

**Issue by slobberbone** [Project-OSRM/osrm-backend#896]
Hello,
I would develop in an OSRM fork an option parameter in url like precision=X and the possibility to set the precision by default in the osrm.ini (not mandatory), whereas in the code the limit stay 6 like now.

It allows changes for futur if the Google API change to 7 or more and it would be apreciate by old routing user which have 5 or less in their javascript code ...

What do you think about that ? If I'll made a pull request, it would be accepted ?

**Comment by danpat** [comment]
Closing in favour of https://github.com/Project-OSRM/osrm-backend/issues/2485 and 

We internally store 6 digits of precision.  Source coordinates from OSM only have 7 digits of precision available (that's all that's stored in the OSM database), although custom OSM-like imports may have more.

Precision beyond 6 digits has not been called for since this ticket was opened (2.5 years ago), so this does not seem like a necessary feature.

https://en.wikipedia.org/wiki/Decimal_degrees

6 digits gives us about 10cm precision near the equator, and 4cm precision at 67 degrees latitude.

As noted in https://github.com/Project-OSRM/osrm-backend/issues/2468, we have about 3 bits of space remaining in our fixed-precision storage integers, so we could conceivably add 1 more digit without incurring any additional overhead.

Closing for now because it doesn't seem like there's anything to do here.  If someone has a use-case for sub-mm routing (OSRM for circuit board routing?), please re-open and we can continue the discussion.
